---
sidebar: sidebar
permalink: rhhc/rhhc-pm-solution.html
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP
summary:
---

== NetApp Solution with Managed Red Hat OpenShift Container platform workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Customers may be "born in the cloud" or may be at a point in their modernization journey when they are ready to move some select workloads or all workloads from their data centers to the cloud. They may choose to use provider-managed OpenShift containers and provider-managed NetApp storage in the cloud for running their workloads. They should plan and deploy the Managed Red Hat OpenShift container clusters in the cloud for a successful production-ready environment for their container workloads. NetApp provides fully managed storage offerings for Managed Red Hat solutions in all three leading public clouds. 

*Amazon FSx for NetApp ONTAP (FSx ONTAP)*

FSx ONTAP delivers data protection, reliability, and flexibility for container deployments in AWS. Trident serves as the dynamic storage provisioner to consume the persistent FSx ONTAP storage for customers' stateful applications.

As ROSA can be deployed in HA mode with control plane nodes spread across multiple availability zones, FSx ONTAP can also be provisioned with Multi-AZ option which provides high availability and protect against AZ failures.

*Google Cloud NetApp Volumes*

Red Hat OpenShift Dedicated is a fully managed application platform that enables you to quickly build, deploy, and scale applications across the hybrid cloud. Google Cloud NetApp Volumes provides persistent volumes bringing the full suite of ONTAP’s enterprise data management capabilities to OpenShift deployments in Google Cloud. 
