---
sidebar: sidebar
permalink: xcp/xcp-bp-high-performance-computing-to-ontap-nfs.html
keywords: use case, gpfs, nfs
summary: We used NetApp XCP to migrate the data from GPFS to NFS so that GPUs can process the data. AI typically processes data from a network file system.
---

= High-performance computing to ONTAP NFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-09-20 14:39:42.292830
//

[.lead]
This use case is based on requests from field organizations. Some NetApp customers have their data in a high-performance computing environment, which provides data analytics for training models and enables research organizations to gain insight and understanding of large amount of digital data. NetApp field engineers need a detailed procedure to extract the data from IBM’s GPFS to NFS. We used NetApp XCP to migrate the data from GPFS to NFS so that GPUs can process the data. AI typically processes data from a network file system.

For more information about the high-performance computing to ONTAP NFS use case, a recorded demo, and test results, see the https://blog.netapp.com/data-migration-xcp[Using XCP to Move Data from a Data Lake and High-Performance Computing to ONTAP NFS^] blog.

For detailed steps on moving MapR-FS data into ONTAP NFS by using NetApp XCP, see Appendix A: GPFS to NFS―Detailed Steps in https://docs.netapp.com/us-en/netapp-solutions/data-analytics/bda-ai-introduction.html.
