---
sidebar: sidebar
permalink: xcp/xcp-bp-using-the-xcp-data-mover-to-migrate-large-files.html
keywords: migrate, large files, rman, ebs, pacemaker
summary: This use case is based on a television network customer. The customer wanted to migrate Oracle Recovery Manager (RMAN) backup files to the cloud and run the Oracle E-Business Suite (EBS) application by using Azure NetApp Files with Pacemaker software. The customer also wanted to migrate their database backup files to on-demand cloud storage and transfer large files (in the range of 25GB to 50GB each) to Azure.
---

= Using the XCP Data Mover to migrate large files
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-09-20 14:39:42.300140
//


link:xcp-bp-using-the-xcp-data-mover-to-migrate-millions-of-small-files-to-flexible-storage.html[Previous: Using the XCP Data Mover to migrate millions of small files to flexible storage.]

[.lead]
This use case is based on a television network customer. The customer wanted to migrate Oracle Recovery Manager (RMAN) backup files to the cloud and run the Oracle E-Business Suite (EBS) application by using Azure NetApp Files with Pacemaker software. The customer also wanted to migrate their database backup files to on-demand cloud storage and transfer large files (in the range of 25GB to 50GB each) to Azure.

The following figure illustrates the data migration from on-premises to Azure NetApp Files for large files.

For more information, see the https://blog.netapp.com/XCP-cloud-data-migration[NetApp XCP Data Mover Solution: On Premises to Cloud^] blog.

link:xcp-bp-duplicate-files.html[Next: Duplicate files.]
