---
sidebar: sidebar
permalink: xcp/xcp-bp-best-practice-guidelines-and-recommendations.html
keywords: best practices, guidelines, recommendations, IMT
summary: This section contains best practices, guidelines and recommendations for migrating data using NetApp XCP.
---

= Best practice guidelines and recommendations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-09-20 14:39:42.484056
//

link:xcp-bp-cifs-data-migration-with-acls-from-a-source-storage-box-to-ontap.html[Previous: CIFS data migration with ACLs From a source storage box to ONTAP.]

[.lead]
* Use the XCP client operating system, which is IMT supported. The IMT supported client is qualified by NetApp.
* Run XCP as a root user in the Linux operating system to perform migration. you can run the xcp command as the sudo user, but it is not supported by XCP.
* Run only one instance of XCP per client. Technically you can run multiple instanced of XCP on the same host from a different location, however this is not a supported practice. Indeed, running many instances might result in failure.
* In the current XCP version, Live Source is not supported. If the source NetApp volume is active and continuously changed by applications and users, you should take a snapshot of the source volume to perform a migration.
* It is a best practice to create a new snapshot with a different name for every incremental sync so that it is easy to create an incremental migration path based on the snapshot name in the event of failure.
* If you are performing a snapshot-based migration, it is a best practice to continue snapshot-based migration until cutover.
* If you have more than 10 million files and you have incremental data change of more than 50%, it is a best practice to use a higher core count and more memory than the minimum recommendation in the installation and administration guide.

link:xcp-bp-troubleshooting.html[Next: Troubleshooting.]
