---
sidebar: sidebar
permalink: xcp/xcp-bp-performance-tuning.html
keywords: performance, tuning, operations, windows
summary: This section provides some of the tuning parameters that help to improve the performance of XCP operations.
---

= Performance tuning
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-09-20 14:39:42.273928
//

link:xcp-bp-sizing-guidelines-overview.html[Previous: Sizing guidelines.]

[.lead]
This section provides some of the tuning parameters that help to improve the performance of XCP operations:

* For better scaling and to distribute the workload across multiple XCP instances, split the subfolders for each XCP instance for the migration and data transfer.
* XCP can use maximum CPU resources—the more the CPU cores, the better the performance. Therefore, you should have more CPUs in the XCP server. We lab tested 128GB RAM and 48x core CPUs, which provided better performance than 8x CPUs and 8GB RAM.
* XCP copy with the `-parallel` option is based on the number of CPUs. The default number of parallel threads (seven) is sometimes sufficient for most XCP data transfer and migration operations. For XCP Windows by default, the number of parallel processes is equal to the number of CPUs. The maximum number for the `-parallel` option should be less than or equal to the number of cores.
* 10GbE is a good start for data transfer. However, we tested with 25GbE and 100GbE, which provided better data transfer and are recommended for large file-size data transfer.
* For Azure NetApp Files, the performance varies based on the service level. For more information, see the following table, which shows Azure NetApp Files service levels and performance details.

|===
|Service level |Standard |Premium |Ultra

|Throughput
|16MBps/terabyte (TB)
|64MBps/TB
|128MBps/TB
|Workload types
|General purpose file shares, email, and web
|BMs, databases, and applications
|Latency-sensitive applications
|Performance explained
|Standard performance: 1,000 IOPS per TB (16K I/O) and 16MBps/TB
|Premium performance – 4,000 IOPS per TB (16k I/O) and 64MBps/TB
|Extreme performance: 8,000 IOPS per TB (16k I/O) and 128MBps/TB
|===

You must choose the right service level based on the throughput and workload types. Most customers start with the Premium level and change the service level based on the workload.

link:xcp-bp-customer-scenarios-overview.html[Next: Customer scenarios.]
