---
sidebar: sidebar
permalink: data-analytics/apache-spark-conclusion.html
keywords: conclusion    
summary: This section summarizes this document concerning the NetApp storage solutions for Apache Spark.
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-08-03 14:35:46.538786
//

link:apache-spark-python-scripts-for-each-major-use-case.html[Previous: Python scripts for each major use case.]

[.lead]
In this document, we discuss the Apache Spark architecture, customer use cases, and the NetApp storage portfolio as it relates to big data, modern analytics, and AI, ML, and DL. In our performance validation tests based on industry-standard benchmarking tools and customer demand, the NetApp Spark solutions demonstrated superior performance relative to native Hadoop systems. A combination of the customer use cases and performance results presented in this report can help you to choose an appropriate Spark solution for your deployment.

link:apache-spark-where-to-find-additional-information.html[Next: Where to find additional information.]