---
sidebar: sidebar
permalink: data-analytics/apache-spark-target-audience.html
keywords: audience, data scientist, engineer, devops, cloud administrator, architect
summary: This section describes who might be interested in the contents of this solution.
---

= Target audience
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-08-03 14:35:46.418093
//

link:apache-spark-solution-overview.html[Previous: Solution overview.]

[.lead]
The world of analytics and data science touches multiple disciplines in IT and business:

* The data scientist needs the flexibility to use their tools and libraries of choice.
* The data engineer needs to know how the data flows and where it resides.
* A DevOps engineer needs the tools to integrate new AI and ML applications into their CI and CD pipelines.
* Cloud administrators and architects must be able to set up and manage hybrid cloud resources.
* Business users want to have access to analytics, AI, ML, and DL applications.

In this technical report, we describe how NetApp AFF, E-Series, StorageGRID, NFS direct access, Apache Spark, Horovod, and Keras help each of these roles bring value to business.

link:apache-spark-solution-technology.html[Next: Solution technology.]