---
sidebar: sidebar
permalink: data-analytics/bda-ai-business-benefits.html
keywords: business, benefits
summary: This section describes the business benefits of this solution.
---

= Business benefits
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-02-03 19:40:46.811361
//

link:bda-ai-hdfs-and-mapr-fs-to-ontap-nfs.html[Previous: HDFS and MapR-FS to ONTAP NFS.]

[.lead]
Moving data from big data analytics to AI provides the following benefits:

* The ability to extract data from different Hadoop file systems and GPFS into a unified NFS storage system
* A Hadoop-integrated and automated way to transfer data
* A reduction in the cost of library development for moving data from Hadoop file systems
* Maximum performance by aggregated throughput of multiple network interfaces from a single source of data by using NIPAM
* Scheduled and on-demand methods to transfer data
* Storage efficiency and enterprise management capability for unified NFS data by using ONTAP data management software
* Zero cost for data movement with the Hadoop method for data transfer

link:bda-ai-gpfs-to-nfs-detailed-steps.html[Next: GPFS to NFS-Detailed steps.]
