---
sidebar: sidebar
permalink: data-analytics/bda-ai-customer-challenges.html
keywords: customer, challenge, data lake, repository, syncing, moving data
summary: This page discusses the challenges that a customer might face when trying to access data from big-data analytics for AI operations.
---

= Customer challenges
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-02-03 19:40:46.777056
//

link:bda-ai-introduction.html[Previous: Introduction.]

[.lead]
Customers might face the following challenges when trying to access data from big-data analytics for AI operations:

* Customer data is in a data lake repository. The data lake can contain different types of data such as structured, unstructured, semi-structured, logs, and machine-to-machine data. All these data types must be processed in AI systems.
* AI is not compatible with Hadoop file systems. A typical AI architecture is not able to directly access HDFS and HCFS data, which must be moved to an AI-understandable file system (NFS).
* Moving data lake data to AI typically requires specialized processes. The amount of data in the data lake can be very large. A customer must have an efficient, high-throughput, and cost-effective way to move data into AI systems.
* Syncing data. If a customer wants to sync data between the big-data platform and AI, sometimes the data processed through AI can be used with big data for analytical processing.

link:bda-ai-data-mover-solution.html[Next: Data mover solution.]
