---
sidebar: sidebar
permalink: data-analytics/cdm-fod-conclusion.html
keywords: conclusion
summary: "Based on this validation, Data scientists and engineers can access NFS data from AWS SageMaker Jupyter Notebooks via S3 buckets from NetApp Cloud Volumes ONTAP. This approach enables easy access and sharing of the same data from both NFS and S3 without the need for additional software."
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2023-04-14 16:09:25.071257
//

link:cdm-fod-data-duality-for-data-scientists-and-other-applications.html[Previous: Data duality for data scientists and other applications.]

[.lead]
Based on this validation, Data scientists and engineers can access NFS data from AWS SageMaker Jupyter Notebooks via S3 buckets from NetApp Cloud Volumes ONTAP. This approach enables easy access and sharing of the same data from both NFS and S3 without the need for additional software.

== Where to find additional information

To learn more about the information that is described in this document, review the following documents and/or websites:

* Text classification using SageMaker BlazingText
+
https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html[https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.html^]

* ONTAP version support for S3 object storage
+
https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html[https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html^]

== Version history

|===
|Version |Date |Document version history

|Version 1.0
|April 2023
|Initial release
|===
