---
sidebar: sidebar
permalink: data-analytics/confluent-kafka-introduction.html
keywords: tr-4912, tr4912, 4912, introduction, best practices, Kafka, confluent
summary: This document describes the best-practice guidelines for using Kafka on a NetApp storage controller.
---

= TR-4912: Best practice guidelines for Confluent Kafka tiered storage with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-11-15 09:15:45.917287
//

Karthikeyan Nagalingam, Rankesh Kumar

Apache Kafka is a community-distributed event-streaming platform capable of handling trillions of events a day. Initially conceived as a messaging queue, Kafka is based on an abstraction of a distributed commit log. Since it was created and open- sourced by LinkedIn in 2011, Kafka has evolved from a messages queue to a full-fledged event-streaming platform. Confluent delivers the distribution of Kafka with the Confluent Platform. The Confluent Platform improves Kafka with additional community and commercial features designed to enhance the streaming experience of both operators and developers in production at a massive scale.

This document describes the best-practice guidelines for using Kafka on a NetApp storage controller by providing the following content:

* Confluent Kafka certification with a NetApp storage controller – StorageGRID
* Kafka performance tests
* Best-practice guidelines for Kafka on NetApp storage systems

link:confluent-kafka-solution.html[Next: Solution.]
