---
sidebar: sidebar
permalink: data-analytics/confluent-kafka-confluent-kafka-rebalance.html
keywords: rebalance, test, self balancing, brokers
summary: This test is based on the self-balancing clusters feature, which automates rebalancing based on cluster topology changes or uneven load.
---

= Confluent Kafka rebalance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-11-15 09:15:45.969634
//


link:confluent-kafka-kafka-s3-connector.html[Previous: Kafka s3 connector.]

This test is based on the self-balancing clusters feature, which automates rebalancing based on cluster topology changes or uneven load. The confluent rebalance test helps to measure the time to add a new broker when node failure or the scaling node requires rebalancing data across brokers. In classic Kafka configurations, the amount of data to be rebalanced grows as the cluster grows, but, in tiered storage, rebalancing is restricted to a small amount of data. Based on our validation, rebalancing in tiered storage takes seconds or minutes in a classic Kafka architecture and grows linearly as the cluster grows.

link:confluent-kafka-best-practice-guidelines.html[Next: Best practice guidelines.]
