---
sidebar: sidebar
permalink: data-analytics/dremio-lakehouse-technology-overview.html
keywords: storagegrid, apache, dremio, lakehouse,
summary: This section describes the technology used in this solution.
---

= Technology Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-11-15 09:15:45.924450
//

[.lead]
The hardware and software configurations outlined below were utilized for validations performed in this document. These configurations serve as a guideline to help you set up your environment, However, please note the specific components may vary depending on individual customer requirements.  

=== Hardware requirements
|===
| Hardware | Details 

|NetApp AFF Storage array HA Pair
a|* A800
* ONTAP 9.14.1
* 48 x 3.49TB SSD-NVM
* Two S3 Buckets: Dremio metadata and customer data.


|4 x FUJITSU PRIMERGY RX2540 M4
a|* 64 CPUs
* Intel® Xeon® Gold 6142 CPU @ 2.60GHz
* 256 GM Physical Memory
* 1 x 100GbE network port

|Networking
a|* 100 GbE
|StorageGRID
|* 1 x SG100, 3xSGF6024
* 3 x 24 x 7.68TB
* Two S3 Buckets: Dremio metadata and customer data.
|===

=== Software requirements
|===
| Software | Details

| Dremio
a|* version - 25.0.3-202405170357270647-d2042e1b
* Enterprise Edition

|On-Prem
a|* 5 node Dremio cluster
* 1 master coordinator and 4 executors

|===


