---
sidebar: sidebar
permalink: data-analytics/dremio-lakehouse-solution.html
keywords: solution, architecture, details, hardware, software
summary: This section covers the hardware and software used for dremio certification. This information is applicable to dremio deployment with NetApp storage.
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-11-15 09:15:45.920602
//

[.lead]
The solution provides unique benefits to address customer challenges faced by Lakehouse customers. By Leveraging NetApp ONTAP, StorageGRID, NetApp Cloud solutions can add significant values to their business operations. The solution not only provides access to multiple NetApp sources to Lakehouse but also enhance performance to business growth. 

== NetApp Overview
•	NetApp's offerings, such as ONTAP and StorageGRID, allow for the separation of storage and compute, enabling optimal resource utilization based on specific requirements. This flexibility empowers customers to independently scale their storage using NetApp storage solutions.
•	By leveraging NetApp's storage controllers, customers can efficiently serve data to their vector database using NFS and S3 protocols. These protocols facilitate customer data storage and manage the vector database index, eliminating the need for multiple copies of data accessed through file and object methods.
•	NetApp ONTAP provides native support for NAS and Object storage across leading cloud service providers like AWS, Azure, and Google Cloud. This wide compatibility ensures seamless integration, enabling customer data mobility, global accessibility, disaster recovery, dynamic scalability, and high performance.

== Dremio overview
Dremio is the unified Lakehouse platform for self-service analytics and AI. Our Unified Analytics Platform brings users closer to the data with Lakehouse flexibility, scalability, and performance at a fraction of the cost.  Dremio enables shift-left analytics to eliminate complex and costly data integration and ETL, delivering seamless enterprise-scale analytics with no data movement.  

Easy-to-use self-service analytics enabled through a universal semantic layer and a tightly integrated, highly performant SQL query engine makes it easier to connect, govern, and analyze all data, both in the cloud and on-premises. 

Dremio’s Apache-native Lakehouse Management capabilities simplify data discovery, and automate data optimization, delivering high-performance analytics with Git-inspired data versioning.  

Foundationally built on open source, Dremio lets companies avoid lock-in and remain positioned for innovation. Enterprise companies trust Dremio as the easiest-to-use Lakehouse platform with the best price-performance on all workloads

== What values Dremio and NetApp partnership adds to customers ?
-	Improved Data Management and Accessibility: Dremio is known for its data lake engine that allows organizations to query data directly from their data lakes at high speed. NetApp, on the other hand, is a leading provider of cloud data services and data storage solutions. A partnership could potentially offer a comprehensive solution for storing, managing, and accessing data efficiently.

-	Performance Optimization: With NetApp's expertise in data storage and Dremio's capabilities in data processing, the partnership could potentially offer solutions that optimize the performance of data operations, reducing latency and increasing speed. We also noticed the Dremio brings performance benefits to NetApp IT team.

-	Scalability: Both Dremio and NetApp offer solutions that are designed to scale. A partnership could provide customers with highly scalable data storage and processing solutions, capable of handling the needs of growing businesses.

-	Data Security and Governance: Both companies have a strong focus on data security. Together, they could offer robust security features, ensuring that data is protected and that data governance requirements are met.

-	Cost Efficiency: By integrating Dremio's data lake engine with NetApp's storage solutions, customers might be able to reduce costs associated with data management, as they could potentially eliminate the need for costly data movement and duplication.
