---
sidebar: sidebar
permalink: data-analytics/dremio-lakehouse-conclusion.html
keywords: conclusion
summary: This document provides best practice guidelines for using Dremio with NetApp storage, including TPCDS certification tests, tuning and customer usecase details.
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-11-15 09:15:45.976303
//

[.lead]
In conclusion, this technical report has provided comprehensive deployment details of Dremio in conjunction with various data sources from NetApp storage controllers, including ONTAP S3, NAS, and StorageGRID. The deployment process was successfully executed, and the TPC-DS benchmarking tool was utilized to perform 99 SQL queries across the different data sources. The report has also explored customer use cases within NetApp, demonstrating the versatility and effectiveness of Dremio in meeting diverse business requirements. Additionally, a specific use case involving an auto parts sales customer was examined, highlighting the practical application and benefits of leveraging Dremio for data analytics and insights.

Overall, this document serves as a valuable resource for understanding the deployment and usage of Dremio with NetApp storage controllers, showcasing its capabilities and potential for driving data-driven decision-making and optimization in various industries.

== Where to find additional information

To learn more about the information that is described in this document, review the following documents and/or websites:

* Zookeeper installation 
+
https://medium.com/@ahmetfurkandemir/distributed-hadoop-cluster-1-spark-with-all-dependincies-03c8ec616166

* Dremio 
+
https://docs.dremio.com/current/get-started/cluster-deployments/deployment-models/standalone/standalone-tarball/

* Configuring Dremio with storageGRID
+
https://docs.netapp.com/us-en/storagegrid-enable/tools-apps-guides/configure-dremio-storagegrid.html#configure-dremio-data-source

* NetApp use case
+
https://www.dremio.com/customers/netapp/

