---
sidebar: sidebar
permalink: data-analytics/dremio-lakehouse-solution.html
keywords: solution, architecture, details, hardware, software
summary: This section covers the hardware and software used for dremio certification. This information is applicable to dremio deployment with NetApp storage.
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-11-15 09:15:45.920602
//

[.lead]
The Hybrid Iceberg Lakehouse solution provides unique benefits to address customer challenges faced by data lake customers. By Leveraging  Dremio Unified Lakehouse platform and NetApp ONTAP, StorageGRID, NetApp Cloud solutions, companies can add significant value to their business operations. The solution not only provides access to multiple data sources, including NetApp sources to but also enhance overall analytical performance and helps companies drive business insight that leads to business growth. 

== NetApp Overview
•	NetApp's offerings, such as ONTAP and StorageGRID, enable the separation of storage and compute, enabling optimal resource utilization based on specific requirements. This flexibility empowers customers to independently scale their storage using NetApp storage solutions.
•	By leveraging NetApp's storage controllers, customers can efficiently serve data to their vector database using NFS and S3 protocols. These protocols facilitate customer data storage and manage the vector database index, eliminating the need for multiple copies of data accessed through file and object methods.
•	NetApp ONTAP provides native support for NAS and Object storage across leading cloud service providers like AWS, Azure, and Google Cloud. This wide compatibility ensures seamless integration, enabling customer data mobility, global accessibility, disaster recovery, dynamic scalability, and high performance.

== Dremio overview
Dremio is the Unified Lakehouse Platform for self-service analytics and AI. Dremio’s Unified Analytics Platform brings users closer to the data with lakehouse flexibility, scalability, and performance at a fraction of the cost. Dremio enables shift-left analytics to eliminate complex and costly data integration and ETL, delivering seamless enterprise-scale analytics with no data movement.  

Easy-to-use self-service analytics enabled through a universal semantic layer and a tightly integrated, highly performant SQL query engine makes it easier to connect, govern, and analyze all data, both in the cloud and on-premises. 

Dremio’s Apache Iceberg-native lakehouse management capabilities simplify data discovery, and automate data optimization, delivering high-performance analytics with Git-inspired data versioning.  

Foundationally built on open source and open standards, Dremio lets companies avoid lock-in and remain positioned for innovation. Enterprise companies trust Dremio as the easiest-to-use lakehouse platform with the best price-performance on all workloads


== What value does the Dremio and NetApp Hybrid Iceberg Lakehouse solution deliver to customers?

-	*Improved Data Management and Accessibility*: Dremio is well-known for its data lakehouse platform that allows organizations to query data directly from their data lakes at high speed. NetApp, on the other hand, is a leading provider of cloud data services and data storage solutions. The joint offer   provides companies a comprehensive solution for storing, managing, accessing  and analyzing  their enterprise’s data efficiently.

-	*Performance Optimization*: With NetApp's expertise in data storage and Dremio's capabilities in data processing and data optimization, the partnership offers a solution that improves the performance of data operations, reduces latency and increasing speed to business insight. Dremio has even delivered performance benefits to NetApp’s own internal IT analytical infrastructure .

-	*Scalability*: Both Dremio and NetApp offer a solution that is designed to scale. The joint solution provides customers with highly scalable data storage, data management and analytical environment. In a Hybrid Iceberg Lakehouse environment, the Dremio SQL query engine paired with NetApp StorageGRID delivers unparalleled scalability, concurrency and query performance, capable of handling the analytical needs of any business. 

-	*Data Security and Governance*: Both companies have a strong focus on data security and governance. Together, they offer robust security and data governance features, ensuring that data is protected and that data governance requirements are met. Features such as role-based and fine-grain access controls, comprehensive auditing, end-to-end data lineage, unified identity management and SSO with an extensive compliance and security framework ensures companies analytical data environments are secure and governed. 

-	*Cost Efficiency*: By integrating Dremio's data lake engine with NetApp's storage solutions, customers are able to reduce costs associated with data management and data movement. Organizations are also able to move from legacy data lake environments to a more modern lakehouse solution composed of NetApp and Dremio. This Hybrid Iceberg Lakehouse solution delivers high-speed query performance and market-leading query concurrency that lowers TCO and decreases time to business insight.

