---
sidebar: sidebar
permalink: hdcs-sh-conclusion.html
keywords:
summary:
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-10-28 12:57:46.914153
//

[.lead]
This section provides a summary of the use cases and solutions provided by NetApp to fulfill various Hadoop data protection requirements. By using the data fabric powered by NetApp, customers can:

* Have the flexibility to choose the right data protection solutions by leveraging NetApp’s rich data management capabilities and integration with Hadoop native workflows.
* Reduce their Hadoop cluster backup window time by almost 70%.
* Eliminate any performance effect resulting from Hadoop cluster backups.
* Provide multicloud data protection and data access from different cloud providers simultaneously to a single source of analytics data.
* Create fast and space-efficient Hadoop cluster copies by using FlexClone technology.

=== Where to find additional information

To learn more about the information described in this document, see the following documents and/or websites: 

* NetApp Big Data Analytics Solutions
+
https://www.netapp.com/us/solutions/applications/big[https://www.netapp.com/us/solutions/applications/big^]https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx[-^]https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx[data^]https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx[-^]https://www.netapp.com/us/solutions/applications/big-data-analytics/index.aspx[analytics/index.aspx^]

* Apache Spark Workload with NetApp Storage
+
https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf[https://www.netapp.com/pdf.html?item=/media/26877-nva-1157-deploy.pdf^]

* NetApp Storage Solutions for Apache Spark
+
http://www.netapp.com/us/media/tr[http://www.netapp.com/us/media/tr^]http://www.netapp.com/us/media/tr-4570.pdf[-^]http://www.netapp.com/us/media/tr-4570.pdf[4570.pdf^]http://www.netapp.com/us/media/tr-4570.pdf[ ^]

* Apache Hadoop on data fabric enabled by NetApp
+
http://www.netapp.com/us/media/tr[http://www.netapp.com/us/media/tr^]http://www.netapp.com/us/media/tr-4529.pdf[-^]http://www.netapp.com/us/media/tr-4529.pdf[4529.pdf^]

* NetApp In-Place Analytics Module
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2854071[https://library.netapp.com/ecm/ecm_download_file/ECMLP2854071^]

=== Acknowledgements

* Paul Burland, Sales Rep, ANZ Victoria District Sales, NetApp 
* Hoseb Dermanilian, Business Development Manager, NetApp 
* Lee Dorrier, Director MPSG, NetApp 
* David Thiessen, Systems Engineer, ANZ Victoria District SE, NetApp

=== Version history

|===
|Version |Date |Document version history

|Version 1.0
|January 2018
|Initial release
|Version 2.0
|October 2021
|Updated with use case #5: Accelerate analytic workload 
|===
