---
sidebar: sidebar
permalink: data-analytics/kafka-nfs-conclusion.html
keywords: conclusion
summary: "The NetApp solution for the silly rename problem provides a simple, inexpensive, and centrally managed form of storage for workloads that were previously incompatible with NFS."
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2023-01-30 15:54:43.203702
//

link:kafka-nfs-performance-overview-and-validation-with-aff-on-premises.html[Previous: Performance overview and validation with AFF on-premises.]

[.lead]
The NetApp solution for the silly rename problem provides a simple, inexpensive, and centrally managed form of storage for workloads that were previously incompatible with NFS. This new paradigm enables customers to create more manageable Kafka clusters that are easier to migrate and mirror for the purpose of disaster recovery and data protection. We have also seen that NFS provides additional benefits such as reduced CPU utilization and a faster recovery time, dramatically improved storage efficiency, and better performance through NetApp ONTAP.

link:kafka-nfs-where-to-find-additional-information.html[Next: Where to find additional information.]