---
sidebar: sidebar
permalink: data-analytics/kafka-nfs-where-to-find-additional-information.html
keywords: 
summary:
---

= Where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2023-01-30 15:54:43.207619
//

link:kafka-nfs-conclusion.html[Previous: Conclusion.]

[.lead]
To learn more about the information that is described in this document, review the following documents and/or websites:

* What is Apache Kafka?
+
https://www.confluent.io/what-is-apache-kafka/[https://www.confluent.io/what-is-apache-kafka/^]

* What is silly rename?
+
https://linux-nfs.org/wiki/index.php/Server-side_silly_rename[https://linux-nfs.org/wiki/index.php/Server-side_silly_rename^] 

* ONATP is read for streaming applications.
+
https://www.netapp.com/blog/ontap-ready-for-streaming-applications/[https://www.netapp.com/blog/ontap-ready-for-streaming-applications/^]

* Silly- rename issue with Kafka.
+
https://sbg.technology/2018/07/10/kafka-nfs/[https://sbg.technology/2018/07/10/kafka-nfs/^]

* NetApp product documentation
+
https://www.netapp.com/support-and-training/documentation/[https://www.netapp.com/support-and-training/documentation/^]

* What is NFS?
+
https://en.wikipedia.org/wiki/Network_File_System[https://en.wikipedia.org/wiki/Network_File_System^]

* What is Kafka partition reassignment?
+
https://docs.cloudera.com/runtime/7.2.10/kafka-managing/topics/kafka-manage-cli-reassign-overview.html[https://docs.cloudera.com/runtime/7.2.10/kafka-managing/topics/kafka-manage-cli-reassign-overview.html^]

* What is the OpenMessaging Benchmark?
+
https://openmessaging.cloud/[https://openmessaging.cloud/^]

* How do you migrate a Kafka broker?
+
https://medium.com/@sanchitbansal26/how-to-migrate-kafka-cluster-with-no-downtime-58c216129058[https://medium.com/@sanchitbansal26/how-to-migrate-kafka-cluster-with-no-downtime-58c216129058^]

* How do you monitor Kafka broker with Prometheus?
+
https://www.confluent.io/blog/monitor-kafka-clusters-with-prometheus-grafana-and-confluent/

* Managed Platform for Apache Kafka
+
https://www.instaclustr.com/platform/managed-apache-kafka/

* Support for Apache Kafka
+
https://www.instaclustr.com/support-solutions/kafka-support/

* Consulting services for Apache Kafka
+
https://www.instaclustr.com/services/consulting/


== Version history

|===
|Version |Date |Document version history

|Version 1.0
|March 2023
|Initial release.
|===
