---
sidebar: sidebar
permalink: data-analytics/kafka-ontap-overview.html
keywords: tr4941, 4941, introduction
summary: This document outlines performance benchmarks for the Confluent platform on NetApp ONTAP using a tiered storage benchmarking kit.
---

= TR-4941: Confluent with NetApp ONTAP storage controllers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-10-03 16:43:19.473990
//

Karthikeyan Nagalingam, Joe Scott, NetApp
Rankesh Kumar, Confluent

[.lead]
To make the Confluent Platform more scalable and elastic, it must be able to scale and balance workloads very quickly. Tiered storage makes storing huge volumes of data in Confluent manageable by reducing this operational burden. The fundamental idea is to separate data storage from data processing, which makes it much easier to scale each independently.

Loaded with industry-leading innovations, NetApp ONTAP data management software provides Confluent with many advantages anywhere the data lives.

This document outlines performance benchmarks for the Confluent platform on NetApp ONTAP using a tiered storage benchmarking kit.

link:kafka-sc-solution.html[Next: Solution.]