---
sidebar: sidebar
permalink: data-analytics/stgr-splunkss-conclusion.html
keywords: conclusion, references
summary: Splunk Enterprise is the market-leading SIEM solution driving outcomes across Security, IT, and DevOps teams. 
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Splunk Enterprise is the market-leading SIEM solution driving outcomes across Security, IT, and DevOps teams. The use of Splunk has increased considerably across our customer’s organizations. Therefore, there is a need to add more data sources while also retaining the data for a longer period, thus stressing the Splunk infrastructure.

The combination of Splunk SmartStore and NetApp StorageGRID is designed to provide a scalable architecture for organizations to achieve improved ingest performance with SmartStore and StorageGRID object storage and increased scalability for a Splunk environment across multiple geographical regions.

== Where to find additional information

To learn more about the information that is described in this document, review the following documents and/or websites:

* https://docs.netapp.com/us-en/storagegrid-family/[NetApp StorageGRID Documentation Resources^]

* https://docs.netapp.com[NetApp Product Documentation^]

* https://docs.splunk.com/Documentation/Splunk[Splunk Enterprise Documentation^]

* https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore[Splunk Enterprise About SmartStore^]

* https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview[Splunk Enterprise Distributed Deployment Manual^]

* https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers[Splunk Enterprise Managing Indexers and Clusters of Indexers^]
