---
sidebar: sidebar
permalink: data-analytics/stgr-splunkss-solution-benefits.html
keywords: benefits, performance, multi-site, scalability, capacity, availability, cache
summary: The solution allows adding compute, hot storage, or S3 resources to meet the growing demand in terms of the number of users or ingest rate across single and multi-site deployments.
---

= Benefits of this solution
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The solution allows adding compute, hot storage, or S3 resources to meet the growing demand in terms of the number of users or ingest rate across single and multi-site deployments.

* *Performance.* The combination of Splunk SmartStore and NetApp StorageGRID provides fast migration of data between hot buckets and warm buckets using object storage. StorageGRID turbocharges the migration process by providing fast performance for large object workloads.
* *Multisite ready.* The StorageGRID distributed architecture allows Splunk SmartStore to extend deployments across single and multiple sites through a single global namespace where data can be accessed from any site regardless of where the data lives.
* *Improved scalability.* Scale storage resources independently from compute resources to meet evolving needs and demands in your Splunk environment, thereby providing improved TCO.
* *Capacity.* Meet rapidly growing volumes in Splunk deployment with StorageGRID by scaling a single namespace to over 560PB.
* *Data availability.* Optimize data availability, performance, geo-distribution, retention, protection, and storage costs with metadata-driven policies that can adjust dynamically as the business value of your data evolves.

Increase performance with the SmartStore cache, which is a component of the indexer that handles the transfer of bucket copies between local (hot) and remote (warm) storage. Splunk sizing for this solution is based on the https://docs.splunk.com/Documentation/Splunk/8.0.5/Capacity/Summaryofperformancerecommendations[guidelines provided by Splunk^]. The solution allows adding compute, hot storage, or S3 resources to meet the growing demand in terms of the number of users or ingest rate across single and multi-site deployments.

