---
sidebar: sidebar
permalink: data-analytics/stgr-splunkss-solution-overview.html
keywords: storagegrid, splunk enterprise, smartstore, object storage, machine data
summary: This page describes the components used to complete this solution, including NetApp StorageGRID, Splunk Enterprise, and Splunk SmartStore.
---

= Solution overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-07-27 16:41:18.417801
//

link:stgr-splunkss-intelligent-tiering-and-cost-savings.html[Previous: Intelligent tiering and cost savings.]

[.lead]
== NetApp StorageGRID

NetApp StorageGRID is a high-performance and cost-effective object storage platform. It offers intelligent, policy-driven global data management using a distributed, node-based grid architecture. It simplifies the management of petabytes of unstructured data and billions of objects through its ubiquitous global object namespace combined with sophisticated data management features. Single-call object access extends across sites and simplifies high availability architectures while ensuring continual object access regardless of site or infrastructure outages.

Multitenancy allows multiple cloud and enterprise unstructured data applications to be securely serviced within the same grid, increasing the ROI and use cases for StorageGRID. Multiple service levels can be created with metadata-driven object lifecycle policies, optimizing durability, protection, performance, and locality across multiple geographies. Users can adjust policies and realign the data landscape non-disruptively as their requirements change.

SmartStore leverages StorageGRID as the remote storage tier and allows customers to deploy multiple geographically distributed sites for robust availability and durability, presented as a single object namespace. This allows Splunk SmartStore to take advantage of the StorageGRID high performance, dense capacity, and ability to scale to hundreds of nodes across multiple physical sites using a single URL to interact with the objects. This single URL also allows storage expansion, upgrades, and repairs to be nondisruptive, even beyond a single site. The StorageGRID unique data management policy engine provides optimized levels of performance and durability and adherence to data locality requirements.

== Splunk Enterprise

Splunk, a leader in the collection and analysis of machine-generated data, helps simplify and modernize IT thru its operational analytics capabilities. It also expands into business analytics, security, and IoT use cases. Storage is a critical enabler for a successful Splunk software deployment.

Machine-generated-data is the fastest-growing type of big data. The format is unpredictable and comes from many different sources, often at high rates and in great volumes. These workload characteristics are often referred to as digital exhaust. Splunk SmartStore helps to make sense of this data and provides smart data tiering for optimized placement of hot and warm data on the most cost-effective storage tier.

== Splunk SmartStore

Splunk SmartStore is an indexer capability that uses object storage (also referred to as remote storage or remote storage tiers) such as StorageGRID to store warm data using the S3 protocol.

As a deployment's data volume increases, demand for storage typically outpaces demand for computer resources. SmartStore allows you to manage your indexer storage and compute resources cost-effectively by scaling compute and storage separately.

SmartStore introduces a remote storage tier, using the S3 protocol, and a cache manager. These features allow data to reside either locally on indexers or remote storage. The cache manager, which resides on the indexer, manages data movement between the indexer and the remote storage tier. Data is stored in buckets (hot and warm) along with bucket metadata.

With SmartStore, you can reduce the indexer storage footprint to a minimum and choose I/O-optimized compute resources because most data resides on the remote storage tier. The indexer maintains a local cache, representing the minimal amount of data necessary to return the results requested and predicted. The local cache contains hot buckets, copies of warm buckets participating in active or recent searches, and bucket metadata.

Splunk SmartStore with StorageGRID enables customers to incrementally scale the environment with high-performance and cost-effective remote storage while providing a high degree of elasticity to the overall solution. This allows customers to add any components (hot storage and/or warm S3 storage) in any given quantity at any given time, whether they need more indexers, change data retention, or to increase the ingest rate without any disruption.

link:stgr-splunkss-flexible-storagegrid-features-for-splunk-smartstore.html[Next: Flexible StorageGRID features for Splunk SmartStore.]
