---
sidebar: sidebar
permalink: data-analytics/stgr-splunkss-conclusion.html
keywords: conclusion, references, history
summary: Splunk Enterprise is the market-leading SIEM solution driving outcomes across Security, IT, and DevOps teams. The use of Splunk has increased considerably across our customer’s organizations. Therefore, there is a need to add more data sources while also retaining the data for a longer period, thus stressing the Splunk infrastructure. 
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-07-27 16:41:18.475127
//

link:stgr-splunkss-single-site-smartstore-performance.html[Previous: Single-site SmartStore performance.]

[.lead]
Splunk Enterprise is the market-leading SIEM solution driving outcomes across Security, IT, and DevOps teams. The use of Splunk has increased considerably across our customer’s organizations. Therefore, there is a need to add more data sources while also retaining the data for a longer period, thus stressing the Splunk infrastructure.

The combination of Splunk SmartStore and NetApp StorageGRID is designed to provide a scalable architecture for organizations to achieve improved ingest performance with SmartStore and StorageGRID object storage and increased scalability for a Splunk environment across multiple geographical regions.

== Where to find additional information

To learn more about the information that is described in this document, review the following documents and/or websites:

* NetApp StorageGRID Documentation Resources
+
https://www.netapp.com/data-storage/storagegrid/documentation/[https://www.netapp.com/data-storage/storagegrid/documentation/^]

* NetApp Product Documentation
+
https://docs.netapp.com[https://docs.netapp.com^]

* Splunk Enterprise Documentation
+
https://docs.splunk.com/Documentation/Splunk[https://docs.splunk.com/Documentation/Splunk^]

* Splunk Enterprise About SmartStore
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore[https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/AboutSmartStore^]

* Splunk Enterprise Distributed Deployment Manual
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview[https://docs.splunk.com/Documentation/Splunk/8.0.6/Deploy/Distributedoverview^]

* Splunk Enterprise Managing Indexers and Clusters of Indexers
+
https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers[https://docs.splunk.com/Documentation/Splunk/8.0.6/Indexer/Aboutindexesandindexers^]

== Version history

|===
|Version |Date |Document version history

|1.0
|July 2022
|Initial release.
|===
