---
sidebar: sidebar
permalink: hyperv/hyperv-deploy-conclusion.html
keywords: hyperv, hyper-v, deploy, netapp, virtualization
summary: "The solution provides the steps required to deploy Hyper-V on NetApp storage"   
---

= Deploying Microsoft Hyper-V on NetApp Storage: Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
ONTAP is the optimal shared storage foundation to deploy a variety of IT workloads. ONTAP AFF or ASA platforms are both flexible and scalable for multiple use cases and applications. Windows Server 2022 and Hyper-V enabled on it is one common use case as the virtualization solution, which is described in this document. The flexibility and scalability of ONTAP storage and associated features enable customers to start out with a right-sized storage layer that can grow with and adapt to their evolving business requirements. In current market conditions, Hyper-V offers a perfect alternate hypervisor option which provides most of the functionalities that was provided VMware.
