:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

. Configure the credentials.
. Create credential types. For solutions involving ONTAP, you must configure the credential type to match username and password entries.
.. Navigate to Administration → Credential Types, and click Add.
.. Provide the name and description.
.. Paste the following content in Input Configuration:
+

[source, cli]
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true


.. Paste the following content into Injector Configuration:
+

[source, cli]
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
.. Navigate to Resources → Credentials, and click Add.
.. Enter the name and organization details for Oracle
.. Select the Machine credential type.
.. Under Type Details, enter the Username and Password for the Oracle hosts.
.. Select the correct Privilege Escalation Method, and enter the username and password.
.. Repeat process if needed for a different credential for the dr_oracle host.
