
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

== AWX/Tower Oracle Data Protection

=== 1. Configure and launch the job template.

. Create the job template.
.. Navigate to Resources → Templates → Add and click Add Job Template.
.. Enter the name and description
.. Select the Job type; Run configures the system based on a playbook, and Check performs a dry run of a playbook without actually configuring the system.
.. Select the corresponding inventory, project, playbook, and credentials for the playbook.
.. Select the all_playbook.yml as the default playbook to be executed.
.. Paste global variables copied from step 4 into the Template Variables field under the YAML tab.
.. Check the box Prompt on Launch in the Job Tags field.
.. Click Save.
. Launch the job template.
.. Navigate to Resources → Templates.
.. Click the desired template and then click Launch.
.. When prompted on launch for Job Tags, type in requirements_config. You might need to click the Create Job Tag line below requirements_config to enter the job tag.
+
NOTE: requirements_config ensures that you have the correct libraries to run the other roles.

.. Click Next and then Launch to start the job.
.. Click View → Jobs to monitor the job output and progress.
.. When prompted on launch for Job Tags, type in ontap_config. You might need to click the Create "Job Tag" line right below ontap_config to enter the job tag.
.. Click Next and then Launch to start the job.
.. Click View → Jobs to monitor the job output and progress
.. After the ontap_config role has completed, run the process again for linux_config.
.. Navigate to Resources → Templates.
.. Select the desired template and then click Launch.
.. When prompted on launch for the Job Tags type in linux_config, you might need to select the Create "job tag" line right below linux_config to enter the job tag.
.. Click Next and then Launch to start the job.
.. Select View → Jobs to monitor the job output and progress.
.. After the linux_config role has completed, run the process again for oracle_config.
.. Go to Resources → Templates.
.. Select the desired template and then click Launch.
.. When prompted on launch for Job Tags, type oracle_config. You might need to select the Create "Job Tag" line right below oracle_config to enter the job tag.
.. Click Next and then Launch to start the job.
.. Select View → Jobs to monitor the job output and progress.
