---
sidebar: sidebar
permalink: ent-apps-db/hybrid_dbops_snapcenter_requirements.html
summary: hybrid cloud database solutions with SnapCenter Requirements
keywords: netapp, solutions, database, SnapCenter
---

= Hybrid Cloud Database Solutions with SnapCenter Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

[.lead]
The solutions are designed in a hybrid cloud setting to support on-prem production databases that burst to all popular public cloud of choice for DEV / TEST database operation as well as disaster recovery when needed.

The solutions support all databases that are currently supported by NetApp SnapCenter although only Oracle and SQL Server databases are demonstrated in solutions. The solutions are validated with virtualized database workloads although bare-metal workloads are supported as well.

It is assumed that production database servers are hosted on-prem with DB volumes presented to DB hosts from ONTAP storage cluster. SnapCenter software is installed on-prem for database backup and data replication to cloud. An Ansible controller is recommendated but not required for database deployment automation or OS kernel and DB configuration syncing up with standby DR instance or DEV and TEST instances in public cloud.

The following are the details of the solution requirements:

== Requirements

[width=100%, cols="3, 9",grid="all"]
|===
|Environment | Requirements

.7+| *On-prem* |
Any supported databases and versions by SnapCenter
| SnapCenter v4.4 or higher
| Ansible v2.09 or higher
| ONTAP cluster 9.x
| Intercluster lifs configured
| Connectivity from ON-prem to cloud VPC (VPN, Interconnect etc.)
| Networking ports open
- ssh 22
- tcp 8145, 8146, 10000, 11104, 11105
.3+| *Cloud - AWS* |
https://docs.netapp.com/us-en/occm/task_creating_connectors_aws.html[Cloud Manager Connector^]
| https://docs.netapp.com/us-en/occm/task_getting_started_aws.html[Cloud Volumes ONTAP^]
| Matching DB OS EC2 instances to On-prem
.3+| *Cloud - Azure* |
https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html[Cloud Manager Connector^]
| https://docs.netapp.com/us-en/occm/task_getting_started_azure.html[Cloud Volumes ONTAP^]
| Matching DB OS Azure Virtual Machines to On-prem
.3+| *Cloud - GCP* |
https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html[Cloud Manager Connector^]
| https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html[Cloud Volumes ONTAP^]
| Matching DB OS Google Compute Engine instances to On-prem
|===
