---
sidebar: sidebar
permalink: ent-apps-db/hybrid_dbops_snapcenter_prerequisite.html
summary: hybrid cloud database solutions with SnapCenter prerequisites
keywords: netapp, solutions, database, SnapCenter, prerequisites
---

= Hybrid Cloud Database Workflow Prerequisites
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

[.lead]
Certain prerequisites needs to be configured at both on-prem and cloud before any actual hybrid cloud database workload execution. Following provide a high level summary and the details of the prerequisites configuration can be drilled down as needed through the attached links.

== On Premises

* SnapCenter Installation and Configuration
* On-prem Database Server Storage Configuration
* Licensing Requirements
* Networking and Security
* Automation

== Cloud

* A NetApp Cloud Central Login
* Network Access from a Web Browser to Several Endpoints
* A Network Location for a connector
* Cloud Provider Permissions
* Networking for Individual Services

Considerations:

. Where to Deploy Cloud Manager Connector?
. Cloud Volume ONTAP Sizing and Architecture
. Single Node or High Availability?

Click on following links for details:

link:hybrid_dbops_snapcenter_prereq_onprem.html[On Premises], link:hybrid_dbops_snapcenter_prereq_cloud.html[Public Cloud]
