---
sidebar: sidebar
permalink: ent-apps-db/hybrid_dbops_snapcenter_requirements.html
summary: hybrid cloud database solutions with SnapCenter Requirements
keywords: netapp, solutions, database, SnapCenter
---

= Hybrid Cloud Database Solutions with SnapCenter Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

[.lead]
The solutions are designed in a hybrid cloud setting to support on-prem production databases that burst to all popular public cloud of choice for DEV / TEST database operation as well as disaster recovery when needed.

The solutions support all databases that are currently supported by NetApp SnapCenter although only Oracle and SQL Server databases are demonstrated in solutions. The solutions are validated with virtualized database workloads although bare-metal workloads are supported as well.

It is assumed that production database servers are hosted on-prem with DB volumes presented to DB hosts from ONTAP storage cluster. SnapCenter software is installed on-prem for database backup and data replication to cloud. An Ansible controller is setup for database deployment automation or OS kernel and DB configuration syncing up with standby DR instance or DEV and TEST instances in public cloud.

The following are details of solution requirements:

== Requirements

[width=100%, cols="3, 9",grid="all"]
|===
|Environment | Requirements

.7+| *On-prem* |
Any supported databases and versions by SnapCenter
| SnapCenter v4.4 or higher
| Ansible v2.10 or higher
| ONTAP cluster 9.x
| Intercluster lifs configured
| VPN connection from ON-prem to cloud VPC
| Networking ports open
- ssh 22
- tcp 8145, 8146
.4+| *Cloud* |
AWS, Azure, GCP
| Cloud manager / connector
| CVO
| Matching DB OS instances to On-prem in the cloud of choice
|===
