---
sidebar: sidebar
permalink: ent-apps-db/hybrid_dbops_snapcenter_getting_started.html
summary: hybrid cloud database solutions with SnapCenter getting started
keywords: netapp, solutions, database, SnapCenter, "getting started"
---

= Hybrid Cloud Database Workflow Getting Started
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

[.lead]
This section provides a summary of tasks that needs to be completed to meet prerequisites requirements as outlined in previous section. Following provide a high level tasks list for both on premises and public cloud. The details of processes and procedures can be drilled down by clicking on the relevant links.

== On Premises

* Setup Database Admin User in SnapCenter

* SnapCenter Plugin Installation Prerequisites

* SnapCenter Host Plugin Installation

* DB Resource Discovery

* Setup Storage Cluster Peering and DB Volumes Replication

* Add CVO Database Storage SVM to SnapCenter

* Setup Database Backup Policy in SnapCenter

* Implement Backup Policy to Protect database

* Validate Backup


== Public Cloud - AWS

* Pre-flight check

* Steps to deploy Cloud Manager and Cloud Volumes ONTAP in AWS

* Deploy EC2 Compute Instance for Database Workload

Click on following links for details:

link:hybrid_dbops_snapcenter_getting_started_onprem.html[On Premises], link:hybrid_dbops_snapcenter_getting_started_aws.html[Public Cloud - AWS]
