---
sidebar: sidebar
permalink: ent-apps-db/hybrid_dbops_snapcenter_usecases.html
summary: Collection of database solutions use cases using SnapCenter in hybrid cloud
keywords: netapp, solutions, database, SnapCenter
---

= Hybrid Cloud Database Solutions with SnapCenter Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

[.lead]
The solutions provide NetApp field and customers with direct instruction and guidance on configuring, operating and migrating databases in a hybrid cloud environment using SnapCenter GUI tool, for the following use case(s)

* Database DEV / TEST OPS in Hybrid Cloud
* Database Disaster Recovery in Hybrid Cloud

Today, many enterprise databases are still residing in private corporate data centers for performance, security and/or other reasons. The hybrid cloud database solutions empower enterprises to operate their primary databases on site while leveraging public cloud for DEV/TEST database operation as well as for disaster recovery to reduce licensing and operational costs.

Many enterprise databases such as Oracle, SQL Server, SAP HANA etc. carry very high licensing and operational costs. Many customers pay a perpetual one time license fee as well as annual support cost based on the number of compute cores in their database environment regardless they are for development, test, production purposes, or disaster recovery. Many of those environments might not be fully utilized throughout applications lifecycle.

The solutions provide an option for customers to potentially reduce their licensable cores count by moving their database environments devoted to development or test or disaster recovery to cloud. Leveraging the public cloud scale, redundancy, high availability, as well as consumption based billing model, the cost saving in licensing and operation can be substantial, while not sacrificing any application usability or availability.

The solutions demonstrate that using NetApp SnapCenter GUI based software tool and NetApp ONTAP Data Fabric SnapMirror, the hybrid cloud databases operations can be easily setup, implemented, and operated as smooth as they can be.       
