---
sidebar: sidebar
permalink: ent-apps-db/saphana_aff_fc_update_history.html
keywords:
summary:
---

= Update history
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


The following technical changes have been made to this solution since its original publication.

[cols=3*,options="header",cols="25,25,50"]
|===
| Version
| Date
| Update summary
| Version 1.0 | October 2015 | Initial Version
| Version 1.1 | March 2016 | Updated capacity sizing
| Version 2.0 | February 2017 | New NetApp storage systems and disk shelves
New features of ONTAP 9
New OS releases (SLES12 SP1 and RHEL 7.2)
New SAP HANA release
| Version 2.1 | July 2017 | Minor updates
| Version 3.0 | September 2018 | New NetApp storage systems
New OS releases (SLES12 SP3 and RHEL 7.4)
Additional minor updates
SAP HANA 2.0 SPS3
| Version 3.1 | November 2019 | New NetApp storage systems and NVMe shelf
New OS releases (SLES12 SP4, SLES 15, and RHEL 7.6)
Additional minor updates
| Version 3.2 | April 2020 | New AFF ASA series storage systems
Introduced multiple data partition feature available since SAP HANA 2.0 SPS4
| Version 3.3 | June 2020 | Additional information about optional functionalities 
Minor updates
