---
sidebar: sidebar
permalink: ent-apps-db/saphana-dr-anf_mount_the_volumes_at_the_target_host.html
keywords: mount, volume, target, host, sap, hana, azure
summary: The volumes can now be mounted at the target host, based on the `/etc/fstab` file created before.
---

= Mount the volumes at the target host
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-24 12:07:40.426774
//

link:saphana-dr-anf_break_and_delete_replication_peering.html[Previous: Break and delete replication peering.]

The volumes can now be mounted at the target host, based on the `/etc/fstab` file created before.

....
vm-pr1:~ # mount -a
....

The following output shows the required file systems.

....
vm-pr1:~ # df
Filesystem                                  1K-blocks     Used    Available Use% Mounted on
devtmpfs                                      8201112        0      8201112   0% /dev
tmpfs                                        12313116        0     12313116   0% /dev/shm
tmpfs                                         8208744     9096      8199648   1% /run
tmpfs                                         8208744        0      8208744   0% /sys/fs/cgroup
/dev/sda4                                    29866736  2543948     27322788   9% /
/dev/sda3                                     1038336    79984       958352   8% /boot
/dev/sda2                                      524008     1072       522936   1% /boot/efi
/dev/sdb1                                    32894736    49180     31151556   1% /mnt
10.0.2.4:/PR1-log-mnt00001-dr            107374182400     6400 107374176000   1% /hana/log/PR1/mnt00001
tmpfs                                         1641748        0      1641748   0% /run/user/0
10.0.2.4:/PR1-shared-sm-dest/hana-shared 107377178368 11317248 107365861120   1% /hana/shared
10.0.2.4:/PR1-shared-sm-dest/usr-sap-PR1 107377178368 11317248 107365861120   1% /usr/sap/PR1
10.0.2.4:/hanabackup-sm-dest             107379678976 35249408 107344429568   1% /hanabackup
10.0.2.4:/PR1-data-mnt0001-sm-dest       107376511232  6696960 107369814272   1% /hana/data/PR1/mnt00001
vm-pr1:~ #
....

link:saphana-dr-anf_hana_database_recovery_01.html[Next: HANA database recovery.]
