---
sidebar: sidebar
permalink: ent-apps-db/saphana_aff_nfs_update_history.html
keywords:
summary:
---

= Update history
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/


The following technical changes have been made to this solution since its original publication.

[cols=3*,options="header",cols="25,25,50"]
|===
| Version
| Date
| Update summary
| Version 1.0 | October 2015 | Initial version
| Version 1.1 | March 2016 | Updated capacity sizing
Updated mount options for `/hana/shared`
Updated sysctl parameter
| Version 2.0 | February 2017 | New NetApp storage systems and disk shelves
New features of ONTAP 9
Support for 40GbE
New OS releases (SUSE Linux Enterprise Server 12 SP1 and Red Hat Enterprise Linux 7.2)
New SAP HANA release
| Version 2.1 | July 2017 | Minor updates
|Version 3.0 | September 2018 | New NetApp storage systems
Support for 100GbE
New OS releases (SUSE Linux Enterprise Server 12 SP3 and Red Hat Enterprise Linux 7.4)
Additional minor changes
SAP HANA 2.0 SPS3
| Version 3.1 | October 2019 | New NetApp storage systems and NVMe shelf
New OS releases (SUSE Linux Enterprise Server 12 SP4, SUSE Linux Enterprise Server 15, and Red Hat Enterprise Linux 7.6)
Max data volume size
Minor changes
| Version 3.2 | December 2019 | New NetApp storage systems
New OS release SUSE Linux Enterprise Server 15 SP1
| Version 3.3 | March 2020 | Support for nconnect for NFSv3
New OS release Red Hat Enterprise Linux 8
| Version 3.4 | May 2020 | Support for multiple data volume partitions available with SAP HANA 2.0 SPS4
| Version 3.5 | June 2020 | Additional information about optional functionalities
Minor updates
|===
