---
sidebar: sidebar
permalink: ent-apps-db/saphana_fas_fc_sap_hana_storage_connector_api.html
keywords: sap, hana, storage, connector, api, fas, fc
summary: A storage connector is required only in multiple-host environments that have failover capabilities.
---

= SAP HANA storage connector API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 16:40:51.358758
//
link:saphana_fas_fc_storage_controller_setup.html[Previous: Storage controller setup.]

A storage connector is required only in multiple-host environments that have failover capabilities. In multiple-host setups, SAP HANA provides high-availability functionality so that an SAP HANA database host can fail over to a standby host. In this case, the LUNs of the failed host are accessed and used by the standby host. The storage connector is used to make sure that a storage partition can be actively accessed by only one database host at a time.

In SAP HANA multiple-host configurations with NetApp storage, the standard storage connector delivered by SAP is used. The “SAP HANA FC Storage Connector Admin Guide” can be found as an attachment to https://service.sap.com/sap/support/notes/1900823[SAP note 1900823^].

link:saphana_fas_fc_host_setup.html[Next: Host setup.]
