---
sidebar: sidebar
permalink: ent-apps-db/saphana_fas_fc_sap_hana_software_installation.html
keywords: install, san, hana, software, multiple, host, system, single,
summary: Below are the requirements for SAP HANA software installation.
---

= SAP HANA software installation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-20 16:40:51.397835
//

== Install on single-host system

SAP HANA software installation does not require any additional preparation for a single-host system.

== Install on multiple-host system

[NOTE]
The following installation procedure is based on SAP HANA 1.0 SPS12 or later.

Before beginning the installation, create a `global.ini` file to enable use of the SAP storage connector during the installation process. The SAP storage connector mounts the required file systems at the worker hosts during the installation process. The `global.ini` file must be available in a file system that is accessible from all hosts, such as the `/hana/shared/SID` file system.

Before installing SAP HANA software on a multiple-host system, the following steps must be completed:

. Add the following mount options for the data LUNs and the log LUNs to the `global.ini` file:

** `relatime` and `inode64` for the data and log file system

. Add the WWIDs of the data and log partitions. The WWIDs must match the alias names configured in the `/etc/multipath.conf` file.
+
The following output shows an example of a 2+1 multiple-host setup in which the system identifier (SID) is SS3.
+
....
stlrx300s8-6:~ # cat /hana/shared/global.ini
[communication]
listeninterface = .global
[persistence]
basepath_datavolumes = /hana/data/SS3
basepath_logvolumes = /hana/log/SS3
[storage]
ha_provider = hdb_ha.fcClient
partition_*_*__prtype = 5
partition_*_data__mountoptions = -o relatime,inode64
partition_*_log__mountoptions = -o relatime,inode64,nobarrier
partition_1_data__wwid = hana- SS3_data_mnt00001
partition_1_log__wwid = hana- SS3_log_mnt00001
partition_2_data__wwid = hana- SS3_data_mnt00002
partition_2_log__wwid = hana- SS3_log_mnt00002
[system_information]
usage = custom
[trace]
ha_fcclient = info
stlrx300s8-6:~ #
....
+

If LVM is used, the needed configuration is different. The example below shows a 2+1 multiple-host setup with SID=FC5.
+

....
sapcc-hana-tst-03:/hana/shared # cat global.ini
[communication]
listeninterface = .global
[persistence]
basepath_datavolumes = /hana/data/FC5
basepath_logvolumes = /hana/log/FC5
[storage]
ha_provider = hdb_ha.fcClientLVM
partition_*_*__prtype = 5
partition_*_data__mountOptions = -o relatime,inode64
partition_*_log__mountOptions = -o relatime,inode64
partition_1_data__lvmname = FC5_data_mnt00001-vol
partition_1_log__lvmname = FC5_log_mnt00001-vol
partition_2_data__lvmname = FC5_data_mnt00002-vol
partition_2_log__lvmname = FC5_log_mnt00002-vol
sapcc-hana-tst-03:/hana/shared #
....
+

Using the SAP `hdblcm` installation tool, start the installation by running the following command at one of the worker hosts. Use the `addhosts` option to add the second worker (sapcc-hana-tst-04) and the standby host (sapcc-hana-tst-05).
The directory where the prepared the `global.ini` file has been stored is included with the `storage_cfg` CLI option (`--storage_cfg=/hana/shared`).
Depending on the OS version being used, it might be necessary to install phyton 2.7 before installing the SAP HANA database.

....
sapcc-hana-tst-03:/mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_LCM_LINUX_X86_64 # ./hdblcm --action=install --addhosts=sapcc-hana-tst-04:role=worker:storage_partion=2,sapcc-hana-tst-05:role:=standby --storage_cfg=/hana(shared/shared
SAP HANA Lifecycle Management - SAP HANA Database 2.00.052.00.1599235305
************************************************************************
Scanning software locations...
Detected components:
    SAP HANA AFL (incl.PAL,BFL,OFL) (2.00.052.0000.1599259237) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_AFL_LINUX_X86_64/packages
    SAP HANA Database (2.00.052.00.1599235305) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server
    SAP HANA Database Client (2.5.109.1598303414) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_CLIENT_LINUX_X86_64/client
    SAP HANA Smart Data Access (2.00.5.000.0) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/SAP_HANA_SDA_20_LINUX_X86_64/packages
    SAP HANA Studio (2.3.54.000000) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_STUDIO_LINUX_X86_64/studio
    SAP HANA Local Secure Store (2.4.24.0) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HANA_LSS_24_LINUX_X86_64/packages
    SAP HANA XS Advanced Runtime (1.0.130.519) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_RT_10_LINUX_X86_64/packages
    SAP HANA EML AFL (2.00.052.0000.1599259237) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_EML_AFL_10_LINUX_X86_64/packages
    SAP HANA EPM-MDS (2.00.052.0000.1599259237) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/SAP_HANA_EPM-MDS_10/packages
    GUI for HALM for XSA (including product installer) Version 1 (1.014.1) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACALMPIUI14_1.zip
    XSAC FILEPROCESSOR 1.0 (1.000.85) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACFILEPROC00_85.zip
    SAP HANA tools for accessing catalog content, data preview, SQL console, etc. (2.012.20341) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSAC_HRTT_20/XSACHRTT12_20341.zip
    XS Messaging Service 1 (1.004.10) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACMESSSRV04_10.zip
    Develop and run portal services for customer apps on XSA (1.005.1) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACPORTALSERV05_1.zip
    SAP Web IDE Web Client (4.005.1) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSAC_SAP_WEB_IDE_20/XSACSAPWEBIDE05_1.zip
    XS JOB SCHEDULER 1.0 (1.007.12) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACSERVICES07_12.zip
    SAPUI5 FESV6 XSA 1 - SAPUI5 1.71 (1.071.25) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACUI5FESV671_25.zip
    SAPUI5 SERVICE BROKER XSA 1 - SAPUI5 Service Broker 1.0 (1.000.3) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACUI5SB00_3.zip
    XSA Cockpit 1 (1.001.17) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACXSACOCKPIT01_17.zip
SAP HANA Database version '2.00.052.00.1599235305' will be installed.
Select additional components for installation:
  Index | Components | Description
  ---------------------------------------------------------------------------------------------
  1     | all        | All components
  2     | server     | No additional components
  3     | client     | Install SAP HANA Database Client version 2.5.109.1598303414
  4     | lss        | Install SAP HANA Local Secure Store version 2.4.24.0
  5     | studio     | Install SAP HANA Studio version 2.3.54.000000
  6     | smartda    | Install SAP HANA Smart Data Access version 2.00.5.000.0
  7     | xs         | Install SAP HANA XS Advanced Runtime version 1.0.130.519
  8     | afl        | Install SAP HANA AFL (incl.PAL,BFL,OFL) version 2.00.052.0000.1599259237
  9     | eml        | Install SAP HANA EML AFL version 2.00.052.0000.1599259237
  10    | epmmds     | Install SAP HANA EPM-MDS version 2.00.052.0000.1599259237
Enter comma-separated list of the selected indices [3]: 2,3
Enter Installation Path [/hana/shared]:
Enter Local Host Name [sapcc-hana-tst-03]:
....

Verify that the installation tool installed all selected components at all worker and standby hosts.
