---
sidebar: sidebar
permalink: ent-apps-db/saphana-dr-anf_mount_the_new_volumes_at_the_target_host.html
keywords: mount, new, volumes, target, host, azure, sap, hana
summary: The new volumes can now be mounted at the target host, based on the /etc/fstab file created before.
---

= Mount the new volumes at the target host
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-24 12:07:40.377280
//

link:saphana-dr-anf_create_new_volumes_based_on_snapshot_backups_at_the_disaster_recovery_site.html[Previous: Create new volumes based on snapshot backups at the disaster recovery site.]

The new volumes can now be mounted at the target host, based on the `/etc/fstab` file created before.

....
vm-pr1:~ # mount -a
....

The following output shows the required file systems.

....
vm-pr1:/hana/data/PR1/mnt00001/hdb00001 # df
Filesystem                                        1K-blocks     Used    Available Use% Mounted on
devtmpfs                                            8190344        8      8190336   1% /dev
tmpfs                                              12313116        0     12313116   0% /dev/shm
tmpfs                                               8208744    17292      8191452   1% /run
tmpfs                                               8208744        0      8208744   0% /sys/fs/cgroup
/dev/sda4                                          29866736  2438052     27428684   9% /
/dev/sda3                                           1038336   101520       936816  10% /boot
/dev/sda2                                            524008     1072       522936   1% /boot/efi
/dev/sdb1                                          32894736    49176     31151560   1% /mnt
tmpfs                                               1641748        0      1641748   0% /run/user/0
10.0.2.4:/PR1-log-mnt00001-dr                  107374182400      256 107374182144   1% /hana/log/PR1/mnt00001
10.0.2.4:/PR1-data-mnt00001-sm-dest-clone      107377026560  6672640 107370353920   1% /hana/data/PR1/mnt00001
10.0.2.4:/PR1-shared-sm-dest-clone/hana-shared 107377048320 11204096 107365844224   1% /hana/shared
10.0.2.4:/PR1-shared-sm-dest-clone/usr-sap-PR1 107377048320 11204096 107365844224   1% /usr/sap/PR1
10.0.2.4:/hanabackup-sm-dest-clone             107379429120 35293440 107344135680   1% /hanabackup
....

link:saphana-dr-anf_hana_database_recovery.html[Next: HANA database recovery.]
