---
sidebar: sidebar
permalink: ent-db/sql-srv-anf_conclusion.html
keywords: takeaways, hybrid-cloud
summary: Whether you are targeting an all-cloud or hybrid cloud with stretch databases, Azure NetApp Files provides excellent options to deploy and manage the database workloads while reducing your TCO by making data requirements seamless to the application layer.
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-06-05 07:52:13.949117
//

Whether you are targeting an all-cloud or hybrid cloud with stretch databases, Azure NetApp Files provides excellent options to deploy and manage the database workloads while reducing your TCO by making data requirements seamless to the application layer.

This document covers recommendations for planning, designing, optimizing, and scaling Microsoft SQL Server deployments with Azure NetApp Files, which can vary greatly between implementations. The right solution depends on both the technical details of the implementation and the business requirements driving the project.

=== Takeaways

The key points of this document include:

* You can now use Azure NetApp Files to host the database and file share witness for SQL Server cluster.
* You can boost the application response times and deliver 99.9999% availability to provide access to SQL Server data when and where it is needed.
* You can simplify the overall complexity of the SQL Server deployment and ongoing management, such as raid striping, with simple and instant resizing.
* You can rely on intelligent operations features to help you deploy SQL Server databases in minutes and speed development cycles.
* If Azure Cloud is the destination, Azure NetApp Files is the right storage solution for optimized deployment.
