---
sidebar: sidebar
permalink: containers/devops_with_netapp/dwn_overview_astra.html
keywords: NetApp Astra Control, Astra Control Center, Application, Trident, Astra Trident, Helm, Operator, ONTAP, OpenShift, Kubernetes, Red Hat OpenShift
summary: NetApp Astra Control Center offers a rich set of storage and application-aware data management services for stateful Kubernetes workloads, deployed in an on-prem environment, powered by NetApp’s trusted data protection technology.
---
= NetApp Astra Control overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/
:k8s_distribution_name: Kubernetes

include::../../_include/containers_common_intro_sections.adoc[tags=astra_cc_overview]

For a detailed installation and operations guide on Astra Control Center, follow the documentation link:https://docs.netapp.com/us-en/astra-control-center/index.html[here^].

== Astra Control Center automation

Astra Control Center has a fully functional REST API for programmatic access. Users can use any programming language or utility to interact with Astra Control REST API endpoints. To learn more about this API, see the documentation link:https://docs.netapp.com/us-en/astra-automation/index.html[here^].

If you are looking for a ready-made software development toolkit for interacting with Astra Control REST APIs, NetApp provides a toolkit with Astra Control Python SDK,  which you can download link:https://github.com/NetApp/netapp-astra-toolkits/[here^].

If programming is not apropriate for your situation and you would like to use a configuration management tool, you can clone and run the Ansible playbooks that NetApp publishes link:https://github.com/NetApp-Automation/na_astra_control_suite[here^].
