---
sidebar: sidebar
permalink: containers/devops_with_netapp/dwn_solution_overview.html
keywords: DevOps, Netapp, Astra Trident, Astra Control, Astra
summary: This technical report outlines how NetApp makes DevOps use-cases easy and efficient in multiple fronts, when using containerized applications. It starts by detailing the NetApp storage systems and their integration with Kubernetes platforms by making use of the Astra portfolio. Lastly, a number of solution validations and real world use cases are explored and documented.
---

= NVA-xxxx: DevOps with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/
:k8s_distribution_name: Red Hat OpenShift, VMware Tanzu, Anthos by Google Cloud etc.



Alan Cowles and Nikhil M Kulkarni, NetApp

This technical report outlines how NetApp makes DevOps use-cases easy and efficient in multiple fronts, when using containerized applications. It starts by detailing the NetApp storage systems and their integration with Kubernetes platforms by making use of the Astra portfolio. Lastly, a number of solution validations and real world use cases are explored and documented.

== Business Value

include::containers/common_intro_sections.adoc[tags=devops_business_value_intro]

== Technology Overview

The DevOps with NetApp solution comprises of the following major components:

=== Container Orchestration

There are numerous container orchestration platforms in use today. Though most of these platforms have been built upon Vanilla Kubernetes, each of them have their own set of pros and cons. So it is important to understand the feature set and integrations when selecting a container orchestration platform for DevOps workflows. With NetApp Astra's suite of products, we support the following platforms for full-fledged DevOps use-cases:

* https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift]
* https://rancher.com/[Rancher]
* https://kubernetes.io/[Vanilla Kubernetes]


=== NetApp Storage Systems

include::containers/common_intro_sections.adoc[tags=solution_overview_netapp_storage_intro]

=== NetApp Storage Integrations

include::containers/common_intro_sections.adoc[tags=solution_overview_netapp_storage_integrations_intro]
