---
sidebar: sidebar
permalink: containers/devops_with_netapp/dwn_solution_overview.html
keywords: DevOps, Netapp, Astra Trident, Astra Control, Astra
summary: This technical report outlines how NetApp makes DevOps use-cases easy and efficient in multiple fronts, when using containerized applications. It starts by detailing the NetApp storage systems and their integration with Kubernetes platforms by making use of the Astra portfolio. Lastly, a number of solution validations and real world use cases are explored and documented.
---

= TR-xxxx: DevOps with NetApp Astra
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/
:k8s_distribution_name: Red Hat OpenShift, VMware Tanzu, Anthos by Google Cloud etc.



Alan Cowles and Nikhil M Kulkarni, NetApp

Over the past several years, organizations that build software have been embracing the concepts of DevOps. DevOps practices break down organizational barriers, bringing development and operations teams closer together. DevOps practices also empower the teams to accelerate delivery, increase availability, and make services and applications more stable, thus improving the team’s productivity. Automation is one key ingredient of success — from building, testing, and operating applications at scale to running a fully automated infrastructure platform or stack.

include::containers/common_intro_sections.adoc[tags=devops_business_value_intro]

Recognizing these capabilities and challenges, this technical report outlines the process of improving and simplifying DevOps use-cases for containerized applications using NetApp's wide portfolio of products.


== Technology Overview

The DevOps with NetApp solution comprises of the following major components:

=== Container Orchestration

There are numerous container orchestration platforms in use today. Though most of these platforms have been built upon Vanilla Kubernetes, each of them have their own set of pros and cons. So it is important to understand the feature set and integrations when selecting a container orchestration platform for DevOps workflows. With NetApp Astra's suite of products, we support the following platforms for full-fledged DevOps use-cases:

* https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift]
* https://rancher.com/[Rancher]
* https://kubernetes.io/[Vanilla Kubernetes]


=== NetApp Storage Systems

include::containers/common_intro_sections.adoc[tags=solution_overview_netapp_storage_intro]

=== NetApp Storage Integrations

include::containers/common_intro_sections.adoc[tags=solution_overview_netapp_storage_integrations_intro]
