---
sidebar: sidebar
permalink: containers/devops_with_netapp/dwn_solution_overview.html
keywords: DevOps, Netapp, Astra Trident, Astra Control, Astra
summary: This technical report outlines how NetApp makes DevOps use-cases easy and efficient in multiple fronts, when using containerized applications. It starts by detailing the NetApp storage systems and their integration with Kubernetes platforms by making use of the Astra portfolio. Lastly, a number of solution validations and real world use cases are explored and documented.
---

= TR-xxxx: DevOps with NetApp Astra
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/
:k8s_distribution_name: Red Hat OpenShift, VMware Tanzu, Anthos by Google Cloud etc.

Alan Cowles and Nikhil M Kulkarni, NetApp


== Use cases

The DevOps with NetApp Astra solution is architected to deliver exceptional value for customers with the following use cases:

* Easy to deploy and manage applications and development environments deployed on top of supported Kubernetes distributions.

* Discussion of real-world use cases for DevOps workflows and examples of the tools and methods that NetApp can provide to make adoption and use of these methods easier.

* Exploration of how application consistent Snapshot, Backups, and Clones can be used to enhance the DevOps experience.


== Business value

Enterprises are increasingly adopting DevOps practices to create new products, shorten release cycles, and rapidly add new features. Because of their innate agile nature, containers and microservices play a crucial role in supporting DevOps practices. However, practicing DevOps at a production scale in an enterprise environment presents its own challenges and imposes certain requirements on the underlying infrastructure, such as the following:

* High availability at all layers in the stack so that workflows are never interrupted.

* Ease of deployment and management procedures for the end user.

* API-driven and programmable infrastructure to keep up with microservices and developer agility.

* Ability to scale infrastructure independently and in an automated fashion, based on workload demands.

* Protecting applications alongside their backing persistent data sets for DevOps workflows accelerate time to market by not having to rely on redeployments or manual copying of data.


Recognizing these capabilities and challenges, this technical report outlines the process of improving and simplifying DevOps use-cases for containerized applications using NetApp's wide portfolio of products.

== Technology Overview

The DevOps with NetApp solution comprises of the following major components:

=== DevOps Practices

DevOps practices tend to centralize on automated, repeatable, and easily manageable operations that enhance the development workflow by allowing the end user to control the environment in which they are developing their code. This solution will provide several examples and use cases of where this is most prevalent, and where technology provided by NetApp can be of utmost benefit.

=== Container Orchestration

There are numerous container orchestration platforms in use today. Though most of these platforms have been built upon Kubernetes, each of them have their own set of pros and cons. So it is important to understand the feature set and integrations when selecting a container orchestration platform for DevOps workflows. With NetApp Astra's suite of products, we support the following platforms for full-fledged DevOps use-cases:

* https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift] 4.6.8+
* https://rancher.com/[Rancher] 2.5+
* https://kubernetes.io/[Kubernetes] 1.19+

=== NetApp Storage Systems

include::../../_include/containers_common_intro_sections.adoc[tags=solution_overview_netapp_storage_intro]

=== NetApp Storage Integrations

include::../../_include/containers_common_intro_sections.adoc[tags=solution_overview_netapp_storage_integrations_intro]

link:dwn_overview_devops.html[Next: NetApp Storage Systems Overview]
