---
sidebar: sidebar
permalink: containers/devops_with_netapp/dwn_use_case_1_data_protection.html
keywords: NetApp Astra Control, Astra Control Center, Application, Trident, Astra Trident, Helm, Operator, ONTAP, OpenShift, Kubernetes, Red Hat OpenShift, DevOps, Data Protection, Continuous Data Protection, Induce Data Protection into CI/CD, CI, CD, CI/CD
summary: NetApp Astra Control Center offers a rich set of storage and application-aware data management services for stateful Kubernetes workloads, deployed in an on-prem environment, powered by NetApp’s trusted data protection technology.
---

= Integrate Protection into CI/CD Pipelines with NetApp Astra Control
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

One of the most common use of DevOps workflows is continuous integration and continuous deployment (CI/CD) pipelines that build, integrate, and run automated test suites on applications as developers commit new code. DevOps engineers and site reliability engineers (SREs) will likely have a few pipelines that cater to the various workflows for new feature development, regression testing, bug fixes, quality engineering, and other functions in the development process.

As teams increase their level of automation, the pace of change to in-production applications can feel overwhelming. Therefore, some teams prefer to protect the in-production applications or services. They don’t only want to protect the code and container images; they also want to protect application state and configuration data (such as Kubernetes objects and resources associated with the application) as well as an application’s persistent data.

In this use-case, we will take a closer look at a promotion-to-production pipeline that deploys a new version of an application—first into a staging environment, and then into a production environment. This example applies equally to the major public clouds or on-premises environments. Although we’re showing a deployment of one version of the app, the pipeline can also be used with other strategies, such as blue/green or canary deployment. As part of the CI/CD pipeline, we’re going to protect the application by creating a complete application backup. An application-aware backup of the in-production application and its data, state, and configuration can be useful for numerous DevOps workflows.

<<image_architecture_of_use_case_1>>

The application used for validating this use-case is https://magento.com/[Magento^], an e-commerce solution with a web-based front end; an Elasticsearch instance for search and analysis features; and a MariaDB database that tracks all the shopping inventory and transaction details. This containerized application is installed in Red Hat OpenShift cluster. Every pod in the application uses persistent volumes to store data. The persistent volumes are automatically created by NetApp® Astra™ Trident, the Container Storage Interface–compliant storage orchestrator for Kubernetes that enables storage to be provisioned on NetApp storage systems. Further, to utilize the Astra Control Center's application protection capabilities, the application in question is managed by Astra Control which will then be used to trigger application backups that store the state of the application along with the data held in persistent volumes. We will use https://github.com/NetApp/netapp-astra-toolkits[NetApp Astra Control Python SDK^] to automate the process of triggering application backups, which will be then induced into a CI/CD pipeline. This pipeline is created and executed using a popular CI/CD tool called [https://www.jenkins.io/[Jenkins^]] to automate the whole flow to build, protect and deploy the application.

Let us run through the pre-requisites and procedure to introduce protection in a CI/CD pipeline.

=== Pre-requisites

The following tools or platforms were deployed and configured as pre-requisites:

. Red Hat OpenShift Container Platform
. NetApp Astra Trident installed on OpenShift with a backend to NetApp ONTAP system configured
. A default storageclass configured, pointing to NetApp ONTAP backend
. NetApp Astra Control Center installed on OpenShift cluster.
. OpenShift cluster added as a managed cluster to Astra Control Center.
. Jenkins installed on OpenShift cluster and configured with an agent node having docker engine installed on it.

=== Installing the Application

Let's start with the initial installation of the application in the staging and production environments. For the purpose of this use-case, this step is considered as a requisite and so is performed manually. The CI/CD pipeline is used for subsequent build and deploy workflows as a result of new version releases of the application.

. Install the Magento application using bitnami helm chart on the staging environment. Few points to note in this use-case is that we use Magento helm chart version 14, along with RWX PVs for magento and mariadb.
+
----

----
+
NOTE: Magento bitnami helm chart requires a LoadBalancer service to expose Magento GUI service. We have used link:https://metallb.universe.tf/[MetalLB^] for providing on-prem load balancer service in this example.

. After a few mins, verify all the pods and services are running.
+
----

----

. Repeat the same procedure for production environment.

=== Manage the Magento application in Astra Control Center

. Navigate to `Applications` and choose the Discovered applications tab.

. Click on ellipsis against the Magento application in staging environment, and click on `Manage`.

. The Magento application is now managed by Astra Control Center. All operations supported by Astra Control can be performed on the application.

. Repeat the steps for managing Magento application in production environment.

=== CI/CD Pipeline with Integrated Protection

The core of this use-case is that as and when new versions of applications are worked upon, we use a CI/CD pipeline to build the container image, take backups of both staging and production environments, then deploy the new version of the application to staging environment, wait for approval to promotion to production, and at last deploy the new version of the application to production environment.

. Log into Jenkins, and create a pipeline by clicking on `New Item` and then click on `Pipeline`.

. Go the netapp-astra-toolkits repository and then copy the pipeline contents from <<directory>>.

. Paste the pipeline into Jenkins pipeline sections and then click on `Save`.

. Fill the parameters of the Jenkins pipeline with the respective details.

. Then click on `Build Now`
