---
sidebar: sidebar
permalink: containers/devops_with_netapp/dwn_overview_astra.html
keywords: NetApp Astra Control, Astra Control Center, Application, Trident, Astra Trident, Helm, Operator, ONTAP, OpenShift, Kubernetes, Red Hat OpenShift
summary: NetApp Astra Control Center offers a rich set of storage and application-aware data management services for stateful Kubernetes workloads, deployed in an on-prem environment, powered by NetApp’s trusted data protection technology.
---

= NetApp Astra Control overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/
:k8s_distribution_name: Kubernetes

include::_include/containers_common_intro_sections.adoc[tags=astra_cc_overview]

For a detailed installation and operations guide on Astra Control Center, follow the documentation link:https://docs.netapp.com/us-en/astra-control-center/index.html[here^].

== Astra Control Center Automation

Astra Control Center has a full-blown REST API for programmatic access. Users can use any programming language or utility to interact with Astra Control REST API endpoints. To learn more about it, check out the documentation link:https://docs.netapp.com/us-en/astra-automation/index.html[here^].

If developers are looking for a ready-made software development toolkit for interacting with Astra Control REST APIs, NetApp provides a toolkit with Astra Control Python SDK. To try it yourself, head on to link:https://github.com/NetApp/netapp-astra-toolkits/[NetApp Astra Toolkits^].

Furthermore, there are scenarios where programming is not an ideal choice and users just want to utilize a configuration management tool. In such scenarios, users can clone and run the Ansible playbooks that NetApp publishes link:https://github.com/NetApp-Automation/na_astra_control_suite[here^].

link:dwn_use_cases_overview.html[Next: Use-case Validations: DevOps with NetApp Astra]
