---
sidebar: sidebar
permalink: about.html
keywords: NetApp Solutions, about
summary:
---

= About this Repository
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Brief introduction of the NetApp Solutions repository - where to find specific solutions and how to use this repository.

== Navigation of the Repository
Navigation of the repository is managed by the main sidebar which is presented on the left side of the page.  Solutions are categorized into higher level technical areas defined as the "technology towers" for NetApp Solutions.

=== Overview of Technology Towers

[width=100%, cols="20%, 60%, 20%", grid=all, frame=all, options="header"]
|===
| *Section* | *Description* | *Content Landing Page*
| Artificial Intelligence
| Collection of AI based solutions.  The AI landing page offers popular content presented in content specific "tiles".
a| * link:ai/index.html[AI content]
//
| Modern Data Analytics
| Collection of Modern Data Analytics solutions (e.g. Splunk SmartStore, Apache Spark, etc.).  The Modern Data Analytics landing page offers popular content presented in content specific "tiles".
a| * link:data-analytics/index.html[Modern Data Analytics content]
//
| Public and Hybrid Cloud
| Defines NetApp solutions in a public or hybrid cloud model and NetApp Storage options in each of the hyperscalers.  There are several options for solutions in this space.
a| * link:ehc/index.html[Hybrid Multicloud with VMware content]
* link:rhhc/index.html[Hybrid MultiCloud with Red Hat content]
* link:vmw-sc/index.html[VMware Sovereign Cloud content]
//
| Virtualization
| Collection of virtualization core solutions, including desktop virtualization.  The Virtualization landing page offers popular content presented in content specific "tiles".  THe topic covers multiple virtuzliation option.
a| * link:vmware/index.html[VMware virtualization content]
* link:hyperv/index.html[Hyper-V virtualization content]
* link:osv/index.html[OpenShift virtualization content]
//
| Containers
| Collection of container based solutions.  The Virtualization landing page offers popular content presented in content specific "tiles".
a| * link:containers/index.html[Containers content]
//
| Databases
| Collection of Oracle and SQL Server database solutions.  Open Source databases are also covered in this section.
a| * link:databases/index.html[Database content]
|===

== Change Log
All major changes to the repository (new solutions, major updates, new videos / demos, etc.) are tracked in the link:change-log-display.html[change log].

== Feedback
Please use link:https://github.com/NetAppDocs/netapp-solutions/issues/new?body=%0d%0a%0d%0aFeedback:%20%0d%0aAdditional%20Comments:&title=Feedback[this link] to request changes to content or provide feedback on the content.  Please be as specific as possible to ensure that your feedback is addressed appropriately.
