= NetApp Solutions Change Log
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

[.lead]
Recent changes to the NetApp Solutions collateral.  The most recent changes are listed first.

++++
<style>
.title-collapsible {
  background-color: #d4d4d4;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: 0.1px solid;
  text-align: left;
  outline: none;
  font-size: 15px;
}

.title-collapsible:hover {
  background-color: #bbb;
}

.content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
}
</style>
<button type="button" class="title-collapsible">All Solutions</button>
<div class="content">
<p>
++++
include::change-log.adoc[]
++++
</p>
</div>
<button type="button" class="title-collapsible">AI & Modern Analytics Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=aiml]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">VMware Virtualization Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all",frame="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=vmware]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">Virtual Desktop Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=vdi]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">Container Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=containers]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">Business Applications Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=apps]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">Enterprise Database Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=ent-db]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">Data Protection and Security Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=dp-sec]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">Infrastructure Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=infra]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">Automation Solutions</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=automation]
|===
++++
</p>
</div>
<button type="button" class="title-collapsible">General Content</button>
<div class="content">
<p>
++++
[width=100%,cols="2, 4, 10",grid="all"]
|===
| *Date* | *Solution Area* | *Description of change*
include::change-log.adoc[tag=general]
|===
++++
</p>
</div>
<script>
var coll = document.getElementsByClassName("title-collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>
++++
