---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false 
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: false
sidebar:
  entries:
    - title: "NetApp Solutions Documentation"
      url: index.html
    - section: ai
    - section: data-analytics
    - section: cloud
    - section: virtualization
    - section: containers
    - section: databases
#    - section: data-access
#
    - title: "SAP & SAP HANA"
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
    - title: "FlexPod Solutions"
      url: https://docs.netapp.com/us-en/flexpod/
 #
    - title: "Change Log"
      url: change-log-display.html
    - title: "About NetApp Solutions"
      url: about.html
    - title: "Legal notices"
      url: /legal-notices.html
