---
settings:
  name: NetApp Solutions
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: "NetApp Solutions Documentation"
      url: /index.html
    - section: ai
    - section: data-analytics
    - section: ehc
    - section: virtualization
    - section: containers
    - section: ent-apps-db
    - section: data-access
    - section: automation
    - title: "FlexPod Solutions"
      url: https://docs.netapp.com/us-en/flexpod/
    - title: "Legacy NetApp HCI Solutions"
      url: https://docs.netapp.com/us-en/hci-solutions/
    - title: "Change Log"
      url: /change-log-display.html
    - title: "About NetApp Solutions"
      url: /about.html
    - title: "Legal Notices"
      url: /reference_legal_notices.html

homepage:
  tiles:
    - title: "Introduction"
      links:
        - title: "About this Repository"
          url: about.html
        - title: "Change History"
          url: change-log-display.html
        - title: "Solution Blogs"
          url: blogs.html
        - title: "Solution Videos & Demos"
          url: videos.html
        - title: "Legal Notice"
          url: reference-legal-notices.html
#
    - title: "Solution Landing Pages"
      links:
        - title: "Artificial Intelligence"
          url: ai/index.html
        - title: "Modern Data Analytics"
          url: data-analytics/index.html
        - title: "Enterprise Hybrid Cloud"
          url: ehc/index.html
        - title: "Virtualization"
          url: virtualization/index.html
        - title: "Containers"
          url: containers/index.html
        - title: "SAP and SAP HAHA"
          url: https://docs.netapp.com/us-en/netapp-solutions-sap/index.html
#
    - title: "Enterprise Hybrid Cloud (EHC)"
      links:
        - title: "EHC Overview"
          url: ehc/ehc-overview.html
        - title: "Use Cases"
          url: ehc/ehc-use-cases.html
        - title: "Supported Configurations"
          url: ehc/ehc-support-configs.html
        - title: "VMware Cloud in Hyperscaler Clouds"
          url: ehc/ehc-hyperscalers.html
        - title: "Hyperscaler Specific Content"
          url: ehc/index.html
#
    - title: "Solution Automation"
      links:
        - title: "Getting Started"
          url: automation/getting-started.html
#        - title: "What's New"
#          url: automation-whatsnew.html
        - title: "Videos and Demos"
          url: videos.html
#        - title: "Blogs"
#          url: blogs.html
        - title: "Request Automation"
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
#
    - title: "FlexPod - A NetApp & Cisco Solution"
      links:
        - title: "FlexPod Solutions Technical Content"
          url: https://docs.netapp.com/us-en/flexpod/
        - title: "FlexPod Sales Page"
          url: https://flexpod.com
        - title: "Videos and Demos"
          url: https://tv.netapp.com/search?q=flexpod
        - title: "Blogs"
          url: https://blog.netapp.com/tag/FlexPod/
#
    - title: "Feedback"
      links:
        - title: "Propose a New Solution"
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
        - title: "Provide Solution Feedback"
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
