---
settings:
  name: NetApp Solutions
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: us-en,ja-jp,zh-cn
sidebar:
  entries:
    - title: NetApp Solutions Documentation
      url: /index.html
    - section: ai
    - section: data-analytics
    - section: virtualization
    - section: vdi-vds
    - section: containers
#    - section: private-cloud
    - section: ent-apps-db
    - section: data-access
    - section: infra
    - section: automation
#    - section: xcp
    - title: FlexPod Solutions
      url: https://docs.netapp.com/us-en/flexpod/
    - title: Change Log
      url: /change-log-display.html
    - title: About NetApp Solutions
      url: /about.html
    - title: Legal Notices
      url: /reference_legal_notices.html

homepage:
  tiles:
    - title: AI & Modern Data Analytics
      links:
        - title: "What's New"
          url: aimda-whatsnew.html
        - title: "NetApp DataOps Toolkit"
          url: https://github.com/NetApp/netapp-data-science-toolkit
        - title: "Videos and Demos"
          url: aimda-videos.html
        - title: "Blogs"
          url: aimda-blogs.html
#
    - title: Enterprise Hybrid Cloud (EHC)
      links:
        - title: "What is EHC?"
          url: ehc/ehc-overview.html
#        - title: "Use Cases"
#          url: ehc/ehc-use-cases.html
#        - title: "Supported Configurations"
#          url: ehc/ehc-support-configs.html
        - title: "VMware Cloud in Hyperscalers"
          url: ehc/ehc-hyperscaler-intro.html
        - title: "Azure VMware Solution (AVS) Solutions"
          url: /ehc/azure.html
        - title: "AWS VMware Managed Cloud (VMC) Solutions"
          url: /ehc/aws.html
        - title: "Google Cloud VMware Engine (GCVE) Solutions"
          url: /ehc/gcp.html
        - title: "Videos and Demos"
          url: ehc-videos.html
        - title: "Blogs"
          url: ehc-blogs.html
#
    - title: Virtualization, Desktop Virtualization & Containers
      links:
        - title: "What's New"
          url: hc-whatsnew.html
        - title: "Videos and Demos"
          url: hc-videos.html
        - title: "Blogs"
          url: hc-blogs.html
#
    - title: Enterprise Applications & Databases
      links:
        - title: "What's New"
          url: appsdb-whatsnew.html
        - title: "Videos and Demos"
          url: appsdb-videos.html
#        - title: "Blogs"
#          url: appsdb-blogs.html
#
#    - title: Data Protection & Security
#      links:
#        - title: "What's New"
#          url: dpsec-whatsnew.html
#        - title: "Videos and Demos"
#          url: dpsec-videos.html
#        - title: "Blogs"
#          url: dpsec-blogs.html
#
    - title: Solution Automation
      links:
        - title: "What's New"
          url: automation-whatsnew.html
        - title: "Videos and Demos"
          url: automation-videos.html
#        - title: "Blogs"
#          url: automation-blogs.html
        - title: Request Automation
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
#
    - title: FlexPod - A NetApp & Cisco Solution
      links:
        - title: FlexPod Solutions Technical Content
          url: https://docs.netapp.com/us-en/flexpod/
        - title: FlexPod Sales Page
          url: https://flexpod.com
        - title: Videos and Demos
          url: https://tv.netapp.com/search?q=flexpod
        - title: Blogs
          url: https://blog.netapp.com/tag/FlexPod/
#
    - title: Feedback
      links:
        - title: Propose a New Solution
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
        - title: Provide Solution Feedback
          url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
