---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  pdf:
    zip-level: 4
    zip-filename: netapp-solutions-pdfs.zip
  internal:
    pdf_enabled: false 
  prod:
    pdf:
      zip-level: 4
      zip-filename: netapp-solutions-pdfs.zip
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: false
sidebar:
  entries:
    - title: "NetApp Solutions Documentation"
      url: index.html
    - section: ai
    - section: containers
    - section: data-access
    - title: "Enterprise Applications"
      entries:
        - title: "SAP & SAP HANA"
          url: https://docs.netapp.com/us-en/netapp-solutions-sap/
    - section: databases
    - section: data-analytics
    - section: ehc
    - section: rhhc
    - section: virtualization
    - section: automation
    - title: "FlexPod Solutions"
      url: https://docs.netapp.com/us-en/flexpod/
    - title: "Legacy NetApp HCI Solutions"
      url: https://docs.netapp.com/us-en/hci-solutions/
    - title: "Change Log"
      url: change-log-display.html
    - title: "About NetApp Solutions"
      url: about.html
    - title: "Legal Notices"
      url: legal-notices.html
