sidebar:
  entries:
    - title: NetApp Solutions Documentation
      url: /index.html
    - section: ai-mda
    - section: hybrid-cloud
    - section: ea-db
    - section: dp-sec
    - section: infra
    - section: automation
    - title: Change Log
      url: /change-log.html

homepage:
  tiles:
    - title: AI & Modern Data Analytics
      links:
        - summary: "<b>What's New?</b>"
        - title: "NetApp ONTAP AI with NVIDIA DGX A100 Systems and Mellanox Spectrum Ethernet Switches"
          summary: Design Guide
          url: https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf
        - title: "NetApp ONTAP AI with NVIDIA DGX A100 Systems and Mellanox Spectrum Ethernet Switches"
          summary: Deployment Guide
          url: https://www.netapp.com/pdf.html?item=/media/21789-nva-1153-deploy.pdf
        - title: "AI Orchestration with NetApp and Run:AI"
          url: /osrunai_executive_summary.html
        - title: "NetApp Data Science Toolkit"
          url: https://github.com/NetApp/netapp-data-science-toolkit
        - summary: "<b>Videos / Demos</b>"
        - title: "NetApp AI Solutions"
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO
        - title: "MLOps"
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW
        - summary: "<b>Blogs</b>"
        - title: "NetApp.com"
          url: https://blog.netapp.com/tag/artificial-intelligence/
        - title: "thePub"
          url: https://netapp.io/category/ai-ml/
#
    - title: Hybrid Cloud & Virtualization
      links:
        - summary: "<b>What's New?</b>"
        - title: "Hybrid Cloud VDI with NetApp Virtual Desktop Service"
          summary: NetApp Virtual Desktop Service (VDS) orchestrates Remote Desktop Services (RDS) in major public clouds as well as on private clouds
          url: /hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html
        - title: "Anthos on Bare Metal with NetApp"
          summary: NetApp ONTAP with Google Cloud Anthos on bare metal
          url: https://www.netapp.com/pdf.html?item=/media/21072-wp-7337.pdf
#
    - title: Business Applications & Enterprise Databases
      links:
#        - summary: NetApp provides application integrated data protection and data mobility for enterprise applications and databases.  Customers choose NetApp to run their mission critical workloads on-premises, hybrid and public clouds, unified by NetApp's secure Data Fabric.
        - summary: "<b>What's New?</b>"
        - title: SAP HANA B&R with SnapCenter
          url: https://www.netapp.com/pdf.html?item=/media/12405-tr4614pdf.pdf
        - title: SAP HANA on FC SAN
          url: https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_sap_ucsm40_fcsan.html
        - title: SAP Applications on Microsoft SQL Server
          url: https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/sap-appservers-flexpod-with-sql.pdf
        - title: SQL Server on SolidFire eSDS for Virtualized Infrastructures
          url: https://www.netapp.com/pdf.html?item=/media/20030-tr-4866.pdf
        - title: SQL Server - Assuring Database Performance with NetApp HCI
          url: https://www.esg-global.com/validation/esg-technical-validation-assuring-database-performance-and-availability-with-netapp-hci
        - summary: "<b>Videos / Demos</b>"
        - title: SAP on Azure NetApp Files - Case Study
          url: https://customers.netapp.com/en/sap-azure-netapp-files-case-study/
        - title: NetApp Solutions for Oracle Database
          url: https://tv.netapp.com/detail/video/6122307529001/netapp-solutions-for-oracle-databases%E2%80%8B
        - title: SQL High Availability Cluster on Azure NetApp Files
          url: https://tv.netapp.com/detail/video/1670591628570468424/deploy-sql-server-always-on-failover-cluster-over-smb-with-azure-netapp-files

    - title: Data Protection & Security
      links:
        - summary: "<b>What's New?</b>"
        - title: "NetApp HCI Verified Architecture for PCI-DSS"
          summary: Third party whitepaper defining the validation of NetApp HCI as a PCI-DSS platform.
          url: https://www.coalfire.com/resources/white-papers/netapp-hci-verified-architecture-for-pci-dss

    - title: Solution Automation
      links:
        - summary: "<b>What's New?</b>"
          summary: COMING SOON!
