---
sidebar: sidebar
permalink: videos.html
summary: Series of videos and demos discussing the features of many of NetApp's solutions
keywords: netapp, solutions, videos, demos
---

= NetApp Solutions: Videos and Demos
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

[.lead]
Overview of the videos and demos highlighting specific features of many of NetApp's solutions.

[[ai]]
.Artificial Intelligence (AI) and Modern Data Analytics
[%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO[NetApp AI solutions^]

* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW[MLOps^]

video::e87773e3-dc53-4195-83ed-b0d50100a788[panopto, title="DevOps Acceleration with DataOps Toolkit and Astra Control Center Cloud Bursting", width=360]
====

[[db]]
.Enterprise Applications and Databases
[%collapsible]
====
[underline]#*Videos for open source databases*#

video::c381b887-8c8b-4d7d-8b0f-b0c0010c5c04[panopto, title="PostgreSQL automated deployment, HA/DR replication setup, failover, resync", width=360]

[underline]#*Videos for Oracle database*#

video::81e389a0-d9b8-495c-883b-b0d701710847[panopto, title="Simplified and automated Oracle deployment on Amazon FSx ONTAP with iSCSI", width=360]

video::79095731-6b02-41d5-9fa1-b0c00100d055[panopto, title="Simplified and automated Oracle deployment on NetApp ASA with iSCSI", width=360]

video::b1a7bb05-caea-44a0-bd9a-b01200f372e9[panopto, title="Part 1 - Oracle modernization with hybrid cloud in AWS and FSx", width=360]

video::bb088a3e-bbfb-4927-bf44-b01200f38b17[panopto, title="Part 2a - Database migration from on-premises to AWS using automated PDB relocation with maximum availability", width=360]

video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto, title="Part 2b - Database migration from on-premises to AWS using BlueXP console via SnapMirror", width=360]

video::5fd03759-a691-4007-9748-b01200f3b79c[panopto, title="Part 3 - Automated database HA/DR replication setup, failover, resync",width=360]

video::2f731d7c-0873-4a4d-8491-b01200f90a82[panopto, title="Part 4a - Database clone for Dev/Test with SnapCenter UI from replicated standby copy", width=360]
 
video::97790d62-ff19-40e0-9784-b01200f920ed[panopto, title="Part 4b - Database backup, restore, clone with SnapCenter UI", width=360]

video::4b0fd212-7641-46b8-9e55-b01200f9383a[panopto, title="Part 4c - Database backup, restore with BlueXP SaaS Apps backup and recovery", width=360]

[underline]#*Videos for SQL Server database*#

video::27f28284-433d-4273-8748-b01200fb3cd7[panopto, title="Deploy SQL Server on AWS EC2 using Amazon FSx for NetApp ONTAP", width=360]

video::krzMWjrrMb0[youtube, title="Oracle Multi-Tenant Pluggable Database Clone Using Storage Snapshots", width=360]
 
video::VcQMJIRzhoY[youtube, title="Automated Oracle 19c RAC Deployment on FlexPod with Ansible", width=360]

*Case Study*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study[SAP on Azure NetApp Files^]
====

[[hmc]]
.Hybrid Multicloud (HMC)
[%collapsible]
====
[underline]#*Videos for AWS/VMC*#

video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto, title="Windows Guest Connected Storage with FSx ONTAP using iSCSI", width=360]

video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto, title="Linux Guest Connected Storage with FSx ONTAP using NFS", width=360]

video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto, title=" VMware Cloud on AWS TCO savings with Amazon FSx for NetApp ONTAP", width=360]
 
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto, title="VMware Cloud on AWS supplemental datastore w/ Amazon FSx for NetApp ONTAP", width=360]
 
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto, title="VMware HCX Deployment and Configuration Setup for VMC", width=360]
 
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto, title="vMotion Migration Demonstration with VMware HCX for VMC and FSxN", width=360]

video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto, title="Cold Migration Demonstration with VMware HCX for VMC and FSxN", width=360]

[underline]#*Videos for Azure/AVS*#

video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto, title="Azure VMware Solution supplemental datastore overview with Azure NetApp Files", width=360]

video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto, title=" Azure VMware Solution DR with Cloud Volumes ONTAP, SnapCenter and JetStream", width=360]
 
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto, title="Cold Migration Demonstration with VMware HCX for AVS and ANF", width=360]
 
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto, title="vMotion Demonstration with VMware HCX for AVS and ANF", width=360]
 
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto, title="Bulk Migration Demonstration with VMware HCX for AVS and ANF", width=360]
====

[[rhhc]]
.Hybrid MultiCloud with Red Hat OpenShift 
[%collapsible]
====
video::01dd455e-7f5a-421c-b501-b01200fa91fd[panopto, title="ROSA DR using Astra Control Service", width=360]

video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto, title="Integration of FSxN with Astra Trident", width=360]

video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto, title="Failover and Fail-back of apps on ROSA with FSxN", width=360]

[underline]#*DR using Astra Control Center*#

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458[Watch on NetAppTV]

video::4efc68f1-d37f-4cdd-874a-b09700e71da9[panopto, title="OpenShift Cluster installation on Google Cloud Platform", width=360]

video::57b63822-6bf0-4d7b-b844-b09700eac6ac[panopto, title="Importing OpenShift clusters into Astra Control Center", width=360]

video::0cec0c90-4c6f-4018-9e4f-b09700eefb3a[panopto, title="Data protection with Astra Control Center", width=360]

video::1546191b-bc46-42eb-ac34-b0d60142c58d[panopto, title="Failover Failback with Astra Control Center", width=360]
====

[[virtualization]]
.Virtualization
[%collapsible]
====
* link:virtualization/vsphere_demos_videos.html[VMware Video Collection]
====

[[containers]]
.Containers / Kubernetes
[%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html[NetApp with Google Anthos Videos]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html[NetApp with VMware Tanzu Videos]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html[NetApp for DevOps Videos]
* link:containers/rh-os-n_videos_and_demos.html[NetApp with Red Hat OpenShift Videos]
====

[[automation]]
.Solution Automation
[%collapsible]
====
video::VcQMJIRzhoY[youtube,, title="Automated Oracle 19c RAC Deployment on FlexPod with Ansible", width=360]
====

