---
sidebar: sidebar
permalink: videos.html
summary: Series of videos and demos discussing the features of many of NetApp's solutions
keywords: netapp, solutions, videos, demos
---

= NetApp Solutions: Videos and Demos
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

[.lead]
Overview of the videos and demos highlighting specific features of many of NetApp's solutions.

[[ai]]
.Artificial Intelligence (AI) and Modern Data Analytics
[%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO[NetApp AI solutions^]

* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW[MLOps^]
====

[[db]]
.Enterprise Applications and Databases
[%collapsible]
====
[underline]#*Videos for open source databases*#
[width=100%,cols="5a, 5a, 5a",frame="none",grid="none"]
|===
.>| PostgreSQL automated deployment, HA/DR replication setup, failover, resync
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=e479b91f-eacd-46bf-bfa1-b01200f0015a&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

| |
|===

[underline]#*Videos for Oracle modernization with hybrid cloud in AWS and FSx*#
[width=100%,cols="5a, 5a, 5a",frame="none",grid="none"]
|===
.>| Part 1 - Use case and solution architecture
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=b1a7bb05-caea-44a0-bd9a-b01200f372e9&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Part 2a - Database migration from on-premises to AWS using automated PDB relocation with maximum availability
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=bb088a3e-bbfb-4927-bf44-b01200f38b17&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Part 2b - Database migration from on-premises to AWS using BlueXP console via SnapMirror
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Part 3 - Automated database HA/DR replication setup, failover, resync
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=5fd03759-a691-4007-9748-b01200f3b79c&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Part 4a - Database clone for Dev/Test with SnapCenter UI from replicated standby copy
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=2f731d7c-0873-4a4d-8491-b01200f90a82&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Part 4b - Database backup, restore, clone with SnapCenter UI
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=97790d62-ff19-40e0-9784-b01200f920ed&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Part 4c - Database backup, restore with BlueXP SaaS Apps backup and recovery
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=4b0fd212-7641-46b8-9e55-b01200f9383a&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

| |
|===

[underline]#*Videos for SQL Server database*#
[width=100%,cols="5a, 5a, 5a",frame="none",grid="none"]
|===
.>| Deploy SQL Server on AWS EC2 using Amazon FSx for NetApp ONTAP
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=27f28284-433d-4273-8748-b01200fb3cd7&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Oracle Multi-Tenant Pluggable Database Clone Using Storage Snapshots
video::krzMWjrrMb0[youtube,width=360]
.>| Automated Oracle 19c RAC Deployment on FlexPod with Ansible
video::VcQMJIRzhoY[youtube,width=360]
|===

*Case Study*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study[SAP on Azure NetApp Files^]
====

[[hmc]]
.Hybrid Multicloud (HMC)
[%collapsible]
====
[underline]#*Videos for AWS/VMC*#
[width=100%,cols="5a, 5a, 5a",frame="none",grid="none"]
|===
.>| Windows Guest Connected Storage with FSx ONTAP using iSCSI
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=0d03e040-634f-4086-8cb5-b01200fb8515&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Linux Guest Connected Storage with FSx ONTAP using NFS
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=c3befe1b-4f32-4839-a031-b01200fb6d60&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| VMware Cloud on AWS TCO savings with Amazon FSx for NetApp ONTAP
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=f0fedec5-dc17-47af-8821-b01200f00e08&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| VMware Cloud on AWS supplemental datastore w/ Amazon FSx for NetApp ONTAP
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=2065dcc1-f31a-4e71-a7d5-b01200f01171&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| VMware HCX Deployment and Configuration Setup for VMC
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=6132c921-a44c-4c81-aab7-b01200fb5d29&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| vMotion Migration Demonstration with VMware HCX for VMC and FSxN
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=52661f10-3f90-4f3d-865a-b01200f06d31&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Cold Migration Demonstration with VMware HCX for VMC and FSxN
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=685c0dc2-9d8a-42ff-b46d-b01200f056b0&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

| |
|===

[underline]#*Videos for Azure/AVS*#
[width=100%,cols="5a, 5a, 5a",frame="none",grid="none"]
|===
.>| Azure VMware Solution supplemental datastore overview with Azure NetApp Files
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=8c5ddb30-6c31-4cde-86e2-b01200effbd6&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Azure VMware Solution DR with Cloud Volumes ONTAP, SnapCenter and JetStream
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=5cd19888-8314-4cfc-ba30-b01200efff4f&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Cold Migration Demonstration with VMware HCX for AVS and ANF
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=b7ffa5ad-5559-4e56-a166-b01200f025bc&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| vMotion Demonstration with VMware HCX for AVS and ANF
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=986bb505-6f3d-4a5a-b016-b01200f03f18&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Bulk Migration Demonstration with VMware HCX for AVS and ANF
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=255640f5-4dff-438c-8d50-b01200f017d1&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

|
|===
====

[[rhhc]]
.Hybrid MultiCloud with Red Hat OpenShift 
[%collapsible]
====
[width=100%,cols="5a, 5a, 5a",frame="none",grid="none"]
|===
.>| ROSA DR using Astra Control Service
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=01dd455e-7f5a-421c-b501-b01200fa91fd&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Integration of FSxN with Astra Trident
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=621ae20d-7567-4bbf-809d-b01200fa7a68&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Failover and Fail-back of apps on ROSA with FSxN
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=e9a07d79-42a1-4480-86be-b01200fa62f5&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| DR using Astra Control Center

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458[Watch on NetAppTV]
| |
|===
====

[[virtualization]]
.Virtualization
[%collapsible]
====
* link:virtualization/vsphere_demos_videos.html[VMware Video Collection]
====

[[containers]]
.Containers / Kubernetes
[%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html[NetApp with Google Anthos Videos]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html[NetApp with VMware Tanzu Videos]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html[NetApp for DevOps Videos]
* link:containers/rh-os-n_videos_and_demos.html[NetApp with Red Hat OpenShift Videos]
====

[[automation]]
.Solution Automation
[%collapsible]
====
.Automated Oracle 19c RAC Deployment on FlexPod with Ansible
video::VcQMJIRzhoY[youtube,width=360]
====
