---
sidebar: sidebar
permalink: ehc/aws-storage-options.html
keywords: aws, netapp, fsxn, storage, options, nfs, supplemental, cvo
summary: NetApp storage can be attached to the Azure VMware Service as either guest connected or supplemental storage.
---

= Amazon Web Services: Options for using NetApp storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp storage can be attached to the Amazon Web Services as either guest connected or supplemental storage.

== Amazon FSx for NetApp ONTAP (FSx ONTAP) as a supplemental NFS datastore

Amazon FSx ONTAP provides excellent options to deploy and manage application workloads along with file services while reducing the TCO by making data requirements seamless to the application layer. Whatever the use case, choose VMware Cloud on AWS along with Amazon FSx ONTAP for rapid realization of cloud benefits, consistent infrastructure, and operations from on-premises to AWS, bidirectional portability of workloads, and enterprise-grade capacity and performance. It is the same familiar process and procedures used to connect storage.

For more information, please visit:

* link:aws-native-overview.html[FSx ONTAP as a Supplemental NFS Datastore: Overview]
* link:aws-native-nfs-datastore-option.html[Amazon FSx for ONTAP as a Supplement datastore]

== Amazon FSx for NetApp ONTAP as guest connected storage

Amazon FSx ONTAP is a fully managed service that provides highly reliable, scalable, high-performing, and feature-rich file storage built on NetApp's popular ONTAP file system. FSx ONTAP combines the familiar features, performance, capabilities, and API operations of NetApp file systems with the agility, scalability, and simplicity of a fully managed AWS service.

FSx ONTAP provides feature-rich, fast, and flexible shared file storage that’s broadly accessible from Linux, Windows, and macOS compute instances running in AWS or on premises. FSx ONTAP offers high-performance solid state drive (SSD) storage with sub-millisecond latencies. With FSx ONTAP, you can achieve SSD levels of performance for your workload while paying for SSD storage for only a small fraction of your data.

Managing your data with FSx ONTAP is easier because you can snapshot, clone, and replicate your files with the click of a button. In addition, FSx ONTAP automatically tiers your data to lower-cost, elastic storage, lessening the need for you to provision or manage capacity.

FSx ONTAP also provides highly available and durable storage with fully managed backups and support for cross-Region disaster recovery. To make it easier to protect and secure your data, FSx ONTAP supports popular data security and antivirus applications.

For more information, please visit link:aws-guest.html#fsx-ontap[FSx ONTAP as Guest Connected Storage]

== Cloud Volumes ONTAP (CVO) as guest connected storage

Cloud volumes ONTAP, or CVO, is the industry-leading cloud data management solution built on NetApp’s ONTAP storage software, available natively on Amazon Web Services (AWS), Microsoft Azure and Google Cloud Platform (GCP).

It is a software-defined version of ONTAP that consumes cloud-native storage, allowing you to have the same storage software in the cloud and on-premises, reducing the need to retrain you IT staff in all-new methods to manage your data.

CVO gives customers the ability to seamlessly move data from the edge, to the data center, to the cloud and back, bringing your hybrid cloud together — all managed with a single-pane management console, NetApp Cloud Manager.

By design, CVO delivers extreme performance and advanced data management capabilities to satisfy even your most demanding applications in the cloud.

For more information, please visit link:aws-guest.html#aws-cvo[CVO as Guest Connected Storage].
