---
sidebar: sidebar
permalink: ehc/azure-storage-options.html
keywords: azure, netapp, anf, storage, options, nfs, supplemental, cvo
summary: NetApp storage can be attached to the Azure VMware Service as either guest connected or supplemental storage.
---

= Azure Virtualization Service: Options for using NetApp storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp storage can be attached to the Azure VMware Service as either guest connected or supplemental storage.

== Azure NetApp Files (ANF) as a supplemental NFS datastore

NFS datastore support was introduced with ESXi version 3 in on-premises deployments, which greatly extended vSphere’s storage capabilities.

Running vSphere on NFS is a widely adopted option for virtualization deployments on-premises because it offers strong performance and stability. If you have significant network-attached storage (NAS) in an on-premises datacenter, you should consider deploying an Azure VMware solution SDDC in Azure with Azure NetApp File datastores to overcome capacity and performance challenges.

Azure NetApp Files is built on industry-leading, highly available NetApp ONTAP data management software. Microsoft Azure services are grouped into three categories: foundational, mainstream, and specialized. Azure NetApp Files is in the specialized category and is backed by hardware already deployed in many regions. With built-in high-availability (HA), Azure NetApp Files protects your data from most outages and offers you an industry-leading SLA of 99.99%^ uptime.

For more information on ANF as a supplemental NFS datastore, please visit:

* link:azure-native-overview.html[ANF as a Supplemental NFS Datastore: Overview]
* link:azure-native-nfs-datastore-option.html[Supplemental NFS Datastore Option in Azure]

== Azure NetApp Files (ANF) as guest connected storage

Azure NetApp Files brings enterprise-grade data management and storage to Azure so you can manage your workloads and applications with ease. Migrate your workloads to the cloud and run them without sacrificing performance.

Azure NetApp Files removes obstacles, so you can move all of your file-based applications to the cloud. For the first time, you do not have to re-architect your applications, and you get persistent storage for your applications without complexity.

Because the service is delivered through the Microsoft Azure Portal, users experience a fully managed service as part of their Microsoft enterprise Agreement. World-class support, managed by Microsoft, gives you complete peace of mind. This single solution enables you to quickly and easily add multiprotocol workloads. you can build and deploy both Windows and Linux file-based applications, even for legacy environments.

For more information, please visit link:azure-guest.html#anf[ANF as Guest Connected Storage].
          
== Cloud Volumes ONTAP (CVO) as guest connected storage

Cloud Volumes ONTAP (CVO) is the industry-leading cloud data management solution built on NetApp’s ONTAP storage software, available natively on Amazon Web Services (AWS), Microsoft Azure and Google Cloud Platform (GCP).

It is a software-defined version of ONTAP that consumes cloud-native storage, allowing you to have the same storage software in the cloud and on-premises, reducing the need to retrain you IT staff in all-new methods to manage your data.

CVO gives customers the ability to seamlessly move data from the edge, to the data center, to the cloud and back, bringing your hybrid cloud together — all managed with a single-pane management console, NetApp Cloud Manager.

By design, CVO delivers extreme performance and advanced data management capabilities to satisfy even your most demanding applications in the cloud

For more information, please visit link:azure-guest.html#azure-cvo[CVO as Guest Connected Storage].
