---
sidebar: sidebar
permalink: ehc/azure-avs.html
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr
summary:
---

= NetApp Capabilities for Azure AVS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Learn more about the capabilities that NetApp brings to the Azure VMware Solution (AVS) - from NetApp as a guest connected storage device or a supplemental NFS datastore to migrating workflows, extending/bursting to the cloud, backup/restore and disaster recovery.

Jump to the section for the desired content by selecting from the following options:

* link:#config[Configuring AVS in Azure]
* link:#datastore[NetApp Storage Options for AVS]
* link:#solutions[NetApp / VMware Cloud Solutions]

[[config]]
== Configuring AVS in Azure
As with on-premises, planning a cloud based virtualization environment is critical for a successful production-ready environment for creating VMs and migration.

include::../../_include/ehc-config-vmware.adoc[tags=azure-config;azure;!ehc-azure]

[[datastore]]
== NetApp Storage Options for AVS
NetApp storage can be utilized in several ways  - either as guess connected or as a supplemental NFS datastore - within Azure AVS.

Please visit link:../ehc-support-configs.html[Supported NetApp Storage Options] for more information.

include::../../_include/ehc-datastore.adoc[tags=azure-datastore;azure;!ehc-azure]

[[solutions]]
== Solution Use Cases
With NetApp and VMware cloud solutions, many use cases are simple to deploy in Azure AVS.  se cases are defined for each of the VMware defined cloud areas:

* Protect (includes both Disaster Recovery and Backup / Restore)
* Extend
* Migrate

link:azure-solutions.html[Browse the NetApp solutions for Azure AVS]
