---
sidebar: sidebar
permalink: ehc/ehc-config-vmware.html
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration
summary:
---

= Configuring the virtualization environment in the cloud provider
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Details for how to configure the virtualization environment in each of the supported hyperscalers are covered here.

Jump to the section for the desired hyperscaler by selecting from the following options:

* link:#Configure_the_Amazon_VMware_Managed_Cloud_(VMC)[Configure the Amazon VMware Managed Cloud (VMC)]

* link:#Configure_the_Azure_VMware_Solution_(AWS)[Configure the Azure VMware Solution (AVS)]

* link:Configure_the_Google_Cloud_Virtualziation_Engine_(GCVE)[Configure the Google Cloud Virtualization Engine (GCVE)]

#
#

// tag::aws-config[]

== Configure the Amazon VMware Managed Cloud (VMC)

<details on how to configure the VMware environment in AWS>

// end::aws-config[]

#
#

// tag::azure-config[]

== Configure the Azure VMware Solution (AVS)

<details on how to configure the VMware environment in Azure>

// end::azure-config[]

#
#

// tag::gcp-config[]

== Configure the Google Cloud Virtualization Engine (GCVE)

<details on how to configure the VMware environment in GCP>

// end::gcp-config[]
