---
sidebar: sidebar
permalink: ehc/ehc-config-vmware.html
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration
summary:
---

= Configuring the virtualization environment in the cloud provider
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Details for how to configure the virtualization environment in each of the supported hyperscalers are covered here.

Jump to the section for the desired hyperscaler by selecting from the following options:

* link:#aws-config[Configure the Amazon VMware Solution (AVS)]
* link:#azure-config[Configure the Azure VMware Managed Cloud (VMC)]
* link:#gcp-config[Configure the Google Cloud Virtualization Engine (GCVE)]

//***********************************
// Section for AWS Configuration    *
//***********************************

[[aws-config]]

== Configuring VMC for AWS

// tag::aws-config[]

As with on-premises, planning VMware Cloud on AWS is critical for a successful production-ready environment for creating VMs and migration.

This section describes how to set up and manage VMware Cloud on AWS SDDC and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting FSx ONTAP and Cloud Volumes ONTAP to AWS VMC.

The setup process can be broken down into the following steps:

// tag::call-from-ehc[]
* link:aws/aws-setup.html#deploy[Deploy and configure VMware Cloud for AWS]
* link:aws/aws-setup.html#connect[Connect VMware Cloud to FSx ONTAP]
// end::call-from-ehc[]

// tag::call-from-aws[]
* link:aws-setup.html#deploy[Deploy and configure VMware Cloud for AWS]
* link:aws-setup.html#connect[Connect VMware Cloud to FSx ONTAP]
// end::call-from-aws[]

// end::aws-config[]

//***********************************
//* Section for Azure Configuration *
//***********************************

[[azure-config]]

== Configuring AVS for Azure

// tag::azure-config[]

As with on-premises, planning Azure VMware Solution is critical for a successful production-ready environment for creating VMs and migration.

This section describes how to set up and manage Azure VMware Solution and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting Azure NetApp Files and Cloud Volumes ONTAP to Azure VMware Solution.

The setup process can be broken down into the following steps:

// tag::call-from-ehc[]
* link:azure/azure-setup.html#register[Register the resource provider and create a private cloud]
* link:azure/azure-setup.html#connect[Connect to a new or existing ExpressRoute virtual network gateway]
* link:azure/azure-setup.html#validate[Validate the network connectivity and access the private cloud]
// end::call-from-ehc[]

// tag::call-from-azure[]
* link:azure-setup.html#register[Register the resource provider and create a private cloud]
* link:azure-setup.html#connect[Connect to a new or existing ExpressRoute virtual network gateway]
* link:azure-setup.html#validate[Validate the network connectivity and access the private cloud]
// end::call-from-azure[]

// end::azure-config[]

//***********************************
// Section for GCP Configuration    *
//***********************************

[[gcp-config]]

== Configuring GCVE for Google Cloud Platform

// tag::gcp-config[]

As with on-premises, planning Google Cloud VMware Engine (GCVE) is critical for a successful production-ready environment for creating VMs and migration.

This section describes how to set up and manage GCVE and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting Cloud Volumes ONTAP and Cloud Volumes Services to GCVE.

The setup process can be broken down into the following steps:

// tag::call-from-ehc[]
* link:gcp/gcp-setup.html#deploy[Deploy and Configure GCVE]
* link:gcp/gcp-setup.html#enable-access[Enable Private Access to GCVE]
// end::call-from-ehc[]

// tag::call-from-gcp[]
* link:gcp-setup.html#deploy[Deploy and Configure GCVE]
* link:gcp-setup.html#enable-access[Enable Private Access to GCVE]
// end::call-from-gcp[]

// end::gcp-config[]
