[role="tabbed-block"]
====
.AWS (VMC)
--
===== AWS
//***********************************
// Section for AWS Configuration    *
//***********************************

// tag::aws-config[]

As with on-premises, planning VMware Cloud on AWS is critical for a successful production-ready environment for creating VMs and migration.

This section describes how to set up and manage VMware Cloud on AWS SDDC and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting FSx ONTAP and Cloud Volumes ONTAP to AWS VMC.

The setup process can be broken down into the following steps:

// tag::ehc-aws[]
* link:aws/aws-setup.html#deploy[Deploy and configure VMware Cloud for AWS]
* link:aws/aws-setup.html#connect[Connect VMware Cloud to FSx ONTAP]
// end::ehc-aws[]

// tag::aws[]
* link:aws-setup.html#deploy[Deploy and configure VMware Cloud for AWS]
* link:aws-setup.html#connect[Connect VMware Cloud to FSx ONTAP]
// end::aws[]

// end::aws-config[]

--
.Azure (AVS)
--
===== Azure
//***********************************
//* Section for Azure Configuration *
//***********************************

// tag::azure-config[]

As with on-premises, planning Azure VMware Solution is critical for a successful production-ready environment for creating VMs and migration.

This section describes how to set up and manage Azure VMware Solution and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting Azure NetApp Files and Cloud Volumes ONTAP to Azure VMware Solution.

The setup process can be broken down into the following steps:

// tag::ehc-azure[]
* link:azure/azure-setup.html#register[Register the resource provider and create a private cloud]
* link:azure/azure-setup.html#connect[Connect to a new or existing ExpressRoute virtual network gateway]
* link:azure/azure-setup.html#validate[Validate the network connectivity and access the private cloud]
// end::ehc-azure[]

// tag::azure[]
* link:azure-setup.html#register[Register the resource provider and create a private cloud]
* link:azure-setup.html#connect[Connect to a new or existing ExpressRoute virtual network gateway]
* link:azure-setup.html#validate[Validate the network connectivity and access the private cloud]
// end::azure[]

// end::azure-config[]

--
.GCP (GCVE)
--
===== GCP
//***********************************
// Section for GCP Configuration    *
//***********************************

// tag::gcp-config[]

As with on-premises, planning Google Cloud VMware Engine (GCVE) is critical for a successful production-ready environment for creating VMs and migration.

This section describes how to set up and manage GCVE and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting Cloud Volumes ONTAP and Cloud Volumes Services to GCVE.

The setup process can be broken down into the following steps:

// tag::ehc-gcp[]
* link:gcp/gcp-setup.html#deploy[Deploy and Configure GCVE]
* link:gcp/gcp-setup.html#enable-access[Enable Private Access to GCVE]
// end::ehc-gcp[]

// tag::gcp[]
* link:gcp-setup.html#deploy[Deploy and Configure GCVE]
* link:gcp-setup.html#enable-access[Enable Private Access to GCVE]
// end::gcp[]
// end::gcp-config

====
