---
sidebar: sidebar
permalink: ehc/ehc-config-vmware.html
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration
summary:
---

= Configuring the virtualization environment in the cloud provider
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Details for how to configure the virtualization environment in each of the supported hyperscalers are covered here.

Jump to the section for the desired hyperscaler by selecting from the following options:

* link:#aws-config[Configure the Amazon VMware Managed Cloud (VMC)]

* link:#azure-config[Configure the Azure VMware Solution (AVS)]

* link:gcp-config[Configure the Google Cloud Virtualization Engine (GCVE)]

//***********************************
// Section for AWS Configuration    *
//***********************************

[[aws-config]]
// tag::aws-config[]

Following are the steps required to configure the Amazon VMware Managed Cloud (VMC) in AWS.

<details on how to configure the VMware environment in AWS>

// end::aws-config[]

//***********************************
//* Section for Azure Configuration *
//***********************************

[[azure-config]]
// tag::azure-config[]

Following are the steps required to configure the Azure VMware Solution (AVS) in Azure.

<details on how to configure the VMware environment in Azure>

// end::azure-config[]

//***********************************
// Section for GCP Configuration    *
//***********************************

[[gcp-config]]
// tag::gcp-config[]

Following are the steps required to configure the Google Cloud Virtualization Engine (GCVE) in Google Cloud Platform.

<details on how to configure the VMware environment in GCP>

// end::gcp-config[]
