---
sidebar: sidebar
permalink: ehc/ehc-config-vmware.html
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration
summary:
---

= Configuring the virtualization environment in the cloud provider
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Details for how to configure the virtualization environment in each of the supported hyperscalers are covered here.

Jump to the section for the desired hyperscaler by selecting from the following options:

* link:#aws-config[Configure the Amazon VMware Managed Cloud (VMC)]

* link:#azure-config[Configure the Azure VMware Solution (AVS)]

* link:#gcp-config[Configure the Google Cloud Virtualization Engine (GCVE)]

//***********************************
// Section for AWS Configuration    *
//***********************************

[[aws-config]]

== Configuring AVS for AWS

// tag::aws-config[]


// end::aws-config[]

//***********************************
//* Section for Azure Configuration *
//***********************************

[[azure-config]]

== Configuring VMC for Azure

// tag::azure-config[]

As with on-premises, planning Azure VMware Solution is critical for a successful production-ready environment for creating VMs and migration.

This section describes how to set up and manage Azure VMware Solution and use it in combination with Azure NetApp Files and Cloud Volumes ONTAP on Azure with in-guest storage.

It is important to note that in-guest storage is the only supported method of connecting Azure NetApp Files and Cloud Volumes ONTAP to Azure VMware Solution.

The setup process can be broken down into three parts:

* link:azure-register-create-pc.html[Register the resource provider and create a private cloud]
* link:azure-connect-virtual-gateway.html[Connect to a new or existing ExpressRoute virtual network gateway]
* link:azure-validate-network.html[Validate the network connectivity and access the private cloud]

// end::azure-config[]

//***********************************
// Section for GCP Configuration    *
//***********************************

[[gcp-config]]

== Configuring GCVE for Google Cloud Platform

// tag::gcp-config[]

Following are the steps required to configure the Google Cloud Virtualization Engine (GCVE) in Google Cloud Platform.

<details on how to configure the VMware environment in GCP>

// end::gcp-config[]
