---
sidebar: sidebar
permalink: ehc/ehc-solutions.html
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst
summary:
---

= NetApp Solutions for VMware in Hyperscalers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Learn more about the solutions that NetApp brings the VMware environment in each of the hyperscalers - from migrating workflows, extending/bursting to the cloud, backup/restore and disaster recovery.

== NetApp Solutions for VMC

The following matrix defines the solution use cases across each of the hyperscalers and NetApp storage options.  Click on the details in the desired cell to view the solution details.

[role="tabbed-block"]
====
.AWS (VMC)
--
[width=100%,cols="20,60",frame=none,grid=rows]
|===
| *Use Case* | *FSx ONTAP*

| Backup to cloud
|

| DR to cloud
|

| Dev / Test
|

| Burst to cloud
|

| Migrate to cloud
|
|===
--
.Azure (AVS)
--
[width=100%,cols="20,30,30",frame=none,grid=rows]
|===
| *Use Case* | *ANF* | *CVO*

| Backup to cloud
| |

| DR to cloud
| |

| Dev / Test
| |

| Burst to cloud
| |

| Migrate to cloud
| |
|===
--
.Google (GCVE)
--
[width=100%,cols="20,30,30",frame=none,grid=rows]
|===
| *Use Case* | *CVS* | *CVO*

| Backup to cloud
| |

| DR to cloud
| |

| Dev / Test
| |

| Burst to cloud
| |

| Migrate to cloud
| |
|===
====
