---
sidebar: sidebar
permalink: ehc/ehc-solutions.html
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst
summary:
---

= NetApp Solutions for VMware in Hyperscalers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Learn more about the solutions that NetApp brings the VMware environment in each of the hyperscalers - from migrating workflows, extending/bursting to the cloud, backup/restore and disaster recovery.

== NetApp Solutions for VMware Environments

Whether you are operating in a hybrid-cloud model or a "cloud first" model, NetApp offers a wide variety of solutions to address the most common use cases for managing workloads in a cloud or hybrid-cloud model.

NetApp also offers solutions for storage provisioned as in-guest (guest connected) storage or as a supplemental NFS datastore in each of the hyperscalers.  All solutions are categorized in unison with the VMware classification of cloud workloads.  Those classifications include:

* Protect (includes both Disaster Recovery and Backup / Restore)
* Migrate
* Extend

For more details on the solutions available for each hyperscaler, please visit:

* link:aws-solutions.html[Solutions for AWS / VMC]
* link:azure-solutions.html[Solutions for Azure / AVS]
* link:gcp-solutions.html[Solutions for GCP / GCVE]
