---
sidebar: sidebar
permalink: ehc/ehc-solutions.html
keywords: NetApp Solutions, aws, amazon, vmc, vmware managed cloud, azure, avs, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr, backup, burst
summary:
---

= NetApp Solutions for VMware in Hyperscalers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Learn more about the solutions that NetApp brings the VMware environment in each of the hyperscalers - from migrating workflows, extending/bursting to the cloud, backup/restore and disaster recovery.

== NetApp Solutions for VMware Environments

Whether you are operating in a hybrid-cloud model or a "cloud first" model, NetApp offers a wide variety of solutions to address the most common use cases for managing workloads in a cloud or hybrid-cloud model.

NetApp also offers solutions for storage provisioned as in-guest (guest connected) storage or as a native datastore in each of the hyperscalers.  These solutions include:

[role="tabbed-block"]
====
.AWS/VMC
--
[%autowidth.stretch,cols="3, 6"]
|===
| *Use Case* | *Solution(s)*
//
| Disaster Recovery
|
link:aws/aws-guest-dr.html#veeam[DR on-premises to cloud using Veeam]
link:aws/aws-guest-dr.html#hcx[DR on-premises to cloud using VMware HCX]
//
| Migrate
|
//
| Extend
|
//
| Data Protection
|
|===
--
.Azure/AVS
--
[%autowidth.stretch,cols="3, 6"]
|===
| *Use Case* | *Solution(s)*
//
| Disaster Recovery
|
//
| Migrate
|
//
| Extend
|
//
| Data Protection
|
|===
--
.GCP/GCVE
--
[%autowidth.stretch,cols="3, 6"]
|===
| *Use Case* | *Solution(s)*
//
| Disaster Recovery
|
//
| Migrate
|
//
| Extend
|
//| Data Protection
|
|===
--
====
