---
sidebar: sidebar
permalink: ehc/ehc-hyperscalers.html
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, microsoft, azure, avs, azure vmware solution, google cloud platform, gcp, google cloud virtualization engine, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr
summary:
---

= NetApp Solutions for VMware in Hyperscalers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Learn more about the capabilities that NetApp brings to the three (3) primary hyperscalers - from NetApp as a datastore to migrating workflows, backup/restore and disaster recovery.

== Introduction

<point to the appropriate section in the TR>

NOTE: To see the capabilities for a specific hyperscaler, click on the appropriate tab for that hyperscaler.

== NetApp as a datastore
<intro>

[role="tabbed-block"]
====
.Azure
--
--
.AWS
--
--
.Google Cloud
--
--
====

== Burst & Extend to cloud

== Data Protection

== Migrate to cloud

== Disaster Recovery to/from cloud




=== AWS FSx ONTAP as Guest Connected Storage

<point to the appropriate section in the TR>

Burst & Extend
Data Protection
Migration
Disaster Recovery

=== AWS FSx ONTAP as Native Datastore (Preview)

<point to the appropriate section in the TR>

Burst & Extend
Datastore Best Practices
Data Protection
Migration
Disaster Recovery

=== Cloud Volumes ONTAP as Guest Connected Storage

<point to the appropriate section in the TR>

Burst & Extend
Data Protection
Migration
Disaster Recovery
