---
sidebar: sidebar
permalink: ehc/ehc-hyperscalers.html
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, microsoft, azure, avs, azure vmware solution, google cloud platform, gcp, google cloud virtualization engine, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr
summary:
---

= NetApp Solutions for VMware in Hyperscalers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Learn more about the capabilities that NetApp brings to the three (3) primary hyperscalers - from NetApp as a datastore to migrating workflows, extending/bursting to the cloud, backup/restore and disaster recovery.

== Introduction

<point to the appropriate section in the TR>

NOTE: To see the capabilities for a specific hyperscaler, click on the appropriate tab for that hyperscaler.

== Configure the VMware Environment
<intro>

[role="tabbed-block"]
====
.Azure
--
include::ehc/azure-config.adoc[tag=azure-config]
--
.AWS
--
include::ehc/aws-config.adoc[tag=aws-config]
--
.Google Cloud
--
include::ehc/gcp-config.adoc[tag=gcp-config]
--
====

== NetApp as a Datastore
<intro>

[role="tabbed-block"]
====
.Azure
--
include::ehc/azure-datastore.adoc[tag=azure-datastore]
--
.AWS
--
include::ehc/aws-datastore.adoc[tag=aws-datastore]
--
.Google Cloud
--
include::ehc/gcp-datastore.adoc[tag=gcp-datastore]
--
====

== NetApp / VMware Cloud Solutions
<intro>

[role="tabbed-block"]
====
.Azure
--
link:azure-solutions.html[Browse the NetApp solutions for Azure]
--
.AWS
--
link:aws-solutions.html[Browse the NetApp solutions for AWS]
--
.Google Cloud
--
link:gcp-solutions.html[Browse the NetApp solutions for Google Cloud Platform (GCP)]
--
====
