---
sidebar: sidebar
permalink: ehc/evs-mount-fsxn-conclusion.html
keywords: Amazon, AWS, EVS, Elastic VMware Service, ONTAP, FSx
summary: This article has provided directions on how to set up FSx for ONTAP as an external storage for Amazon EVS for use with both the NFS and iSCSI protocols. 
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This document has provided directions on how to set up FSx for ONTAP as an external storage for Amazon EVS for use with both the NFS and iSCSI protocols. 

Using FSx for ONTAP as external storage for Amazon EVS provides clear operational and business values. It provides better data resilience, protection, replication, and cost efficiency through ONTAP technology, and keeps TCO optimized thanks to decoupling the VMware hyper-converged architecture. With FSx for ONTAP, Amazon EVS users can scale storage without adding compute resources, and without inflating costs. That opens up the full potential for elasticity and scale presented by the AWS Cloud.

To learn more, read the Amazon what's new announcement: link:https://aws.amazon.com/about-aws/whats-new/2025/06/amazon-elastic-vmware-service-fsx-netapp-ontap/[Amazon EVS now integrates with FSx for ONTAP], and the NetApp blog: link:https://www.netapp.com/blog/amazon-elastic-vmware-service-fsx-ontap/[Amazon EVS announces support for FSx for ONTAP].
