---
sidebar: sidebar
permalink: ehc/gcp-storage-options.html
keywords: gcp, gcve, gcnv, nfs, supplemental, datastore, vcenter, vmware, cvo, storage, options
summary: NetApp storage can be attached to the Google Cloud Virtualization Engine as either guest connected or supplemental storage.
---

= Google Cloud VMware Engine: Options for using NetApp storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp storage can be attached to the Google Cloud Virtualization Engine as either guest connected or supplemental storage.

== Google Cloud NetApp Volumes (NetApp Volumes) as a supplemental NFS Datastore

Customers that requires additional storage capacity on their Google Cloud VMware Engine (GCVE) environment can utilize Google Cloud NetApp Volumes to mount as supplemental NFS datastore.
Storing data on Google Cloud NetApp Volumes allows customers to replicate between regions to protect from diaster.

For more information, please visit link:gcp-ncvs-datastore.html[Google Cloud NetApp Volumes (NetApp Volumes) as a supplemental NFS Datastore]

== NetApp CVO as Guest Connected Storage

Cloud volumes ONTAP, or CVO, is the industry-leading cloud data management solution built on NetApp’s ONTAP storage software, available natively on Amazon Web Services (AWS), Microsoft Azure and Google Cloud Platform (GCP).

It is a software-defined version of ONTAP that consumes cloud-native storage, allowing you to have the same storage software in the cloud and on-premises, reducing the need to retrain you IT staff in all-new methods to manage your data.

CVO gives customers the ability to seamlessly move data from the edge, to the data center, to the cloud and back, bringing your hybrid cloud together — all managed with a single-pane management console, NetApp Cloud Manager.

By design, CVO delivers extreme performance and advanced data management capabilities to satisfy even your most demanding applications in the cloud.

For more information, please visit link:gcp-guest.html#gcp-cvo[NetApp CVO as Guest Connected Storage]

== Google Cloud NetApp Volumes (NetApp Volumes) as Guest Connected Storage

Google Cloud NetApp Volumes shares can be mounted from VMs that are created in the VMware Engine environment. The volumes can also be mounted on the Linux client and mapped on the Windows client because Google Cloud NetApp Volumes supports SMB and NFS protocols. Google Cloud NetApp Volumes volumes can be set up in simple steps.

Google Cloud NetApp Volumes and Google Cloud VMware Engine private cloud must be in the same region.

For more information, please visit link:gcp-guest.html#gcnv[Google Cloud NetApp Volumes (NetApp Volumes) as Guest Connected Storage]