---
sidebar: sidebar
permalink: citrix_executive_summary.html
keywords: TR-4854, tr4854, 4854, NetApp HCI, virtual apps, desktops, citrix hypervisor, Xen, pvs accelerator, LTSR
summary: TR-4852
---

= TR-4854: NetApp HCI for Citrix Virtual Apps and Desktops with Citrix Hypervisor

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 0.9 (July 10, 2020)
//
// 2020-07-31 10:32:38.700792
//

[.lead]

Suresh Thoppay, NetApp

NetApp HCI infrastructure allows you to start small and build in small increments to meet the demands of virtual desktop users. Compute or storage nodes can be added or removed to address changing business requirements.

Citrix Virtual Apps and Desktops provides a feature-rich platform for end-user computing that addresses various deployment needs, including support for multiple hypervisors. The premium edition of this software includes tools to manage images and user policies.

Citrix Hypervisor (formerly known as Citrix Xen Hypervisor) provides additional features to Citrix Virtual Apps and Desktops compared to running on other hypervisor platforms. The following are key benefits of running on Citrix Hypervisor:

* A Citrix Hypervisor license is included with all versions of Citrix Virtual Apps and Desktops. This licensing helps to reduce the cost of running the Citrix Virtual Apps and Desktops platform.

* Features like PVS Accelerator and Storage Accelerator are only available with Citrix Hypervisor.

* For Citrix solutions, the Citrix Hypervisor is the preferred workload choice.

* Available in Long Term Service Release (LTSR; aligns with Citrix Virtual Apps and Desktops) and Current Release (CR) options.
