---
sidebar: sidebar
permalink: hybrid-cloud/nhci_euc_vmware.html
summary: An introduction to End User Computing on NetApp HCI with VMware
keywords: hci, euc, vmware, horizon, vdi
---

= End User Computing on NetApp HCI with VMware

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Overview of the End User Computing capabilities on NetApp HCI with VMware Horizon.

link:nhci_intro.html[Learn more] about NetApp HCI.

== End User Computing (EUC) versus Virtual Desktop Infrastructure (VDI)

Traditionally, the focus on end user computing was centered around the virtualization of desktop infrastructure, or VDI.  As VDI evolves, the focus of the conversation has shifted to the accessibility of end user applications and data.  To read more about the evolution of VDI and the industry migration to EUC, link:https://blog.netapp.com/vdi-vs-euc-moving-beyond-desktops-and-silos/[read the blog] discussing the evolution of VDI and infrastructure to EUC and application accessibility.

== NetApp Validated Architectures and Technical Reports

End User Computing on NetApp HCI with VMware Horizon is a set of fully validated and supported solutions.  Details of the design and deployment considerations are documented in the NetApp Validated Architecture (NVA) documents and Technical Reports (TR).

* link:https://www.netapp.com/us/media/nva-1132-design.pdf[NVA: EUC with VMware (Design Guide)]
* link:https://www.netapp.com/us/media/nva-1132-deploy.pdf[NVA: EUC with VMware (Deployment Guide)]
* link:https://www.netapp.com/us/media/nva-1129-design.pdf[NVA: EUC with VMware and NVIDIA GPUs (Design Guide)]
* link:https://www.netapp.com/us/media/nva-1129-deploy.pdf[NVA: EUC with VMware and NVIDIA GPUs(Deployment Guide)]
* link:https://www.netapp.com/us/media/tr-4792.pdf[TR: EUC with VMware for 3D Graphics]

== Additional Material
