---
sidebar: sidebar
permalink: rh-os-rhv_design_considerations.html
keywords: network, VLAN, IPMI, OCP
summary:
---

= Design Considerations: NetApp HCI for Red Hat OpenShift on RHV
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.555482
//

[.lead]

=== Network Design

The Red Hat OpenShift on RHV on HCI solution uses two data switches to provide primary data connectivity at 25Gbps. It also uses two additional management switches that provide connectivity at 1Gbps for in-band management for the storage nodes and out-of-band management for IPMI functionality.  OCP uses the logical network on the RHV for the cluster management.  This section describes the arrangement and purpose of each virtual network segment used in the solution and outlines the pre-requisites for deployment of the solution.

==== VLAN Requirements

The NetApp HCI for Red Hat OpenShift on RHV solution is designed to logically separate network traffic for different purposes by using virtual local area networks (VLANs). NetApp HCI requires a minimum of three network segments. However, this configuration can be scaled to meet customer demands or to provide further isolation for specific network services. The following table lists the VLANs that are required to implement the solution, as well as the specific VLAN IDs that are used later in the verified architecture deployment.

|===
|VLANs |Purpose |VLAN ID

|Out-of-band management network
|Management for HCI nodes and IPMI
|16
|In-band management network
|Management for HCI nodes, ovirtmgmt, and VMs
|1172
|Storage network
|Storage network for NetApp Element
|3343
|Migration network
|Network for virtual guest migration
|3345
|===

==== Network Infrastructure Support Resources

The following infrastructure should be in place prior to the deployment of the OpenShift Container Platform (OCP) on Red Hat Virtualization on NetApp HCI solution:

* At least one DNS server which provides a full host-name resolution that is accessible from the in-band management network and the VM network.

* At least one NTP server that is accessible from the in-band management network and the VM network.

* (Optional) Outbound internet connectivity for both the in-band management network and the VM network.

* RHV cluster should have at least 28x vCPUs, 112GB RAM, and 840GB of available storage (depending on the production workload requirements).
