---
sidebar: sidebar
permalink: hybrid-cloud/vsphere_admin_introduction.html
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP
summary: This page describes the best practices for implementing a NetApp ONTAP storage solution in a VMware vSphere environment.
---

= Introduction to ONTAP for vSphere Administrators
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with Atom 1.57.0 (June 18, 2021)
//
//

== Why ONTAP for vSphere

NetApp ONTAP simplifies storage and data management operations and distinctly complements VMware environments whether deploying on-premises or to the cloud.  NetApp’s best in-class data protection, storage efficiency innovations and outstanding performance in both SAN and NAS based VMware architectures are among the reasons why tens of thousands of customers have selected ONTAP as their storage solution for vSphere deployments.

NetApp’s numerous VMware plug-ins, validations, and qualifications of various VMware products serve as evidence for customers seeking a data management partner that understands the unique challenges of administering a virtualization environment. NetApp does for storage and data management what VMware does for virtualization, allowing customers to focus on their core competencies rather than managing physical storage. This nearly 20-year partnership between VMware and NetApp continues to evolve and add customer value as new technologies, such as VMware Cloud Foundation and Tanzu, emerge, while continuing to support the foundation of vSphere.

Key factors customers value today include:

* *Unified storage*
* *Storage efficiency*
* *Virtual volumes and storage policy-based management*
* *Hybrid cloud*


NOTE: *For more information regarding supported NetApp and VMware solutions please consult the following:*

** The NetApp https://mysupport.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] (IMT). The IMT defines the qualified components and versions you can use to build FC/FCoE, iSCSI, NFS and CIFS configurations.
** The https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc[VMware Compatibility Guide^]. The VMware Compatibility guide lists System, I/O, Storage/SAN and Backup compatibility with VMware Infrastructure and software products
** The NetApp https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/[ONTAP Tools for VMware^] ONTAP tools for VMware vSphere is a single vCenter Server plug-in that includes VSC, VASA Provider and Storage Replication Adapter (SRA) extensions.
