---
sidebar: sidebar
permalink: hybrid-cloud/vsphere_auto_introduction.html
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP
summary: This page describes the benefits of automating base ONTAP functionality in a VMware vSphere environment.
---

= Introduction to Automation for ONTAP and vSphere
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with Atom 1.57.0 (June 18, 2021)
//
//

== VMware Automation

Automation has been an integral part of managing VMware environments since the first days of VMware ESX. The ability to deploy infrastructure as code and extend practices to private cloud operations helps alleviates concerns surrounding scale, flexibility, self-provisioning, and efficiency.

Automation can be organized into the following categories:

* *Virtual infrastructure deployment*
* *Guest machine operations*
* *Cloud operations*

There are many options available to administrators with respect to automating their infrastructure. Whether through using native vSphere features such as Host Profiles or Customization Specifications for virtual machines to available API’s on the VMware software components, operating systems and NetApp storage systems; there is significant documentation and guidance available.

Data ONTAP 8.0.1 and later supports certain VMware vSphere  APIs for Array Integration (VAAI) features when the ESX host is running ESX 4.1 or later. VMware vSphere Storage APIs Array Integration (VAAI), are a set of APIs to enabling communication between VMware vSphere ESXi hosts and storage devices. These features help offload operations from the ESX host to the storage system and increase the network throughput. The ESX host enables the features automatically in the correct environment. You can determine the extent to which your system is using the VAAI features by checking the statistics contained in the VAAI counters.

The most common starting point for automating the deployment of a VMware environment is provisioning Block or File-based datastores. It is important to map out the requirements of the actual tasks prior to developing the corresponding automation.

//=

NOTE: *For more information regarding automating VMware environments, please consult the following:*

* The https://netapp.io/configuration-management-and-automation/[NetApp Pub^]. NetApp Configuration Management and Automation.
* The https://galaxy.ansible.com/community/vmware[Ansible Galaxy Community for VMware^]. Collection of Ansible resources for VMware.
* The https://code.vmware.com/resources[VMware {code} Resources^]. Resources needed to design solutions for the software-defined data center, including forums, design standards, sample code, and developer tools.
