---
sidebar: sidebar
permalink: containers/tanzu_with_netapp/vtwn_solution_overview.html
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Astra Trident, Astra Control, Astra
summary:
---

= NVA-xxxx: VMware Tanzu with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

Alan Cowles and Nikhil M Kulkarni, NetApp

This reference document provides deployment validation of different flavors of VMware Tanzu Kubernetes solutions, deployed either as Tanzu Kubernetes Grid (TKG), Tanzu Kubernetes Grid Service (TKGS), or Tanzu Kubernetes Grid Integrated (TKGI) in several different data center environments as validated by NetApp. It also details storage integration with NetApp storage systems by making use of the Astra Trident storage orchestrator for the management of persistent storage, and Astra Control Center for the backup and cloning of stateful applications making use of that peristent storage. Lastly, the document also showcases certain video demos of the solution integrations and validations.

== Use cases

The VMware Tanzu with NetApp solution is architected to deliver exceptional value for customers with the following use cases:

* Easy to deploy and manage VMware Tanzu Kubernetes Grid offerings deployed on VMware vSphere and integrate it with NetApp storage systems.

* Combined power of enterprise container and virtualized workloads with VMware Tanzu Kubernetes Grid offerings.

* Real world configuration and use cases highlighting the features of VMware Tanzu when used with NetApp storage and the NetApp Astra suite of products.

* Application-consistent protection or migration of containerized workloads deployed on VMware Tanzu Kubernetes Grid clusters whose data resides on NetApp storage systems, using Astra Control Center.

== Business value

Enterprises are increasingly adopting DevOps practices to create new products, shorten release cycles, and rapidly add new features. Because of their innate agile nature, containers and microservices play a crucial role in supporting DevOps practices. However, practicing DevOps at a production scale in an enterprise environment presents its own challenges and imposes certain requirements on the underlying infrastructure, such as the following:

* High availability at all layers in the stack

* Ease of deployment procedures

* Non-disruptive operations and upgrades

* API-driven and programmable infrastructure to keep up with microservices agility

* Multitenancy with performance guarantees

* Ability to run virtualized and containerized workloads simultaneously

* Ability to scale infrastructure independently based on workload demands

* Ability to deploy in a hybrid-cloud model with containers running in both on-premises data centers as well as in the cloud.

VMware Tanzu with NetApp acknowledges these challenges and presents a solution that helps address each concern by deploying VMware Tanzu Kubernetes offerings in the customer's choice of hybrid cloud environment.

== Technology overview

The VMware Tanzu with NetApp solution is comprised of the following major components:

=== VMware Tanzu Kubernetes platforms

VMware Tanzu comes in a variety of flavors that the solutions engineering team at NetApp has validated in our labs. Each Tanzu release successfully integrates with the NetApp storage portfolio, and each can help meet certain infrastructure demands. Below are bulleted highlights of the features and offers of each version of Tanzu described in this document.

VMware Tanzu Kubernetes Grid (TKG)
* Standard upstream Kubernetes environment deployed in VMware vSphere Environment
* Formerly known as Essential PKS (From Heptio acquisiton Feb 2019).
* TKG is deployed with a separate management cluster instance for support on vSphere 6.7U3 onward.
* TKG deployments are able to be deployed in the cloud as well with AWS and Azure both supported.
* Allows for use of Windows worker nodes or Linux worker nodes (Ubuntu/Photon).
* NSX-T, HA Proxy, AVI networking or load balancers can be used for control plane.
* TKG supports MetalLB for application/data plane.
* Can use vSphere CSI as well as third party CSIs like NetApp Astra Trident.

VMware Tanzu Kubernetes Grid Service (TKGS)

* Standard upstream Kubernetes environment deployed in VMware vSphere Environment
* Formerly known as Essential PKS (From Heptio acquisiton Feb 2019).
* TKGS deployed with supervisor cluster and workload clusters only on vSphere 7.0U1 onward.
* Allows for use of Windows worker nodes or Linux worker nodes (Ubuntu/Photon).
* NSX-T, HA Proxy, AVI networking or load balancers can be used for control plane.
* TKGS supports MetalLB for application/data plane.
* Can use vSphere CSI as well as third party CSIs like NetApp Astra Trident.
* Provides support for vSphere Pods with Tanzu, allowing pods to run directly on enabled ESXi hosts in the environment.

VMWare Tanzu Kubernetes Grid Integrated (TKGI)

* Formerly known as Enterprise PKS (From Heptio acquisition Feb 2019).
* Can use NSX-T, HA Proxy, Avi, or bring your own load balancer.
* Supported from vSphere 6.7U3 onward, as well as AWS, Azure, and GCP.
* Setup via wizard to allow for ease of deployment.
* Runs Tanzu in controlled immutable VM’s managed by BOSH.
* Can make use vSphere CSI as well as third party CSIs like NetApp Astra Trident (Some conditions apply).

=== NetApp storage systems

NetApp has several storage systems perfect for enterprise data centers and hybrid cloud deployments. The NetApp portfolio includes NetApp ONTAP, NetApp Element, and NetApp e-Series storage systems, all of which can provide persistent storage for containerized applications.

For more information visit the NetApp website https://www.netapp.com[here].

=== NetApp storage integrations

NetApp Astra Control Center offers a rich set of storage and application-aware data management services for stateful Kubernetes workloads, deployed in an on-prem environment and powered by trusted NetApp data protection technology.

For more information, visit the NetApp Astra website https://cloud.netapp.com/astra[here].

Astra Trident is an open-source and fully-supported storage orchestrator for containers and Kubernetes distributions, including VMware Tanzu.

For more information, visit the Astra Trident website https://docs.netapp.com/us-en/trident/index.html[here].

== Current support matrix for validated releases

|===
|Technology |Purpose |Software version
|NetApp ONTAP
|Storage
|9.9.1
|NetApp Astra Control Center
|Application Aware Data Management
|22.04
|NetApp Astra Trident
|Storage Orchestration
|22.04.0
|VMware Tanzu Kubernetes Grid
|Container orchestration
|1.3.1
.2+|VMware Tanzu Kubernetes Grid Service
.2+|Container orchestration
|0.0.15 [vSphere Namespaces]
|1.22.6 [Supervisor Cluster Kubernetes]
|VMware Tanzu Kubernetes Grid Integrated
|Container orchestration
|1.13.3
|VMware vSphere
|Data center virtualization
|7.0U3
|VMware NSX-T Data Center
|Networking and Security
|3.1.3
|VMware NSX Advanced Load Balancer
|Load Balancer
|20.1.3
|===


link:vtwn_overview_vmware_tanzu.html[Next: VMware Tanzu Overview.]
