---
sidebar: sidebar
permalink: containers/anthos-with-netapp/a-w-n_overview_advanced.html
keywords: Advanced Configuration, Load Balancers
summary: This section is dedicated to customizations that real world users would likely need to perform when deploying this solution into production, such as deploying custom load balancer instances.
---

= Advanced configuration options
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.563897
//

[.lead]
Typically, the easiest-to-deploy solution is best, but, in some cases, advanced customizations are required to meet the requirements or specifications of a specific application or the environment that solution is being deployed to. To this end, the Red Hat OpenShift with NetApp solution allows for the following customizations to meet these needs.

NOTE: In this section we have documented some advanced configuration options such as using third-party load balancers or creating a private registry for hosting customized container images, both of which are prerequisites for installing the NetApp Astra Control Center.

The following pages have additional information about the advanced configuration options validated in the Red Hat OpenShift with NetApp solution:

link:a-w-n_load_balancers.html[Next: Exploring Load Balancer Options.]
