---
sidebar: sidebar
permalink: containers/anthos-with-netapp/a-w-n_LB_SeeSaw.html
summary: This page details installation and configuration instructions for the SeeSaw load balancer.
keywords: Anthos, GKE, Kubernetes, SeeSaw, LoadBalancer
---

= Installing SeeSaw load balancers: Anthos with NetApp

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

This page lists the installation and configuration instructions for the SeeSaw managed load balancer.

Seesaw is the default managed network load balancer installed in an Anthos Clusters on VMware environment.

== Installing The SeeSaw Load Balancer

The SeeSaw load balancer is fully integrated with Anthos Clusters on VMware, and has an automated deployment performed as part of Admin and User cluster setups. There are blocks of text in the cluster.yaml configuration files that need to be modified to provide the load balancer info, and then an additional step prior to cluster deployment to deploy the load balancer using the built in 'gkectl' tool.

NOTE: SeeSaw load balancers can be deployed in HA or Non-HA mode. For the purpose of this validation, the SeeSaw load balancer was deployed in Non-HA mode, which is the default setting. For production purposes, it is preferred to deploy SeeSaw in an HA configuration for fault tolerance and reliability.

== Integration with Anthos

There is a section in each configuration file, respectively for the admin cluster, and each user cluster that you choose to deploy to configure the load balancer so that it will be managed by Anthos On Prem.

The following is a sample from the configuration of the partition for the GKE-Admin cluster, the values that need to be uncommented and modified are placed in bold text below:

[subs="+quotes,+verbatim"]
----
*loadBalancer:*
  # (Required) The VIPs to use for load balancing
  *vips:*
    # Used to connect to the Kubernetes API
    *controlPlaneVIP: "10.61.181.230"*
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  *kind: Seesaw*
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   # NodePort for ingress service's http (only needed for user cluster)
  #   ingressHTTPNodePort: 0
  #   # NodePort for ingress service's https (only needed for user cluster)
  #   ingressHTTPSNodePort: 0
  #   # NodePort for control plane service
  #   controlPlaneNodePort: 30968
  #   # NodePort for addon service (only needed for admin cluster)
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address:
  #   credentials:
  #     username:
  #     password:
  #   partition:
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  *seesaw:*
  # (Required) The absolute or relative path to the yaml file to use for IP allocation
  #  for LB VMs. Must contain one or two IPs.
  *ipBlockFilePath: "admin-seesaw-block.yaml"*
  #   (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
  #   be between 1-255 and unique in a VLAN.
    *vrid: 100*
  #   (Required) The IP announced by the master of Seesaw group
    *masterIP: "10.61.181.236"*
  #   (Required) The number CPUs per machine
    *cpus: 1*
  #   (Required) Memory size in MB per machine
    *memoryMB: 2048*
  #   (Optional) Network that the LB interface of Seesaw runs in (default: cluster
  #   network)
    *vCenter:*
  #   vSphere network name
      *networkName: VM_Network*
  #   (Optional) Run two LB VMs to achieve high availability (default: false)
    *enableHA: false*
----

The SeeSaw load balancer also has a separate static 'seesaw-block.yaml' file that must be provided for each cluster deployment. This file must be located in the same directory relative to the cluster.yaml deployment file, or the full path must be specified in the section above.

A sample of the admin-seesaw-block.yaml file looks like the following:

[subs="+quotes,+verbatim"]
----
blocks:
  - netmask: "255.255.255.0"
    gateway: "10.63.172.1"
    ips:
    - ip: "10.63.172.152"
      hostname: "admin-seesaw-vm"
----

NOTE: This file provides the gateway and netmask for the network that the load balancer will provide to the underlying cluster, as well as the management IP and hostname for the virtual machine that will be deployed to run the load balancer.

link:anthos-with-netapp/a-w-n_use_cases.html[Next: Solution validation/use cases: Anthos with NetApp.]
