---
sidebar: sidebar
permalink: containers/anthos-with-netapp/a-w-n_overview_storint.html
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage
summary: NetApp provides a number of products which assist our customers with orchestrating and managing persistent data in container based environments, like Anthos.
---

= NetApp Storage Integration Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.563897
//

== Anthos Ready storage partner program.

Google Cloud periodically requests updated validation of partner storage integrations with new releases of Anthos through their Anthos Ready storage partner program. A listing of currently validated storage solutions, CSI drivers, available features, and the versions of Anthos supported can be found https://cloud.google.com/anthos/docs/resources/partner-storage[here^].

NetApp has maintained regular compliance with the requests to validate our Astra Trident CSI-compliant storage orchestrator, and our ONTAP and Element storage systems with versions of Anthos on a quarterly basis.

The following table contains the Anthos versions that have been tested by NetApp and NetApp partner engineers for the validation NetApp Astra Trident CSI drivers, and feature sets, as a part of the Anthos Ready storage partner program:

|===
|Deployment Type | Version | Storage System | Astra Trident Version | Protocol | Features
|VMware  | 1.11 | ONTAP | 22.04 | NAS | Multiwriter, Volume Expansion, SnapShots
|VMware  | 1.11 | ONTAP | 22.04 | SAN | Raw Block, Volume Expansion, SnapShots
|VMware  | 1.11 | Element | 22.04 | SAN | Raw Block, Volume Expansion, SnapShots
|bare metal   | 1.10 | ONTAP | 22.01 | NAS | Multiwriter, Volume Expansion, SnapShots
|bare metal  | 1.10 | ONTAP | 22.01 | SAN | Raw Block, Volume Expansion, SnapShots
|===


== NetApp Storage Integrations

NetApp provides a number of products to help you with orchestrating and managing persistent data in container based environments, such as Anthos.

NetApp Astra Trident is an open-source and fully-supported storage orchestrator for containers and Kubernetes distributions, including Anthos. For more information, visit the Astra Trident website https://docs.netapp.com/us-en/trident/index.html[here].

The following pages have additional information about the NetApp products that have been validated for application and persistent storage management in the Anthos with NetApp solution:

* link:a-w-n_overview_trident.html[NetApp Astra Trident]

link:a-w-n_overview_advanced.html[Next: Advanced Configuration Options: Anthos with NetApp.]
