---
sidebar: sidebar
permalink: containers/anthos-with-netapp/a-w-n_solution_overview.html
keywords: NVA-XXXX, Anthos, GKE, Netapp, Astra Trident
summary: This reference document provides deployment validation of the Anthos with NetApp solution, deployed in multiple data center environments as validated by NetApp and our engineering partners.
---

= NVA-XXXX: Anthos with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.537397
//

Alan Cowles and Nikhil Kulkarni, NetApp

This reference document provides deployment validation of the Anthos with NetApp solution, deployed in multiple data center environments as validated by NetApp and our engineering partners.
It also details storage integration with NetApp storage systems by making use of the Astra Trident storage orchestrator for the management of persistent storage.
Lastly, a number of solution validations and real world use cases are explored and documented.

== Use cases

The Anthos with NetApp solution is architected to deliver exceptional value for customers with the following use cases:

* Easy to deploy and manage Anthos environment deployed using the provided 'bmctl' tool on bare metal, or the 'gkectl' tool on VMware vSphere.

* Combined power of enterprise container and virtualized workloads with Anthos deployed virtually on vSphere, or on bare metal with https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads[kubevirt^].

* Real world configuration and use cases highlighting the features of Anthos when used with NetApp storage and Astra Trident, the open source storage orchestrator for Kubernetes.

== Business value

Enterprises are increasingly adopting DevOps practices to create new products, shorten release cycles, and rapidly add new features. Because of their innate agile nature, containers and microservices play a crucial role in supporting DevOps practices. However, practicing DevOps at a production scale in an enterprise environment presents its own challenges and imposes certain requirements on the underlying infrastructure, such as the following:

* High availability at all layers in the stack

* Ease of deployment procedures

* Non-disruptive operations and upgrades

* API-driven and programmable infrastructure to keep up with microservices agility

* Multitenancy with performance guarantees

* Ability to run virtualized and containerized workloads simultaneously

* Ability to scale infrastructure independently based on workload demands

The Anthos with NetApp solution acknowledges these challenges and presents a solution that helps address each concern by implementing the fully automated deployment of Anthos On Prem in the customers data center environment of choice.

== Technology overview

The Anthos with NetApp solution is comprised of the following major components:

=== Anthos On Prem

Anthos On Prem is a fully supported enterprise Kubernetes platform that can be deployed in the VMware vSphere hypervisor, or on a bare metal infrastructure of your choosing.

For more information about Anthos, see the Anthos website located https://https://cloud.google.com/anthos/[here^].

=== NetApp storage systems

NetApp has several storage systems perfect for enterprise data centers and hybrid cloud deployments. The NetApp portfolio includes NetApp ONTAP, NetApp Element, and NetApp e-Series storage systems, all of which can provide persistent storage for containerized applications.

For more information visit the NetApp website https://www.netapp.com[here].

=== NetApp storage integrations


Astra Trident is an open-source and fully-supported storage orchestrator for containers and Kubernetes distributions, including Anthos.

For more information, visit the Astra Trident website https://docs.netapp.com/us-en/trident/index.html[here].

== Advanced configuration options

This section is dedicated to customizations that real world users would likely need to perform when deploying this solution into production, such as creating a dedicated private image registry or deploying custom load balancer instances.

== Current support matrix for validated releases

|===
|Technology |Purpose |Software version
|NetApp ONTAP
|Storage
|9.8, 9.9.1
|NetApp Element
|Storage
|12.3
|NetApp Astra Trident
|Storage Orchestration
|22.01.0
|Anthos Clusters on VMware
|Container orchestration
|1.10
|Anthos on bare metal
|Container Orchestration
|1.9
|VMware vSphere
|Data center virtualization
|6.7U3, 7.0U3
|===


link:a-w-n_overview_anthos.html[Next: Anthos Overview: Anthos with NetApp.]
