---
sidebar: sidebar
permalink: infra/hcicaci_netapp_hci_with_cisco_aci.html
keywords: TR-4875, tr4875, 4875, Cisco ACI, Application Centric Infrastructure, SDN, NetApp HCI,
summary: TR-4875
---

= TR-4857: NetApp HCI with Cisco ACI

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Abhinav Singh, Nikhil M Kulkarni, NetApp

Cisco Application Centric Infrastructure (Cisco ACI) is an industry-leading, secure, open, and comprehensive Software-Defined Networking (SDN) solution. Cisco ACI radically simplifies, optimizes, and accelerates infrastructure deployment and governance, and it expedites the application deployment lifecycle. Cisco ACI deployed in data centers is proven to work with NetApp HCI with full interoperability. You can manage Ethernet networks for compute, storage, and access with Cisco ACI. You can establish and manage secure network segments for server-to-server and virtual machine (VM)-to-VM communications as well as secure storage-network access through iSCSI from server-to-NetApp HCI storage. This level of endpoint-to-endpoint network security allows customers to architect and operate NetApp HCI in a more secure fashion.

link:hcicaci_use_cases.html[Next: Use Cases]
