---
sidebar: sidebar
permalink: hcicaci_validation_results.html
keywords: Validation, iPerf, IOmeter, VMware, RHV, KVM
summary: TR-4857
---

= Validation Results
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-31 14:10:37.477494
//

[.lead]
We used the iPerf tool for testing network throughput, and the baseline expectation was that the test systems should achieve throughput within 10% of the maximum line rate. Test results for different virtual switches is indicated in the following table.

For storage IOPS subsystem measurement, we used the IOmeter tool. The baseline expectation was that the test systems should achieve read/write throughput within 10% of the maximum. Test results for different hypervisors is indicated in the following table.

We considered the following scenarios for the network line rate and storage IOPS testing:

== VMware

* VMs on a NetApp HCI datastore (with and without micro-segmentation)
* VMs on a NetApp ONTAP datastore
* VMs on a NetApp ONTAP Select datastore

== Red Hat Virtualization

* VMs on a NetApp HCI datastore
* VMs on a NetApp ONTAP datastore

== KVM (RHEL)

* VMs on a NetApp HCI datastore

== Miscellaneous

* One VM on RHV with a NetApp HCI datastore and one VM on VMware vSphere with a NetApp ONTAP datastore.

|===
|Hypervisor |Virtual Switch |iPerf |IOmeter |Micro-segmentation

|VMware
|VDS
|Pass
|Pass
|Pass
|RHV
|Linux Bridge
|Pass
|Pass
|N/A
|RHEL-KVM
|Open vSwitch
|Pass
|Pass
|N/A
|===

link:hcicaci_additional_information.html[Next: Where to Find Additional Information]
