---
sidebar: sidebar
permalink: infra/rhv-architecture_overview.html
keywords: hardware, software, Compute, Storage, Switches, Element, RHV, virtualization
summary:
---

= Architecture Overview: NetApp HCI with RHV
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:26:00.131440
//

[.lead]

=== Hardware Requirements

The following table lists the minimum number of hardware components that are required to implement the solution. The hardware components that are used in specific implementations of the solution might vary based on customer requirements.

|===
|Hardware |Model |Quantity

|NetApp HCI compute nodes
|NetApp H410C
|2
|NetApp HCI storage nodes
|NetApp H410S
|4
|Data switches
|Mellanox SN2010
|2
|Management switches
|Cisco Nexus 3048
|2
|===

=== Software Requirements

The following table lists the software components that are required to implement the solution. The software components that are used in any implementation of the solution might vary based on customer requirements.

|===
|Software |Purpose |Version

|NetApp HCI
|Infrastructure (compute/storage)
|1.8
|NetApp Element
|Storage
|12.0
|Red Hat Virtualization
|Virtualization
|4.3.9
|===

link:infra/rhv-design_considerations.html[Next: Design Considerations]
