---
sidebar: sidebar
permalink: rhv-updating_rhv_manager_and_rhv-h_hosts.html
keywords: security updates, stability updates, Red Hat Content Delivery Network, Red Hat Satellite repository
summary:
---

= Updating RHV Manager and RHV-H Hosts: NetApp HCI with RHV
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:26:00.225899
//

[.lead]

It is a recommended best practice to make sure that both the RHV Manager and the RHV-H hosts have the latest security and stability updates applied to make sure that the environment is protected and continues to run as expected. To apply the updates to the hosts in the deployment, they must first be subscribed to either the Red Hat Content Delivery Network or a local Red Hat Satellite repository. The tasks involved in updating the platform include updating the manager VM and afterward updating each physical host non-disruptively after ensuring virtual guests are migrated to another node in the cluster.

Official documentation to support the upgrade of RHV 4.3 between minor releases can be found https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html-single/upgrade_guide/index[here^].

link:rhv-enabling_fencing_for_rhv-h_hosts.html[Next: Best Practices - Enabling Fencing for RHV-H Hosts]
