---
sidebar: sidebar
permalink: vmw-sc/sc-overview.html
keywords: NetApp Solutions, vmware, sovereign cloud
summary:
---

= Overview of VMware Sovereign Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
The concept of sovereignty is emerging as a necessary component of cloud computing for many entities that process and maintain highly sensitive data, such as national and state governments, and highly regulated industries, such finance and healthcare. National governments are also looking to expand digital economic capability and reduce reliance on multi-national firms for their cloud services. 

== VMware Sovereign Cloud Initiative

VMware defines a sovereign cloud as one that:

* Protects and unlocks the value of critical data (e.g., national data, corporate data, and personal data) for both private and public sector organizations
* Delivers a national capability for the digital economy
* Secures data with audited security controls
* Ensures compliance with data privacy laws
* Improves control of data by providing both data residency and data sovereignty with full jurisdictional control
 
== Partnering with a Trusted VMware Sovereign Cloud Service Provider
 
To ensure success, organizations must work with partners they trust and that are capable of hosting authentic and autonomous sovereign cloud platforms. VMware Cloud Providers recognized within the VMware Sovereign Cloud initiative commit to designing and operating cloud solutions based on modern, software-defined architectures that embody key principles and best practices outlined in the VMware Sovereign Cloud framework.
 
* *Data Sovereignty and Jurisdictional Control* – All data is resident and subject to the exclusive control and authority of the nation state where that data was collected. Operations are fully managed within the jurisdiction
* *Data Access and Integrity* – Cloud infrastructure is resilient and available in at least two data center locations within the jurisdiction with secure and private connectivity options available.
* *Data Security and Compliance* – Information security management system controls are certified against an industry recognized global (or regional) standard and audited regularly.
* *Data Independence and Mobility* – Support for modern application architectures to prevent vendor cloud lock-in and enable application portability and independence
 
== NetApp StorageGRID Integration with VMware Cloud Director
 
NetApp has collaborated with VMware to integrate NetApp StorageGRID into VMware Cloud Director in support of the VMware Sovereign Cloud. This plug-in to VMware Cloud Director enables service providers to use StorageGRID as their object storage offering (regardless of use case) and allows StorageGRID management through the same VMware multi-tenant solution (VMware Cloud Director) used by service providers to manage other parts of their offering catalog. 

Partners that deliver VMware Sovereign Clouds can choose NetApp StorageGRID to help them managed and maintain cloud environments with unstructured data. Its universal compatibility in its native support for industry-standard APIs, like Amazon S3 API, helps ensure smooth interoperability across diverse cloud environments, and unique innovations such as automated lifecycle management helps ensure more cost-effective safeguarding, storage, and long-term preservation of customers’ unstructured data.
 
NetApp’s Sovereign Cloud integration with Cloud Director providers customers with:

* Assurance that sensitive data, including metadata, remains under sovereign control while preventing access by foreign authorities that could violate data privacy laws. 
* Increased security and compliance that protects applications and data from rapidly evolving attack vectors while maintaining continuous compliance with a trusted local. infrastructure, built-in frameworks, and local experts.
* Future-proofed infrastructure to react quickly to changing data privacy regulations, security threats, and geopolitics.
* The ability to unlock the value of data with secure data sharing and analysis to drive innovation without violating privacy laws. Data integrity is protected to ensure accurate insights.