---
sidebar: sidebar
permalink: vmw-sc/sc-overview.html
keywords: NetApp Solutions, vmware, sovereign cloud
summary:
---

= Overview of VMware Sovereign Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
The concept of sovereignty is emerging as a necessary component of cloud computing for many entities that process and maintain highly sensitive data, such as national and state governments, and highly regulated industries, such finance and healthcare. National governments are also looking to expand digital economic capability and reduce reliance on multi-national firms for their cloud services. 

== VMware Sovereign Cloud Initiative

VMware defines a sovereign cloud as one that:

* Protects and unlocks the value of critical data (e.g., national data, corporate data, and personal data) for both private and public sector organizations
* Delivers a national capability for the digital economy
* Secures data with audited security controls
* Ensures compliance with data privacy laws
* Improves control of data by providing both data residency and data sovereignty with full jurisdictional control
 
== Partnering with a Trusted VMware Sovereign Cloud Service Provider
 
To ensure success, organizations must work with partners they trust and that are capable of hosting authentic and autonomous sovereign cloud platforms. VMware Cloud Providers recognized within the VMware Sovereign Cloud initiative commit to designing and operating cloud solutions based on modern, software-defined architectures that embody key principles and best practices outlined in the VMware Sovereign Cloud framework.
 
* *Data Sovereignty and Jurisdictional Control* – All data is resident and subject to the exclusive control and authority of the nation state where that data was collected. Operations are fully managed within the jurisdiction
* *Data Access and Integrity* – Cloud infrastructure is resilient and available in at least two data center locations within the jurisdiction with secure and private connectivity options available.
* *Data Security and Compliance* – Information security management system controls are certified against an industry recognized global (or regional) standard and audited regularly.
* *Data Independence and Mobility* – Support for modern application architectures to prevent vendor cloud lock-in and enable application portability and independence
 
For more information from VMware, please visit:

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["VMware Sovereign Cloud Overview"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["What is VMware Sovereign Cloud?"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["Introducing the New VMware Sovereign Cloud Initiative"]
* link:https://www.vmware.com/content/dam/learn/en/amer/fy22/pdf/1173457_Sovereign_Cloud_Technical_Whitepaper_V3.pdf["VMware Sovereign Cloud Technical White Paper"]
