---
sidebar: sidebar
permalink: containers/anthos_reference_hardware_software_requirements.html
summary: This section describes the hardware and software requirements for the NetApp HCI and Anthos solution.
keywords: H410C, H410S, Cisco Nexus, Mellanox, F5 Big-IP, Terraform
---

= Hardware and Software Requirements

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]

This section describes the hardware and software requirements for the NetApp HCI and Anthos solution.

== Hardware Requirements

The following table lists the minimum number of hardware components that are required to implement the solution. The hardware components that are used in specific implementations of the solution might vary based on customer requirements.

[cols=3*,options="header",cols="40,40,20"]
|===
| Hardware
| Model
| Quantity
| NetApp HCI compute nodes | NetApp H410C | 2
| NetApp HCI storage nodes | NetApp H410S | 4
| Data switches | Cisco Nexus 3048 | 2
| Management switches | Mellanox NS2010 | 2
|===

== Software Requirements

The following table lists the software components that are required to implement the solution. The software components that are used in any implementation of the solution might vary based on customer requirements.

[cols=3*,options="header",cols="40,40,20"]
|===
| Software
| Purpose
| Version
| NetApp HCI | Infrastructure (compute/storage) | 1.6P1
| VMware vSphere | Virtualization | 6.5U2
| Anthos on VMware | Container orchestration | 1.1
| F5 Big-IP Virtual Edition | Load balancing | 15.0.1
| HashiCorp Terraform | Automation and provisioning | 0.12.12
| NetApp Trident | Storage management | 19.10
|===

link:containers/anthos_reference_workflow_summary.html[Next: Workflow Summary]
