---
sidebar: sidebar
permalink: containers/anthos_concept_overview.html
summary: Concept NVA-1141 program summary
keywords: Kubernetes, GKE, NVA-1141
---

= NVA-1141: NetApp HCI with Anthos, Design and Deployment

:hardbreaks: ;
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Alan Cowles

The program solutions described in this document are designed and thoroughly tested to minimize deployment risks and accelerate time to market.

This document is for NetApp and partner solutions engineers and customer strategic decision makers. It describes the architecture design considerations that were used to determine the specific equipment, cabling, and configurations required to support the validated workload.

NetApp HCI with Anthos is a verified, best-practice hybrid cloud architecture for the deployment of an on-premises Google Kubernetes Engine (GKE) environment in a reliable and dependable manner. This NetApp Verified Architecture reference document serves as both a design guide and a deployment validation of the Anthos solution on NetApp HCI. The architecture described in this document has been validated by subject matter experts at NetApp and Google to provide the advantage of running Anthos on NetApp HCI within your own enterprise data-center environment.

NetApp HCI, is the industry’s first and leading disaggregated hybrid cloud infrastructure, providing the widely recognized benefits of hyperconverged solutions. Benefits include lower TCO and ease of acquisition, deployment, and management for virtualized workloads, while also allowing enterprise customers to independently scale compute and storage resources as needed. NetApp HCI with Anthos provides an on-premises, cloud-like experience for the deployment of containerized workloads managed by Anthos GKE on-premises. This solution provides simplified management, detailed metrics, and a range of additional functionalities that enable the easy movement of workloads deployed both on-site and in the cloud.

== Features

With NetApp HCI for Anthos, you can deploy a fully integrated, production-grade Anthos GKE environment in your on-premises data center, which allows you to take advantage of the following features:

*	NetApp HCI compute and storage nodes
** Enterprise-grade hyperconverged infrastructure designed for hybrid cloud workloads
** NetApp Element storage software
** Intel-based server compute nodes, including options for Nvidia GPUs
* VMware vSphere 6.5
** Enterprise hypervisor solution for deployment and management of virtual infrastructures
* Anthos GKE in Google Cloud and On-Prem
** Deploy Anthos GKE instances in Google Cloud or on NetApp HCI

The NetApp Verified Architecture program gives customers reference configurations and sizing guidance for specific workloads and use cases.

link:containers/anthos_concept_solution_components.html[Next: Solution Components]
