---
sidebar: sidebar
permalink: containers/anthos_task_deploy_the_anthos_admin_workstation.html
summary: The admin workstation is a vSphere VM deployed within your NetApp HCI environment that is preinstalled with all the tools necessary to administer the Anthos on VMware solution. Follow the instructions in this section to deploy the Anthos admin workstation.
keywords: virtual appliance, vCenter, vDS, gkectl, DHCP
---

= 7. Deploy the Anthos admin workstation

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

The admin workstation is a vSphere VM deployed within your NetApp HCI environment that is preinstalled with all the tools necessary to administer the Anthos on VMware solution. Follow the instructions in this section to deploy the Anthos admin workstation.

To deploy the Anthos admin workstation, complete the following steps:

. Download the gkeadm binary into your working directory
+
----
[user@rhel7 anthos-install]$ gsutil cp gs://gke-on-prem-release/gkeadm/1.6.1-gke.1/linux/gkeadm ./
[user@rhel7 anthos-install]$ chmod +x gkeadm
----

. Use the gkeadm tool to create an admin workstation configuration file.
+
----
[user@rhel7 anthos-install]$ ./gkeadm create config
----

. Two files are created: `credential.yaml` and `admin-ws-config.yaml`. Fill out each of these files.
+
.. credential.yaml contains your username and passwords for your VMware vCenter server.
+

----
kind: CredentialFile
items:
- name: vCenter
  username: "administrator@vsphere.local"
  password: "vSphereAdminPassword"
----

.. admin-ws-config.yaml contains other information about your vSphere environment as well as the physical and networking options for the admin-workstation VM.
+

----
gcp:
  # Path of the whitelisted service account's JSON key file
  whitelistedServiceAccountKeyPath: "/home/anthos-install/service-keys/access-key.json"
# Specify which vCenter resources to use
vCenter:
  # The credentials and address GKE On-Prem should use to connect to vCenter
  credentials:
    address: "anthos-vc.cie.netapp.com"
    datacenter: "NetApp-HCI-Datacenter-01"
    datastore: "VM_Datastore"
    cluster: "NetApp-HCI-Cluster-01"
    network: "VM_Network"
    resourcePool: "Anthos-Resource-Pool"
# Provide the path to vCenter CA certificate pub key for SSL verification
    caCertPath: "/home/anthos-install/vcenter.pem"
# The URL of the proxy for the jump host
proxyUrl: ""
adminWorkstation:
  name: gke-admin-ws-200915-151421
  cpus: 4
  memoryMB: 8192
#The boot disk size of the admin workstation in GB. It is recommended to use a disk with at least 50 GB to host images decompressed from the bundle.
  diskGB: 50
# Name for the persistent disk to be mounted to the home directory (ending in
.vmdk).
# Any directory in the supplied path must be created before deployment.
  dataDiskName: gke-on-prem-admin-workstation-data-disk/gke-admin-ws-200915-151421-data-disk.vmdk
# The size of the data disk in MB.
  dataDiskMB: 512
  network:
# The IP allocation mode: 'dhcp' or 'static'
    ipAllocationMode: "dhcp"
# # The host config in static IP mode. Do not include if using DHCP
  # hostConfig:
    #   # The IPv4 static IP address for the admin workstation
    #   ip: ""
    #   # The IP address of the default gateway of the subnet in which the admin workstation
    #   # is to be created
    #   gateway: ""
    #   # The subnet mask of the network where you want to create your admin workstation
    #   netmask: ""
    #   # The list of DNS nameservers to be used by the admin workstation
    #   dns:
    #   - ""
  # The URL of the proxy for the admin workstation
  proxyUrl: ""
  ntpServer: ntp.ubuntu.com
----

. Create the admin workstation.
+

----
[user@rhel7 anthos-install]$ ./gkeadm create admin-workstation
The output will be verbose as the workstation is created. In the end you will be prompted with the IP address to login to the workstation if you chose DHCP.
...
Getting ... service account...
...
********************************************************************
Admin workstation is ready to use.

Admin workstation information saved to /usr/local/google/home/me/my-admin-workstation
This file is required for future upgrades
SSH into the admin workstation with the following command:
ssh -i /home/user/.ssh/gke-admin-workstation ubuntu@10.63.172.10
********************************************************************
----


link:anthos_task_deploy_the_admin.html[Next: Deploy the admin and the first user cluster]
