---
sidebar: sidebar
permalink: containers/rh-os-n_use_case_openshift_virtualization_deployment_
rosa_prerequisites.html
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, ROSA, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization
summary: Red Hat OpenShift Virtualization on ROSA
---

= Deploy Red Hat OpenShift Virtualization with FSxN on ROSA 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This section provides details for setting up FSx for NetApp ONTAP as the default Storage Class for the ROSA cluster, and then create a Virtual Machine that will leverage FSx ONTAP storage for its volumes. 
We will also look into connecting to the Virtual Machine using the guest credentials, and restarting the VM. And finally, we will perform a live migration of the Virtual Machine from the current node to a new node. We will examine the contents of the disk storage after a VM restart and the live migration .

== Prerequisites

*	link:https://signin.aws.amazon.com/signin?redirect_uri=https://portal.aws.amazon.com/billing/signup/resume&client_id=signup[AWS account]

*	link:https://console.redhat.com/[A Red Hat account]

*	IAM user link:https://www.rosaworkshop.io/rosa/1-account_setup/[with appropriate permissions] to create and access ROSA cluster
*   link:https://aws.amazon.com/cli/[AWS CLI]
*   link:https://console.redhat.com/openshift/downloads[ROSA CLI]
*   link:https://console.redhat.com/openshift/downloads[OpenShift command-line interface] (oc)
*   link:https://docs.aws.amazon.com/eks/latest/userguide/helm.html[Helm 3 documentation]
*   link:https://docs.openshift.com/rosa/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html[A HCP ROSA cluster] (with at least 3 bare-metal worker nodes)
*   link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/virtualization/installing#virt-aws-bm_preparing-cluster-for-virt[OpenShift Virtualization installed on ROSA Cluster]
*   link:https://console.redhat.com/openshift/overview[Access to Red Hat OpenShift web console]
