---
sidebar: sidebar
permalink: containers/rh-os-n_use_case_openshift_virtualization_deployment_prerequisites.html
keywords: OpenShift, OCP, NetApp Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization
summary: Red Hat OpenShift Virtualization with NetApp ONTAP
---

= Deploy Red Hat OpenShift Virtualization with NetApp ONTAP

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]

=== Pre-requisites:

*	A Red Hat OpenShift cluster (greater than version 4.6) installed on bare-metal infrastructure with RHCOS worker nodes.
*	The OpenShift cluster must be installed via installer provisioned infrastructure (IPI).
*	Deploy Machine Health Checks to maintain HA for VMs.
*	A NetApp ONTAP cluster.
*	NetApp Trident installed on the OpenShift cluster.
*	A Trident backend configured with an SVM on ONTAP cluster.
*	A StorageClass configured on the OpenShift cluster with NetApp Trident as the provisioner.
*	Cluster-admin access to Red Hat OpenShift cluster.
*	Admin access to NetApp ONTAP cluster.
*	An admin workstation with tridentctl and oc tools installed and added to $PATH.

Since OpenShift Virtualization is managed by an operator installed on the OpenShift cluster, it imposes additional overhead on memory, CPU and storage which will need to be accounted for while planning the hardware requirements for the cluster. Refer to the documentation https://docs.openshift.com/container-platform/4.7/virt/install/preparing-cluster-for-virt.html#virt-cluster-resource-requirements_preparing-cluster-for-virt[here] to get more details.

Optionally, you can also specify a subset of the OpenShift cluster nodes which would host the OpenShift Virtualization operators, controllers and VMs by configuring node placement rules. To configure node placement rules for OpenShift Virtualization, follow the documentation https://docs.openshift.com/container-platform/4.7/virt/install/virt-specifying-nodes-for-virtualization-components.html[here].

For the storage backing OpenShift Virtualization, it is recommended to have a dedicated StorageClass which requests storage from a particular Trident backend which in turn is backed by a dedicated SVM. This maintains a level of multi-tenancy w.r.t. the data being served for VM based workloads on the OpenShift cluster.

link:rh-os-n_use_case_openshift_virtualization_deployment.html[Next: Deploy via operator]
