---
sidebar: sidebar
permalink: containers/rh-os-n_load_balancers.html
keywords: Advanced Configuration, Load Balancers, MetalLB
summary: This section is dedicated to exploring load balancer options for users that want to customize their Red Hat OpenShift with NetApp deployment.
---

= Exploring Load Balancer Options: Red Hat OpenShift with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.563897
//

Traditionally Red Hat OpenShift makes applications available to the outside world through routes. A service is exposed by giving it an externally-reachable hostname. The defined route and the endpoints identified by it's service can be consumed by an OpenShift router to provide this named connectivity to external clients.

In some cases applications will require the deployment and configuration of customized load balancers to expose the appropriate services. One example of this is NetApp Astra Control Center. To meet this need, we have evaluated a number of custom load balancer options, their installation and configuration are detailed within this section.

The following pages have additional information about the load balancer options validated in the Red Hat OpenShift with NetApp solution:

* link:rh-os-n_LB_MetalLB.html[MetalLB]

link:rh-os-n_use_cases.html[Next: Solution Validation/Use Cases: Red Hat OpenShift with NetApp.]
