---
sidebar: sidebar
permalink: containers/rh-os-n_videos_and_demos.html
keywords: video, demonstration, deployment
summary:
---

= Videos and Demos: Red Hat OpenShift with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.664333
//

[.lead]
The following videos demonstrate some of the capabilities documented in this document:

video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto, title="Ansible automation to deploy Trident and create Storage Class on the OpenShift Cluster", width=360]

link:https://github.com/NetApp/trident-install[The playbook used to install NetApp Trident, StorageClasses, and Backend using Ansible can be found in github.]

video::2e2c6fdb-4651-46dd-b028-b1ed00d37da3[panopto, title="Deploy a new VM in OpenShift Virtualization using ONTAP SAN (iSCSI) Storage Class", width=360]

video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto, title="Deploy a postgresql container app using ONTAP NAS Storage Class", width=360]

video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto, title="Cloud Insights integration with Openshift Virtualization", width=360]

video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto, title="Using Red Hat MTV to migrate VMs to OpenShift Virtualization with NetApp ONTAP Storage", width=360]

video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto, title="Accelerate Software Development with Astra Control and NetApp FlexClone Technology - Red Hat OpenShift with NetApp", width=360]

video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto, title="Leverage NetApp Astra Control to Perform Post-mortem Analysis and Restore Your Application", width=360]

video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto, title="Data Protection in CI/CD pipeline with Astra Control Center", width=360]
 
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto, title="Workload Migration using Astra Control Center - Red Hat OpenShift with NetApp", width=360]
 
video::27773297-a80c-473c-ab41-b01200fa009a[panopto, title="Workload Migration - Red Hat OpenShift with NetApp", width=360]

video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto, title="Installing OpenShift Virtualization - Red Hat OpenShift with NetApp", width=360]

video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto, title="Deploying a Virtual Machine with OpenShift Virtualization - Red Hat OpenShift with NetApp", width=360]
 
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto, title="NetApp HCI for Red Hat OpenShift on Red Hat Virtualization", width=360]

