---
sidebar: sidebar
permalink: containers/rh-os-rhv_architectural_overview.html
keywords: hardware, software, HCI, Mellanox, Cisco, Nexus, Trident, RHV
summary:
---

= Architectural Overview: NetApp HCI for Red Hat OpenShift on RHV
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.548101
//

[.lead]

== Hardware Requirements

The following table lists the minimum number of hardware components that are required to implement the solution.  The hardware components that are used in specific implementations of the solution might vary based on customer requirements.

|===
|Hardware |Model |Quantity

|NetApp HCI compute nodes
|NetApp H410C
|2
|NetApp HCI storage nodes
|NetApp H410S
|4
|Data switches
|Mellanox SN2010
|2
|Management switches
|Cisco Nexus 3048
|2
|===

=== Software Requirements

The following table lists the software components that are required to implement the solution. The software components that are used in any implementation of the solution might vary based on customer requirements.

|===
|Software |Purpose |Version

|NetApp HCI
|Infrastructure (compute/storage)
|1.8
|NetApp Element
|Storage
|12.0
|NetApp Trident
|Storage orchestration
|20.04
|RHV
|Virtualization
|4.3.9
|Red Hat OpenShift
|Container orchestration
|4.4.6
|===

link:rh-os-rhv_design_considerations.html[Next: Design Considerations: NetApp HCI for Red Hat OpenShift on RHV]
