---
sidebar: sidebar
permalink: containers/rh-os-n_solution_overview.html
keywords: NVA-1160, Red Hat, OpenShift, Netapp, Astra Trident
summary: This reference document provides deployment validation of the Red Hat OpenShift solution, deployed through Installer Provisioned Infrastructure (IPI) in several different data center environments as validated by NetApp. It also details storage integration with NetApp storage systems by making use of the Astra Trident storage orchestrator for the management of persistent storage. Lastly, a number of solution validations and real world use cases are explored and documented.
---

= NVA-1160: Red Hat OpenShift with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.537397
//

Alan Cowles and Nikhil M Kulkarni, NetApp

This reference document provides deployment validation of the Red Hat OpenShift solution, deployed through Installer Provisioned Infrastructure (IPI) in several different data center environments as validated by NetApp. It also details storage integration with NetApp storage systems by making use of the Astra Trident storage orchestrator for the management of persistent storage. Lastly, a number of solution validations and real world use cases are explored and documented.

== Use cases

The Red Hat OpenShift with NetApp solution is architected to deliver exceptional value for customers with the following use cases:

* Easy to deploy and manage Red Hat OpenShift deployed using IPI (Installer Provisioned Infrastructure) on bare metal, Red Hat OpenStack Platform, Red Hat Virtualization, and VMware vSphere.

* Combined power of enterprise container and virtualized workloads with Red Hat OpenShift deployed virtually on OSP, RHV, or vSphere, or on bare metal with OpenShift Virtualization.

* Real world configuration and use cases highlighting the features of Red Hat OpenShift when used with NetApp storage and Astra Trident, the open source storage orchestrator for Kubernetes.

== Business value

Enterprises are increasingly adopting DevOps practices to create new products, shorten release cycles, and rapidly add new features. Because of their innate agile nature, containers and microservices play a crucial role in supporting DevOps practices. However, practicing DevOps at a production scale in an enterprise environment presents its own challenges and imposes certain requirements on the underlying infrastructure, such as the following:

* High availability at all layers in the stack

* Ease of deployment procedures

* Non-disruptive operations and upgrades

* API-driven and programmable infrastructure to keep up with microservices agility

* Multitenancy with performance guarantees

* Ability to run virtualized and containerized workloads simultaneously

* Ability to scale infrastructure independently based on workload demands

Red Hat OpenShift with NetApp acknowledges these challenges and presents a solution that helps address each concern by implementing the fully automated deployment of RedHat OpenShift IPI in the customer's choice of data center environment.

== Technology overview

The Red Hat OpenShift with NetApp solution is comprised of the following major components:

=== Red Hat OpenShift Container Platform

Red Hat OpenShift Container Platform is a fully supported enterprise Kubernetes platform. Red Hat makes several enhancements to open-source Kubernetes to deliver an application platform with all the components fully integrated to build, deploy, and manage containerized applications.

For more information visit the OpenShift website https://www.openshift.com[here].

=== NetApp storage systems

NetApp has several storage systems perfect for enterprise data centers and hybrid cloud deployments. The NetApp portfolio includes NetApp ONTAP, NetApp Element, and NetApp e-Series storage systems, all of which can provide persistent storage for containerized applications.

For more information visit the NetApp website https://www.netapp.com[here].

=== NetApp storage integrations

NetApp Astra Control offers a rich set of storage and application-aware data management services for stateful Kubernetes workloads, deployed in an on-prem environment and powered by trusted NetApp data protection technology.

For more information, visit the NetApp Astra website https://docs.netapp.com/us-en/astra-family/[here].

Astra Trident is an open-source and fully-supported storage orchestrator for containers and Kubernetes distributions, including Red Hat OpenShift.

For more information, visit the Astra Trident website https://docs.netapp.com/us-en/trident/index.html[here].

== Advanced configuration options

This section is dedicated to customizations that real world users would likely need to perform when deploying this solution into production, such as creating a dedicated private image registry or deploying custom load balancer instances.

== Current support matrix for validated releases

|===
|Technology |Purpose |Software version
|NetApp ONTAP
|Storage
|9.8, 9.9.1, 9.12.1
|NetApp Element 
|Storage
|12.3
|NetApp Astra Control 
|Application Aware Data Management
|21.12.60, 23.04, 23.07, 23.10, 24.02
|NetApp Astra Trident
|Storage Orchestration
|22.01.0, 23.04, 23.07, 23.10, 24.02
|Red Hat OpenShift
|Container orchestration
|4.6 EUS, 4.7, 4.8, 4.10, 4.11, 4.12, 4.13, 4.14
|VMware vSphere
|Data center virtualization
|7.0, 8.0.2
|===
