---
sidebar: sidebar
permalink: containers/rh-os-n_videos_and_demos.html
keywords: video, demonstration, deployment
summary:
---

= Videos and Demos: Red Hat OpenShift with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.664333
//

The following videos demonstrate some of the capabilities documented in this document:

[width=100%,cols="5a, 5a, 5a",frame="none",grid="rows"]
|===
.>| Accelerate Software Development with Astra Control and NetApp FlexClone Technology - Red Hat OpenShift with NetApp
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=26b7ea00-9eda-4864-80ab-b01200fa13ac&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Leverage NetApp Astra Control to Perform Post-mortem Analysis and Restore Your Application
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=3ae8eb53-eda3-410b-99e8-b01200fa30a8&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Data Protection in CI/CD pipeline with Astra Control Center
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=a6400379-52ff-4c8f-867f-b01200fa4a5e&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Workload Migration using Astra Control Center - Red Hat OpenShift with NetApp
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=e397e023-5204-464d-ab00-b01200f9e6b5&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Workload Migration - Red Hat OpenShift with NetApp
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=27773297-a80c-473c-ab41-b01200fa009a&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Installing OpenShift Virtualization - Red Hat OpenShift with NetApp
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=e589a8a3-ce82-4a0a-adb6-b01200f9b907&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| Deploying a Virtual Machine with OpenShift Virtualization - Red Hat OpenShift with NetApp
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=8a29fa18-8643-499e-94c7-b01200f9ce11&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| NetApp HCI for Red Hat OpenShift on Red Hat Virtualization
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=13b32159-9ea3-4056-b285-b01200f0873a&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

|
|===

link:rh-os-n_additional_information.html[Next: Additional Information: Red Hat OpenShift with NetApp.]
