---
sidebar: sidebar
permalink: containers/rh-os-n_use_case_multitenancy_configuration.html
keywords: OpenShift, OCP, NetApp Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy
summary: Configuring Multitenancy on Red Hat OpenShift with NetApp
---

= Configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]

For any multi-tenant solution, it is necessary to ensure that no user has more access to any cluster resources than required. So, the entire set of resources that are to be configured as part of the multi-tenancy configuration is divided between cluster-admin, storage-admin and developers working on each project.

The below table outlines the different tasks to be performed by different users:

[frame="all"]
|===
|Role | Tasks

.4+| *Cluster-admin*
| Create projects for different applications/workloads
|	Create ClusterRoles and RoleBindings for storage-admin
|	Create Roles and RoleBindings for developers assigning access to specific projects
| [Optional] Configure projects to schedule pods on specific nodes

.4+| *Storage-admin*
|	Create SVMs on NetApp ONTAP
| Create Trident backends
|	Create StorageClasses
|	Create Storage ResourceQuotas

.3+| *Developers*
|	Validate access to create/patch PVCs/pods in assigned project
|	Validate access to create/patch PVCs/pods in another project
|	Validate access to view/edit Projects, ResourceQuotas and StorageClasses
|===


link:rh-os-n_use_case_multitenancy_configuration_prerequisites.html[Next: Pre-Requisites]
