---
sidebar: sidebar
permalink: containers/rh-os-n_astra_protect.html
summary:
keywords: Astra, OpenShift, Kubernetes, Protection
---

= Protect Your Applications

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

With the application workloads selected, it's now time to manage protection settings for those workloads.

== Creating An Application SnapShot

A snapshot of an application creates an ONTAP Snapshot copy, and allows you to restore the application back to it's original cluster.

.	To take a snapshot of the application, go to ‘Apps’ -> ‘Managed’ tab and click on the application you wish to take a snapshot of.

. Go to to ‘Data Protection’ tab, click on ‘Create Snapshot’, verify the snapshot details and then click on ‘Snapshot App’.

. It will take a few minutes to create the snapshot and once it is successfully created, the status becomes ‘Available’.

<<create snapshot screenshot>>

== Creating An Application Backup

A backup of an application captures the active state of the application and the configuration of it's resources, coverts them into files, and stores them in a remote object storage bucket.

For the backup/restore of managed applications in Astra Control Center, the pre-requisite is to configure superuser settings for the backing ONTAP systems.

This can be performed with the following syntax.

----
ONTAP::> export-policy rule modify -vserver ocp-trident -policyname default -ruleindex 1 -superuser sys
ONTAP::> export-policy rule modify -policyname default -ruleindex 1 -anon 65534 -vserver ocp-trident
----

.	To create a backup of the managed application in Astra Control Center, go to ‘Apps’ -> ‘Managed’ tab and click on the application you wish to take a backup of.

. Then go to ‘Data Protection’ tab, click on ‘Create Backup’, enter the backup details, click on ‘Review’ and once the details are reviewed, click on ‘Backup’.

. Depending on the size of the application and data, the backup can take around 10-20 minutes and once the backup is completed successfully, the status of the backup becomes ‘Available’.
<<backup create screenshot>>

== Creating A Clone Of An Application

An application can be cloned at the push of a button either to the same, or a remote cluster for test, dev, or application protection / disaster recovery purposes.


== Restoring An Application From Backup.

An application can be restored to a previous state on the cluster it was backed up from, or to a remote cluster for application migration purposes.

link:rh-os-n_use_cases.html[Next: Solution Validation / Use Cases: Red Hat OpenShift with NetApp.]
