---
sidebar: sidebar
permalink: containers/rh-os-n_astra_register.html
summary:
keywords: Astra, OpenShift, Kubernetes, Register
---

= Register Your Red Hat OpenShift Clusters

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

To enable Astra Control Center to manage your workloads, you first need to register your Red Hat OpenShift Cluster.

== Register A Red Hat OpenShift Cluster

.	The first step is to add the OpenShift clusters to the Astra Control Center and manage them as Compute clusters. Go to ‘Clusters’ and click on ‘Add a Cluster’, upload the kubeconfig file for the OpenShift cluster and then select the storageclass that is being provisioned using Trident backed by an SVM on NetApp ONTAP. Verify the details and click on ‘Add Cluster’.
<<add cluster screenshot>>

.	Register both the OpenShift clusters as described in step 1. The clusters when added move to ‘Discovering’ status while Astra Control Center inspects the clusters and are successfully registered when their status changes to ‘Available’.
<<clusters available screenshot>>
+
NOTE: All the Red Hat OpenShift clusters that are to be managed by Astra Control Center should have access to the image registry that was used for its installation.

.	Next step is to import ONTAP clusters as Storage resources to be managed as backends by Astra Control Center. When OpenShift clusters are added to Astra and a storageclass is configured, it automatically discovers and inspects the ONTAP cluster backing the storageclass but is not imported into Astra Control Center to be managed.
<<backend discovery screenshot>>

.	To import the ONTAP clusters, go to ‘Backends’ and click on ‘Import’ next to the ONTAP cluster that has to be managed. Enter the ONTAP cluster management IP and credentials, click ‘Review Information’ and then click ‘Import storage backend’.
<<add backend screenshot>>

.	For backup and restore across OpenShift clusters, Astra Control Center requires to be backed up by object storage. It currently supports ONTAP S3, StorageGRID, AWS S3 and for the purpose of this installation, we are going to configure AWS S3 bucket. Go to ‘Buckets’, click ‘Add bucket’ and select ‘Generic S3’. Enter the details about the S3 bucket and credentials to access it, click on the checkbox ‘Make this bucket the default bucket for the cloud’ and then click ‘Add’.
<<add storage bucket>>



link:rh-os-n_astra_applications.html[Next: Discover Which Applications To Protect: Red Hat OpenShift with NetApp.]
