---
sidebar: sidebar
permalink: containers/rh-os-rhv-5._generate_and_add_ssh_private_key.html
keywords: SSH, Private Key
summary:
---

= 5. Generate and Add SSH Private Key: NetApp HCI for Red Hat OpenShift on RHV
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.601986
//

[.lead]

To generate and add an SSH private key, complete the following steps:

. For the installation debugging or disaster recovery on the OpenShift cluster, you must provide an SSH key to both the `ssh-agent` and the installation program. Create an SSH key if one does not already exist for password-less authentication on the RHEL machine.
+

....
[user@rhel7 ~]$  ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa
....

. Start the `ssh-agent` process and configure it as a background running task.
+

....
[user@rhel7 ~]$  eval "$(ssh-agent -s)"
Agent pid 31874
....

. Add the SSH private key that you created in step 2 to the  `ssh-agent` , which enables you to SSH directly to the nodes without having to interactively pass the key.
+

....
[user@rhel7 ~]$  ssh-add ~/.ssh/id_rsa
....

link:rh-os-rhv-6._install_openshift_container_platform.html[Next: 6. Install OpenShift Container Platform]
