---
sidebar: sidebar
permalink: containers/rh-os-n_use_case_multitenancy_overview.html
keywords: OpenShift, OCP, NetApp Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy
summary: Configuring Multitenancy on Red Hat OpenShift with NetApp
---

= Configuring Multitenancy on Red Hat OpenShift with NetApp: Red Hat OpenShift with NetApp


:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]

Many organizations that run multiple applications or workloads on containers tend to deploy one Red Hat OpenShift cluster per application/workload. This allows the organizations to implement strict isolation for the application/workload hence optimizing performance and reducing security vulnerabilities. However, deploying a separate Red Hat OpenShift cluster for each application poses its own set of problems. It increases operational overhead having to monitor and manage each cluster on its own, increases cost owing to dedicated resources for different applications and hinders efficient scalability.

To overcome these problems, one can consider running all the applications/workloads in a single Red Hat OpenShift cluster. But in such an architecture, resource isolation and application security vulnerabilities pose themselves as one of the major challenges. Any security vulnerability in one workload would naturally spill over into another workload thus increasing the impact zone. In addition to that, any abrupt uncontrolled resource utilization by one application would affect the performance of another application since there is no resource allocation policy by default.

Hence, organizations look out for solutions that pick up the best in both worlds i.e., allow them to run all their workloads in a single cluster and yet offer the benefits of dedicated cluster for each workload. One such effective solution is to configure multi-tenancy on Red Hat OpenShift. Multi-tenancy is an architecture that allows multiple tenants to co-exist on the same cluster with proper isolation of resources, security etc. In this context, a tenant can be viewed as a subset of the cluster resources that are configured to be used by a particular group of users for an exclusive purpose. Hence, configuring multi-tenancy on a Red Hat OpenShift cluster provides the following advantages –

. Reduction in CapEx/OpEx by allowing the cluster resources to be shared.
. Lower operational and management overhead.
. Securing the workloads from cross-contamination of security breaches.
. Protection of workloads from unexpected performance degradation due to resource contention.

For a full-fledged multi-tenant OpenShift cluster, quotas and restrictions must be configured for cluster resources belonging to different resource buckets – compute, storage, networking, security etc. Although we cover certain aspects of all the resource buckets in this solution, the focus is to highlight the best-practices for isolating and securing the data served or consumed by multiple workloads on the same Red Hat OpenShift cluster by configuring multi-tenancy on storage resources that are dynamically allocated by NetApp Trident backed by NetApp ONTAP.

link:rh-os-n_use_case_multitenancy_architecture.html[Next: Architecture]
