---
sidebar: sidebar
permalink: containers/rh-os-n_use_case_advanced_cluster_management_deployment_prerequisites.html
keywords: OpenShift, OCP, Astra Trident, NetApp ONTAP, ONTAP, Trident, Red Hat OpenShift, Advanced Cluster Management, Advanced Cluster Management for Kubernetes
summary: Advanced Cluster Management for Kubernetes on Red Hat OpenShift with NetApp
---

= Deploy Advanced Cluster Management for Kubernetes


:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

== Prerequisites

.	A Red Hat OpenShift cluster (greater than version 4.5) for the hub cluster
.	Red Hat OpenShift clusters (greater than version 4.4.3) for managed clusters
.	Cluster-admin access to the Red Hat OpenShift cluster
.	A Red Hat subscription for Advanced Cluster Management for Kubernetes

Advanced Cluster Management is an add-on on for the OpenShift cluster, so there are certain requirements and restrictions on the hardware resources based on the features used across the hub and managed clusters. You need to take these issues into account when sizing the clusters. See the documentation https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html-single/install/index#network-configuration[here] for more details.

Optionally, if the hub cluster has dedicated nodes for hosting infrastructure components and you would like to install Advanced Cluster Management resources only on those nodes, you need to add tolerations and selectors to those nodes accordingly. For more details, see the documentation https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/install/installing#installing-on-infra-node[here].

link:rh-os-n_use_case_advanced_cluster_management_deployment.html[Next: Installation.]
