---
sidebar: sidebar
permalink: containers/rh-os-n_openshift_OCP.html
keywords: OpenShift, OpenStack, private cloud
summary:
---

= OpenShift on Red Hat OpenStack Platform: Red Hat OpenShift with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 0.9 (June 4, 2020)
//
// 2020-06-25 14:31:33.555482
//




=== Network Design

The Red Hat OpenShift with NetApp solution uses two data switches to provide primary data connectivity at 25Gbps. It also uses two additional management switches that provide connectivity at 1Gbps for in-band management for the storage nodes and out-of-band management for IPMI functionality.

==== VLAN Requirements

The Red Hat OpenShift with NetApp solution is designed to logically separate network traffic for different purposes by using virtual local area networks (VLANs). Depending on the type of OpenShift deployment (Baremetal, Private Cloud, Virtual) there are several networking options available.
Please consult the guide for your physical infrastructure deployment to determine which networking configuration applies.

==== Network Infrastructure Support Resources

The following infrastructure should be in place prior to the deployment of the OpenShift Container Platform (OCP):

* At least one DNS server which provides a full host-name resolution.

* At least three NTP servers which can keep time synchronized for the servers in the solution.

* (Optional) Outbound internet connectivity for the OpenShift environment.


link:rh-os-n_deployment_summary.html[Next: Deploying Red Hat OpenShift with NetApp]
