---
sidebar: sidebar
permalink: ehr-epic-deploy/ehr-epic-deploy_ontap_documentation.html
keywords: ontap, documentation, guides, flexpod, deployment
summary: The following links and guides are relevant to this document and FlexPod deployment.
---

= ONTAP documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-07 11:34:58.373251
//

* NetApp Product Documentation
+
https://www.netapp.com/us/documentation/index.aspx[https://www.netapp.com/us/documentation/index.aspx^]

* Virtual Storage Console (VSC) for vSphere documentation
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048[https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048^]

* ONTAP 9 Documentation Center
+
http://docs.netapp.com/ontap-9/index.jsp[http://docs.netapp.com/ontap-9/index.jsp^]

* FC Express Guide for ESXi
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html^]

* All ONTAP 9.3 Documentation
+
https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579[https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579^]

** Software Setup Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html?lang=dot-cm-ssg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html?lang=dot-cm-ssg^]

** Disks and Aggregates Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html?lang=dot-cm-psmg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html?lang=dot-cm-psmg^]

** SAN Administration Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html?lang=dot-cm-sanag[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html?lang=dot-cm-sanag^]

** SAN Configuration Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?lang=dot-cm-sanconf[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?lang=dot-cm-sanconf^]

** FC Configuration for Red Hat Enterprise Linux Express Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-rhel-cg/home.html?lang=exp-fc-rhel-cg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-rhel-cg/home.html?lang=exp-fc-rhel-cg^]

** FC Configuration for Windows Express Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-cpg/home.html?lang=exp-fc-cpg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-cpg/home.html?lang=exp-fc-cpg^]

** FC SAN Optimized AFF Setup Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-fcsan-optaff-sg/home.html?lang=cdot-fcsan-optaff-sg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-fcsan-optaff-sg/home.html?lang=cdot-fcsan-optaff-sg^]

** High-Availability Configuration Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-hacg/home.html?lang=dot-cm-hacg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-hacg/home.html?lang=dot-cm-hacg^]

** Logical Storage Management Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html?lang=dot-cm-vsmg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html?lang=dot-cm-vsmg^]

** Performance Management Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html?lang=pow-perf-mon[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html?lang=pow-perf-mon^]

** SMB/CIFS Configuration Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/home.html?lang=pow-cifs-cg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/home.html?lang=pow-cifs-cg^]

** SMB/CIFS Reference
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html?lang=cdot-famg-cifs[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html?lang=cdot-famg-cifs^]

** Data Protection Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html?lang=pow-dap[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html?lang=pow-dap^]

** Data Protection Tape Backup and Recovery Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ptbrg/home.html?lang=dot-cm-ptbrg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ptbrg/home.html?lang=dot-cm-ptbrg^]

** NetApp Encryption Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html?lang=pow-nve[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html?lang=pow-nve^]

** Network Management Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html?lang=dot-cm-nmg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html?lang=dot-cm-nmg^]

** Commands: Manual Page Reference for ONTAP 9.3
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/home.html?lang=dot-cm-cmpr-930[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/home.html?lang=dot-cm-cmpr-930^]
