---
sidebar: sidebar
permalink: ehr-epic-deploy/ehr-epic-deploy_base_infrastructure_configuration.html
keywords: base, configuration, infrastructure, network, connectivity, storage, host, software
summary: This section discribes the network connections, storage connections, and software that must be in place to configure the infrastructure.
---

= Base infrastructure configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-07 11:34:58.150784
//

== Network connectivity

The following network connections must be in place before configuring the infrastructure:

* Link aggregation using port channels and virtual port channels is used throughout, enabling the design for higher bandwidth and HA.
** Virtual port channel is used between the Cisco FI and Cisco Nexus switches.
** Each server has vNICs with redundant connectivity to the unified fabric. NIC failover is used between FI for redundancy.
** Each server has vHBAs with redundant connectivity to the unified fabric.
* The Cisco UCS FI are configured in end-host mode as recommended, providing dynamic pinning of vNICs to uplink switches.

== Storage connectivity

The following storage connections must be in place before configuring the infrastructure:

* Storage ports ifgroups (vPC)
* 10G link to switch N9k-A
* 10G link to switch N9k-B
* In- band management (active-passive bond):
** 1G link to management switch N9k-A
** 1G link to management switch N9k-B
* 16G FC end-to-end connectivity through Cisco MDS switches. Single initiator zoning configured.
* FC SAN boot to fully achieve stateless computing. Servers are booted from LUNs in the boot volume hosted on the AFF storage cluster.
* All Epic workloads are hosted on FC LUNs, which are spread across the storage controller nodes.

== Host software

The following software must be installed:

* ESXi is installed on the Cisco UCS blades.
* vCenter is installed and configured, with all the hosts registered in vCenter.
* VSC is installed and registered in vCenter.
* A NetApp cluster is configured.

link:ehr-epic-deploy_cisco_ucs_blade_server_and_switch_configuration.html[Next: Cisco UCS Blade Server and Switch Configuration]
