---
sidebar: sidebar
permalink: ehr-epic-deploy/ehr-epic-deploy_genio_tool.html
keywords: genio, tool, storage, performance, epic, intersystems, cache, command, line, application
summary: GenIO is the storage-performance testing tool used by Epic. It simulates the workload generated by an InterSystems Caché database used in an Epic production environment, including the write-cycle patterns. It is available as a command- line application on various host operating systems on which Caché is deployed. Always test with the latest copy of the GenIO tool from Epic.
---

= GenIO tool
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-07 11:34:58.313660
//


GenIO is the storage-performance testing tool used by Epic. It simulates the workload generated by an InterSystems Caché database used in an Epic production environment, including the write-cycle patterns. It is available as a command- line application on various host operating systems on which Caché is deployed. Always test with the latest copy of the GenIO tool from Epic.

A performance test run involves executing the GenIO application on the production Epic database host with a set of I/O parameters. These parameters simulate the I/O patterns for the customer's Epic environment, including the write cycles.

Epic pushes the controller past the 100% full load detailed in the hardware configuration guide to determine how much headroom is on the controller. Epic also runs a full load test and simulates backup operations.

Epic server support representatives use it to verify storage performance from the host perspective. NetApp has also used GenIO to validate the performance of NetApp storage systems in the lab.
