---
sidebar: sidebar
permalink: citrix_netapp_value.html
keywords: Data fabric, Cloud Volumes ONTAP, Azure NetApp Files, ShareFile, filecache
summary: TR-4852
---

= NetApp Value
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 0.9 (July 10, 2020)
//
// 2020-07-31 10:32:38.959322
//

[.lead]

=== Data Fabric

Infrastructure built with the data fabric powered by NetApp allows you to migrate data or perform disaster recovery from one site to another (including the cloud). The data in Citrix Virtual Apps and Desktops can be categorized as follows:

* Infrastructure components

* Machine images

* Applications

* User profiles

* User data

Based on your needs, sites can be configured as active/active or active/passive. Infrastructure components can be on-premises or in the cloud and accessed as a service. VM templates must be distributed to each site to provision desktop and application pools. Application layers, user profiles, and data are stored in SMB file shares that must be available on each site.

You can create a global namespace using Azure NetApp Files, NetApp Cloud Volumes ONTAP, and FlexGroup volumes at the location where most of your users reside. Other locations can use Global FileCache to cache the content locally on a file server. If Citrix ShareFile is preferred, NetApp StorageGRID provides high-performance, S3-compatible storage to host data on-premises with NAS gateway access.

=== Cloud Insights

Cloud Insights allows you to monitor, optimize, and troubleshoot resources deployed in the public cloud as well as on private datacenters.

Cloud Insights helps you in the following ways:

* *Reduce the mean time to resolution by as much as 90%.* Stop lengthy log hunting and failing to manually correlate infrastructure; use our dynamic topology and correlation analysis to pinpoint the problem area immediately.

* *Reduce cloud infrastructure costs by an average of 33%.* Remove inefficiencies by identifying abandoned and unused resources and right-size workloads to optimized performance and cost tiers.

* *Prevent as much as 80% of cloud issues from affecting end users.* Stop searching through vast amounts of data to find the relevant item by using advanced analytics and machine learning to identify issues before they become critical outages.
