---
sidebar: sidebar
permalink: vdi-vds/hcvdivds_why_ontap.html
keywords: VDS, Virtual Desktop Service, ONTAP, FlexGroup
summary: ONTAP features for Virtual Desktop Service.
---

= ONTAP features for Virtual Desktop Service
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/
:author: Suresh Thoppay, TME - Hybrid Cloud Solutions
//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-24 13:21:46.280864
//

[.lead]
The following features of ONTAP makes it attractive to use it along with Virtual Desktop Service.

. *Scale-out Filesystem*
ONTAP FlexGroup volumes can grow up to 20+PB and can contain 
400+ billion files with single namespace. The cluster can contain up to 24 storage nodes each having flexibility to customize the number of network interface cards based on the model used.
+
Users virtual desktops, home folders, user profile containers, shared data, etc. can grow based on demand and not to worry about filesystem limitations.

. *File System Analytics*
To gain insights of shared data, XCP tool can be utilized. With ONTAP 9.8+ and ActiveIQ Unified Manager,file metadata information can be queried and retrieve it easily. It can also be used to identify the cold data.

. *Cloud Tiering*
The cold data can be migrated to an object store in cloud or to any S3 compatible storage in datacenter.

. *File Versions*
Users can recover files by themselves which is protected by ONTAP snapshots. ONTAP snapshots are very space efficient and it occupies only the changed blocks.

. *Global Namespace*
ONTAP Flexcache allows remote caching of file storage making it easier to manage shared data across locations where ONTAP storage systems are available. 

. *Secure Multi-tenancy support*
Single Physical Storage Cluster can be presented as multiple virtual storage arrays each with its own volumes, storage protocols, logical network interfaces, identity and authentication domain,management users, etc. It will enables to share the storage array for multiple business units or different environments like test, development and production.
+
To guarantee performance, Adaptive QoS can be utilized to set the performance levels based on used space or allocated space.
Storage capacity can be controlled using Quotas.

. *VMware Integration*
ONTAP tools for VMware vSphere provides a vCenter Plugin to provision datastores, implement vSphere host best practices, monitor ONTAP resources. 
+
ONTAP supports vStorage APIs for Array Integration (VAAI) for offloading SCSI/file operations to storage array. Supports vStorage APIs for Storage Awareness (VASA) and Virtual Volumes support for both Block and File protocols.
+
Snapcenter Plug-in for VMware vSphere provides an easy way to backup and restore virtual machines using snapshot feature on storage array.
+
ActiveIQ Unified Manager provides end to end storage network visibility in vSphere environment. Administrators can easily identify latency issue if it occurs on virtual desktop environments hosted on ONTAP.

. *Security Compliance*
Using ActiveIQ Unified Manager, multiple ONTAP systems can be monitored and it alerts for any policy violations.

. *Multi-Protocol Support*
ONTAP supports block (iSCSI,FC,FCoE,NVMe/FC), File (NFSv3,NFSv4.1,SMB2.x,SMB3.x) and object (S3) storage protocols.

. *Automation Support*
ONTAP provides RESTapi, Ansible, PowerShell module to automate tasks which can be utilized with VDS Management Portal.

link:hcvdivds_data_management.html[Next: Data Management]
