---
sidebar: sidebar
permalink: vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html
keywords: TR-4861, VDS, Windows Virtual Desktop, Remote Desktop Services, Virtual Desktop Services,
summary: The NetApp Virtual Desktop Service (VDS) orchestrates Remote Desktop Services (RDS) in major public clouds as well as on private clouds. VDS supports Windows Virtual Desktop (WVD) on Microsoft Azure. VDS automates many tasks that must be performed after deployment of WVD or RDS, including setting up SMB file shares (for user profiles, shared data, and the user home drive), enabling Windows features, application and agent installation, firewall, and policies, and so on.
---

= TR-4861: Hybrid Cloud VDI with Virtual Desktop Service
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-24 13:21:45.954094
//

Suresh Thoppay, NetApp

[.lead]
The NetApp Virtual Desktop Service (VDS) orchestrates Remote Desktop Services (RDS) in major public clouds as well as on private clouds. VDS supports Windows Virtual Desktop (WVD) on Microsoft Azure. VDS automates many tasks that must be performed after deployment of WVD or RDS, including setting up SMB file shares (for user profiles, shared data, and the user home drive), enabling Windows features, application and agent installation, firewall, and policies, and so on.

Users consume VDS for dedicated desktops, shared desktops, and remote applications. VDS provides scripted events for automating application management for desktops and reduces the number of images to manage.

VDS provides a single management portal for handling deployments across public and private cloud environments.

== Customer Value

The remote workforce explosion of 2020 has changed requirements for business continuity. IT departments are faced with new challenges to rapidly provision virtual desktops and thus require provisioning agility, remote management, and the TCO advantages of a hybrid cloud that makes it easy to provision on-premises and cloud resources. They need a hybrid-cloud solution that:

* Addresses the post-COVID workspace reality to enable flexible work models with global dynamics
* Enables shift work by simplifying and accelerating the deployment of work environments for all employees, from task workers to power users
* Mobilizes your workforce by providing rich, secure VDI resources regardless of the physical location
* Simplifies hybrid-cloud deployment
* Automates and simplifies risk reduction management

link:hcvdivds_use_cases.html[Next: Use Cases]
