---
sidebar: sidebar
permalink: vdi-vds/hcvdivds_solutions_for_industry.html
keywords: GPU, Azure, NVIDIA, Tesla M60,
summary: Graphics workstations are typically used in industries such as manufacturing, healthcare, energy, media and entertainment, education, architecture, and so on. Mobility is often limited for graphics-intensive applications.
---

= Solutions for Industry
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Graphics workstations are typically used in industries such as manufacturing, healthcare, energy, media and entertainment, education, architecture, and so on. Mobility is often limited for graphics-intensive applications.

To address the issue of mobility, Virtual Desktop Services provide a desktop environment for all types of workers, from task workers to expert users, using hardware resources in the cloud or with NetApp HCI, including options for flexible GPU configurations. VDS enables users to access their work environment from anywhere with laptops, tablets, and other mobile devices.

To run manufacturing workloads with software like ANSYS Fluent, ANSYS Mechanical, Autodesk AutoCAD, Autodesk Inventor, Autodesk 3ds Max, Dassault Systèmes SOLIDWORKS, Dassault Systèmes CATIA, PTC Creo, Siemens PLM NX, and so on, the GPUs available on various clouds (as of Jan 2021) are listed in the following table.

[cols=5,options="header",cols="20,20,20,20,20"]
|===
| GPU Model
| Microsoft Azure
| Google Compute (GCP)
| Amazon Web Services (AWS)
| On-Premises (NetApp HCI)
| NVIDIA M60 | Yes | Yes | Yes | No
| NVIDIA T4 | No | Yes | Yes | Yes
| NVIDIA P100 | No | Yes | No | No
| NVIDIA P4 | No | Yes | No | No
|===

Shared desktop sessions with other users and dedicated personal desktops are also available. Virtual desktops can have one to four GPUs or can utilize partial GPUs with NetApp HCI. The NVIDIA T4 is a versatile GPU card that can address the demands of a wide spectrum of user workloads.
Each GPU card on NetApp HCI H615C has 16GB of frame buffer memory and three cards per server. The number of users that can be hosted on single H615C server depends on the user workload.

[cols=4,options="header",cols="25,25,25,25"]
|===
| Users/Server
| Light (4GB)
| Medium (8GB)
| Heavy (16GB)
| H615C | 12 | 6 | 3
|===

To determine the user type, run the GPU profiler tool while users are working with applications performing typical tasks. The GPU profiler captures memory demands, the number of displays, and the resolution that users require. You can then pick the vGPU profile that satisfies your requirements.

Virtual desktops with GPUs can support a display resolution of up to 8K, and the utility nView can split a single monitor into regions to work with different datasets.

With ONTAP file storage, you can realize the following benefits:

* A single namespace that can grow up to 20PB of storage with 400 billion of files, without much administrative input
* A namespace that can span the globe with a Global File Cache
* Secure multitenancy with managed NetApp storage
* The migration of cold data to object stores using NetApp FabricPool
* Quick file statistics with file system analytics
* Scaling a storage cluster up to 24 nodes increasing capacity and performance
* The ability to control storage space using quotas and guaranteed performance with QoS limits
* Securing  data with encryption
* Meeting broad requirements for data protection and compliance
* Delivering flexible business continuity options

link:vdi-vds/hcvdivds_conclusion.html[Next: Conclusion]
