---
sidebar: sidebar
permalink: vdi-vds/hcvdivds_nvidia_licensing.html
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC
summary: When using an H610C or H615C, the license for the GPU must be procured from NVIDIA partners that are authorized to resell the licenses.
---

= NVIDIA Licensing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-24 13:21:46.086177
//

[.lead]
When using an H610C or H615C, the license for the GPU must be procured from NVIDIA partners that are authorized to resell the licenses. You can find NVIDIA partners with the https://www.nvidia.com/object/partner-locator.html[partner locator^]. Search for competencies such as virtual GPU (vGPU) or Tesla.

NVIDIA vGPU software is available in four editions:

* NVIDIA GRID Virtual PC (GRID vPC)
* NVIDIA GRID Virtual Applications (GRID vApps)
* NVIDIA Quadro Virtual Data Center Workstation (Quadro vDWS)
* NVIDIA Virtual ComputeServer (vComputeServer)

== GRID Virtual PC

This product is ideal for users who want a virtual desktop that provides a great user experience for Microsoft Windows applications, browsers, high-definition video, and multi-monitor support. The NVIDIA GRID Virtual PC delivers a native experience in a virtual environment, allowing you to run all your PC applications at full performance.

== GRID Virtual Applications

GRID vApps are for organizations deploying a Remote Desktop Session Host (RDSH) or other app-streaming or session-based solutions. Designed to deliver Microsoft Windows applications at full performance, Windows Server-hosted RDSH desktops are also supported by GRID vApps.

== Quadro Virtual Data Center Workstation

This edition is ideal for mainstream and high-end designers who use powerful 3D content creation applications like Dassault CATIA, SOLIDWORKS, 3Dexcite, Siemens NX, PTC Creo, Schlumberger Petrel, or Autodesk Maya. NVIDIA Quadro vDWS allows users to access their professional graphics applications with full features and performance anywhere on any device.


== NVIDIA Virtual ComputeServer

Many organizations run compute-intensive server workloads such as artificial intelligence (AI), deep learning (DL), and data science. For these use cases, NVIDIA vComputeServer software virtualizes the NVIDIA GPU, which accelerates compute-intensive server workloads with features such as error correction code, page retirement, peer-to-peer over NVLink, and multi-vGPU.

[NOTE]
A Quadro vDWS license enables you to use GRID vPC and NVIDIA vComputeServer.

link:hcvdivds_deployment.html[Next: Deployment]
