---
sidebar: sidebar
permalink: vdi-vds/hcvdivds_use_cases.html
keywords: Use cases, target audience
summary: Hybrid VDI with NetApp VDS allows service providers and enterprise virtual desktop administrators to easily expand resources to other cloud environment without affecting their users. Having on-premises resources on NetApp HCI provides better control of GPU resources and allows you to expand compute or storage nodes based on demand.
---

= Use Cases
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-24 13:21:45.974970
//

[.lead]
Hybrid VDI with NetApp VDS allows service providers and enterprise virtual desktop administrators to easily expand resources to other cloud environment without affecting their users. Having on-premises resources provides better control of resources and offers wide selection of choices (compute, GPU, storage, and network) to meet demand.

This solution applies to the following use cases:

* Bursting into the cloud for surges in demand for remote desktops and applications
* Reducing TCO for long running remote desktops and applications by hosting them on-premises with flash storage and GPU resources
* Ease of management of remote desktops and applications across cloud environments
* Experience remote desktops and applications by using a software-as-a- service model with on-premises resources

== Target Audience

The target audience for the solution includes the following groups:

* EUC/VDI architects who wants to understand the requirements for a hybrid VDS
* NetApp partners who would like to assist customers with their remote desktop and application needs
* Existing NetApp HCI customers who want to address remote desktop and application demands

link:hcvdivds_netapp_virtual_desktop_service_overview.html[Next: NetApp Virtual Desktop Service Overview]
