---
sidebar: sidebar
permalink: vdi-vds/vdi-index.html
keywords: vdi, vds, virtual desktop, end use computing,
summary: Task workers can quickly launch an application from the list of applications made available to them. App services publish applications from the Remote Desktop Services session hosts. With WVD, App Groups provide similar functionality from multi-session Windows 10 host pools.
---

= End User Computing (EUC) / Virtual Desktop Infrastructure (VDI) Solutions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
Whether you are deploying virtual desktops on-premises or in the cloud, NetApp has a variety of EUC/VDI solutions to address your needs.

== NetApp Virtual Desktop Services (VDS)

The NetApp Virtual Desktop Service (VDS) orchestrates Remote Desktop Services (RDS) in major public clouds as well as on private clouds.

Available solutions for VDS:

* link:vdi-vds/hcvdivds_hybrid_cloud_vdi_with_virtual_desktop_service.html[Hybrid Cloud VDI with NetApp Virtual Desktop Service]

== End User Computing with VMware Horizon

NetApp has verified architectures for VMware Horizon spanning several compute environments.  The available solutions include:

* link:https://www.netapp.com/us/media/nva-1132-design.pdf[End User Computing with VMware (Design Guide)]
* link:https://www.netapp.com/us/media/nva-1129-design.pdf[End User Computing with VMware and NVIDIA GPUs (Design Guide)]
* link:https://www.netapp.com/us/media/nva-1129-deploy.pdf[End User Computing with VMware and NVIDIA GPUs (Deployment Guide)]
* link:https://www.netapp.com/us/media/tr-4792.pdf[End User Computing with VMware for 3D Graphics]
