---
sidebar: sidebar
permalink: virtualization/netapp-aria.html
keywords: netapp, vmware, aria, getting, started
summary:
---

= NetApp & VMware Aria
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
VMware Aria is an intelligent multi-cloud management solution, consisting of a suite of products that enable you to consistently deploy and operate your apps, infrastructure, and platform services. 

VMware Aria enables you to gain control of your environment across private, hybrid, and multiple clouds from a single platform and with a common data model. The editor of the Aria Automation Orchestrator Client allows for the creation of simple to complex service offerings by using the library of predefined and administrator-configured workflows. By combining predefined storage tasks within this library with NetApp’s REST-based APIs, a variety of service offerings can be created. It is when these service offerings are published in a self-service catalog, within Aria Automation, that any business or IT objective can be accomplished. 

In addition to the operations related tasks that can be achieved, Aria helps administrators with real-time visibility into their infrastructure. The VMware Aria Management Pack for NetApp FAS/AFF is an embedded adapter for VMware Aria Operations. This integration provides analytics and up to the minute information about the infrastructure, helping you identify problems as they arise or potentially sooner. 

* link:https://www.vmware.com/products/aria.html[VMware Aria Product Page]
* link:https://docs.vmware.com/en/VMware-Aria-Operations-for-Integrations/4.2/Management-Pack-for-NetApp-FAS-AFF/GUID-9B9C2353-3975-403A-8803-EBF6CDB62D2C.html[VMware Aria Operations Management Pack for NetApp FAS/AFF]
