---
sidebar: sidebar
permalink: virtualization/vmware_vcf_aff_intro.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, san, array, ontap tools, otv
summary:
---

== VMware Cloud Foundation with NetApp All-Flash SAN Array
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
VMware Cloud Foundation (VCF) is a set of technologies that provides a straightforward path to accessing a hybrid cloud experience. Within the VCF solution, support is provided for both native Kubernetes and virtual machine based workloads. Essential services like VMware vSphere, VMware vSAN, VMware NSX-T Data Center, and VMware vRealize Cloud Management are integral components of the VCF package. When combined, these services establish a software-defined infrastructure capable of managing compute, storage, networking, security, and cloud management. This collective infrastructure provides a hybrid experience, wherein the VCF framework extends the environment from onsite data center to Amazon Web Services (AWS), Azure, and Google Cloud.

=== Documentation resources

For detailed information on NetApp offerings for VMware Cloud Foundation, refer to the following four (4) part blog series:

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-getting-started/[NetApp and VMware Cloud Foundation made easy Part 1: Getting started]

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-ontap-principal-storage/[NetApp and VMware Cloud Foundation made easy Part 2: VCF and ONTAP principal storage]

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-element-principal-storage/[NetApp and VMware Cloud Foundation made easy Part 3: VCF and Element principal storage]

* link:https://www.netapp.com/blog/netapp-vmware-cloud-foundation-supplemental-storage/[NetApp and VMware Cloud Foundation made easy - Part 4: ONTAP Tools for VMware and supplemental storage]

*NetApp FlexPod solutions for VMware Cloud Foundation*

* link:https://www.netapp.com/blog/expanding-flexpod-hybrid-cloud-with-vmware-cloud-foundation/[Expanding FlexPod hybrid cloud with VMware Cloud Foundation]

* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf.html[FlexPod as a Workload Domain for VMware Cloud Foundation]

* link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_vcf_design.html[FlexPod as a Workload Domain for VMware Cloud Foundation Design Guide]