---
sidebar: sidebar
permalink: virtualization/vmware-glossary.html
keywords: netapp, vmware, product, glossary
summary:
---

= VMware & NetApp: A powerful solution alliance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
The NetApp and VMware partnership is the only partnership where a single storage system addresses all of the key VMware defined use cases.

*What is VMware vSphere?*

vSphere is the product name VMware's suite of server virtualization products that includes its ESXi hypervisor and vCenter management software.  link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/What-s-new-with-ONTAP-tools-for-VMware-vSphere-9-12/ba-p/443759[See why] you should upgrade to vSphere 8 with NetApp ONTAP Tools.  link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html[Get] all the documentation on vSphere on NetApp. 

*How do VMware datastores work?*

Need help on this one – link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_best_practices.html#vsphere-datastore-and-protocol-features[Any protocol with NetApp]

*What is VMware Cloud Foundation?*

VMware Cloud Foundation (VCF) is a hybrid cloud platform for both traditional enterprise and modern applications. Built on VMware’s software-defined stack for compute, storage, network, container, and cloud management.  link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/vmware_cloud_foundation_mode_deployment.html[See how] NetApp infrastructure works with VCF. 

*What is VMware Tanzu?*

vSphere with Tanzu is the new generation of vSphere for containerized applications. This single, streamlined solution bridges the gap between IT operations and developers with a new kind of infrastructure for modern, cloud-native applications both on premises and in public clouds.  Looking to manage K8’s with Tanzu on NetApp?  Get all the info link:https://www.netapp.com/hybrid-cloud/vmware/what-is-vmware-tanzu/[here]. 

*What is VMware virtual volumes (vVols)?*

vVols use storage policy-based management (SPBM) to eliminate storage provisioning and use descriptive policies at the VM or VMDK level that can be applied or changed in minutes. SPBM accelerates storage operations and reduces the need for specialized skills for storage infrastructure.  link:https://www.netapp.tv/details/29476[Hear] what VMware vVols can do on NetApp.  Get technical documentation link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vvols-overview.html[here]. 

*Why is NVMe over TCP important to VMs?*

For VM’s running on NVMe over TCP, you can reduce CPU utilization and gain performance and reliability with NVMe coupled with Virtual Volumes on NetApp for scalability, simplicity, and automation.  link:https://www.netapp.com/data-storage/nvme/what-is-nvme/?internal_promo=comp_pure_ww_ontap_awareness-coas_blog[See] the benefits of NVMe. 

*What is hybrid multicloud with VMware & NetApp?*

No other infrastructure provider can support workloads on VMware both on-premises and in the cloud, any cloud.  NetApp is the first infrastructure provider to support VMware in the cloud on AWS, MS Azure and Google Cloud. 
