---
sidebar: sidebar
permalink: virtualization/vmware-scv-overview.html
keywords: netapp, vmware, getting, started
summary:
---

== SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
The SnapCenter Plug-in for VMware vSphere offers rapid, efficient, and VM-consistent backup and restore operations for virtual machines (VMs), Datastores, and VMDKs. It works together with SnapCenter Server, enabling application-based backup and restore functionality for SnapCenter application-specific plug-ins.

=== Documentation resources

Refer to the following documentation resources for detailed information.

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/[SnapCenter Plug-in for VMware vSphere documentation]


=== Solution resources

Refer to the following 3-2-1 backup solution featuring SnapCenter Plug-in for VMware vSphere and BlueXP backup and recovery for VMs.

NetApp Solutions Engineering: https://docs.netapp.com/us-en/netapp-solutions/ehc/bxp/bxp-scv-hybrid-solution.html[3-2-1 Data Protection for VMware with SnapCenter Plug-in and BlueXP backup and recovery for VMs]

Tech ONTAP Blog: https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180[3-2-1 Data Protection for VMware with SnapCenter Plug-in and BlueXP backup and recovery for VMs]

=== Video resources

[width=100%,cols="5a, 5a, 5a",frame="none",grid="rows"]
|===
.>| SnapCenter Plug-in for VMware vSphere - Solution Pre-Requisites
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=38881de9-9ab5-4a8e-a17d-b01200fade6a&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| SnapCenter Plug-in for VMware vSphere - Deployment
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=10cbcf2c-9964-41aa-ad7f-b01200faca01&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| SnapCenter Plug-in for VMware vSphere - Backup Workflow
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=b7272f18-c424-4cc3-bc0d-b01200faaf25&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| SnapCenter Plug-in for VMware vSphere - Restore Workflow
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=ed41002e-585c-445d-a60c-b01200fb1188&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

.>| SnapCenter - SQL Restore Workflow
[pass]
<iframe src="https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=8df4ad1f-83ad-448b-9405-b01200fb2567&autoplay=false&offerviewer=false&showtitle=false&showbrand=false&captions=false&interactivity=all" height="203" width="360" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>
|