---
sidebar: sidebar
permalink: virtualization/vsphere_demos_videos.html
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP
summary: This page provides and introduction to videos and tutorials.
---

= Hybrid Cloud, Virtualization and Containers Videos and Demos
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with Atom 1.57.0 (June 18, 2021)
//
//

See the following videos and demos highlighting specific features of the hybrid cloud, virtualization, and container solutions.

.NetApp ONTAP Tools for VMware vSphere
[%collapsible]
=====

.ONTAP Tools for VMware - Overview
[%collapsible]
=====
video::otv_overview.mp4[]
=====

.VMware iSCSI Datastore Provisioning with ONTAP
[%collapsible]
=====
video::otv_iscsi_provision.mp4[]
=====

.VMware NFS Datastore Provisioning with ONTAP
[%collapsible]
=====
video::otv_nfs_provision.mp4[]
=====

.VMware Cloud on AWS with AWS FSx for NetApp ONTAP
[%collapsible]
=====

.Windows Guest Connected Storage with FSx ONTAP using iSCSI
[%collapsible]
=====
video::vmc_windows_vm_iscsi.mp4[]
=====

.Linux Guest Connected Storage with FSx ONTAP using NFS
[%collapsible]
=====
video::vmc_linux_vm_nfs.mp4[]
=====

=====

.SnapCenter Plug-in for VMware vSphere
[%collapsible]
=====

NetApp SnapCenter software is an easy-to-use enterprise platform to securely coordinate and manage data protection across applications, databases, and file systems.

The SnapCenter Plug-in for VMware vSphere allows you to perform backup, restore, and attach operations for VMs and backup and mount operations for datastores that are registered with SnapCenter directly within VMware vCenter.

For more information about NetApp SnapCenter Plug-in for VMware vSphere, see the link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html[NetApp SnapCenter Plug-in for VMware vSphere Overview].

.SnapCenter Plug-in for VMware vSphere - Solution Pre-Requisites
[%collapsible]
=====
video::scv_prereq_overview.mp4[]
=====

.SnapCenter Plug-in for VMware vSphere - Deployment
[%collapsible]
=====
video::scv_deployment.mp4[]
=====

.SnapCenter Plug-in for VMware vSphere - Backup Workflow
[%collapsible]
=====
video::scv_backup_workflow.mp4[]
=====

.SnapCenter Plug-in for VMware vSphere - Restore Workflow
[%collapsible]
=====
video::scv_restore_workflow.mp4[]
=====

.SnapCenter - SQL Restore Workflow
[%collapsible]
=====
video::scv_sql_restore.mp4[]
=====

.NetApp with VMware Tanzu
[%collapsible]
=====

VMware Tanzu enables customers to deploy, administer, and manage their Kubernetes environment through vSphere or the VMware Cloud Foundation. This portfolio of products from VMware allows customer to manage all their relevant Kubernetes clusters from a single control plane by choosing the VMware Tanzu edition that best suits their needs.

For more information about VMware Tanzu, see the https://tanzu.vmware.com/tanzu[VMware Tanzu Overview^]. This review covers use cases, available additions, and more about VMware Tanzu.

* https://www.youtube.com/watch?v=ZtbXeOJKhrc[How to use vVols with NetApp and VMware Tanzu Basic, part 1^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE[How to use vVols with NetApp and VMware Tanzu Basic, part 2^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU[How to use vVols with NetApp and VMware Tanzu Basic, part 3^]

=====
// == NetApp with VMware Cloud Foundation

// VMware Cloud Foundation allows customer to build software defined infrastructure as a standardized stack of compute, storage, networking, and management whether in the datacenter or in the public cloud. As deployments grow beyond the initial management domain, customers can choose to deploy the principal or supplemental storage that best meets their needs for their various workload domains and modern applications.
//
// NOTE: *For more information regarding VMware Cloud Foundation please consult the following:*
//
// * The https://www.vmware.com/products/cloud-foundation.html[VMware Cloud Foundation Overview^]. Review the product details, deployment options and learn more about VMware Cloud Foundation.
//
// == NetApp with VMware Cloud Foundation Videos
//
// * NetApp and VMware Cloud Foundations Basics
// * NetApp ONTAP and VCF VI Workload Domain Creation with vVols and NFS
// * NetApp ONTAP and VCF VI Workload Domain Creation with FlexGroup and NFS
// * NetApp Element and VCF VI Workload Domain with vVols and iSCSI
//
.NetApp with Red Hat OpenShift
[%collapsible]
=====

Red Hat OpenShift, an enterprise Kubernetes platform, enables you to run container-based applications with an open hybrid-cloud strategy. Available as a cloud service on leading public clouds or as self-managed software, Red Hat OpenShift provides customers with the flexibility they need when designing their container-based solution.

For more information regarding Red Hat OpenShift, see this https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift Overview^]. You can also review the product documentation and deployment options to learn more about Red Hat OpenShift.

<<<<<<< HEAD

=====

.NetApp with Red Hat OpenShift videos
[%collapsible]
=====

=======
>>>>>>> eb7c32e7f4f8817ecccaefb7129770468497e832
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html[Workload Migration - Red Hat OpenShift with NetApp^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html[Red Hat OpenShift Deployment on RHV: Red Hat OpenShift with NetApp^]

=====