---
sidebar: sidebar
permalink: virtualization/vsphere_ontap_auto_block_iscsi.html
keywords: vSphere, datastore, VMFS, iSCSI, ONTAP tools, vlan, network interface, service policy
summary: This page provides steps to deploy a NetApp ONTAP storage iSCSI VMFS datastore in a VMware vSphere environment.
---


= vSphere VMFS Datastore - iSCSI Storage backend with ONTAP

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/
:scriptsdir: ./../scripts/
:author: Suresh Thoppay, TME - Hybrid Cloud Solutions
:ontap_version: ONTAP 9.8 or later
:vsphere_version: vSphere 7.0 or later

[.lead]
== About this task

This section covers the creation of a VMFS datastore with ONTAP iSCSI storage.

For automated provisioning, use one of these scripts: <<PowerShell>>, <<Ansible>>, or <<Terraform>>.


== What you need

* The basic skills necessary to manage a vSphere environment and ONTAP.

* An ONTAP storage system (FAS/AFF/CVO/ONTAP Select/ASA) running {ontap_version}

* ONTAP credentials (SVM name, userID, and password)

* ONTAP network port, SVM, and LUN information for iSCSI

* link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-429C4DDD-5EC0-4DBD-8EA8-76082AB7ADEC.html++[A completed iSCSI configuration worksheet]

* vCenter Server credentials

* vSphere host(s) information

** {vsphere_version}

* iSCSI VMKernel adapter IP informattion

* Network switch(es)

** With ONTAP system network data ports and connected vSphere hosts

** VLAN(s) configured for iSCSI

** (Optional) link aggregation configured for ONTAP network data ports

* ONTAP Tool for VMware vSphere deployed, configured, and ready to consume

== Steps

. Check compatibility with the https://mysupport.netapp.com/matrix[Interoperability Matrix Tool (IMT)].

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-7D444A0D-02CE-4A21-8017-CB1DC99EFD9A.html++[Verify that the iSCSI configuration is supported.]

. Complete the following ONTAP and vSphere tasks.

== ONTAP tasks

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-980/system__license__show.html++[Verify the ONTAP license for iSCSI].

.. Use the `system license show` command to check if iSCSI is listed.

.. Use `license add -license-code <license code>` to add the license.

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/GUID-ED75D939-C45A-4546-8B22-6B765FF6083F.html++[Verify that the iSCSI protocol is enabled on the SVM.]

. Verify that iSCSI network logical interfaces are available on the SVM.
+
NOTE: When an SVM is created using the GUI, iSCSI network interfaces are also created.

. Use the `Network interface` command to view or make changes to the network interface.
+
TIP: Two iSCSI network interfaces per node are recommended.

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-CEE760DF-A059-4018-BE6C-6B3A034CB377.html++[Create an iSCSI network interface.] You can use the default-data-blocks service policy.

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-BBC2D94B-DD3A-4029-9FCE-F71F9C157B53.html++[Verify that the data-iscsi service is included in the service policy.] You can use `network interface service-policy show` to verify.

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DE59CF49-3A5F-4F38-9F17-E2C16B567DC0.html++[Verify that jumbo frames are enabled.]

. link:++https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-D4DAC7DB-A6B0-4696-B972-7327EE99FD72.html++[Create and map the LUN.] Skip this step if you are using ONTAP tools for VMware vSphere. Repeat this step for each LUN.

== VMware vSphere tasks

. Verify that at least one NIC is available for the iSCSI VLAN. Two NICs are preferred for better performance and fault tolerance.

. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.networking.doc/GUID-B2AA3EEE-2334-45FE-9A0F-1172FDDCC6A8.html++[Identify the number of physical NICs available on the vSphere host.]

. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-C476065E-C02F-47FA-A5F7-3B3F2FD40EA8.html++[Configure the iSCSI initiator.] A typical use case is a software iSCSI initiator.

. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.networking.doc/GUID-660423B1-3D35-4F85-ADE5-FE1D6BF015CF.html++[Verify that the TCPIP stack for iSCSI is available].

. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-0D31125F-DC9D-475B-BC3D-A3E131251642.html++[Verify that iSCSI portgroups are available].
** We typically use a single virtual switch with multiple uplink ports.
** Use 1:1 adapter mapping.

. Verify that iSCSI VMKernel adapters are enabled to match the number of NICs and that IPs are assigned.

. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-D9B862DF-476A-4BCB-8CA5-DE6DB2A1A981.html++[Bind the iSCSI software adapter to the iSCSI VMKernel adapter(s).]

. link:++https://docs.netapp.com/vapp-98/topic/com.netapp.doc.vsc-iag/GUID-D7CAD8AF-E722-40C2-A4CB-5B4089A14B00.html++[Provision the VMFS datastore with ONTAP Tools]. Repeat this step for all datastores.

. link:++https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-0520FD37-D7AD-4FBA-9A2E-E5F8211FCBBB.html++[Verify hardware acceleration support.]

== What's next?

After these the tasks are completed, the VMFS datastore is ready to consume for provisioning virtual machines.

.Ansible Playbook
[[Ansible]]
[source]
----
## Disclaimer: Sample script for reference purpose only.

- hosts: '{{ vsphere_host }}'
  name: Play for vSphere iSCSI Configuration
  connection: local
  gather_facts: false
  tasks:
    # Generate Session ID for vCenter
    - name: Generate a Session ID for vCenter
      uri:
        url: "https://{{ vcenter_hostname }}/rest/com/vmware/cis/session"
        validate_certs: false
        method: POST
        user: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
        force_basic_auth: yes
        return_content: yes
      register: vclogin

    # Generate Session ID for ONTAP tools with vCenter
    - name: Generate a Session ID for ONTAP tools with vCenter
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/security/user/login"
        validate_certs: false
        method: POST
        return_content: yes
        body_format: json
        body:
          vcenterUserName: "{{ vcenter_username }}"
          vcenterPassword: "{{ vcenter_password }}"
      register: login

    # Get existing registered ONTAP Cluster info with ONTAP tools
    - name: Get ONTAP Cluster info from ONTAP tools
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/storage/clusters"
        validate_certs: false
        method: Get
        return_content: yes
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
      register: clusterinfo

    - name: Get ONTAP Cluster ID
      set_fact:
        ontap_cluster_id: "{{ clusterinfo.json | json_query(clusteridquery) }}"
      vars:
        clusteridquery: "records[?ipAddress == '{{ netapp_hostname }}' && type=='Cluster'].id | [0]"

    - name: Get ONTAP SVM ID
      set_fact:
        ontap_svm_id: "{{ clusterinfo.json | json_query(svmidquery) }}"
      vars:
        svmidquery: "records[?ipAddress == '{{ netapp_hostname }}' && type=='SVM' && name == '{{ svm_name }}'].id | [0]"

    - name: Get Aggregate detail
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/storage/clusters/{{ ontap_svm_id }}/aggregates"
        validate_certs: false
        method: GET
        return_content: yes
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
          cluster-id: "{{ ontap_svm_id }}"
      when: ontap_svm_id != ''
      register: aggrinfo

    - name: Select Aggregate with max free capacity
      set_fact:
        aggr_name: "{{ aggrinfo.json | json_query(aggrquery) }}"
      vars:
        aggrquery: "max_by(records, &freeCapacity).name"

    - name: Convert datastore size in MB
      set_fact:
        datastoreSizeInMB: "{{ iscsi_datastore_size | human_to_bytes/1024/1024 | int }}"

    - name: Get vSphere Cluster Info
      uri:
        url: "https://{{ vcenter_hostname }}/api/vcenter/cluster?names={{ vsphere_cluster }}"
        validate_certs: false
        method: GET
        return_content: yes
        body_format: json
        headers:
          vmware-api-session-id: "{{ vclogin.json.value }}"
      when: vsphere_cluster != ''
      register: vcenterclusterid

    - name: Create iSCSI VMFS-6 Datastore with ONTAP tools
      uri:
        url: "https://{{ ontap_tools_ip }}:8143/api/rest/3.0/admin/datastore"
        validate_certs: false
        method: POST
        return_content: yes
        status_code: [200]
        body_format: json
        body:
          traditionalDatastoreRequest:
            name: "{{ iscsi_datastore_name }}"
            datastoreType: VMFS
            protocol: ISCSI
            spaceReserve: Thin
            clusterID:  "{{ ontap_cluster_id }}"
            svmID: "{{ ontap_svm_id }}"
            targetMoref: ClusterComputeResource:{{ vcenterclusterid.json[0].cluster }}
            datastoreSizeInMB: "{{ datastoreSizeInMB | int }}"
            vmfsFileSystem: VMFS6
            aggrName: "{{ aggr_name }}"
            existingFlexVolName: ""
            volumeStyle: FLEXVOL
            datastoreClusterMoref: ""
        headers:
          vmware-api-session-id: "{{ login.json.vmwareApiSessionId }}"
      when: ontap_cluster_id != '' and ontap_svm_id != '' and aggr_name != ''
      register: result
      changed_when: result.status == 200
----
