---
sidebar: sidebar
permalink: virtualization/vsphere_demos_videos.html
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP
summary: This page provides and introduction to videos and tutorials.
---

= Hybrid cloud, desktop virtualization and containers videos and demos
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with Atom 1.57.0 (June 18, 2021)
//
//

See the following videos and demos highlighting specific features of the hybrid cloud, desktop virtualization, and container solutions.

== NetApp SnapCenter

NetApp SnapCenter software is an easy-to-use enterprise platform to securely coordinate and manage data protection across applications, databases, and file systems.

SnapCenter simplifies backup, restore, and clone lifecycle management by offloading these tasks to application owners without sacrificing the ability to oversee and regulate activity on the storage systems. And by leveraging storage-based data management, it enables increased performance and availability, as well as reduced testing and development times.

For more information about NetApp SnapCenter, see the https://www.netapp.com/data-protection/backup-recovery/snapcenter-backup-management/[NetApp SnapCenter Overview^].

== NetApp with NetApp SnapCenter video series


* https://review.docs.netapp.com/us-en/netapp-solutions_main_cr/virtualization/scv_videos_deployment.html[SnapCenter Deployment^]
* https://review.docs.netapp.com/us-en/netapp-solutions_main_cr/virtualization/scv_videos_prerequisites.html[SnapCenter Solution Pre-Requisites^]
* https://review.docs.netapp.com/us-en/netapp-solutions_main_cr/virtualization/scv_videos_backup_workflow.html[SnapCenter Backup Workflow^]
* https://review.docs.netapp.com/us-en/netapp-solutions_main_cr/virtualization/scv_videos_restore_workflow.html[SnapCenter Restore Workflow^]
* https://review.docs.netapp.com/us-en/netapp-solutions_main_cr/virtualization/scv_videos_sql_restore.html[SnapCenter SQL Restore Workflow^]


== NetApp with VMware Tanzu

VMware Tanzu enables customers to deploy, administer, and manage their Kubernetes environment through vSphere or the VMware Cloud Foundation. This portfolio of products from VMware allows customer to manage all their relevant Kubernetes clusters from a single control plane by choosing the VMware Tanzu edition that best suits their needs.

For more information about VMware Tanzu, see the https://tanzu.vmware.com/tanzu[VMware Tanzu Overview^]. This review covers use cases, available additions, and more about VMware Tanzu.

== NetApp with VMware Tanzu video series

* https://www.youtube.com/watch?v=ZtbXeOJKhrc[How to use vVols with NetApp and VMware Tanzu Basic, part 1^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE[How to use vVols with NetApp and VMware Tanzu Basic, part 2^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU[How to use vVols with NetApp and VMware Tanzu Basic, part 3^]

// == NetApp with VMware Cloud Foundation

// VMware Cloud Foundation allows customer to build software defined infrastructure as a standardized stack of compute, storage, networking, and management whether in the datacenter or in the public cloud. As deployments grow beyond the initial management domain, customers can choose to deploy the principal or supplemental storage that best meets their needs for their various workload domains and modern applications.
//
// NOTE: *For more information regarding VMware Cloud Foundation please consult the following:*
//
// * The https://www.vmware.com/products/cloud-foundation.html[VMware Cloud Foundation Overview^]. Review the product details, deployment options and learn more about VMware Cloud Foundation.
//
// == NetApp with VMware Cloud Foundation Videos
//
// * NetApp and VMware Cloud Foundations Basics
// * NetApp ONTAP and VCF VI Workload Domain Creation with vVols and NFS
// * NetApp ONTAP and VCF VI Workload Domain Creation with FlexGroup and NFS
// * NetApp Element and VCF VI Workload Domain with vVols and iSCSI
//
== NetApp with Red Hat OpenShift

Red Hat OpenShift, an enterprise Kubernetes platform, enables you to run container-based applications with an open hybrid-cloud strategy. Available as a cloud service on leading public clouds or as self-managed software, Red Hat OpenShift provides customers with the flexibility they need when designing their container-based solution.

For more information regarding Red Hat OpenShift, see this https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift Overview^]. You can also review the product documentation and deployment options to learn more about Red Hat OpenShift.

== NetApp with Red Hat OpenShift videos

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html[Workload Migration - Red Hat OpenShift with NetApp^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html[Red Hat OpenShift Deployment on RHV: Red Hat OpenShift with NetApp^]
