---
sidebar: sidebar
permalink: virtualization/vsphere_admin_vvols_and_spbm.html
keywords: vSphere, vVols, virtual volumes, SPBM, storage police based management, ONTAP
summary: This page describes the best practices for implementing a NetApp ONTAP storage solution in a VMware vSphere environment.
---

= Virtual Volumes (vVols) and Storage Policy Based Management (SPBM)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with Atom 1.57.0 (May 19, 2021)
//
//

[.lead]
== About vVols and SPBM

NetApp was an early design partner with VMware in the development of vSphere Virtual Volumes (vVols), providing architectural input and early support for vVols and VMware vSphere APIs for Storage Awareness (VASA). Not only did this approach bring VM granular storage management to VMFS, it also supported automation of storage provisioning through Storage Policy-Based Management (SPBM).

SPBM provides a framework that serves as an abstraction layer between the storage services available to your virtualization environment and the provisioned storage elements via policies. This approach allows storage architects to design storage pools with different capabilities that can be easily consumed by VM administrators. Administrators can then match virtual machine workload requirements against the provisioned storage pools, allowing for granular control of various settings on a per-VM or virtual disk level.

ONTAP leads the storage industry in vVols scale, supporting hundreds of thousands of vVols in a single cluster, whereas enterprise array and smaller flash array vendors support as few as several thousand vVols per array. NetApp is also driving the evolution of VM granular management with upcoming capabilities in support of vVols 3.0.

NOTE: For more information on VMware vSphere Virtual Volumes, SPBM, and ONTAP, see https://www.netapp.com/pdf.html?item=/media/13555-tr4400.pdf[TR-4400: VMware vSphere Virtual Volumes with ONTAP^].
