---
sidebar: sidebar
permalink: virtualization/vsphere_demos_videos.html
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP
summary: This page provides and introduction to videos and tutorials.
---

= Hybrid cloud, desktop virtualization and containers videos and demos
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with Atom 1.57.0 (June 18, 2021)
//
//

See the following videos and demos highlighting specific features of the hybrid cloud, desktop virtualization, and container solutions.

== NetApp ONTAP Tools for VMware vSphere

video::otv_overview.mp4[]

Utilizing ONTAP Tools for VMware vSphere Restful API, sample Ansible playbook is created for provisioning and removal of Traditional (VMFS and NFS) vSphere datastores as well as Virtual Volume Datastores.

video::otv_iscsi_provision.mp4[]
video::otv_nfs_provision.mp4[]

== VMware Cloud on AWS with AWS FSx for NetApp ONTAP

video::vmc_windows_vm_iscsi.mp4[]
video::vmc_linux_vm_nfs.mp4[]

== SnapCenter Plug-in for VMware vSphere

video::scv_prereq_overview[]
video::scv_deployment[]
video::scv_backup_workflow[]
video::scv_restore_workflow[]
video::scv_sql_restore[]



== NetApp with VMware Tanzu

VMware Tanzu enables customers to deploy, administer, and manage their Kubernetes environment through vSphere or the VMware Cloud Foundation. This portfolio of products from VMware allows customer to manage all their relevant Kubernetes clusters from a single control plane by choosing the VMware Tanzu edition that best suits their needs.

For more information about VMware Tanzu, see the https://tanzu.vmware.com/tanzu[VMware Tanzu Overview^]. This review covers use cases, available additions, and more about VMware Tanzu.

== NetApp with VMware Tanzu video series

* https://www.youtube.com/watch?v=ZtbXeOJKhrc[How to use vVols with NetApp and VMware Tanzu Basic, part 1^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE[How to use vVols with NetApp and VMware Tanzu Basic, part 2^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU[How to use vVols with NetApp and VMware Tanzu Basic, part 3^]

// == NetApp with VMware Cloud Foundation

// VMware Cloud Foundation allows customer to build software defined infrastructure as a standardized stack of compute, storage, networking, and management whether in the datacenter or in the public cloud. As deployments grow beyond the initial management domain, customers can choose to deploy the principal or supplemental storage that best meets their needs for their various workload domains and modern applications.
//
// NOTE: *For more information regarding VMware Cloud Foundation please consult the following:*
//
// * The https://www.vmware.com/products/cloud-foundation.html[VMware Cloud Foundation Overview^]. Review the product details, deployment options and learn more about VMware Cloud Foundation.
//
// == NetApp with VMware Cloud Foundation Videos
//
// * NetApp and VMware Cloud Foundations Basics
// * NetApp ONTAP and VCF VI Workload Domain Creation with vVols and NFS
// * NetApp ONTAP and VCF VI Workload Domain Creation with FlexGroup and NFS
// * NetApp Element and VCF VI Workload Domain with vVols and iSCSI
//
== NetApp with Red Hat OpenShift

Red Hat OpenShift, an enterprise Kubernetes platform, enables you to run container-based applications with an open hybrid-cloud strategy. Available as a cloud service on leading public clouds or as self-managed software, Red Hat OpenShift provides customers with the flexibility they need when designing their container-based solution.

For more information regarding Red Hat OpenShift, see this https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat OpenShift Overview^]. You can also review the product documentation and deployment options to learn more about Red Hat OpenShift.

== NetApp with Red Hat OpenShift videos

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html[Workload Migration - Red Hat OpenShift with NetApp^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html[Red Hat OpenShift Deployment on RHV: Red Hat OpenShift with NetApp^]
