---
sidebar: sidebar
permalink: virtualization/vsphere_ontap_asa_otv.html
keywords: vsphere, ontap, cloud insights, asa, all-flash san array, 
summary:
---

= NetApp All-Flash SAN Array with VMware vSphere 8
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
// For the imagesdir setting, make sure the path to the media folder is correct.  The default path assumes
// the source is located in the root of the repository.  Select the appropriate setting based on the level
// of the folder containing the source
//:imagesdir: ./media/
//:imagesdir: ./../media/
:imagesdir: ./../../media/


[.lead]
Author: Josh Powell - NetApp Solutions Engineering

== Block Storage with ONTAP Tools for VMware vSphere
The ONTAP Tools for VMware allows administrators to manage NetApp storage directly from within the vSphere Client. ONTAP Tools allows you to deploy and manage datastores, as well as provision vVol datastores. 
ONTAP Tools allows mapping of datastores to storage capability profiles which determine a set of storage system attributes. This allows the creation of datastores with specific attributes such as storage performance and QoS.

ONTAP Tools includes the following components:

*Virtual Storage Console (VSC):* The VSC includes the interface integrated with the vSphere client where you can add storage controllers, provision datastores, monitor performance of datastores, and view and update ESXi host settings.

*VASA Provider:* The VMware vSphere APIs for Storage Awareness (VASA) Provider for ONTAP send information about storage used by VMware vSphere to the vCenter Server, enabling provisioning of VMware Virtual Volumes (vVols) datastores, creation and use of storage capability profiles, compliance verification, and performance monitoring.

*Storage Replication Adapter (SRA):* When enabled and used with VMware Site Recovery Manager (SRM), SRA facilitates the recovery of vCenter Server datastores and virtual machines in the event of a failure, allowing configuration of protected sites and recovery sites for disaster recovery.

For more information on NetApp ONTAP tools for VMware, see the following: https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html.

=== Solution Overview
In this solution we will demonstrate the use of the ONTAP Tools for VMware vSphere to provision a VMware Virtual Volumes (VVOL) datastores and create a virtual machine on a VVOL datastore. 

In a vVols datastore each virtual disk is a vVol and becomes a native LUN object on the storage system. The integration of the storage system and vSphere takes place through the VMware API’s for Storage Awareness (VASA) provider (installed with ONTAP Tools) and allows the storage system to be aware of the VM data and manage it accordingly. Storage policies, defined in the vCenter Client are used to allocate and manage storage resources. 

The solution will cover the following high level steps:

1. Add a storage system in ONTAP Tools.

2. Create a storage capability profile in ONTAP Tools.

3. Create a VVOLs datastore in ONTAP Tools.

4. Create a VM storage policy in the vSphere client.

5. Create a new virtual machine on the VVOL datastore.


The following components were used in this solution:

* NetApp All-Flash SAN Array A400 with ONTAP 9.13
* ONTAP Tools for VMware vSphere 9.13
* vSphere 8.0 cluster
* VVOLs datastore running on the iSCSI protocol

