---
sidebar: sidebar
permalink: virtualization/vsphere_ontap_asa_overview.html
keywords: vsphere, ontap, cloud insights, asa, all-flash san array, 
summary:
---

= NetApp ONTAP 9.13, AFF ASA A400, and VMware vSphere 8 Design Guide
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
// For the imagesdir setting, make sure the path to the media folder is correct.  The default path assumes
// the source is located in the root of the repository.  Select the appropriate setting based on the level
// of the folder containing the source
//:imagesdir: ./media/
//:imagesdir: ./../media/
:imagesdir: ./../../media/


[.lead]
Authors: Suresh Thoppay, Chris Reno, Josh Powell - NetApp Solutions Engineering

== Technology Overview
// Describe WHAT problem this solution addresses.  What are the use cases(s) and how does it solve a problem?
// Use a bulleted list and keep it brief!

=== Virtualized Infrastructure
Talk about generic compute and switches, SAN workloads. Make to sure to mention Cloud Insight.

=== VMware vSphere 8.0
VMware vSphere is a virtualization platform that transforms physical resources into pools of compute, network and storage which can be used to satisfy customer’s workload and application requirements.

==== New Improvements in vSphere 8.0
vSphere 8.0 introduces some new improvements including, but not limited to:

*Scalability* - vSphere 8.0 supports the latest Intel and AMD CPUs and has extended limits for vGPU devices, ESXi hosts, VMs per cluster, and VM DirectPath I/O devices.

*Distributed Services Engine* - Network offloading with NSX to Data Processing Units (DPUs).

*Enhanced Device Efficiency* - vSphere 8.0 boosts device management capabilities with features like device groups and Device Virtualization Extensions (DVX).

*Improved Security* - The inclusion of an SSH timeout and TPM Provision Policy strengthens the security framework.

*Integration with Hybrid Cloud Services* - This feature facilitates seamless transition between on-premises and cloud workloads.

*Integrated Kubernetes Runtime* - With the inclusion of Tanzu, vSphere 8.0 simplifies container orchestration.

For more information on refer to the blog, https://core.vmware.com/resource/whats-new-vsphere-8/[What's New in vSphere 8?]

==== VMware vSphere vCenter
VMware vCenter allows for a central management experience for interacting with compute resources, networking and storage as part of your virtual infrastructure.

==== VMware vSphere ESXi
VMware’s hypervisor which enables the abstraction of compute processors, memory, network and other resources and makes them available to virtual machines and container workloads.

==== VMware networking

==== Modern workloads with VMware

===== VMware Virtual Volumes (vVols)
vVols are a revolutionary new approach to storage management in vSphere clusters, providing simplified management and more granular control of storage resources. In a vVols datastore each virtual disk is a vVol and becomes a native LUN object on the storage system. The integration of the storage system and vSphere takes place through the VMware API’s for Storage Awareness (VASA) provider and allows the storage system to be aware of the VM data and manage it accordingly. Storage policies, defined in the vCenter Client are used to allocate and manage storage resources. 

vVols are a simplified approach to storage management and are preferred in some use cases.

For more information on vVols see the https://core.vmware.com/resource/vvols-getting-started-guide[vVols Getting Started Guide].

===== NVMe-oF
With the release of vSphere 8.0, NVMe is now supported end-to-end from...

=== NetApp ONTAP 9.13

==== ONTAP ONE

===== ONTAP One for SAN

* Block Protocols
** NVMe/FC, NVMe/TCP, FCP, iSCSI
* Data Protection – SnapMirror A/S/BC
* SnapLock
* SnapMirror Cloud

==== Base ONTAP Features
Note the ONTAP One for SAN. Just touch on this.

==== Disaster Recovery Features
Metrocluster, SRM, SMBC

=== NetApp ASA A-Series Storage
Platform specific info for ASA. Make statements about AFF, ASA, C-Series but focus on ASA.

==== Product portfolio
Deeper dive on specifically the ASA. Talk about ONTAP One for SAN. Include product portfolio image

==== Why SAN only

==== Consistent operations with ONTAP
Talk about how this is SAN only but it is still ONTAP. 

Make note to include something in design considerations around mixed clusters and dos and don't's.

==== Modern (change header)
Symmetric Active-Active. All-NVMe. The power and resiliency of a legacy frame array in a modern system.

===== Protocols

==== Guarantees

Six Nines Data Availability Guarantee
* Guranteed 99.999% uptime. 
* Should you experience an unplanned data availability downtime event in excess of 31.56 seconds per year (99.9999%), NetApp will issue a credit.

Storage Efficiency Guarantee
* NetApp raw to useable ratio is higher than many competitors.
* 4:1 storage efficiency guarantee available for customer using SAN protocols.
* If we don’t meet your workload efficiency goals, we’ll make it right at no cost to you.

Ransomware Recovery Guarantee

* NetApp will warrant snapshot data recovery in the event of a ransomware attack.
* If you can’t recover your data copies with help from NetApp or partner assistance, NetApp will offer compensation.


