---
sidebar: sidebar
permalink: virtualization/vsrm-ontap9_appendix_a__troubleshooting_srm_when_using_vvols_replication.html
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, srm, vvols, replication
summary: The workflow within SRM is significantly different when using vVols replication from what is used with SRA and traditional datastores.
---

= Troubleshooting SRM when using vVols replication
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-06-24 16:18:25.264894
//

[.lead]
The workflow within SRM is significantly different when using vVols replication from what is used with SRA and traditional datastores. For example, there is no array manager concept. As such, `discoverarrays` and `discoverdevices` commands are never seen.

When troubleshooting, it is beneficial to understand the new workflows, which are listed below:

. queryReplicationPeer: Discovers the replication agreements between two fault domains.
. queryFaultDomain: Discovers fault domain hierarchy.
. queryReplicationGroup: Discovers the replication groups present in the source or target domains.
. syncReplicationGroup: Synchronizes the data between source and target.
. queryPointInTimeReplica: Discovers the point in time replicas on a target.
. testFailoverReplicationGroupStart: Begins test failover.
. testFailoverReplicationGroupStop: Ends test failover.
. promoteReplicationGroup: Promotes a group currently in test to production.
. prepareFailoverReplicationGroup: Prepares for a disaster recovery.
. failoverReplicationGroup: Executes disaster recovery.
. reverseReplicateGroup: Initiates reverse replication.
. queryMatchingContainer: Finds containers (along with Hosts or Replication Groups) that might satisfy a provisioning request with a given policy.
. queryResourceMetadata: Discovers the metadata of all resources from the VASA provider, the resource utilization can be returned as an answer to the queryMatchingContainer function.

The most common error seen when configuring vVols replication is a failure to discover the SnapMirror relationships. This occurs because the volumes and SnapMirror relationships are created outside of the purview of ONTAP Tools. Therefore, it is a best practice to always make sure your SnapMirror relationship is fully initialized and that you have run a rediscovery in ONTAP Tools at both sites before attempting to create a replicated vVols datastore.
