---
sidebar: sidebar
permalink: virtualization/vvols-resources.html
keywords: tr-4400, vvols, ontap, virtual volumes, protect
summary: 
---

= Troubleshooting
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
There are several troubleshooting resources available with additional information.

== NetApp Support Site

In addition to a variety of Knowledgebase articles for NetApp virtualization products, the NetApp Support site also offers a convenient landing page for the https://mysupport.netapp.com/site/products/all/details/otv/docs-tab[ONTAP tools for VMware vSphere] product. This portal provides links to articles, downloads, technical reports, and VMware Solutions Discussions on NetApp Community. It is available at:

https://mysupport.netapp.com/site/products/all/details/otv/docs-tab[_NetApp Support Site_]

Additional solution documentation is available here:

https://docs.netapp.com/us-en/netapp-solutions/virtualization/index.html[_NetApp Solutions for Virtualization_]

== Product Troubleshooting

The various components of ONTAP tools, such as the vCenter plugin, VASA Provider, and Storage Replication Adapter are all documented together in the NetApp documents repository. However, each has a separate subsection of the Knowledge Base and may have specific troubleshooting procedures. These address the most common issues that may be encountered with the VASA Provider.

=== VASA Provider UI Problems

Occasionally the vCenter vSphere Web Client encounters problems with the Serenity components, causing the VASA Provider for ONTAP menu items not to display. See Resolving VASA Provider registration issues in the Deployment Guide, or this Knowledgebase https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/How_to_resolve_display_issues_with_the_vSphere_Web_Client[article].

=== vVols Datastore Provisioning Fails

Occasionally vCenter services may time out when creating the vVols datastore. To correct it, restart the vmware-sps service, and re-mount the vVols datastore using the vCenter menus (Storage > New Datastore). This is covered under vVols datastore provisioning fails with vCenter Server 6.5 in the Administration Guide.

=== Upgrading Unified Appliance Fails to Mount ISO

Due to a bug in vCenter, the ISO used to upgrade the Unified Appliance from one release to the next may fail to mount. If the ISO is able to be attached to the appliance in vCenter, follow the process in this Knowledgebase https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/Virtual_Storage_Console_(VSC)%3A_Upgrading_VSC_appliance_fails_%22failed_to_mount_ISO%22[article] to resolve.
