---
sidebar: sidebar
permalink: containers/baremetal-anthos/bmanthos_solution_requirements.html
keywords: Hardware, software, compute, storage, requirements
summary: The hardware-agnostic capabilities of Anthos on bare metal allow you to select a compute platform optimized for your use-case. Therefore, your can match your existing infrastructure and reduce capital expenditure.
---

= Solution requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-03-29 10:17:22.546702
//

== Hardware requirements

=== Compute: bring your own server

The hardware-agnostic capabilities of Anthos on bare metal allow you to select a compute platform optimized for your use case. Therefore, your can match your existing infrastructure and reduce capital expenditure.

The following table lists the minimum number of compute hardware components that are required to implement this solution, although the hardware models used can vary based on customer requirements.

|===
|Usage |Hardware and model |Quantity

|Admin nodes
|Cisco UCS B200
|3
|Worker nodes
|HP Proliant DL360
|4
|===

=== Storage: NetApp ONTAP

The following table lists the minimum number of storage-hardware components needed to implement the solution, although the hardware models used can vary based on customer requirements.

|===
|Hardware  |Model |Quantity

|NetApp AFF
|NetApp AFF A300
|2 (1 HA pair)
|===

== Software requirements

The software versions identified in the following table were used by NetApp and our partners to validate the solution with NetApp, although the software components used can vary based on customer requirements.

|===
|Software  |Purpose |Version

|Ubuntu
|OS on 3 Admins
|20.04
|
|OS on Worker4
|20.04
|
|OS on Worker3
|18.04
|CentOS
|OS on Worker2
|8.2
|Red Hat Enterprise Linux
|OS on Worker1
|8.1
|Anthos on bare metal
|Container Orchestration
|1.6.0
|NetApp ONTAP
|Storage OS
|9.7P8
|NetApp Astra Trident
|Container Storage Management
|20.10
|===

[NOTE]
This multi-OS environment shows the interoperability with supported OS versions of the Anthos on bare metal solution. We anticipate that customers will standardize on one or a subset of operating systems for deployment.

For Anthos on bare metal hardware and software requirements, see the https://cloud.google.com/anthos/gke/docs/bare-metal/concepts/hw-sw-storage[Anthos on bare metal documentation^] page.

link:bmanthos_deployment_summary.html[Next: Deployment summary.]
