---
sidebar: sidebar
permalink: containers/baremetal-anthos/bmanthos_solution_validation.html
keywords: validation, google cloud, nginx
summary: The current deployment of this solution was put through two rigorous validation processes using tools provided by the Google Cloud team.
---

= Solution validation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-03-29 10:17:22.575687
//

The current deployment of this solution was put through two rigorous validation processes using tools provided by the Google Cloud team. These validations include a subset of the following tests:

* Partner validation of the Anthos-ready platform:
** Confirm that all Anthos on bare metal platform services are installed and running.
** Scale down the physical Anthos on bare metal cluster from four worker nodes to three and then back to four.
** Create and delete a custom namespace.
** Create a deployment of the Nginx web server, scaling that deployment by increasing the number of replicas.
** Create an ingress for the Nginx application and verify connectivity by curling the index.html.
** Successfully clean up all test suite activities and return the cluster to a pretest state.

* Partner validation of Anthos-ready storage:
** Create a deployment with a persistent volume claim.
** Use NetApp Astra Trident to provision and attach the requested persistent volume from NetApp ONTAP.
** Validate the detach-and-reattach capability of persistent volumes.
** Validate multi-attach, read-only access of persistent volumes from other pods on the node.
** Validate the offline volume resize operation.
** Verify that the persistent volume survives a cluster-scaling operation.

link:bmanthos_conclusion.html[Next: Conclusion.]
