


//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-02-16 10:32:05.121542
//
=== fsx_vars.yml - Global VARS Config

Input parameters into blue underlined fields, then use copy button and paste the entries into your fsx_vars.yml file at Ansible controller host.
 
++++
<style>
div {
position: relative;
}
div button {
position: absolute;
top: 0;
right: 0;
}
button {
  transition-duration: 0.4s;
  background-color: white;
  color: #1563a3;
  border: 2px solid #1563a3;
}
button:hover {
  background-color: #1563a3;
  color: white;
}
#more_storage_vlans {
  display: block;
}
#more_storage_vlans_button {
  display: none;
}
#more_nfs_volumes {
  display: block;
}
#more_nfs_volumes_button {
  display: none;
}
</style>
<div class="listingblock"><div class="content"><div><button id="copy-button" onclick="CopyClassText()">Copy</button></div><pre><code><div class="CopyMeClass" id="CopyMeID">
########################################################################
######  PostgreSQL HADR global user configuration variables       ######
######  Consolidate all variables from FSx, Linux, and postgresql ######
########################################################################

###########################################
### Ontap env specific config variables ###
###########################################

####################################################################################################
# Variables for SnapMirror Peering
####################################################################################################

#Passphrase for cluster peering authentication
passphrase: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>xxxxxxx</i></span>

#Please enter destination or standby FSx cluster name
dst_cluster_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>FsxId0cf8e0bccb14805e8</i></span>

#Please enter destination or standby FSx cluster management IP 
dst_cluster_ip: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>172.30.15.90</i></span>

#Please enter destination or standby FSx cluster inter-cluster IP
dst_inter_ip: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>172.30.15.13</i></span>

#Please enter destination or standby SVM name to create mirror relationship
dst_vserver: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>dr</i></span>

#Please enter destination or standby SVM management IP
dst_vserver_mgmt_lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>172.30.15.88</i></span>

#Please enter destination or standby SVM NFS lif
dst_nfs_lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>172.30.15.88</i></span>

#Please enter source or primary FSx cluster name
src_cluster_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>FsxId0cf8e0bccb14805e8</i></span>

#Please enter source or primary FSx cluster management IP 
src_cluster_ip: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>172.30.15.20</i></span>

#Please enter source or primary FSx cluster inter-cluster IP
src_inter_ip: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>172.30.15.5</i></span>

#Please enter source or primary SVM name to create mirror relationship
src_vserver: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>prod</i></span>

#Please enter source or primary SVM management IP
src_vserver_mgmt_lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>172.30.15.115</i></span>

#####################################################################################################
# Variable for PostgreSQL Volumes, lif - source or primary FSx NFS lif address
#####################################################################################################

src_db_vols:
  - {vol_name: &quot<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>{{groups.postgresql[0]}}_pgdata</i></span>&quot, aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr1</i></span>, lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.200</i></span>, size: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>100</i></span>}

src_archivelog_vols:
  - {vol_name: &quot<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>{{groups.postgresql[0]}}_pglogs</i></span>&quot, aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr1</i></span>, lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.200</i></span>, size: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>100</i></span>}

#Names of the Nodes in the ONTAP Cluster
nfs_export_policy: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>default</i></span>

#####################################################################################################
### Linux env specific config variables ###
#####################################################################################################

#NFS Mount points for PostgreSQL DB volumes
mount_points:
  - <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>/pgdata</i></span>
  - <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>/pglogs</i></span>

#RedHat subscription username and password
redhat_sub_username: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>xxxxx</i></span>
redhat_sub_password: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>xxxxx</i></span>

####################################################
### DB env specific install and config variables ###
####################################################
#The latest version of PostgreSQL RPM is pulled/installed and config file is deployed from a preconfigured template
#Recovery type and point: default as all logs and promote and leave all PITR parameters blank

</div></code></pre></div></div>
<script>
function CopyClassText(){
  	var textToCopy = document.getElementById("CopyMeID");
  	var currentRange;
  	if(document.getSelection().rangeCount > 0)
  	{
  		currentRange = document.getSelection().getRangeAt(0);
  		window.getSelection().removeRange(currentRange);
  	}
  	else
  	{
  		currentRange = false;
  	}
  	var CopyRange = document.createRange();
  	CopyRange.selectNode(textToCopy);
  	window.getSelection().addRange(CopyRange);
    document.getElementById("more_storage_vlans").style.display = "none";
    document.getElementById("more_nfs_volumes").style.display = "none";
    var command = document.execCommand("copy");
      if (command)
      {
          document.getElementById("copy-button").innerHTML = "Copied!";
          setTimeout(revert_copy, 3000);
      }
  	window.getSelection().removeRange(CopyRange);
  	if(currentRange)
  	{
  		window.getSelection().addRange(currentRange);
  	}
}
function revert_copy() {
      document.getElementById("copy-button").innerHTML = "Copy";
      document.getElementById("more_storage_vlans").style.display = "block";
      document.getElementById("more_nfs_volumes").style.display = "block";
}
function storagevlandropdown() {
    document.getElementById("more_storage_vlans").style.display = "none";
	document.getElementById("more_storage_vlans_button").style.display = "block";
    var x=1;
    var myHTML = '';
    var buildup = '';
    var wrapper = document.getElementById("select_more_storage_vlans");
    while (x < 10) {
      buildup += '<option value="' + x + '">' + x + '</option>';
  	  x++;
    }
    myHTML += '<a id="more_storage_vlans_info">How many extra VLANs do you wish to add?</a><select name="number_of_extra_storage_vlans" id="number_of_extra_storage_vlans">' + buildup + '</select>';
    wrapper.innerHTML = myHTML;
}
function addstoragevlans() {
    var y = document.getElementById("number_of_extra_storage_vlans").value;
    var j=0;
    var myHTML = '';
    var wrapper = document.getElementById("extra_storage_vlans");
    while (j < y) {
    	j++;
        myHTML += '   - {vlan_id: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>203</i></span>&quot;, name: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>infra_NFS</i></span>&quot;, protocol: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>NFS</i></span>&quot;}<br>';
    }
	wrapper.innerHTML = myHTML;
	document.getElementById("select_more_storage_vlans").style.display = "none";
	document.getElementById("more_storage_vlans_button").style.display = "none";
}
function nfsvolumesdropdown() {
    document.getElementById("more_nfs_volumes").style.display = "none";
	document.getElementById("more_nfs_volumes_button").style.display = "block";
    var x=1;
    var myHTML = '';
    var buildup = '';
    var wrapper = document.getElementById("select_more_nfs_volumes");
    while (x < 100) {
      buildup += '<option value="' + x + '">' + x + '</option>';
  	  x++;
    }
    myHTML += '<a id="more_nfs_volumes_info">How many extra NFS volumes do you wish to add?</a><select name="number_of_extra_nfs_volumes" id="number_of_extra_nfs_volumes">' + buildup + '</select>';
    wrapper.innerHTML = myHTML;
}
function addnfsvolumes() {
    var y = document.getElementById("number_of_extra_nfs_volumes").value;
    var j=0;
    var myHTML = '';
    var wrapper = document.getElementById("extra_nfs_volumes");
    while (j < y) {
    	j++;
        myHTML += '  - {vol_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>rtpora04_u01</i></span>, aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr01_node02</i></span>, lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.201</i></span>, size: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>25</i></span>}<br>';
    }
	wrapper.innerHTML = myHTML;
	document.getElementById("select_more_nfs_volumes").style.display = "none";
	document.getElementById("more_nfs_volumes_button").style.display = "none";
}

</script>
++++
