:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

. Configure the credentials.
. Create credential types. For solutions involving ONTAP, you must configure the credential type to match username and password entries, we will also add entries for Cloud Central and AWS.
.. Navigate to Administration → Credential Types, and click Add.
.. Provide the name and description.
.. Paste the following content in Input Configuration:
+

[source, cli]
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true


.. Paste the following content into Injector Configuration and click Save:
+

[source, cli]
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'

. Create Credential for ONTAP/CVO/AWS
.. Navigate to Resources → Credentials, and click Add.
.. Enter the name and organization details for the ONTAP Credentials
.. Select the credential type that was created in the previous step.
.. Under Type Details, enter the Username and Password for your Source and CVO Clusters, Cloud Central/Manager, AWS Access/Secret Key and Cloud Central Refresh Token.
.. Click Save

. Create Credential for Oracle (Source)
.. Navigate to Resources → Credentials, and click Add.
.. Enter the name and organization details for Oracle host
.. Select the Machine credential type.
.. Under Type Details, enter the Username and Password for the Oracle hosts.
.. Select the correct Privilege Escalation Method, and enter the username and password.
.. Click Save

. Create Credential for Oracle Destination
.. Navigate to Resources → Credentials, and click Add.
.. Enter the name and organization details for the DR Oracle host
.. Select the Machine credential type.
.. Under Type Details, enter the Username (ec2-user or if you have changed it from default enter that), and the SSH Private Key
.. Select the correct Privilege Escalation Method (sudo), and enter the username and password if needed.
.. Click Save
