
// tag::all[]

[role="tabbed-block"]
====
.AWS / VMC
--
//***********************************
//* AWS DataStore Support           *
//***********************************

// tag::aws-datastore[]

AWS supports NetApp storage in the following configurations:

* FSx ONTAP as guest connected storage
* Cloud Volumes ONTAP (CVO) as guest connected storage
* FSx ONTAP as a native datastore^1^

// tag::ehc-aws[]
View the detailed link:aws/aws-guest.html[guest connect storage options for VMC].
// end::ehc-aws[]

// tag::aws[]
View the detailed link:aws-guest.html[guest connect storage options for VMC].
// end::aws[]

NOTE: 1 - FSxN for VMC is currently in IA (Initial Availability).  Contact your NetApp sales representative for more information.

// end::aws-datastore[]
--
.Azure / AVS
--
//***********************************
//* Azure Datastore Support         *
//***********************************

// tag::azure-datastore[]

Azure supports NetApp storage in the following configurations:

* Azure NetApp Files (ANF) as guest connected storage
* Cloud Volumes ONTAP (CVO) as guest connected storage
* Azure NetApp Files (ANF) as a native datastore^1^

// tag::ehc-azure[]
View the detailed link:azure/azure-guest.html[guest connect storage options for AVS].
// end::ehc-azure[]

// tag::azure[]
View the detailed link:azure-guest.html[guest connect storage options for AVS].
// end::azure[]

Read more about https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal[Azure NetApp Files (ANF) as a native datastore - Public Preview].

// end::azure-datastore[]
--
.GCP / GCVE
--
//***********************************
//* Google Cloud Datastore Support  *
//***********************************

// tag::gcp-datastore[]

Google Cloud supports NetApp storage in the following configurations:

* Cloud Volumes ONTAP (CVO) as guest connected storage
* Cloud Volumes Service (CVS) as guest connected storage
* Cloud Volumes Service (CVS) as a native datastore^1^

// tag::ehc-gcp[]
View the detailed link:gcp/gcp-guest.html[guest connect storage options for GCVE].
// end::ehc-gcp[]

// tag::gcp[]
View the detailed link:gcp-guest.html[guest connect storage options for GCVE].
// end::gcp[]

Read more about link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/[Cloud Volumes Service (CVS) as a native datastore^1^].

NOTE: 1 - Currently in Private Preview

// end::gcp-datastore[]
====

// end::all[]
