
// tag::all[]

[role="tabbed-block"]
====
.AWS / VMC
--
//***********************************
// Section for AWS Configuration    *
//***********************************

// tag::aws-config[]

This section describes how to set up and manage VMware Cloud on AWS SDDC and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting Cloud Volumes ONTAP to AWS VMC.

The setup process can be broken down into the following steps:

* Deploy and Configure VMware Cloud for AWS
* Connect VMware Cloud to FSx ONTAP

// tag::ehc-aws[]
View the detailed link:aws-setup.html[configuration steps for VMC].
// end::ehc-aws[]

// tag::aws[]
View the detailed link:aws-setup.html[configuration steps for VMC].
// end::aws[]
// end::aws-config[]
--
.Azure / AVS
--
//***********************************
//* Section for Azure Configuration *
//***********************************

// tag::azure-config[]

This section describes how to set up and manage Azure VMware Solution and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting Cloud Volumes ONTAP to Azure VMware Solution.

The setup process can be broken down into the following steps:

* Register the resource provider and create a private cloud
* Connect to a new or existing ExpressRoute virtual network gateway
* Validate the network connectivity and access the private cloud

// tag::ehc-azure[]
View the detailed link:azure-setup.html[configuration steps for AVS].
// end::ehc-azure[]

// tag::azure[]
View the detailed link:azure-setup.html[configuration steps for AVS].
// end::azure[]
// end::azure-config[]
--
.GCP / GCVE
--
//***********************************
// Section for GCP Configuration    *
//***********************************

// tag::gcp-config[]

This section describes how to set up and manage GCVE and use it in combination with the available options for connecting NetApp storage.

NOTE: In-guest storage is the only supported method of connecting Cloud Volumes ONTAP and Cloud Volumes Services to GCVE.

The setup process can be broken down into the following steps:

* Deploy and Configure GCVE
* Enable Private Access to GCVE

// tag::ehc-gcp[]
View the detailed link:gcp-setup.html[configuration steps for GCVE].
// end::ehc-gcp[]

// tag::gcp[]
View the detailed link:gcp-setup.html[configuration steps for GCVE].
// end::gcp[]
// end::gcp-config[]
--
====
// end::all[]
