---
sidebar: sidebar
permalink: databases/aws_ora_fsx_ec2_migration.html
summary: This section provides details on factors to be considered when migrating Oracle database from on-premises to AWS EC2 instance and FSx storage.
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter
---

= Database migration from on-prem to public cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

link:aws_ora_fsx_ec2_mgmt.html[Previous: Database management.]

[.lead]
Database migration is a challenging endeavor by any means. Migrating an Oracle database from on-premises to the cloud is no exception.

The following sections provide key factors to consider when migrating Oracle databases to the AWS public cloud with the AWS EC2 compute and FSx storage platform.

== ONTAP storage is available on-premises

If the on-premises Oracle database is sitting on an ONTAP storage array, then it is easier to set up replication for database migration using the NetApp SnapMirror technology that is built into AWS FSx ONTAP storage. The migration process can be orchestrated using NetApp BlueXP console.

. Build a target compute EC2 instance that matches the on-premises instance.

. Provision matching, equally sized database volumes from FSx console.

. Mount the FSx database volumes to the EC2 instance.

. Set up SnapMirror replication between the on-premises database volumes to the target FSx database volumes. The initial sync might take some time to move the primary source data, but any following incremental updates are much quicker.

. At the time of switchover, shut down the primary application to stop all transactions. From the Oracle sqlplus CLI interface, execute an Oracle online log switch and allow SnapMirror sync to push the last archived log to the target volume. 

. Break up the mirrored volumes, run Oracle recovery at the target, and bring up the database for service.

. Point applications to the Oracle database in the cloud.

The following video demonstrates how to migrate an Oracle database from on-premises to AWS FSx/EC2 using the NetApp BlueXP console and SnapMirror replication.

link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[Oracle Database Migration from On-premises to FSx/EC2 via SnapMirror and BlueXP^]

== ONTAP storage is not available on premises

If the on-premises Oracle database is hosted on third-party storage other than ONTAP, database migration is based on the restore of a Oracle database backup copy. You must play the archive log to make it current before switching over.

AWS S3 can be used as a staging storage area for database move and migration. See the following high level steps for this method:

. Provision a new, matching EC2 instance that is comparable with the on-premises instance.

. Provision equal database volumes from FSx storage and mount the volumes to the EC2 instance.

. Create a disk-level Oracle backup copy.

. Move the backup copy to AWS S3 storage.

. Recreate the Oracle control file and restore and recover the database by pulling data and the archive log from S3 storage.

. Sync the target Oracle database with the on-premises source database.

. At switchover, shut down the application and source Oracle database. Copy the last few archive logs and apply them to the target Oracle database to bring it up to date.

. Start up the target database for user access.

. Redirect application to the target database to complete the switchover.

== Migrate on-premises Oracle databases to AWS FSx/EC2 using PDB relocation with maximum availability

This migration approach is best suited to Oracle databases that are already deployed in PDB/CDB multitenant model, and ONTAP storage is not available on-premises. The PDB relocation method utilizes Oracle PDB hot clone technology to move PDBs between a source CDB and a target CDB while minimizing service interruption.  

First, create CDB in the AWS FSx/EC2 with sufficient storage to host PDBs to be migrated from on-premises. Multiple on-premises PDBs can be relocated one at a time.

. If the on-premises database is deployed in a single instance rather than in the multitenant PDB/CDB model, follow the instructions in link:https://docs.netapp.com/us-en/netapp-solutions/databases/azure_ora_nfile_migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb[Converting a single instance non-CDB to a PDB in a multitenant CDB^] to convert the single instance to multitenant PDB/CDB. Then follow the next step to migrate the converted PDB to CDB in AWS FSx/EC2.

. If the on-premises database is already deployed in the multitenant PDB/CDB model, follow the instructions in link:https://docs.netapp.com/us-en/netapp-solutions/databases/azure_ora_nfile_migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation[Migrate on-premises Oracle databases to cloud with PDB relocation^] to perform the migration. 

The following video demonstrates how an Oracle database (PDB) can be migrated to FSx/EC2 using PDB relocation with maximum availability.

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796[Migrate on-prem Oracle PDB to AWS CDB with max availability^]


[NOTE]

Although the instructions in step 1 and 2 are illustrated in the context of Azure public cloud, the procedures are applicable to AWS cloud without any changes. 

The NetApp Solutions Automation team provides a migration toolkit that can facilitate Oracle database migration from on-premises to the AWS cloud. Use following command to download the Oracle database migration toolkit for PDB relocation.

[source, cli]
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
