---
sidebar: sidebar
permalink: databases/azure_ora_nfile_migration.html
summary: This section provides details on how to migrate Oracle database from on-premises to Azure NetApp Files and vise versa.
keywords: database, Oracle, Azure, ANF, Azure NetApp Files, migration
---

= Database migration from on-premises to Azure cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

link:azure_ora_nfile_protection.html[Previous: Database protection.]

Since Oracle announcement to phase out the single instance database, many organizations have converted single instance Oracle database into multitenant container database. This enables easy relocation of a subset of a container database called PDB to cloud with maximum availability option, which minimize the downtime during the migration.

However, if you still have single instance of Oracle database, it can first be converted into a multitenant container database in place before PDB relocation can be attempted.

The following sections provide details for migration of on-premises Oracle database to Azure cloud in either scenarios.

== Converting a single instance non CDB to a PDB in a multitenant CDB

If you are still sitting on single instance Oracle database, it needs to be converted to multitenant container database whether migrating to cloud or not. Oracle will stop supporting single instance database at some point.

Following are procedures to plug a single instance database into a container database as a pluggable database or PDB.

. Build a shell container database on the same host as the single instance database in a separate ORACLE_HOME.

. Shutdown single instance database and restart open read only

. Run DBMS_PDB.DESCRIBE procedure to generate database metadata
+
[source, cli]
BEGIN
  DBMS_PDB.DESCRIBE(
    pdb_descr_file => '/home/oracle/ncdb.xml');
END;
/

. Shutdown single instance database

. Startup the container database

. Run the DBMS_PDB.CHECK_PLUG_COMPATIBILITY function to determine whether the non-CDB is compatible with the CDB.
+
[source, cli]
SET SERVEROUTPUT ON
DECLARE
  compatible CONSTANT VARCHAR2(3) :=
    CASE DBMS_PDB.CHECK_PLUG_COMPATIBILITY(
           pdb_descr_file => '/disk1/oracle/ncdb.xml',
           pdb_name       => 'NCDB')
    WHEN TRUE THEN 'YES'
    ELSE 'NO'
END;
BEGIN
  DBMS_OUTPUT.PUT_LINE(compatible);
END;
/
+
If the output is YES, then the non-CDB is compatible, and you can continue with the next step.
+
If the output is NO, then the non-CDB is not compatible, and you can check the PDB_PLUG_IN_VIOLATIONS view to see why it is not compatible. All violations must be corrected before you continue. For example, any version or patch mismatches should be resolved by running an upgrade or the opatch utility. After correcting the violations, run DBMS_PDB.CHECK_PLUG_COMPATIBILITY again to ensure that the non-CDB is compatible with the CDB.

. Plug in the single instance non-CDB
+
[source, cli]
CREATE PLUGGABLE DATABASE ncdb USING '/home/oracle/ncdb.xml'
  COPY
  FILE_NAME_CONVERT = ('/disk1/oracle/dbs/', '/disk2/oracle/ncdb/')
;
+

[NOTE]
If there is no sufficient space on the host, NOCOPY option may be used to create the PDB. In that case, single instance non CDB will not be useable after plugin as a PDB, because the original data files has been used for the PDB. Make sure make a backup before the conversion so that there is something to fall back if anything goes wrong.

. Start with PDB upgrade after conversion if the version between source single instance non CDB and target CDB are different. For the same version conversion, this step can be bypassed.
+
[source, cli]
sqlplus / as sysdba;
+
[source, cli]
alter session set container=ncdb;
+
[source, cli]
alter pluggable database open upgrade;
exit;
+
[source, cli]
dbupgrade -c ncdb -l /home/oracle
+
Review the upgrade log file in /home/oracle directory.

. Open the pluggable database, check pdb plugin violations, and recompile the invalid objects.
+
[source, cli]
alter pluggable database ncdb open;
+
[source, cli]
alter session set container=ncdb;
select message from pdb_plug_in_violations where type like '%ERR%' and status <> 'RESOLVED';
+
[source, cli]
$ORACLE_HOME/perl/bin/perl $ORACLE_HOME/rdbms/admin/catcon.pl -n 1 -c 'ncdb' -e -b utlrp -d $ORACLE_HOME/rdbms/admin utlrp.sql

. Now, execute noncdb_to_pdb.sql to update data dictionary
+
[source, cli]
sqlplus / as sysdba
+
[source, cli]
alter session set container=ncdb;
@$ORACLE_HOME/rdbms/admin/noncdb_to_pdb.sql;
+
shutdown and restart the container DB, ncdb will be take out of restricted mode.

== Migrate on-premises Oracle databases to Azure with PDB relocation

Oracle PDB relocation with maximum availability option utilize PDB hot clone technology that allows the source PDB availability while PDB is being copied over to target.

At the switching over, sessions and connections are redirected target PDB automatically. Thus, the down time is minimized regardless the size of PDB to be relocated.

NetApp provides an Ansible based toolkit that automate migration procedure.

. Create a CDB in the Azure public cloud on Azure VM with the same version and patch level.

. From Ansible controller, clone a copy of automation toolkit.
+
[source, cli]
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git

. Read the instruction in README file.

. Configure the Ansible host variable files for both source and target Oracle servers and DB server hosts configuration file for name resolution.

. Install Ansible controller prerequisites on Ansible controller.
+
[source, cli]
ansible-playbook -i hosts requirements.yml
ansible-galaxy collection install -r collections/requirements.yml --force

. Execute pre-migration tasks against on-prem server.
+
[source, cli]
ansible-playbook -i hosts ora_pdb_relocate.yml -u admin -k -K -t ora_pdb_relo_onprem
+

[NOTE]
Admin user is management user on on-premises Oracle server host with sudo privileges and is authenticated using password.

. Execute Oracle PDB relocation from on-premises to target Azure Oracle host.
+
[source, cli]
ansible-playbook -i hosts ora_pdb_relocate.yml -u azureuser --private-key db1.pem -t ora_pdb_relo_primary

[NOTE]

Ansible controller can be located either on-premises or Azure cloud. The controller needs connectivity to on-premises Oracle server host and Azure Oracle VM host. The Oracle database port such as 1521 is open between on-premises Oracle server host and Azure Oracle VM host.

== Additional Oracle database migration options consideration

Please refer to Microsoft documentation for additional migration options: link:https://learn.microsoft.com/en-us/azure/architecture/example-scenario/oracle-migrate/oracle-migration-overview[Oracle database migration decision process^]
