---
sidebar: sidebar
permalink: databases/azure_ora_nfile_usecase.html
summary: This best practice guide provides details of a solution for deploying and protecting Oracle database on Azure NetApp file storage and Azure VM.
keywords: database, Oracle, Azure NetApp files, Azure
---

= Oracle Database Deployment and Protection on Azure NetApp Files Best Practices
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

Allen Cao, Niyaz Mohamed, Jeffrey Steiner, NetApp

Many mission-critical enterprise Oracle databases are still hosted on-premises, and many enterprises are looking to migrate these Oracle databases to a public cloud. Often, these Oracle databases are application centric and thus require user-specific configurations, a capability that is missing from many database-as-a-service public-cloud offerings. Therefore, the current database landscape calls for a public-cloud-based Oracle database solution built from a high-performance, scalable compute and storage service that can accommodate unique requirements. Azure virtual machine compute instances and the Azure NetApp Files storage service might be the missing pieces of this puzzle that you can leverage to build and migrate your mission critical Oracle database workloads to a public cloud.

Azure virtual machines are one of several types of on-demand, scalable computing resources that Azure offers. Typically, you choose a virtual machine when you need more control over the computing environment than the other choices offer. Azure virtual machines offer a quick and easy way to create a computer with specific configurations required to run your Oracle database, whether it is for compute or memory intensive workload. virtual machines in an Azure virtual network can easily be connected to your organization’s network such as via a secured VPN tunnel.

Azure NetApp Files is a fully managed Microsoft service that will take your database workload to the cloud faster and more securely than ever before. Enterprise databases like Oracle are critical to your success. Ensure your data and business processes remain safe and reliable in the cloud is paramount. Azure NetApp Files is built for simplicity, performance, and compliance. You gain a better understanding of your infrastructure, achieve high performance and reliability requirements, and protect and optimize your services. With Azure NetApp file, you can unlock the full capabilities of Azure without extra risk, cost, or time and trust the only enterprise file service native to Azure.

The goal of this documentation is to provide step-by-step processes, procedures, and best-practice guidance on how to deploy and configure an Oracle database with Azure virtual machine and Azure NetApp Files storage service, that delivers performance similar to an on-premises system. NetApp also provides an automation toolkit that automates most of the tasks that are required for the deployment, configuration, and management of your Oracle database workload in the Azure public cloud.

link:azure_ora_nfile_architecture.html[Next: Solutions architecture.]
