---
sidebar: sidebar
permalink: databases/cli_automation.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Step-by-step deployment procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-02-16 10:32:05.121542
//

[.lead]
This document details the deployment of Oracle 19c using the automation command line interface (cli).

== CLI deployment Oracle 19c Database

This section covers the steps required to prepare and deploy Oracle19c Database with the CLI. Make sure that you have reviewed the link:getting_started_requirements.html[Getting Started and Requirements section] and prepared your environment accordingly.

=== Download Oracle19c repo

. From your ansible controller, run the following command:
+
[source, cli]
git clone https://github.com/NetApp-Automation/na_oracle19c_deploy.git

. After downloading the repository, change directories to  na_oracle19c_deploy <cd na_oracle19c_deploy>.

=== Edit the hosts file

Complete the following before deployment:

. Edit your hosts file na_oracle19c_deploy directory.
. Under [ontap], change the IP address to your cluster management IP.
. Under the [oracle] group, add the oracle hosts names. The host name must be resolved to its IP address either through DNS or the hosts file, or it must be specified in the host.
. After you have completed these steps, save any changes.

The following example depicts a host file:

[source, shell]
----
#ONTAP Host

[ontap]

"10.61.184.183"

#Oracle hosts

[oracle]

"rtpora01"

"rtpora02"
----

This example executes the playbook and deploys oracle 19c on two oracle DB servers concurrently. You can also test with just one DB server. In that case, you only need to configure one host variable file.

NOTE: The playbook executes the same way regardless of how many Oracle hosts and databases you deploy.

=== Edit the host_name.yml file under host_vars

Each Oracle host has its host variable file identified by its host name that contains host-specific variables. You can specify any name for your host. Edit and copy the `host_vars` from the Host VARS Config section and paste it into your desired `host_name.yml` file.

NOTE: The items in blue must be changed to match your environment.

include::../_include/host_vars.adoc[]

=== Edit the vars.yml file

The `vars.yml` file consolidates all environment-specific variables (ONTAP, Linux, or Oracle) for Oracle deployment.

- Edit and copy the variables from the VARS section and paste these variables into your `vars.yml` file.

include::../_include/vars.adoc[]

=== Run the playbook

After completing the required environment prerequisites and copying the variables into `vars.yml` and `your_host.yml`, you are now ready to deploy the playbooks.

NOTE: <username> must be changed to match your environment.

. Run the ONTAP playbook by passing the correct tags and ONTAP cluster username. Fill the password for ONTAP cluster, and vsadmin when prompted.
+
[source, cli]
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config -e @vars/vars.yml

. Run the Linux playbook to execute Linux portion of deployment. Input for admin ssh password as well as sudo password.
+
[source, cli]
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config -e @vars/vars.yml

. Run the Oracle playbook to execute Oracle portion of deployment. Input for admin ssh password as well as sudo password.
+
[source, cli]
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config -e @vars/vars.yml

=== Deploy Additional Database on Same Oracle Host

The Oracle portion of the playbook creates a single Oracle container database on an Oracle server per execution. To create additional container database on the same server, complete the following steps:

. Revise the host_vars variables.
.. Go back to step 3 - Edit the `host_name.yml` file under `host_vars`.
.. Change the Oracle SID to a different naming string.
.. Change the listener port to different number.
.. Change the EM Express port to a different number if you have installed EM Express.
.. Copy and paste the revised host variables to the Oracle host variable file under `host_vars`.
. Execute the playbook with the `oracle_config` tag as shown above in <<Run the playbook>>.

=== Validate Oracle installation

include::../_include/validation.adoc[]
