---
sidebar: sidebar
permalink: databases/db_protection_overview.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
== Automated Data Protection for Oracle Databases

Organizations are automating their environments to gain efficiencies, accelerate deployments, and reduce manual effort. Configuration management tools like Ansible are being used to streamline enterprise database operations. In this solution, we demonstrate how you can use Ansible to automate the data protection of Oracle with NetApp ONTAP. By enabling storage administrators, systems administrators, and DBAs to consistently and rapidly setup data replication to an offsite data center or to public cloud, you achieve the following benefits:

* Eliminate design complexities and human errors, and implement a repeatable consistent deployment and best practices
* Decrease time for configuration of Intercluster replication, CVO instantiation, and recovery of Oracle databases
* Increase database administrators, systems and storage administrators productivity
* Provides database recovery workflow for ease of testing a DR scenario.

NetApp provides customers with validated Ansible modules and roles to accelerate deployment, configuration, and lifecycle management of your Oracle database environment. This solution provides instruction and Ansible playbook code, to help you:

=== On Prem to on prem replication

* Create intercluster lifs on source and destination
* Establish cluster and vserver peering
* Create and initialize SnapMirror of Oracle volumes
* Create a replication schedule through AWX/Tower for Oracle binaries, databases, and logs
* Restore Oracle DB on the destination, and bring database online

=== On Prem to CVO in AWS

* Create AWS connector
* Create CVO instance in AWS
* Add On-Prem cluster to Cloud Manager
* Create intercluster lifs on source
* Establish cluster and vserver peering
* Create and initialize SnapMirror of Oracle volumes
* Create a replication schedule through AWX/Tower for Oracle binaries, databases, and logs
* Restore Oracle DB on the destination, and bring database online

For more details or to begin, please see the overview videos below.

=== AWX/Tower Deployments

* Part 1: TBD

video::

* Part 2: TBD

video::

After you are ready, click link:db_protection_getting_started.html[here for getting started with the solution].
