---
sidebar: sidebar
permalink: databases/hybrid_dbops_snapcenter_prerequisite.html
summary: Certain prerequisites must be configured both on-premises and in the cloud before the execution of hybrid cloud database workloads. The following section provides a high-level summary of this process, and the following links provide further information about necessary system configuration.
keywords: workflow, prerequisites, licensing, networking, security
---

= Prerequisites configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

link:hybrid_dbops_snapcenter_requirements.html[Previous: Solutions requirements.]

[.lead]
Certain prerequisites must be configured both on-premises and in the cloud before the execution of hybrid cloud database workloads. The following section provides a high-level summary of this process, and the following links provide further information about necessary system configuration.

== On premises

* SnapCenter installation and configuration
* On-premises database server storage configuration
* Licensing requirements
* Networking and security
* Automation

== Public cloud

* A NetApp Cloud Central login
* Network access from a web browser to several endpoints
* A network location for a connector
* Cloud provider permissions
* Networking for individual services

Important considerations:

. Where to deploy the Cloud Manager Connector?
. Cloud Volume ONTAP sizing and architecture
. Single node or high availability?

The following links provide further details:

link:hybrid_dbops_snapcenter_prereq_onprem.html[On Premises]

link:hybrid_dbops_snapcenter_prereq_cloud.html[Public Cloud]

link:hybrid_dbops_snapcenter_prereq_onprem.html[Next: Prerequisites on-premises.]
