---
sidebar: sidebar
permalink: databases/hybrid_dbops_snapcenter_getting_started.html
summary: This section provides a summary of the tasks that must be completed to meet the prerequisite requirements as outlined in previous section. The following section provide a high level tasks list for both on-premises and public cloud operations. The detailed processes and procedures can be accessed by clicking on the relevant links.
keywords: introduction, workflow
---

= Getting started overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

link:hybrid_dbops_snapcenter_prereq_cloud.html[Previous: Prerequisites for the public cloud.]

[.lead]
This section provides a summary of the tasks that must be completed to meet the prerequisite requirements as outlined in previous section. The following section provide a high level tasks list for both on-premises and public cloud operations. The detailed processes and procedures can be accessed by clicking on the relevant links.

== On-premises

* Setup database admin user in SnapCenter

* SnapCenter plugin installation prerequisites

* SnapCenter host plugin installation

* DB resource discovery

* Setup storage cluster peering and DB volume replication

* Add CVO database storage SVM to SnapCenter

* Setup database backup policy in SnapCenter

* Implement backup policy to protect database

* Validate backup

== AWS public cloud

* Pre-flight check

* Steps to deploy Cloud Manager and Cloud Volumes ONTAP in AWS

* Deploy EC2 compute instance for database workload

Click the following links for details:

link:hybrid_dbops_snapcenter_getting_started_onprem.html[On Premises], link:hybrid_dbops_snapcenter_getting_started_aws.html[Public Cloud - AWS]
