---
sidebar: sidebar
permalink: databases/hybrid_dbops_snapcenter_requirements.html
summary: This solution is designed in a hybrid cloud setting to support on-premises production databases that can burst to all of the popular public clouds for dev/test and disaster recovery operations.
keywords: requirements, virtualized, bare metal, versions, automation
---

= SnapCenter Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

link:hybrid_dbops_snapcenter_architecture.html[Previous: Solutions architecture.]

[.lead]
This solution is designed in a hybrid cloud setting to support on-premises production databases that can burst to all of the popular public clouds for dev/test and disaster recovery operations.

This solution supports all databases that are currently supported by SnapCenter, although only Oracle and SQL Server databases are demonstrated here. This solution is validated with virtualized database workloads, although bare-metal workloads are also supported.

We assume that production database servers are hosted on-premises with DB volumes presented to DB hosts from a ONTAP storage cluster. SnapCenter software is installed on-premises for database backup and data replication to the cloud. An Ansible controller is recommended but not required for database deployment automation or OS kernel and DB configuration syncing with a standby DR instance or dev/test instances in the public cloud.

== Requirements

[width=100%, cols="3, 9",grid="all"]
|===
|Environment | Requirements

.7+| *On-premises* |
Any databases and versions supported by SnapCenter
| SnapCenter v4.4 or higher
| Ansible v2.09 or higher
| ONTAP cluster 9.x
| Intercluster LIFs configured
| Connectivity from on-premises to a cloud VPC (VPN, interconnect, and so on)
| Networking ports open
- ssh 22
- tcp 8145, 8146, 10000, 11104, 11105
.3+| *Cloud - AWS* |
https://docs.netapp.com/us-en/occm/task_creating_connectors_aws.html[Cloud Manager Connector^]
| https://docs.netapp.com/us-en/occm/task_getting_started_aws.html[Cloud Volumes ONTAP^]
| Matching DB OS EC2 instances to On-prem
.3+| *Cloud - Azure* |
https://docs.netapp.com/us-en/occm/task_creating_connectors_azure.html[Cloud Manager Connector^]
| https://docs.netapp.com/us-en/occm/task_getting_started_azure.html[Cloud Volumes ONTAP^]
| Matching DB OS Azure Virtual Machines to On-prem
.3+| *Cloud - GCP* |
https://docs.netapp.com/us-en/occm/task_creating_connectors_gcp.html[Cloud Manager Connector^]
| https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html[Cloud Volumes ONTAP^]
| Matching DB OS Google Compute Engine instances to on-premises
|===

link:hybrid_dbops_snapcenter_prerequisite.html[Next: Prerequisites configuration.]
