---
sidebar: sidebar
permalink: databases/marketing_overview.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/



== Automated Deployment of Oracle19c for ONTAP on NFS

Organizations are automating their environments to gain efficiencies, accelerate deployments, and reduce manual effort. Configuration management tools like Ansible are being used to streamline enterprise database operations. In this solution, we demonstrate how you can use Ansible to automate the provisioning and configuration of Oracle 19c with NetApp ONTAP. By enabling storage administrators, systems administrators, and DBAs to consistently and rapidly deploy new storage, configure database servers, and install Oracle 19c software, you achieve the following benefits:

* Eliminate design complexities and human errors, and implement a repeatable consistent deployment and best practices
* Decrease time for provisioning of storage, configuration of DB hosts, and Oracle installation
* Increase database administrators, systems and storage administrators productivity
* Enable scaling of storage and databases with ease

NetApp provides customers with validated Ansible modules and roles to accelerate deployment, configuration, and lifecycle management of your Oracle database environment. This solution provides instruction and Ansible playbook code, to help you:

* Create and configure ONTAP NFS storage for Oracle Database
* Install Oracle 19c on RedHat Enterprise Linux 7/8 or Oracle Linux 7/8
* Configure Oracle 19c on ONTAP NFS storage

For more details or to begin, please see the overview videos below.

=== AWX/Tower Deployments

* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d844a9c3-4eb3-4512-bf21-b01200f09f66[Part 1: Getting Started, Requirements, Automation Details and Initial AWX/Tower Configuration]

* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6da1b960-e1c9-4950-b750-b01200f0bdfa[Part 2: Variables and Running the Playbook]

=== CLI Deployment

* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=373e7f2a-c101-4292-a3e4-b01200f0d078[Part 1: Getting Started, Requirements, Automation Details and Ansible Control Host Setup]

* link:https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d58ebdb0-8bac-4ef9-b4d1-b01200f95047[Part 2: Variables and Running the Playbook]
