---
sidebar: sidebar
permalink: databases/tr-4722.html
keywords: 
summary: 
---

= TR-4722: MySQL Database on NetApp ONTAP Best Practices
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

Anup Bharti, Manohar Kulkarni, Jeffrey Steiner NetApp

[.lead]
MySQL and its variants, including MariaDB and Percona, are widely used for many enterprise applications. These applications range from global social networking sites and massive e-commerce systems to SMB hosting systems containing thousands of database instances. This document describes the configuration requirements and provides guidance on tuning and storage configuration for deploying MySQL on NetApp® ONTAP® data management software. To determine whether the environment,configurations, and versions specified in this report support your environment, consult the Interoperability Matrix Tool (IMT).


link:https://www.netapp.com/pdf.html?item=/media/16423-tr-4722pdf.pdf[TR-4722: MySQL Database on NetApp ONTAP Best Practices^]