---
sidebar: sidebar
permalink: ehc/dro/azure-dro-overview.html
keywords: NetApp Solutions, hybrid, multicloud, multi cloud, hyperscalers, vmware, disaster recovery orchestrator, DRO
summary:
---

= TR-4955: Disaster Recovery with Azure NetApp Files (ANF) and Azure VMware Service (AVS)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

[.lead]
Niyaz Mohamed, NetApp

== Overview

== Getting started  

== DRO installation

== DRO configuration

== Benefits

* Use of the efficient and resilient SnapMirror replication.
* Recovery to any available point in time with Snapshot copy retention.
* Full automation of all required steps to recover hundreds to thousands of VMs from the storage, compute, network, and application validation steps.
* Workload recovery with ONTAP FlexClone technology using a method that doesn't change the replicated volume.
** Avoids risk of data corruption for volumes or Snapshot copies.
** Avoids replication interruptions during DR test workflows.
** Potential use of DR data with cloud computing resources for workflows beyond DR such as DevTest, security testing, patch or upgrade testing, and remediation testing.
* CPU and RAM optimization to help lower cloud costs by allowing recovery to smaller compute clusters.
