---
sidebar: sidebar
permalink: ehc/ncvs/ncvs-gc-overview.html
keywords: 4918, tr4918, overview, introduction, scope, audience, abbreviation, definition
summary: Security, particularly in the cloud where infrastructure is outside of the control of storage administrators, is paramount to trusting your data to service offerings provided by cloud providers. This document is an overview of the security offerings that NetApp Cloud Volumes Service provides in Google Cloud.
---

= TR-4918: Security overview - NetApp Cloud Volumes Service in Google Cloud

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-09 14:20:40.881406
//

Oliver Krause, Justin Parisi, NetApp

[.lead]
== Document scope

Security, particularly in the cloud where infrastructure is outside of the control of storage administrators, is paramount to trusting your data to service offerings provided by cloud providers. This document is an overview of the security offerings that NetApp https://cloud.netapp.com/cloud-volumes-service-for-gcp[Cloud Volumes Service provides in Google Cloud^].

== Intended audience

This document’s intended audience includes, but is not limited to, the following roles:

* Cloud providers
* Storage administrators
* Storage architects
* Field resources
* Business decision makers

If you have questions about the content of this technical report, see the section link:ncvs-gc-additional-information.html#contact-us[“Contact us.”]

|===
|Abbreviation |Definition

|CVS-SW
|Cloud Volumes Service, Service Type CVS
|CVS-Performance
|Cloud Volume Service, Service Type CVS-Performance
|PSA
|
|===

link:ncvs-gc-how-cloud-volumes-service-in-google-cloud-secures-your-data.html[Next: How Cloud Volumes Service in Google Cloud secures your data.]
