---
sidebar: sidebar
permalink: ehc/ncvs/ncvs-gc-data-encryption-at-rest.html
keywords: aes-256 encryption, cmek
summary: All volumes in Cloud Volumes Service are encrypted-at-rest using AES-256 encryption, which means all user data written to media is encrypted and can only be decrypted with a per-volume key.
---

= Data encryption at rest
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-09 14:20:40.961444
//

link:ncvs-gc-data-encryption-in-transit.html[Previous: Data encryption in transit.]

[.lead]
All volumes in Cloud Volumes Service are encrypted-at-rest using AES-256 encryption, which means all user data written to media is encrypted and can only be decrypted with a per-volume key.

* For CVS-SW, Google-generated keys are used.
* For CVS-Performance, the per-volume keys are stored in a key manager built into the Cloud Volumes Service.

Starting in November 2021, preview customer-managed encryption keys (CMEK) functionality was made available. This enables you to encrypt the per-volume keys with a per-project, per-region master key that is hosted in https://cloud.google.com/kms/docs[Google Key Management Service (KMS).^] KMS enables you to attach external key managers.

For information about configuring KMS for CVS-Performance, see https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US[Setting up customer-managed encryption keys^].

link:ncvs-gc-firewall.html[Next: Firewall.]
