---
sidebar: sidebar
permalink: ehc/ncvs/ncvs-gc-additional-information.html
keywords:
summary:
---

= Additional information, version history, and contact information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-09 14:20:41.109511
//

link:ncvs-gc-service-operation.html[Previous: Service operation.]

[.lead]
To learn more about the information that is described in this document, review the following documents and/or websites:

* Google Cloud documentation for Cloud Volumes Service
+
https://cloud.google.com/architecture/partners/netapp-cloud-volumes/[https://cloud.google.com/architecture/partners/netapp-cloud-volumes/^]

* Google private service access
+
https://cloud.google.com/vpc/docs/private-services-access?hl=en_US[https://cloud.google.com/vpc/docs/private-services-access?hl=en_US^]

* NetApp product documentation
+
https://www.netapp.com/support-and-training/documentation/[https://www.netapp.com/support-and-training/documentation/^]

* Cryptographic Validation Module Program—NetApp CryptoMod
+
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144[https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144^]

* The NetApp Solution for Ransomware
+
https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745[https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745^]

* TR-4616: NFS Kerberos in ONTAP
+
https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf[https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf^]

== Version history

|===
|Version |Date |Document version history

|Version 1.0
|May 2022
|Initial release.
|===

== Contact us

Let us know how we can improve this technical report.

Contact us at mailto:doccomments@netapp.com[doccomments@netapp.com^]. Include TECHNICAL REPORT 4918 in the subject line.
