---
sidebar: sidebar
permalink: ehc/ncvs/ncvs-gc-data-encryption-in-transit.html
keywords: google cloud network, nas protocols, smb encryption, NFSv4.1 Kerberos
summary: Data in transit can be encrypted at the NAS protocol layer, and the Google Cloud network itself is encrypted, as described in the following sections.
---

= Data encryption in transit
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-09 14:20:40.950308
//

link:ncvs-gc-data-plane-architecture.html[Previous: Data plane architecture.]

[.lead]
Data in transit can be encrypted at the NAS protocol layer, and the Google Cloud network itself is encrypted, as described in the following sections.

== Google Cloud network

Google Cloud encrypts traffic on the network level as described in https://cloud.google.com/security/encryption-in-transit[Encryption in transit^] in the Google documentation.  As mentioned in the section “Cloud Volumes Services architecture,” Cloud Volumes Service is delivered out of a NetApp-controlled PSA producer project.

In case of CVS-SW, the producer tenant runs Google VMs to provide the service. Traffic between user VMs and Cloud Volumes Service VMs is encrypted automatically by Google.

Although the data path for CVS-Performance isn’t fully encrypted on the network layer, NetApp and Google use a combination https://1.ieee802.org/security/802-1ae/[of IEEE 802.1AE encryption (MACSec)^], https://datatracker.ietf.org/doc/html/rfc2003[encapsulation^] (data encryption), and physically restricted networks to protect data in transit between the Cloud Volumes Service CVS-Performance service type and Google Cloud.

== NAS protocols

NFS and SMB NAS protocols provide optional transport encryption at the protocol layer.

=== SMB encryption

https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-security[SMB encryption^] provides end-to-end encryption of SMB data and protects data from eavesdropping occurrences on untrusted networks. You can enable encryption for both the client/server data connection (only available to SMB3.x capable clients) and the server/domain controller authentication.

When SMB encryption is enabled, clients that do not support encryption cannot access the share.

Cloud Volumes Service supports RC4-HMAC, AES-128-CTS-HMAC-SHA1, and AES-256-CTS-HMAC-SHA1 security ciphers for SMB encryption. SMB negotiates to the highest supported encryption type by the server.

=== NFSv4.1 Kerberos

For NFSv4.1, CVS-Performance offers Kerberos authentication as described in https://datatracker.ietf.org/doc/html/rfc7530[RFC7530^]. You can enable Kerberos on a per-volume basis.

The current strongest available encryption type for Kerberos is AES-256-CTS-HMAC-SHA1. NetApp Cloud Volumes Service supports AES-256-CTS-HMAC-SHA1, AES-128-CTS-HMAC-SHA1, DES3,  and DES for NFS. It also supports ARCFOUR-HMAC (RC4) for CIFS/SMB traffic, but not for NFS.

Kerberos provides three different security levels for NFS mounts that offer choices for how strong the Kerberos security should be.

As per RedHat’s https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/storage_administration_guide/s1-nfs-client-config-options[Common Mount Options^] documentation:

....
sec=krb5 uses Kerberos V5 instead of local UNIX UIDs and GIDs to authenticate users.
sec=krb5i uses Kerberos V5 for user authentication and performs integrity checking of NFS operations using secure checksums to prevent data tampering.
sec=krb5p uses Kerberos V5 for user authentication, integrity checking, and encrypts NFS traffic to prevent traffic sniffing. This is the most secure setting, but it also involves the most performance overhead.
....

As a general rule, the more the Kerberos security level has to do, the worse the performance is, as the client and server spend time encrypting and decrypting NFS operations for each packet sent. Many clients and NFS servers provide support for AES-NI offloading to the CPUs for a better overall experience, but the performance impact of Kerberos 5p (full end-to-end encryption) is significantly greater than the impact of Kerberos 5 (user authentication).

The following table shows differences in what each level does for security and performance.

|===
|Security level |Security |Performance

|NFSv3—sys
a|* Least secure; plain text with numeric user IDs/group IDs
* Able to view UID, GID, client IP addresses, export paths, file names, permissions in packet captures
a|* Best for most cases
|NFSv4.x—sys
a|* More secure than NFSv3 (client IDs, name string/domain string matching) but still plain text
* Able to view UID, GID, client IP addresses, name strings, domain IDs, export paths, file names, permissions in packet captures
a|* Good for sequential workloads (such as VMs, databases, large files)
* Bad with high file count/high metadata (30-50% worse)
|NFS—krb5
a|* Kerberos encryption for credentials in every NFS packet—wraps UID/GID of users/groups in RPC calls in GSS wrapper
* User requesting access to mount needs a valid Kerberos ticket (either through username/password or manual key tab exchange); ticket expires after a specified time period and user must reauthenticate for access
* No encryption for NFS operations or ancillary protocols like mount/portmapper/nlm (can see export paths, IP addresses, file handles, permissions, file names, atime/mtime in packet captures)
a|* Best in most cases for Kerberos; worse than AUTH_SYS
|NFS—krb5i
a|* Kerberos encryption for credentials in every NFS packet—wraps UID/GID of users/groups in RPC calls in GSS wrapper
* User requesting access to mount needs a valid Kerberos ticket (either via username/password or manual key tab exchange); ticket expires after a specified time period and user must reauthenticate for access
* No encryption for NFS operations or ancillary protocols like mount/portmapper/nlm (can see export paths, IP addresses, file handles, permissions, file names, atime/mtime in packet captures)
* Kerberos GSS checksum is added to every packet to ensure nothing intercepts the packets. If checksums match, conversation is allowed.
a|* Better than krb5p because the NFS payload is not encrypted; only added overhead compared to krb5 is the integrity checksum. Performance of krb5i won’t be much worse than krb5 but will see some degradation.
|NFS – krb5p
a|* Kerberos encryption for credentials in every NFS packet—wraps UID/GID of users/groups in RPC calls in GSS wrapper
* User requesting access to mount needs a valid Kerberos ticket (either via username/password or manual keytab exchange); ticket expires after specified time period and user must reauthenticate for access
* All of the NFS packet payloads are encrypted with the GSS wrapper (cannot see file handles, permissions, file names, atime/mtime in packet captures).
* Includes integrity check.
* NFS operation type is visible (FSINFO, ACCESS, GETATTR, and so on).
* Ancillary protocols (mount, portmap, nlm, and so on) are not encrypted - (can see export paths, IP addresses)
a|* Worst performance of the security levels; krb5p has to encrypt/decrypt more.
* Better performance than krb5p with NFSv4.x for high file count workloads.
|===

In Cloud Volumes Service, a configured Active Directory server is used as Kerberos server and LDAP server (to lookup user identities from an RFC2307 compatible schema). No other Kerberos or LDAP servers are supported. NetApp highly recommends that you use LDAP for identity management in Cloud Volumes Service. For information on how NFS Kerberos is shown in packet captures, see the section link:ncvs-gc-cloud-volumes-service-architecture.html#packet-sniffing/trace-considerations[“Packet sniffing/trace considerations.”]

link:ncvs-gc-data-encryption-at-rest.html[Next: Data encryption at rest.]
