---
sidebar: sidebar
permalink: ehc/ncvs/ncvs-gc-firewall.html
keywords: tcp, nfs, smb share, kerberos, active directory, dns
summary: Cloud Volumes Service exposes multiple TCP ports to serve NFS and SMB shares.
---

= Firewall
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-09 14:20:40.965446
//

link:ncvs-gc-data-encryption-at-rest.html[Previous: Data encryption at rest.]

[.lead]
Cloud Volumes Service exposes multiple TCP ports to serve NFS and SMB shares:

* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US[Ports required for NFS access^]
* https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US[Ports required for SMB access^]

Additionally, SMB, NFS with LDAP including Kerberos, and dual-protocol configurations require access to a Windows Active Directory domain. Active Directory connections must be https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes?hl=en_US[configured^] on a per-region basis. Active Directory Domain controllers (DC) are identified by using https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04[DNS-based DC discovery^] using the specified DNS servers. Any of the DCs returned are used. The list of eligible DCs can be limited by specifying an Active Directory site.

Cloud Volumes Service reaches out with IP addresses from the CIDR range allocated with the `gcloud compute address` command while https://cloud.google.com/architecture/partners/netapp-cloud-volumes/setting-up-private-services-access?hl=en_US[on-boarding the Cloud Volumes Service^]. You can use this CIDR as source addresses to configure inbound firewalls to your Active Directory domain controllers.

Active Directory Domain Controllers must https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US[expose ports to the Cloud Volumes Service CIDRs as mentioned here^].

link:ncvs-gc-nas-protocols_overview.html[Next: NAS protocols overview.]
