---
sidebar: sidebar
permalink: ehc/ncvs/ncvs-gc-nas-protocols_overview.html
keywords: nas, nfs, smb, cifs
summary: NAS protocols include NFS (v3 and v4.1) and SMB/CIFS (2.x and 3.x). These protocols are how CVS allows shared access to data across multiple NAS clients. In addition, Cloud Volumes Service can provide access to NFS and SMB/CIFS clients simultaneously (dual-protocol) while honoring all of the identity and permission settings on files and folders in the NAS shares.
---

= NAS protocols overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-09 14:20:40.972109
//

link:ncvs-gc-firewall.html[Previous: Firewall.]

[.lead]
NAS protocols include NFS (v3 and v4.1) and SMB/CIFS (2.x and 3.x). These protocols are how CVS allows shared access to data across multiple NAS clients. In addition, Cloud Volumes Service can provide access to NFS and SMB/CIFS clients simultaneously (dual-protocol) while honoring all of the identity and permission settings on files and folders in the NAS shares. To maintain the highest possible data transfer security, Cloud Volumes Service supports protocol encryption in flight using SMB encryption and NFS Kerberos 5p.

[NOTE]
Dual-protocol is available with CVS-Performance only.

link:ncvs-gc-basics-of-nas-protocols.html[Next: Basics of NAS protocols.]
