---
sidebar: sidebar
permalink: ehc/azure/azure-native-overview.html
keywords:
summary:
---

= Overview of ANF Datastore Solutions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-06-09 12:19:16.416036
//

[.lead]
Every successful organization is on a path of transformation and modernization. As part of this process, companies typically use their existing VMware investments while leveraging cloud benefits and exploring how to make migration, burst, extend,  and disaster recovery processes as seamless as possible.  Customers migrating to the cloud must evaluate the issues of elasticity and burst, data center exit, data center consolidation, end- of- life scenarios, mergers, acquisitions,  and so on.  The approach adopted by each organization can vary based on their respective business priorities. When choosing cloud-based operations, selecting a low- cost model with appropriate performance and minimal hindrance is a critical goal. Along with choosing the right platform, storage and workflow orchestration is particularly important to unleash the power of cloud deployment and elasticity.

== Use Cases

Although the Azure VMware solution delivers unique hybrid capabilities to a customer, limited native storage options have restricted its usefulness for organizations with storage-heavy workloads. Because storage is directly tied to hosts, the only way to scale storage is to add more hosts, which can increase costs by 35-40% or more for storage intensive workloads. These workloads need additional storage, not additional horsepower, but that means paying for additional hosts.

Let’s consider the following scenario;  a customer requires six hosts for horsepower (vCPU/vMem),  but they also have a substantial requirement for storage. Based on their assessment,  they require 12 hosts to meet storage requirements. This increases the overall TCO because they must buy all that additional horsepower when all they really need is more storage. This is applicable for any use case,  including migration, disaster recovery, bursting, dev/test,  and so on.

Another common use case for Azure VMware Solution is disaster recovery (DR). Most organizations do not have a fool- proof DR strategy,  or they might struggle to justify running a ghost datacenter just for DR.  Administrators might explore zero- footprint DR options with a pilot- light cluster or an on-demand cluster. They could then scale the storage without adding additional hosts,  potentially an attractive option.

So, to summarize, the use cases can be classified in two ways:

* Scaling storage capacity using ANF datastores
* Using ANF datastores as a disaster recovery target for a cost- optimized recovery workflow from on-premises or within Azure regions between the software-defined datacenters (SDDCs).This guide provides insight into using Azure NetApp Files to provide optimized storage for datastores (currently in public preview) along with best-in-class data protection and DR capabilities in an Azure VMware solution, which enables you to offload storage capacity from vSAN storage.

NOTE: The Azure NetApp Files datastore capability is currently in public preview. Contact NetApp or Microsoft solution architects in your region for additional information.

== VMware Cloud options in Azure

=== Azure VMware Solution

The Azure VMware Solution (AVS) is a hybrid cloud service that provides fully functioning VMware SDDCs within a Microsoft Azure public cloud. AVS is a first-party solution fully managed and supported by Microsoft and verified by VMware that uses Azure infrastructure. Therefore, customers get VMware ESXi for compute virtualization, vSAN for hyper-converged storage, and NSX for networking and security, all while taking advantage of Microsoft Azure's global presence, class-leading data center facilities,  and proximity to the rich ecosystem of native Azure services and solutions.  A combination of Azure VMware Solution SDDC and Azure NetApp Files provides the best performance with minimal network latency.

Regardless of the cloud used, when a VMware SDDC is deployed, the initial cluster includes the following components:

* VMware ESXi hosts for compute virtualization with a vCenter server appliance for management.
* VMware vSAN hyper-converged storage incorporating the physical storage assets of each ESXi host.
* VMware NSX for virtual networking and security with an NSX Manager cluster for management.

== Conclusion

Whether you are targeting all-cloud or hybrid cloud, Azure NetApp files provide excellent options to deploy and manage the application workloads along with file services while reducing the TCO by making the data requirements seamless to the application layer.  Whatever the use case, choose Azure VMware Solution along with Azure NetApp Files for rapid realization of cloud benefits, consistent infrastructure, and operations across on-premises and multiple clouds, bi-directional portability of workloads, and enterprise-grade capacity and performance. It is the same familiar process and procedures used to connect the storage. Remember, it is just the position of the data that changed along with new names;  the tools and processes all remain the same,  and Azure NetApp Files helps in optimizing the overall deployment.

== Takeaways

The key points of this document include:

* You can now use Azure NetApp Files as a datastore on AVS SDDC.
* Boost the application response times and deliver higher availability to provide access workload data when and where it is needed.
* Simplify the overall complexity of the vSAN storage with simple and instant resizing capabilities.
* Guaranteed performance for mission-critical workloads using dynamic reshaping capabilities.
* If Azure VMware Solution Cloud is the destination, Azure NetApp Files is the right storage solution for optimized deployment.

== Where to find additional information

To learn more about the information described in this document, refer to the following website links:

* Azure VMware Solution documentation
+
https://docs.microsoft.com/en-us/azure/azure-vmware/[https://docs.microsoft.com/en-us/azure/azure-vmware/^]

* Azure NetApp Files documentation
+
https://docs.microsoft.com/en-us/azure/azure-netapp-files/[https://docs.microsoft.com/en-us/azure/azure-netapp-files/^]

* Integrate Azure NetApp Files with Azure VMware Solution
+
https://docs.microsoft.com/en-us/azure/azure-vmware/netapp-files-with-azure-vmware-solution[https://docs.microsoft.com/en-us/azure/azure-vmware/netapp-files-with-azure-vmware-solution^]
