---
sidebar: sidebar
permalink: ehc/aws/aws-guest-dr-technology.html
keywords: technology, vmware cloud foundation, vsphere, nsx, snapcenter, veeam, VMware Cloud on AWS, Amazon FSx
summary: This section provide an overview of the different technological components that power this solution.
---

= Technology
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-07-20 15:53:45.341601
//

link:aws-guest-dr-solution-overview.html[Previous: Solution overview.]

This solution includes innovative technologies from NetApp, VMware, Amazon Web Services (AWS), and Veeam.

== VMware

=== VMware Cloud Foundation

The VMware Cloud Foundation platform integrates multiple products offerings that enable administrators to provision logical infrastructures across a heterogenous environment. These infrastructures (known as domains) provide consistent operations across private and public clouds. Accompanying the Cloud Foundation software is a bill of materials that identifies prevalidated and qualified components to reduce risk for customers and ease deployment.

The components of the Cloud Foundation BoM include the following:

* Cloud Builder
* SDDC Manager
* VMware vCenter Server Appliance
* VMware ESXi
* VMware NSX
* vRealize Automation
* vRealize Suite Lifecycle Manager
* vRealize Log Insight

For more information on the VMware Cloud Foundation, see the https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html[VMware Cloud Foundation documentation^].

=== VMware vSphere

VMware vSphere is a virtualization platform that transforms physical resources into pools of compute, network, and storage that can be used to satisfy customers’ workload and application requirements. The main components of VMware vSphere include the following:

* *ESXi.* This VMware hypervisor enables the abstraction of compute processors, memory, network, and other resources and makes them available to virtual machines and container workloads.
* *vCenter.* VMware vCenter creates a central management experience for interacting with compute resources, networking, and storage as part of your virtual infrastructure.

Customers realize the full potential of their vSphere environment by using NetApp ONTAP with deep product integration, robust support, and powerful features and storage efficiencies to create a robust hybrid multi-cloud.

For more information about VMware vSphere, follow https://docs.vmware.com/en/VMware-vSphere/index.html[this link^].

For more information about NetApp solutions with VMware, follow https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html[this link^].

=== VMware NSX

Commonly referred to as a network hypervisor, VMware NSX employs a software-defined model to connect virtualized workloads. VMware NSX is ubiquitous on premises and in VMware Cloud on AWS where it powers network virtualization and security for customer applications and workloads.

For more information on VMware NSX, follow https://docs.vmware.com/en/VMware-NSX-T-Data-Center/index.html[this link^].

== NetApp

=== NetApp ONTAP

NetApp ONTAP software has been a leading storage solution for VMware vSphere environments for almost two decades and continues to add innovative capabilities to simplify management while reducing costs. Using ONTAP together with vSphere is a great combination that lets you reduce host hardware and VMware software expenses. You can also protect your data at lower cost with consistent high performance while taking advantage of native storage efficiencies.

For more information on NetApp ONTAP, follow https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html[this link^].

=== NetApp ONTAP tools for VMware

ONTAP tools for VMware combine multiple plugins into a single virtual appliance that provides end-to-end lifecycle management for virtual machines in VMware environments that use NetApp storage systems. ONTAP tools for VMware includes the following:

* *Virtual Storage Console (VSC).* Performs comprehensive administrative tasks for VMs and datastores using NetApp storage.
* *VASA Provider for ONTAP.* Enables Storage Policy- Based Management (SPBM) with VMware virtual volumes (vVols) and NetApp storage.
* *Storage Replication Adapter (SRA)*. Recovers vCenter datastores and virtual machines in the event of a failure when coupled with VMware Site Recovery Manager (SRM).

ONTAP tools for VMware allows users to manage not only external storage but also integrate with vVols as well as VMware Site Recovery Manager. This makes it much easier to deploy and operate NetApp storage from within your vCenter environment.

For more information on NetApp ONTAP tools for VMware, follow https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html[this link^].

=== NetApp SnapCenter

NetApp SnapCenter software is an easy-to-use enterprise platform to securely coordinate and manage data protection across applications, databases, and file systems. SnapCenter simplifies backup, restore, and clone lifecycle management by offloading these tasks to application owners without sacrificing the ability to oversee and regulate activity on the storage systems. By leveraging storage-based data management, SnapCenter increases performance and availability as well as reducing testing and development times.

The SnapCenter Plug-in for VMware vSphere supports crash-consistent and VM-consistent backup and restore operations for virtual machines (VMs), datastores, and virtual machine disks (VMDKs). It also supports SnapCenter application-specific plug-ins to protect application-consistent backup and restore operations for virtualized databases and file systems.

For more information on NetApp SnapCenter, follow https://docs.netapp.com/us-en/snapcenter/[this link^].

== Third-party data protection

=== Veeam Backup & Replication

Veeam Backup & Replication is a backup, recovery, and data management solution for cloud, virtual, and physical workloads. Veeam Backup & Replication has specialized integrations with NetApp Snapshot technology that further protect vSphere environments.

For more information on Veeam Backup & Replication, follow https://www.veeam.com/vm-backup-recovery-replication-software.html[this link^].

== Public cloud

=== AWS identity and access management

AWS environments contain a wide variety of products including compute, storage, database, network, analytics, and much more to help solve business challenges. Enterprises must be able to define who is authorized to access these products, services, and resources. It is equally important to determine under which conditions users are allowed to manipulate, change, or add configurations.

AWS Identity and Access Management (AIM) provides a secure control plane for managing access to AWS services and products. Properly configured users, access keys, and permissions allow for the deployment of VMware Cloud on AWS and Amazon FSx.

For more information on AIM, follow https://docs.aws.amazon.com/iam/index.html[this link^].

=== VMware Cloud on AWS

VMware Cloud on AWS brings VMware’s enterprise-class SDDC software to the AWS Cloud with optimized access to native AWS services. Powered by the VMware Cloud Foundation, VMware Cloud on AWS integrates VMware’s compute, storage, and network virtualization products (VMware vSphere, VMware vSAN, and VMware NSX) along with VMware vCenter Server management optimized to run on dedicated, elastic, bare-metal AWS infrastructure.

For more information on VMware Cloud on AWS, follow https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html[this link^].

=== Amazon FSx for NetApp ONTAP

Amazon FSx for NetApp ONTAP is a fully featured and fully managed ONTAP system available as a native AWS service. Built on NetApp ONTAP, it offers familiar features while offering the simplicity of a fully managed cloud service.

Amazon FSx for ONTAP offers multiprotocol support to a variety of compute types including VMware in the public cloud or on premises. Available for guest-connected use cases today and NFS datastores in tech preview, Amazon FSx for ONTAP allows enterprises to take advantage of familiar features from their on-premises environments and in the cloud.

For more information on Amazon FSx for NetApp ONTAP, follow this link.

link:aws-guest-dr-overview.html[Next: Overview - AWS guest-connected storage disaster recovery.]
