---
sidebar: sidebar
permalink: ehc/aws/aws-vmc.html
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr
summary:
---

= NetApp Capabilities for AWS VMC
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

[.lead]
Learn more about the capabilities that NetApp brings to the AWS VMware Cloud (VMC) - from NetApp as a guest connected storage device or a native datastore to migrating workflows, extending/bursting to the cloud, backup/restore and disaster recovery.

Jump to the section for the desired content by selecting from the following options:

* link:#config[VMware in the Hyperscalers Configuration]
* link:#datastore[NetApp Storage Options]
//* link:#solutions[NetApp / VMware Cloud Solutions]

[[config]]
== Configuring VMC in AWS
As with on-premises, planning a cloud based virtualization environment is critical for a successful production-ready environment for creating VMs and migration.

include::ehc/ehc-config-vmware.adoc[tags=aws-config;aws]

[[datastore]]
== NetApp Storage Options for VMC
NetApp storage can be utilized in several ways  - either as guess connected or as a native datastore - within AWS VMC.

Please visit link:ehc-support-configs.html[Supported NetApp Storage Options] for more information.

include::ehc/ehc-datastore.adoc[tags=aws-datastore;aws]

[[solutions]]
//== Solution Use Cases
//With NetApp and VMware cloud solutions, many use cases are simple to deploy in your AWS VMC.  The use cases include:
//
//* Extend / Burst
//* Data Center Maintenance
//* Migration
//* Backup / Restore
//* Disaster Recovery
//* Data Protection
//
//link:aws-solutions.html[Browse the NetApp solutions for AWS VMC]
