---
sidebar: sidebar
permalink: ehc/aws/aws-guest-dr-snapcenter-overview.html
keywords: overview, dr, snapcenter, data replication, snapmirror
summary: In this solution, SnapCenter provides application-consistent snapshots for SQL Server and Oracle application data. This configuration, together with SnapMirror technology, provides high-speed data replication between our on-premises AFF and FSx ONTAP cluster. Additionally, Veeam Backup & Replication provides backup and restore capabilities for our virtual machines.
---

= Overview - Disaster recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-07-20 15:53:45.436726
//

link:aws-guest-dr-cloud-backup-tools.html[Previous: Cloud Backup Tools.]

In this solution, SnapCenter provides application-consistent snapshots for SQL Server and Oracle application data. This configuration, together with SnapMirror technology, provides high-speed data replication between our on-premises AFF and FSx ONTAP cluster. Additionally, Veeam Backup & Replication provides backup and restore capabilities for our virtual machines.

In this section, we cover the configuration of SnapCenter, SnapMirror, and Veeam for both backup and restore.

The following sections cover configuration and the steps needed to complete a failover at the secondary site:

* Configure SnapMirror and retention schedules (secondary storage).
* Deploy and configure Windows SnapCenter server on-premises.
* Deploy and configure Veeam Backup & Replication server on-premises.
* Deploy and configure cloud backup tools, SnapCenter, and Veeam.
* SnapCenter database backup for disaster recovery.
* SnapCenter database restore at a secondary site.
* Restore application virtual machines using Veeam Backup & Replication.
* Restore SQL Server application data.
* Restore Oracle application data.

link:aws-guest-dr-configure-snapmirror.html[Next: Configure SnapMirror relationships and retention schedules.]
