---
sidebar: sidebar
permalink: ehr-epic-deploy/ehr-epic-deploy_where_to_find_additional_information_overview.html
keywords: additional, information, flexpod, deployment, epic, ehr
summary: To learn more about the information that is described in this document, see the following documents or websites.
---

= Where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-05-07 11:34:58.333972
//


To learn more about the information that is described in this document, see the following documents or websites:

== FlexPod design zone

* FlexPod design zone
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html[https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html^]

* FlexPod DC with FC Storage (MDS Switches) Using NetApp AFF, vSphere 6.5U1, and Cisco UCS Manager
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html[https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html^]

* Cisco Best Practices with Epic on Cisco UCS
+
https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf[https://www.cisco.com/c/dam/en_us/solutions/industries/healthcare/Epic_on_UCS_tech_brief_FNL.pdf^]

== NetApp technical reports

* TR-3929: Reallocate Best Practices Guide
+
https://fieldportal.netapp.com/content/192896[https://fieldportal.netapp.com/content/192896^]

* TR-3987: Snap Creator Framework Plug-In for InterSystems Caché
+
https://fieldportal.netapp.com/content/248308[https://fieldportal.netapp.com/content/248308^]

* TR-3928: NetApp Best Practices for Epic
+
https://fieldportal.netapp.com/?oparams=68646[https://fieldportal.netapp.com/?oparams=68646^]

* TR-4017: FC SAN Best Practices
+
http://media.netapp.com/documents/tr-4017.pdf[http://media.netapp.com/documents/tr-4017.pdf^]

* TR-3446: SnapMirror Async Overview and Best Practices Guide
+
http://media.netapp.com/documents/tr-3446.pdf[http://media.netapp.com/documents/tr-3446.pdf^]

== ONTAP documentation

* NetApp Product Documentation
+
https://www.netapp.com/us/documentation/index.aspx[https://www.netapp.com/us/documentation/index.aspx^]

* Virtual Storage Console (VSC) for vSphere documentation
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048[https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30048^]

* ONTAP 9 Documentation Center
+
http://docs.netapp.com/ontap-9/index.jsp[http://docs.netapp.com/ontap-9/index.jsp^]

* FC Express Guide for ESXi
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html^]

* All ONTAP 9.3 Documentation
+
https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579[https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579^]

** Software Setup Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html?lang=dot-cm-ssg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html?lang=dot-cm-ssg^]

** Disks and Aggregates Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html?lang=dot-cm-psmg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html?lang=dot-cm-psmg^]

** SAN Administration Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html?lang=dot-cm-sanag[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html?lang=dot-cm-sanag^]

** SAN Configuration Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?lang=dot-cm-sanconf[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?lang=dot-cm-sanconf^]

** FC Configuration for Red Hat Enterprise Linux Express Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-rhel-cg/home.html?lang=exp-fc-rhel-cg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-rhel-cg/home.html?lang=exp-fc-rhel-cg^]

** FC Configuration for Windows Express Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-cpg/home.html?lang=exp-fc-cpg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-cpg/home.html?lang=exp-fc-cpg^]

** FC SAN Optimized AFF Setup Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-fcsan-optaff-sg/home.html?lang=cdot-fcsan-optaff-sg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-fcsan-optaff-sg/home.html?lang=cdot-fcsan-optaff-sg^]

** High-Availability Configuration Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-hacg/home.html?lang=dot-cm-hacg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-hacg/home.html?lang=dot-cm-hacg^]

** Logical Storage Management Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html?lang=dot-cm-vsmg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html?lang=dot-cm-vsmg^]

** Performance Management Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html?lang=pow-perf-mon[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html?lang=pow-perf-mon^]

** SMB/CIFS Configuration Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/home.html?lang=pow-cifs-cg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/home.html?lang=pow-cifs-cg^]

** SMB/CIFS Reference
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html?lang=cdot-famg-cifs[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html?lang=cdot-famg-cifs^]

** Data Protection Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html?lang=pow-dap[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html?lang=pow-dap^]

** Data Protection Tape Backup and Recovery Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ptbrg/home.html?lang=dot-cm-ptbrg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ptbrg/home.html?lang=dot-cm-ptbrg^]

** NetApp Encryption Power Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html?lang=pow-nve[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html?lang=pow-nve^]

** Network Management Guide
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html?lang=dot-cm-nmg[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html?lang=dot-cm-nmg^]

** Commands: Manual Page Reference for ONTAP 9.3
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/home.html?lang=dot-cm-cmpr-930[http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-930/home.html?lang=dot-cm-cmpr-930^]

== Cisco Nexus, MDS, Cisco UCS, and Cisco UCS Manager guides

* Cisco UCS Servers Overview
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html^]

* Cisco UCS Blade Servers Overview
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html^]

* Cisco UCS B200 M5 Datasheet
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/index.html^]

* Cisco UCS Manager Overview
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html[https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-manager/index.html^]

* Cisco UCS Manager 3.2(3a) Infrastructure Bundle (requires Cisco.com authorization)
+
https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529[https://software.cisco.com/download/home/283612660/type/283655658/release/3.2%25283a%2529^]

* Cisco Nexus 9300 Platform Switches
+
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html[https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html^]

* Cisco MDS 9148S FC Switch
+
https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html[https://www.cisco.com/c/en/us/products/storage-networking/mds-9148s-16g-multilayer-fabric-switch/index.html^]
