---
sidebar: sidebar
permalink: vmware/vmw-getting-started-ontap-tools-for-vmware.html
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools
summary: 
---

= Getting Started with NetApp and VMware: ONTAP Tools for VMware (OTV)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

*Introduction*

ONTAP tools for VMware vSphere provides end-to-end life cycle management for virtual machines in VMware environments that use NetApp storage systems. It enables  administrators to manage the storage within the vCenter Server directly and simplify the storage and data management for VMware environments. The VMware vSphere Client plug-in tool is designed to integrate plug-in functionality into the vSphere Client without the need to run inside vCenter Server. This provides plug-in isolation and enables scale-out of plug-ins that operate in large vSphere environments.
 
*ONTAP Tools Components*

* *Virtual Storage Console (VSC)* The VSC includes the interface integrated with the vSphere client where you can add storage controllers, provision datastores, monitor performance of datastores, and view and update ESXi host settings.

* *VASA Provider* The VMware vSphere APIs for Storage Awareness (VASA) Provider for ONTAP send information about storage used by VMware vSphere to the vCenter Server, enabling provisioning of VMware Virtual Volumes (vVols) datastores, creation and use of storage capability profiles, compliance verification, and performance monitoring.

* *Storage Replication Adapter (SRA)* When enabled and used with VMware Site Recovery Manager (SRM), SRA facilitates the recovery of vCenter Server datastores and virtual machines in the event of a failure, allowing configuration of protected sites and recovery sites for disaster recovery.

For more information on NetApp ONTAP tools for VMware see https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html[ONTAP tools for VMware vSphere Documentation].