---
sidebar: sidebar
permalink: vmware/vmw-vcf-migrate.html
keywords: vmware, vcf, migrate, import
summary: 
---

= Migrate Existing Infrastructure to VCF
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Converting a vSphere environment with existing datastores running on ONTAP into a VMware Cloud Foundation (VCF) environment, involves integrating the existing infrastructure into a modern private cloud architecture. This process leverages the flexibility of ONTAP storage for seamless data access and management. Once the VCF management domain is established, administrators can efficiently import additional vSphere environments into the VCF ecosystem. This integration enhances resource utilization, simplifies private cloud management, and ensures a smooth transition with minimal disruption to existing workloads.

Point to the specific solutions for more details.

* link:vmw-vcf-mgmt-nfs.html[Convert Existing vCenter Instance to VCF Management Domain (NFS)]

* link:vmw-vcf-mgmt-fc.html[Convert vCenter Instance (FC datastore) to VCF Management Domain]
