---
sidebar: sidebar
permalink: vmware/vmw-vcf-protect-sc.html
keywords: vmware, vcf, protect, snapcenter
summary: 
---

= Protect Workloads with SnapCenter
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for VMware vSphere enhances VMware Cloud Foundation by simplifying backup and recovery, ensuring application-consistent backups, and optimizing storage with NetApp's efficiency technologies. It supports automated workflows, and scalable operations while providing seamless integration with the vSphere client. With SnapMirror replication providing secondary backup on-premises or to the cloud, it offers robust data protection and operational efficiency in virtualized environments. 

Point to the specific solutions for more details.

* link:vmw-vcf-scv-wkld.html[Protect VCF Workload Domain]

* link:vmw-vcf-scv-multiwkld.html[Protect VCF Multiple Workload Domains]

* link:vmw-vcf-scv-nvme.html[Protect VCF Workload Domain with NVMe]

* link:vmw-vcf-scv-321.html[3-2-1 Data Protection for VMware with SnapCenter Plug-in and BlueXP backup and recovery for VMs]
