---
sidebar: sidebar
permalink: vmware/vmw-vcf-provision.html
keywords: vmware, vcf, provision, principal, storage
summary: 
---

= Provision VCF Environment with Principal Storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp ONTAP storage serves as an ideal principal storage solution for VMware Cloud Foundation (VCF) management and VI workload domains, offering high performance, scalability, advanced data management, and seamless integration, which collectively enhance operational efficiency and data protection.

Please refer to the following solutions for the technical details of provisioning a VCF environment in the appropriate domain and with the appropriate protocol.

* link:vmw-vcf-mgmt-principal-fc.html[Management Domain with FC]

* link:vmw-vcf-mgmt-principal-nfs.html[Management Domain with NFS]

* link:vmw-vcf-viwld-principal-fc.html[Virtual Infrastructure Workload Domain with FC]

* link:vmw-vcf-viwld-principal-nfs.html[Virtual Infrastructure Workload Domain with NFS]
