---
sidebar: sidebar
permalink: vmware/vmw-getting-started-bluexp-disaster-recovery.html
keywords: vmware, getting, started, overview, netapp, bluexp, disaster, recovery, draas
summary: 
---

= Getting Started with NetApp and VMware: BlueXP Disaster Recovery (DRaaS)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

*Introduction*
Disaster recovery planning is critical for VMWare administrators to minimize downtime in the event of hardware failures, cyberattacks or natural disasters. Having a successful plan and combination of technologies ensures the protection of critical data, applications and VMs. The challenge with DR is determining the appropriate level of protection and associated costs. 

ONTAP arrays offer built-in replication to transfer volume data, and therefore the virtual machines residing on the designated datastore LUNs, from one site to another. BlueXP DRaaS integrates with vSphere and automates the entire workflow for seamless failover and failback in the event of disaster. 

For more information on BlueXP DRaaS, see link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-overview.html[Overview of BlueXP DRaaS].

*Considerations*
The most time-consuming parts of a DR failover in a VMware vSphere environment is the execution of the steps necessary to inventory, register, reconfigure, and power up VMs at the DR site. An ideal solution has both a low RPO (as measured in minutes) and a low RTO (measured in minutes to hours). One factor that is often overlooked in a DR solution is the ability to test the DR solution efficiently on a periodic interval. 

To architect a DR solution, keep the following factors in mind:

* The recovery time objective (RTO). The RTO is how quickly a business can recover from a disaster, or, more specifically, how long it takes to execute the recovery process to make business services available again.
* The recovery point objective (RPO). The RPO is how old the recovered data is after it has been made available, relative to the time that the disaster occurred.
* Scalability and adaptability. This factor includes the ability to grow storage resources incrementally as demand increases.

For more technical information on the available solutions, please see:

* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-nfs.html[DR using BlueXP DRaaS for NFS Datastores]

* link:https://docs.netapp.com/us-en/netapp-solutions/ehc/dr-draas-vmfs.html[DR using BlueXP DRaaS for VMFS Datastores]