---
sidebar: sidebar
permalink: vmware/vmw-getting-started-metro-storage-cluster.html
keywords: vmware, getting, started, overview, netapp, storage, metro, cluster
summary: 
---

= vSphere Metro Storage Cluster 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Advanced business continuity is critical to organizations as they look to protect their VMware environments from the event of outages in one or more failure domains.

== Introduction

In addition to availabilities built into the products, VMware and NetApp offer advanced configurations that further protect workloads that are spread across failure domains such as racks, building, campuses or even cities. 

== NetApp MetroCluster

NetApp MetroCluster uses NetApp’s high-availability (HA) capability to protect against controller failures. MetroCluster also includes SyncMirror technology, cluster failover on demand (CFOD), hardware redundancy, and geographical separation for high availability. SyncMirror synchronously mirrors data across two plexes: the local plex actively serving data and the remote plex as a standby. All MetroCluster components, such as controllers, storage, cables, switches, and adapters, have hardware redundancy.

== NetApp SnapMirror active sync

NetApp SnapMirror active sync provides datastore-granular protection with FCP and iSCSI SAN protocols, selectively protecting high-priority workloads topology. It offers active-active access to both local and remote sites, unlike the active-standby MetroCluster. Starting with ONTAP 9.15.1, SnapMirror active sync supports symmetric active/active capability, allowing read and write I/O operations from both copies of a protected LUN with bidirectional synchronous replication. 

== VMware vSphere Metro Storage Cluster

VMware vSphere Metro Storage Cluster (vMSC) enhances VMware HA with active-active stretched storage. This certified configuration protects VMs and containers against failures. This is accomplished by using stretched storage concepts along with clusters of vSphere hosts. These hosts are distributed across different failure domains. The NetApp MetroCluster and SnapMirror active sync storage technologies are used to provide protection and supported storage offerings. By leveraging vMSC, with a NetApp certified solution provides robust and resilient IT operations across failure domains. 

For detailed information see the https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html#continuous-availability-solutions-for-vsphere-environments[vSphere Metro Storage Cluster with ONTAP].
{nbsp}