---
sidebar: sidebar
permalink: vmware/vmw-vcf-protect-vmsc.html
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster
summary: 
---

= High Availability with VMware vSphere Metro Storage Cluster (vMSC)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp ONTAP High Availability, integrated with VMware vSphere Metro Storage Cluster (vMSC), provides a robust solution for VMware Cloud Foundation (VCF) management and VI workload domains. This combination ensures continuous data availability, seamless failover, and disaster recovery across geographically dispersed sites, enhancing resilience and operational continuity for critical workloads. SnapMirror active sync, enables business services to continue operating even through a complete site failure, supporting applications to fail over transparently using a secondary copy. There is no manual intervention or custom scripting required to trigger a failover with SnapMirror active sync.

Refer to the following solutions for more details.

* link:vmw-vcf-vmsc-mgmt-smas.html[Stretch Cluster for Management Domain using SnapMirror active sync]

* link:vmw-vcf-vmsc-mgmt-mcc.html[Stretch Cluster for Management Domain using MetroCluster]

* link:vmw-vcf-vmsc-viwld-smas.html[Stretch Cluster for VI Workload Domain using SnapMirror active sync]

* link:vmw-vcf-vmsc-viwld-mcc.html[Stretch Cluster for VI Workload Domain using MetroCluster]
