---
sidebar: sidebar
permalink: vmware/vmw-getting-started-vm-data-collector.html
keywords: vmware, getting, started, overview, netapp, vm, data, collector, vmdc
summary: 
---

= Getting Started with NetApp and VMware: VM Data Collector (VMDC)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

*Introduction*
A key component in right-sizing and projecting possible optimization opportunities is understanding the current state of the VMware environment. Virtual Machine Data Collector (VMDC) is a free, lightweight, simple GUI based toolkit for VMware environments that allows users to collect detailed inventory information about their virtual machines (VMs), hosts, storage, and networks. 

For more information on Virtual Machine Data Collector, see link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmdc.html[Virtual Machine Data Collector Documentation].


*VMDC Capabilities*

VMDC is just a stepping stone to collect quick and instant statistics for projecting optimization possibilities for VMWare core licensing along with vCPU and RAM. NetApp Data Infrastructure Insights which requires installation of AUs and data collectors should be the obvious next step for understanding detailed VM topology, grouping of VMs using annotation so as to right size the workloads and future proof the infrastructure.

Sampling of the metrics gathered with VMDC:

* VM information 
** VM name
** VM power state
** VM CPU information
** VM memory information
** VM location
** VM network information
** and more

* VM performance 
** Performance data for VMs at selected interval
** VM read / write information
** VM IOPS information
** VM latency
** and more

* ESXi host information
** Host datacenter information
** Host cluster information
** Host model information
** Host CPU information
** Host memory information
** and more 