---
sidebar: sidebar
permalink: vmware/vmw-getting-started-migration.html
keywords: vmware, getting, started, overview, netapp
summary: 
---

= Getting Started with NetApp and VMware: Migrating VMs to ONTAP backed datastores
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
*Introduction* 

Migrating VMware workloads to NetApp ONTAP simplifies data management and enhances performance through ONTAP's advanced storage features like deduplication, compression, and efficient snapshots. This migration enables seamless integration, improved data protection, and greater flexibility in managing virtualized environments, ensuring a smooth transition with minimal downtime. 

For more information on migrating VMware workloads to ONTAP backed datastores, see the link:https://docs.netapp.com/us-en/netapp-solutions/vmware/migrate-vms-to-ontap-datastore.html[Migrate VMs to ONTAP Datastores].

*Use Cases*

There are many options with migration in terms of the source and destination when considering moving to ONTAP backed datastores. 

* Migration from third party storage systems (including vSAN) to ONTAP datastores. 
* Migration of VMs in the same vSphere cluster
* Migration of VMs across multiple vSphere clusters
* Migration of VMs across vCenter servers in same SSO domain  
* Migration of VMs across vCenter servers in different SSO domains  
* Migration of VMs across datacenter locations 
* Migration from third party storage systems (including vSAN) to ONTAP datastores. 
* Migration of VMs in a hybrid cloud environment 