---
sidebar: sidebar
permalink: vmware/vmw-vcf-mgmt-principal-fc.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc
summary:
---

= VMFS on FC as principal storage for Management Domains
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this scenario we will review how to deploy VMFS datastore with Fiber Channel (FC) principal storage for management domains. Where appropriate we will refer to external documentation for the steps that must be performed in VCF's SDDC Manager, and cover those steps that are specific to the storage configuration portion.

== Benefits of Fibre Channel

*High Performance:* FC provides high-speed data transfer rates, making it ideal for applications requiring fast and reliable access to large amounts of data.

*Low Latency:* Very low latency, which is crucial for performance-sensitive applications like databases and virtualized environments.

*Reliability:* FC networks are known for their robustness and reliability, with features like built-in redundancy and error correction.

*Dedicated Bandwidth:* FC provides dedicated bandwidth for storage traffic, reducing the risk of network congestion.

For more information on using Fibre Channel with NetApp storage systems, refer to https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html[SAN Provisioning with FC] for more info.

== Scenario Overview

This scenario covers the following high level steps:

* Create a storage virtual machine (SVM) with logical interfaces (LIFs) for FC traffic.
* Collect WWPN information of hosts to be deployed and create corresponding initiator groups on the ONTAP storage system.
* Create an FC volume on the ONTAP storage system.
* Map initiator groups to create FC volume
* Utilize single initiator-target zoning on FC switches. Create one zone for each initiator (single initiator zone).
** For each zone, include a target that is the ONTAP FC logical interface (WWPN) for the SVMs. There should be at least two logical interfaces per node per SVM. Do not use the WWPN of the physical ports.
* Configure a new VMFS datastore for use as principal storage.
* Leverage VCF import tool or SDDC API to reuse an existing vSphere cluster or deploy additional cluster, respectively.

[NOTE]
This solution is applicable for ONTAP platforms supporting FC storage including NetApp ASA, AFF and FAS. 

== Prerequisites

The following components and configurations are used in this scenario:

* NetApp ASA storage system with a storage virtual machine (SVM) configured to allow FC traffic.
* Logical interfaces (LIF) have been created on the FC fabric that is to carry FC traffic and is associated with the SVM.
* Zoning has been configured to use single initiator-target zoning on FC switches for host HBAs and storage targets.

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html[VMware Cloud Foundation Documentation].

== Deployment Steps

=== Management Domain - Default Cluster

FC Principal storage on initial cluster is only supported with VCF brownfield import tool. If VCF is deployed with Cloud Builder tool (till version 5.2.x), only VSAN is supported. 

For more information on using an existing vSphere environment, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html[converting existing vSphere environment to management domain] for more info.

=== Management Domain - Additional Cluster

The additional vSphere cluster on management domain can be deployed with following options:

* Have additional cluster in vSphere environment and use the VCF brownfield import tool to convert the vSphere environment to Management domain. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html[ONTAP tools for VMware vSphere] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html[System Manager or ONTAP API] can be used to deploy the VMFS datastore to vSphere cluster.
* Use SDDC API to deploy additional cluster. The vSphere hosts should have the VMFS datastore configured. Use https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html[System Manager or ONTAP API] to deploy LUN to vSphere hosts.
* Use SDDC Manager UI to deploy additional cluster. But this option only creates VSAN datastore till version 5.2.x.

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html[VMware Cloud Foundation Documentation].


