---
sidebar: sidebar
permalink: vmware/vmw-getting-started-hybrid-multicloud.html
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud
summary: 
---

= Hybrid Multi-Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

== Introduction
VMware hybrid multicloud architectures with Netapp allow for seamless integration between on-premises infrastructure and public cloud services, providing flexibility and scalability. This approach enables businesses to easily migrate workloads, optimize resource usage, and maintain consistent operations across both environments.

For more information on hybrid cloud scenarios with VMware and NetApp, see link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud[Overview of NetApp Hybrid Multicloud with VMware].

== VMware Deployment Scenarios with NetApp

This section describes various deployment options for VMware environments across on-premises and public clouds. Each of the cloud providers support a VMware Software Defined Data Center (SDDC) and/or VMware Cloud Foundation (VCF) stack within their respective public cloud offerings.

* *VMware on-premises*

Using VMware with NetApp storage on-premises provides a robust, scalable and flexible virtualization environment. By pairing NetApp's advanced data management features like deduplication, compression, and efficient snapshots with the appropriate storage system powered by ONTAP, customers can choose the platform that works for them. This combination ensures high performance, reliability, and simplified management for virtualized workloads, enhancing overall data center efficiency.

* *Azure VMware Solution*

Azure VMware Solution is a hybrid cloud service that allows for fully functioning VMware SDDCs within the Microsoft Azure public cloud. Azure VMware Solution is a first-party solution fully managed and supported by Microsoft, verified by VMware leveraging Azure infrastructure. This means that when Azure VMware Solution is deployed, customer's get VMware's ESXi for compute virtualization, vSAN for hyper-converged storage, and NSX for networking and security, all while taking advantage of Microsoft Azure's global presence, class-leading data center facilities and proximity to the rich ecosystem of native Azure services and solutions.

* *VMware Cloud on AWS*

VMware Cloud on AWS brings VMware’s enterprise-class SDDC software to the AWS Cloud with optimized access to native AWS services. Powered by VMware Cloud Foundation, VMware Cloud on AWS integrates VMware's compute, storage, and network virtualization products (VMware vSphere, VMware vSAN, and VMware NSX) along with VMware vCenter Server management, optimized to run on dedicated, elastic, bare-metal AWS infrastructure.

* *Google Cloud VMware Engine*

Google Cloud VMware Engine is an infrastructure-as-a-service (IaaS) offering built on Google Cloud’s highly performant scalable infrastructure and VMware Cloud Foundation stack – VMware vSphere, vCenter, vSAN, and NSX-T. This service enables a fast path to the cloud, seamlessly migrating or extending existing VMware workloads from on-premises environments to Google Cloud Platform without the cost, effort ,or risk of rearchitecting applications or retooling operations. It is a service sold and supported by Google, working closely with VMware.