---
sidebar: sidebar
permalink: vmware/vmw-vcf-mgmt-principal-fc.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc
summary:
---

= VMFS on FC as principal storage for Management Domains
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this scenario we will review the use case of using using an existing FC-based VMFS datastore, on ONTAP, for use as principal storage for a VMware Cloud Foundation (VCF) management domains. Where appropriate we will refer to external documentation for the steps that must be performed in VCF's SDDC Manager, and reference those steps that are specific to the storage configuration portion.

For information on converting an existing FC-based vSphere environment with ONTAP, refer to link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmw-vcf-mgmt-fc.html[Convert vSphere Environment (FC datastore) to VCF Management Domain].

[NOTE]
VCF release 5.2 introduced the the capability to convert an existing vSphere 8 environment to a VCF management domain or import as VCF VI workload domains. Prior to this release, VMware vSAN was the only option for principal storage for the VCF management domain. 

[NOTE]
This solution is applicable for ONTAP platforms supporting FC storage including NetApp ASA, AFF and FAS. 

== Prerequisites

The following components and configurations are used in this scenario:

* NetApp storage system with a storage virtual machine (SVM) configured to allow FC traffic.
* Logical interfaces (LIF) have been created on the FC fabric that is to carry FC traffic and is associated with the SVM.
* Zoning has been configured to use single initiator-target zoning on FC switches for host HBAs and storage targets.

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html[VMware Cloud Foundation Documentation].

== Deployment Steps

=== Management Domain - Default Cluster

FC Principal storage on the initial cluster is only supported with VCF brownfield import tool. If VCF is deployed with Cloud Builder tool (priort to release version 5.2.x), only vSAN is supported. 

For more information on using an existing vSphere environment, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html[converting existing vSphere environment to management domain] for more info.

=== Management Domain - Additional Cluster

The additional vSphere cluster on management domain can be deployed with following options:

* Have additional cluster in vSphere environment and use the VCF brownfield import tool to convert the vSphere environment to Management domain. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html[ONTAP tools for VMware vSphere] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html[System Manager or ONTAP API] can be used to deploy the VMFS datastore to vSphere cluster.
* Use SDDC API to deploy additional cluster. The vSphere hosts should have the VMFS datastore configured. Use https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html[System Manager or ONTAP API] to deploy LUN to vSphere hosts.
* Use SDDC Manager UI to deploy additional cluster. But this option only creates VSAN datastore till version 5.2.x.

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html[VMware Cloud Foundation Documentation].


