---
sidebar: sidebar
permalink: vmware/vmware_vcf_aff_prin_fc.html
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, array, ontap tools, otv, sddc, fc
summary:
---

= VMFS on FC as a VCF Principal Datastore
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this scenario we will demonstrate how to deploy VMFS datastore with Fiber Channel(FC) backend for management and workload domains.

== Scenario Overview
VCF Principal storage refers to any type of storage that is deployed, converted or imported as part of the VCF domain setup process.
This document covers the following scenarios.
[width=100%,cols="20% 20% 20% 20% 20%", frame=all, grid=all, options="header"]
|===
| Storage Type | Management Domain - Default Cluster | Management Domain - Additional Cluster | VI Workload Domain - Default Cluster | VI Workload Domain - Additional Cluster
| VMFS on FC | *Import Tool* | *Import Tool, SDDC API* | Yes | Yes
|===


== Prerequisites
This scenario requires the following components and configurations:

* An ONTAP storage system with FC ports connected to FC switches.
* SVM created with FC lifs.
* vSphere with FC HBAs connected to FC switches.
* Single initiator-target zoning is configured on FC switches.
[NOTE]
Use SVM FC logical interface in zone configuration rather than physical FC ports on ONTAP systems.

NetApp recommends multipath for FC LUNs. 



== Deployment Steps

=== Management Domain - Default Cluster

FC Principal storage on initial cluster is only supported with VCF brownfield import tool. If VCF is deployed with cloudbuilder tool (till version 5.2.x), only VSAN is supported. Refer https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html[converting existing vSphere environment to management domain] for more info.

=== Management Domain - Additional Cluster

The additional vSphere cluster on management domain can be deployed with following options:
* Have additional cluster in vSphere environment and use the VCF brownfield import tool to convert the vSphere environment to Management domain. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html[ONTAP tools for VMware vSphere], https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html[System Manager or ONTAP API] can be used to deploy the VMFS datastore to vSphere cluster.
* Use SDDC API to deploy additional cluster. The vSphere hosts should have the VMFS datastore configured. Use https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html[System Manager or ONTAP API] to deploy LUN to vSphere hosts.
* Use SDDC Manager UI to deploy additional cluster. But this option only creates VSAN datastore till version 5.2.x.

=== VI Workload Domain - Default Cluster

After the management domain is up and running, VI Workload domain can be created 
* Using SDDC Manager UI. The vSphere hosts should have the VMFS datastore configured. Use System Manager or ONTAP API to deploy LUN to vSphere hosts.
* Import an existing vSphere environment as new VI workload domain. ONTAP tools for VMware vSphere, System Manager or ONTAP API can be used to deploy the VMFS datastore to vSphere cluster.

=== VI Workload Domain - Additional Cluster

Once VI workload is up and running, additional clusters can be deployed with VMFS on FC LUN using the following options.

* Additional clusters in vSphere environment imported using VCF brownfield import tool. ONTAP tools for VMware vSphere, System Manager or ONTAP API can be used to deploy the VMFS datastore to vSphere cluster.
* Using SDDC Manager UI or API to deploy additional cluster. The vSphere hosts should have the VMFS datastore configured. Use System Manager or ONTAP API to deploy LUN to vSphere hosts.

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html[VMware Cloud Foundation Documentation].


