---
sidebar: sidebar
permalink: vmware/vmware_vcf_aff_multi_wkld_scv.html
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, vvol, vvols, array, ontap tools, otv, sddc, scv, workload, domain, backup
summary:
---

= VMware Cloud Foundation with NetApp AFF Arrays
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead] 
VMware Cloud Foundation (VCF) workload domains enable organizations to logically separate resources into different domains to group different workloads, enhance security and fault tolerance. Domains can scale independently, meet specific compliances and provide multitenancy. Data Protection for VMware Cloud Foundation (VCF) is a critical aspect to ensure the availability, integrity, and recoverability of data across the management domain and workload domains. NetApp SnapCenter Plug-in for VMware vSphere (SCV) is a powerful tool that integrates NetApp’s data protection capabilities into VMware environments. It simplifies backup, restore, and cloning of VMware vSphere virtual machines (VMs) hosted on NetApp storage. 

Author: Rachel Zhu

This document provides deployment steps on how to protect VCF workload domains with NetApp SnapCenter for VMware. 

== Use Cases
Use cases covered in this documentation:

* Storage options for customers seeking uniform environments across both private and public clouds.
* Automated solution for deploying virtual infrastructure for workload domains.
* Scalable storage solution tailored to meet evolving needs, even when not aligned directly with compute resource requirements.
* Deploy VCF VI Workload Domains using ONTAP as principal storage.
* Deploy supplemental storage to VI Workload Domains using ONTAP Tools for VMware vSphere.

== Audience

This solution is intended for the following people: 

* Solution architects looking for more flexible storage options for VMware environments that are designed to maximize TCO.
* Solution architects looking for VCF storage options that provide data protection and disaster recovery options with the major cloud providers.
* Storage administrators wanting to understand how to configure VCF with principal and supplemental storage.

== Technology Overview
The VCF with NetApp AFF solution is comprised of the following major components:

=== VMware Cloud Foundation
VMware Cloud Foundation extends VMware’s vSphere hypervisor offerings by combining key components such as SDDC Manager, vSphere, vSAN, NSX, and VMware Aria Suite to create a virtualized datacenter.
