---
sidebar: sidebar
permalink: vmware/vmware_vcf_asa_mgmt_stretchcluster.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, iscsi
summary:
---

= Stretch Cluster with ONTAP for VCF Management Domains
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this scenario we will demonstrate how to use ONTAP Tools for VMware vSphere (OTV) to configure a stretch cluster for a VCF management domain.

Author: Suresh Thoppay

== Scenario Overview

The stretch cluster deployed on default cluster of management domain and stretch cluster deployed on additional cluster on management domain.

Here are the high level steps for the default cluster.

* Deploy vSphere and vCenter servers.
* Deploy ONTAP tools & configure.
* Provision VMFS (FC/iSCSI) datastore.
* Ensure NFS or vSAN datastore available (if iSCSI is used)
* Protect the datastore using SnapMirror active sync.
* Convert the vSphere into VCF.

The high level steps below are for additional cluster.

* Deploy vSphere hosts.
* Use SDDC Manager API to create additional cluster in management domain.
* Use ONTAP tools to protect the datastore using SnapMirror active sync.


// == Prerequisites

.Stetch cluster on default cluster
[%collapsible]
==== 
====

.Stetch cluster on additional cluster
[%collapsible]
==== 
====

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html[VMware Cloud Foundation Documentation].

== Video demo for this solution

// video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto, title="iSCSI Datastores as Supplemental Storage for VCF Management Domains", width=360]