---
sidebar: sidebar
permalink: vmware/vmware_vcf_asa_wkld_stretchcluster.html
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, iscsi
summary:
---

= Stretch Cluster with ONTAP for VCF VI Workload Domains
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this scenario we will demonstrate how to use ONTAP Tools for VMware vSphere (OTV) to configure a stretch cluster for a VCF VI workload domain.

Author: Suresh Thoppay

== Scenario Overview

The stretch cluster deployment with 
 * VMFS on FC as principal storage
 * VMFS on FC as supplemental storage
 * VMFS on iSCSI as supplemental storage

Here are the high level steps for the default cluster.

* Deploy vSphere servers.
* Create VI workload domain.
* Deploy ONTAP tools plugin to VI workload vCenter.
* Provision datastore in case of supplemental storage.
* Protect the datastore.




// == Prerequisites

.Stetch cluster on principal storage
[%collapsible]
==== 
====

.Stetch cluster on supplemental storage
[%collapsible]
==== 
====

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html[VMware Cloud Foundation Documentation].

== Video demo for this solution

// video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto, title="iSCSI Datastores as Supplemental Storage for VCF Management Domains", width=360]