---
sidebar: sidebar
permalink: vmware/vmware_vcf_aff_supp_fc.html
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, array, ontap tools, otv, sddc, fc
summary:
---

= VMFS on FC as a VCF Supplemental Datastore
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
In this scenario we will demonstrate how to deploy VMFS datastore with Fiber Channel(FC) backend for management and workload domains utilizing ONTAP tools.

Author: Suresh Thoppay

== Scenario Overview

VCF Supplemental datastore is provisoned as part of day-2 operations using vCenter.
This scenario covers the following high level steps:

* Deployment of ONTAP tools on management domain
* Register VI workload vCenter servers to ONTAP tools
* Define Storage backend on ONTAP tools plugin for VMware vSphere
* Provision VMFS on FC transport

== Prerequisites
This scenario requires the following components and configurations:

* An ONTAP storage system with FC ports connected to FC switches.
* SVM created with FC lifs.
* vSphere with FC HBAs connected to FC switches.
* Single initiator-target zoning is configured on FC switches.
[NOTE]
Use SVM FC logical interface in zone configuration rather than physical FC ports on ONTAP systems.

NetApp recommends multipath for FC LUNs. 


== Deployment Steps for management domain
To deploy ONTAP Tools and use it to create a VMFS datastore on the VCF management domain, complete the following steps:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html[Deploy ONTAP tools on management domain]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html[Define Storage backend using vSphere client interface]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html[Provision VMFS on FC]

== Deployment Steps for VI workload domain
To deploy ONTAP Tools and use it to create a VMFS datastore on the VCF VI workload domain, complete the following steps:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html[Register VI workload vCenter to enable the vCenter Plugin]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html[Define Storage backend using vSphere client interface]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html[Provision VMFS on FC]

== Additional information

For information on configuring ONTAP storage systems refer to the link:https://docs.netapp.com/us-en/ontap[ONTAP 9 Documentation] center.

For information on configuring VCF refer to link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html[VMware Cloud Foundation Documentation].


== Video demo for this solution

video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto, title="VMFS(FC) Datastore as Supplemental Storage for VCF Management Domain", width=360]


