---
sidebar: sidebar
permalink: ai/a400-thinksystem-conclusion.html
keywords: acknowledgements, additional information
summary: This NetApp and Lenovo solution is a flexible scale-out architecture that is ideal for entry into mid-level enterprise AI. NetApp storage delivers the same or better performance as local SSD storage and offers the following benefits to data scientists, data engineers, and IT decision makers.
---
= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2023-02-13 11:07:00.573226
//

[.lead]
The NetApp and Lenovo solution validated here is a flexible scale-out architecture that is ideal for entry into mid-level enterprise AI. 

NetApp storage delivers the same or better performance as local SSD storage and offers the following benefits to data scientists, data engineers, and IT decision makers:

* Effortless sharing of data between AI systems, analytics, and other critical business systems. This data sharing reduces infrastructure overhead, improves performance, and streamlines data management across the enterprise.
* Independently scalable compute and storage to minimize costs and improve resource utilization.
* Streamlined development and deployment workflows using integrated snapshots and clones for instantaneous and space-efficient user workspaces, integrated version control, and automated deployment.
* Enterprise-grade data protection for disaster recovery and business continuance.

== Acknowledgments

* Karthikeyan Nagalingam, Technical Marketing Engineer, NetApp
* Jarrett Upton, Admin, AI Lab Systems, Lenovo

== Where to find additional information 

To learn more about the information described in this document, refer to the following documents and/or websites:

* NetApp All Flash Arrays product page
+
https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx[https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx^]

* NetApp AFF A400 page 
+
https://docs.netapp.com/us-en/ontap-systems/a400/index.html[https://docs.netapp.com/us-en/ontap-systems/a400/index.html]

* NetApp ONTAP data management software product page
+
http://www.netapp.com/us/products/data-management-software/ontap.aspx[http://www.netapp.com/us/products/data-management-software/ontap.aspx^]

* MLPerf
+
https://mlperf.org/[https://mlperf.org^]

* TensorFlow benchmark
+
https://github.com/tensorflow/benchmarks[https://github.com/tensorflow/benchmarks^]

* NVIDIA SMI (nvidia-smi)
+
https://developer.nvidia.com/nvidia-system-management-interface[https://developer.nvidia.com/nvidia-system-management-interface]
