---
sidebar: sidebar
permalink: ai-edge-conclusion.html
keywords:
summary:
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-10-18 12:10:22.542896
//

[.lead]
AI- driven automation and edge computing is a leading approach to help business organizations achieve digital transformation and maximize operational efficiency and safety. With edge computing, data is processed much faster because it does not have to travel to and from a data center. Therefore, the cost associated with sending data back and forth to data centers or the cloud is diminished. Lower latency and increased speed can be beneficial when businesses must make decisions in near-real time using AI inferencing models deployed at the edge.

NetApp storage systems deliver the same or better performance as local SSD storage and offer the following benefits to data scientists, data engineers, AI/ML developers, and business or IT decision makers:

* Effortless sharing of data between AI systems, analytics, and other critical business systems. This data sharing reduces infrastructure overhead, improves performance, and streamlines data management across the enterprise.
* Independently scalable compute and storage to minimize costs and improve resource usage.
* Streamlined development and deployment workflows using integrated Snapshot copies and clones for instantaneous and space-efficient user workspaces, integrated version control, and automated deployment.
* Enterprise-grade data protection for disaster recovery and business continuity. The NetApp and Lenovo solution presented in this document is a flexible, scale-out architecture that is ideal for enterprise-grade AI inference deployments at the edge. 

=== Acknowledgments

* J.J. Falkanger, Sr. Manager, HPC & AI Solutions, Lenovo
* Dave Arnette, Technical Marketing Engineer, NetApp
* Joey Parnell, Tech Lead E-Series AI Solutions, NetApp
* Cody Harryman, QA Engineer, NetApp

=== Where to find additional information

To learn more about the information described in this document, refer to the following documents and/or websites:

* NetApp AFF A-Series arrays product page
+
https://www.netapp.com/data-storage/aff-a-series/[https://www.netapp.com/data-storage/aff-a-series/^]

* NetApp ONTAP data management software—ONTAP 9 information library
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286^]

* TR-4727: NetApp EF-Series Introduction
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf[https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf^]

* NetApp E-Series SANtricity Software Datasheet
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf[https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf^]

* NetApp Persistent Storage for Containers—NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[https://netapp.io/persistent^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[-^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[storage^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[-^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[provisioner^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[-^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[for^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[-^]https://netapp.io/persistent-storage-provisioner-for-kubernetes/[kubernetes/^] 

* MLPerf
** https://mlcommons.org/en/[https://mlcommons.org/en/^]
** http://www.image[http://www.image^]http://www.image-net.org/[-^]http://www.image-net.org/[net.org/^]
** https://mlcommons.org/en/news/mlperf-inference-v11/[https://mlcommons.org/en/news/mlperf-inference-v11/^]
* NetApp Cloud Sync 
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html[https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works^] 

* TensorFlow benchmark
+
https://github.com/tensorflow/benchmarks[https://github.com/tensorflow/benchmark^]https://github.com/tensorflow/benchmarks[s^]

* Lenovo ThinkSystem SE350 Edge Server 
+
https://lenovopress.com/lp1168[https://lenovopress.com/lp1168^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[-^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[thinksystem^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[-^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[se350^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[-^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[edge^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[-^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[server^]https://lenovopress.com/lp1168-thinksystem-se350-edge-server[ ^]

* Lenovo ThinkSystem DM5100F Unified Flash Storage Array 
+
https://lenovopress.com/lp1365[https://lenovopress.com/lp1365^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[-^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[thinksystem^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[-^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[dm5100f^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[-^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[unified^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[-^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[flash^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[-^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[storage^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[-^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[array^]https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array[ ^]

=== Version history

|===
|Version |Date |Document version history

|Version 1.0
|March 2021
|Initial release
|Version 2.0
|October 2021
|Updated with EF and MLPerf Inference v1.1
|===
