---
sidebar: sidebar
permalink: ai/ai-edge-architecture-sizing-options.html
keywords: architecture, sizing, computer server, shared storage
summary: You can adjust the setup used for the validation to fit other use cases.
---

= Architecture sizing options
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-10-18 12:10:22.538999
//

link:ai-edge-test-results.html[Previous: Test results.]

[.lead]
You can adjust the setup used for the validation to fit other use cases.

== Compute server

We used an Intel Xeon D-2123IT CPU, which is the lowest level of CPU supported in SE350, with four physical cores and 60W TDP. While the server does not support replacing CPUs, it can be ordered with a more powerful CPU. The top CPU supported is Intel Xeon D-2183IT with 16 cores, 100W running at 2.20GHz. This increases the CPU computational capability considerably. While CPU was not a bottleneck for running the inference workloads themselves, it helps with data processing and other tasks related to inference. At present, NVIDIA T4 is the only GPU available for edge use cases; therefore, currently, there is no ability to upgrade or downgrade the GPU.

== Shared storage

For testing and validation, the NetApp AFF C190 system, which has maximum storage capacity of 50.5TB, a throughput of 4.4GBps for sequential reads, and 230K IOPS for small random reads, was used for the purpose of this document and is proven to be well-suited for edge inference workloads.

However, if you require more storage capacity or faster networking speeds, you should use the NetApp AFF A220 or https://tv.netapp.com/detail/video/6211798209001/netapp-aff-a250-virtual-tour-and-demo[NetApp AFF A250^] storage systems. In addition, the NetApp EF280 system, which has a maximum capacity of 1.5PB, bandwidth 10GBps was also used for the purpose of this solution validation. If you prefer more storage capacity with higher bandwidth, https://www.netapp.com/pdf.html?item=/media/19339-DS-4082.pdf&v=2021691654[NetApp EF300^] can be used.

link:ai-edge-conclusion.html[Next: Conclusion.]
