---
sidebar: sidebar
permalink: ai/ai-protopia-test-and-validation-plan.html
keywords: validation scenarios, obfuscation, batch inferencing job
summary: This section provides an overview of the three scenarios validated in this solution.
---

= Test and validation plan
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-27 11:48:17.729471
//

link:ai-protopia-technology-overview.html[Previous: Technology overview.]

[.lead]
For this solution design, the following three scenarios were validated:

* An inferencing task, with and without Protopia obfuscation, within a JupyterLab workspace that was orchestrated by using the NetApp DataOps Toolkit for Kubernetes.
* A batch inferencing job, with and without Protopia obfuscation, on Kubernetes with a data volume that was orchestrated by using NetApp DataOps Toolkit for Kubernetes.
* An inferencing task using an NVIDIA Triton Inference Server instance that was orchestrated by using the NetApp DataOps Toolkit for Kubernetes. We applied Protopia obfuscation to the image before invoking the Triton inference API to simulate the common requirement that any data that is transmitted over the network must be obfuscated. This workflow is applicable to use cases where data is collected within a trusted zone but must be passed outside of that trusted zone for inferencing. Without Protopia obfuscation, it is not possible to implement this type of workflow without sensitive data leaving the trusted zone.

link:ai-protopia-test-configuration.html[Next: Test configuration.]
