---
sidebar: sidebar
permalink: ai/ai-protopia-inferencing-accuracy-comparison.html
keywords: faceboxes, alpha value, accuracy, comparison
summary: For this validation, we performed inferencing for an image detection use case by using a set of raw images. We then performed the same inferencing task on the same set of images with Protopia obfuscation added before inferencing. We repeated the task using different values of ALPHA for the Protopia obfuscation component.
---

= Inferencing accuracy comparison
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-27 11:48:17.802295
//

link:ai-protopia-test-procedure.html[Previous: Test procedure.]

[.lead]
For this validation, we performed inferencing for an image detection use case by using a set of raw images. We then performed the same inferencing task on the same set of images with Protopia obfuscation added before inferencing. We repeated the task using different values of ALPHA for the Protopia obfuscation component. In the context of Protopia obfuscation, the ALPHA value represents the amount of obfuscation that is applied, with a higher ALPHA value representing a higher level of obfuscation. We then compared inferencing accuracy across these different runs.

The following two tables provide details about our use case and outline the results.

Protopia works directly with customers to determine the appropriate ALPHA value for a specific use case.

|===
|Component |Details

|Model
|FaceBoxes (PyTorch) -
|Dataset
|FDDB dataset
|===

|===
|Protopia obfuscation |ALPHA |Accuracy

|No
|N/A
|0.9337148153739079
|Yes
|0.05
|0.9028766627325002
|Yes
|0.1
|0.9024301009661478
|Yes
|0.2
|0.9081836283186224
|Yes
|0.4
|0.9073066107482036
|Yes
|0.6
|0.8847816568680239
|Yes
|0.8
|0.8841195749171925
|Yes
|0.9
|0.8455427675252052
|Yes
|0.95
|0.8455427675252052
|===

link:ai-protopia-obfuscation-speed.html[Next: Obfuscation speed.]
