---
sidebar: sidebar
permalink: ai/ai-protopia-where-to-find-additional-information,-acknowledgements,-and-version-history.html
keywords:
summary:
---

= Where to find additional information, acknowledgements, and version history
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-27 11:48:17.821553
//

link:ai-protopia-conclusion.html[Previous: Conclusion.]

[.lead]
To learn more about the information described in this document, refer to the following documents and/or websites:

* NetApp ONTAP data management software — ONTAP information library
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286^]

* NetApp Persistent Storage for Containers—NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[https://netapp.io/persistent-storage-provisioner-for-kubernetes/^]

* NetApp DataOps Toolkit
+
https://github.com/NetApp/netapp-dataops-toolkit[https://github.com/NetApp/netapp-dataops-toolkit^]

* NetApp Persistent Storage for Containers—NetApp Astra Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[https://netapp.io/persistent-storage-provisioner-for-kubernetes/^]

* Protopia AI—Confidential Inference
+
https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/[https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/^]

* NetApp Cloud Sync
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works[https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works^]

* NVIDIA Triton Inference Server
+
https://developer.nvidia.com/nvidia-triton-inference-server[https://developer.nvidia.com/nvidia-triton-inference-server^]

* NVIDIA Triton Inference Server Documentation
+
https://docs.nvidia.com/deeplearning/triton-inference-server/index.html[https://docs.nvidia.com/deeplearning/triton-inference-server/index.html^]

* FaceBoxes in PyTorch
+
https://github.com/zisianw/FaceBoxes.PyTorch[https://github.com/zisianw/FaceBoxes.PyTorch^]

== Acknowledgments

* Mark Cates, Principal Product Manager, NetApp
* Sufian Ahmad, Technical Marketing Engineer, NetApp
* Hadi Esmaeilzadeh, Chief Technology Officer and Professor, Protopia AI

== Version history

|===
|Version |Date |Document Version History

|Version 1.0
|May 2022
|Initial release.
|===
