---
sidebar: sidebar
permalink: ai/ai-sent-where-to-find-additional-information.html
keywords:
summary:
---

= Where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-10-25 11:10:26.115311
//

link:ai-sent-conclusion.html[Previous: Conclusion.]

[.lead]
To learn more about the information that is described in this document, review the following documents and/or websites:

* 3D interactive demos
+
http://www.netapp.com/ai[www.netapp.com/ai^]

* Connect directly with a NetApp AI specialist
+
https://www.netapp.com/artificial-intelligence/[https://www.netapp.com/artificial-intelligence/^]

* NVDIA Base Command Platform with NetApp solution brief
+
https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf[https://www.netapp.com/pdf.html?item=/media/32792-DS-4145-NVIDIA-Base-Command-Platform-with-NetApp.pdf^]

* NetApp for AI 10 Good Reasons infographic
+
https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf[https://www.netapp.com/us/media/netapp-ai-10-good-reasons.pdf^]

* AI in Healthcare: Deep learning to identify COVID-19 lesions in lung CT scans white paper
+
https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf[https://www.netapp.com/pdf.html?item=/media/31240-WP-7342.pdf^]

* AI in Healthcare: Monitoring face mask usage in healthcare settings white paper
+
https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf[https://www.netapp.com/pdf.html?item=/media/37490-NA-611-Monitoring-face-mask-usage-in-healthcare-settings.pdf^]

* AI in Healthcare: Diagnostic Imaging Technical Report
+
https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf[https://www.netapp.com/pdf.html?item=/media/7395-tr4811.pdf^]

* AI for Retail: NetApp Conversational AI using NVIDIA RIVA
+
https://docs.netapp.com/us-en/netapp-solutions/ai/cainvidia_executive_summary.html[https://docs.netapp.com/us-en/netapp-solutions/ai/cainvidia_executive_summary.html^]

* NetApp ONTAP AI solution brief
+
https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf[https://www.netapp.com/pdf.html?item=/media/6736-sb-3939.pdf^]

* NetApp DataOps Toolkit solution brief
+
https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf[https://www.netapp.com/pdf.html?item=/media/21480-SB-4111-1220-NA-Data-Science-Toolkit.pdf^]

* NetApp AI Control Plane solution brief
+
https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf[https://www.netapp.com/pdf.html?item=/media/6737-sb-4055.pdf^]

* Transforming Industry with Data Drive AI eBook
+
https://www.netapp.com/us/media/na-337.pdf[https://www.netapp.com/us/media/na-337.pdf^]

* NetApp EF-Series AI solution brief
+
https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf[https://www.netapp.com/pdf.html?item=/media/26708-SB-4136-NetApp-AI-E-Series.pdf^]

* NetApp AI and Lenovo ThinkSystem for AI Inferencing solution brief
+
https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf[https://www.netapp.com/pdf.html?item=/media/25316-SB-4129.pdf^]

* NetApp AI and Lenovo ThinkSystem for enterprise AI and ML solution brief
+
https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf[https://www.netapp.com/pdf.html?item=/media/25317-SB-4128.pdf^]

* NetApp and NVIDIA – Redefining What is Possible with AI video
+
https://www.youtube.com/watch?v=38xw65SteUc[https://www.youtube.com/watch?v=38xw65SteUc^]
