---
sidebar: sidebar
permalink: ai/aicp_where_to_find_additional_information.html
keywords: Additional, Information, references
summary: To learn more about the information that is described in this document, see the resources listed on this page.
---

= Where to Find Additional Information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:15.319139
//

[.lead]
To learn more about the information that is described in this document, see the following resources:

* NVIDIA DGX-1 servers:
** NVIDIA DGX-1 servers
+
https://www.nvidia.com/en-us/data-center/dgx-1/[https://www.nvidia.com/en-us/data-center/dgx-1/^]

** NVIDIA Tesla V100 Tensor Core GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[https://www.nvidia.com/en-us/data-center/tesla-v100/^]

** NVIDIA GPU Cloud (NGC)
+
https://www.nvidia.com/en-us/gpu-cloud/[https://www.nvidia.com/en-us/gpu-cloud/^]

* NetApp AFF systems:
** AFF datasheet
+
https://www.netapp.com/us/media/ds-3582.pdf[https://www.netapp.com/us/media/ds-3582.pdf^]

** NetApp FlashAdvantage for AFF
+
https://www.netapp.com/us/media/ds-3733.pdf[https://www.netapp.com/us/media/ds-3733.pdf^]

** ONTAP 9.x documentation
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286^]

** NetApp FlexGroup technical report
+
https://www.netapp.com/us/media/tr-4557.pdf[https://www.netapp.com/us/media/tr-4557.pdf^]

* NetApp persistent storage for containers:
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[https://netapp.io/persistent-storage-provisioner-for-kubernetes/^]

* NetApp Interoperability Matrix:
** NetApp Interoperability Matrix Tool
+
http://support.netapp.com/matrix[http://support.netapp.com/matrix^]

* ONTAP AI networking:
** Cisco Nexus 3232C Switches
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html^]

** Mellanox Spectrum 2000 series switches
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000^]

* ML framework and tools:
** DALI
+
https://github.com/NVIDIA/DALI[https://github.com/NVIDIA/DALI^]

** TensorFlow: An Open-Source Machine Learning Framework for Everyone
+
https://www.tensorflow.org/[https://www.tensorflow.org/^]

** Horovod: Uber’s Open-Source Distributed Deep Learning Framework for TensorFlow
+
https://eng.uber.com/horovod/[https://eng.uber.com/horovod/^]

** Enabling GPUs in the Container Runtime Ecosystem
+
https://devblogs.nvidia.com/gpu-containers-runtime/[https://devblogs.nvidia.com/gpu-containers-runtime/^]

** Docker
+
https://docs.docker.com[https://docs.docker.com^]

** Kubernetes
+
https://kubernetes.io/docs/home/[https://kubernetes.io/docs/home/^]

** NVIDIA DeepOps
+
https://github.com/NVIDIA/deepops[https://github.com/NVIDIA/deepops^]

** Kubeflow
+
http://www.kubeflow.org/[http://www.kubeflow.org/^]

** Jupyter Notebook Server
+
http://www.jupyter.org/[http://www.jupyter.org/^]

* Dataset and benchmarks:
** ImageNet
+
http://www.image-net.org/[http://www.image-net.org/^]

** COCO
+
http://cocodataset.org/[http://cocodataset.org/^]

** Cityscapes
+
https://www.cityscapes-dataset.com/[https://www.cityscapes-dataset.com/^]

** nuScenes
+
http://www.nuscenes.org[www.nuscenes.org^]

** SECOND: Sparsely Embedded Convolutional Detection model
+
https://pdfs.semanticscholar.org/5125/a16039cabc6320c908a4764f32596e018ad3.pdf[https://pdfs.semanticscholar.org/5125/a16039cabc6320c908a4764f32596e018ad3.pdf^]

** TensorFlow benchmarks
+
https://github.com/tensorflow/benchmarks[https://github.com/tensorflow/benchmarks^]
