---
sidebar: sidebar
permalink: ai/aicp_hardware_and_software_requirements.html
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu
summary: Open Source MLOps with NetApp - Architecture
---

= Architecture
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:11.619251
//

[.lead]
This solution is not dependent on this specific hardware. The solution is compatible with any NetApp physical storage appliance, software-defined instance, or cloud service, that is supported by Trident. Examples include a NetApp AFF storage system, Amazon FSx for NetApp ONTAP, Azure NetApp Files, or a NetApp Cloud Volumes ONTAP instance. Additionally, the solution can be implemented on any Kubernetes cluster as long as the Kubernetes version used is supported by Kubeflow and NetApp Astra Trident. For a list of Kubernetes versions that are supported by Kubeflow, see the see the https://www.kubeflow.org/docs/started/getting-started/[official Kubeflow documentation^]. For a list of Kubernetes versions that are supported by Trident, see the https://docs.netapp.com/us-en/trident/index.html[Trident documentation^]. See the following tables for details on the environment that was used to validate the solution.

|===
|Software Component |Version

|Apache Airflow
|2.0.1
|Apache Airflow Helm Chart
|8.0.8
|Kubeflow
|1.7, deployed via link:https://www.deploykf.org[deployKF] 0.1.1
|Kubernetes
|1.26
|NetApp Astra Trident
|23.07
|===

== Support
NetApp does not offer enterprise support for Apache Airflow, Kubeflow, or Kubernetes. If you are interested in a fully supported MLOps platform, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us[contact NetApp] about fully supported MLOps solutions that NetApp offers jointly with partners.
