---
sidebar: sidebar
permalink: ai/aicp_performance_testing.html
keywords: Performance, Testing, benchmark, Tensorflow, Docker
summary:
---

= Performance Testing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:15.262319
//

[.lead]
We performed a simple performance comparison as part of the creation of this solution. We executed several standard NetApp benchmarking jobs by using Kubernetes, and we compared the benchmark results with executions that were performed by using a simple Docker run command. We did not see any noticeable differences in performance. Therefore, we concluded that the use of Kubernetes to orchestrate containerized jobs does not adversely affect performance. See the following table for the results of our performance comparison.

|===
|Benchmark |Dataset |Docker Run (images/sec) |Kubernetes (images/sec)

|Single-node TensorFlow
|Synthetic data
|6,667.2475
|6,661.93125
|Single-node TensorFlow
|ImageNet
|6,570.2025
|6,530.59125
|Synchronous distributed two-node TensorFlow
|Synthetic data
|13,213.70625
|13,218.288125
|Synchronous distributed two-node TensorFlow
|ImageNet
|12,941.69125
|12,881.33875
|===

link:aicp_conclusion.html[Next: Conclusion]
