---
sidebar: sidebar
permalink: ai/aicp_hardware_and_software_requirements.html
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu
summary: Open Source MLOps with NetApp - Architecture
---

= Architecture
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:11.619251
//

[.lead]
This solution is not dependent on specific hardware. The solution is compatible with any NetApp physical storage appliance, software-defined instance, or cloud service, that is supported by NetApp Astra Trident. Examples include a NetApp AFF storage system, Amazon FSx for NetApp ONTAP, Azure NetApp Files, Google Cloud NetApp Volumes, or a NetApp Cloud Volumes ONTAP instance. Additionally, the solution can be implemented on any Kubernetes cluster as long as the Kubernetes version used is supported by NetApp Astra Trident and the other solution components that are being implemented. For a list of Kubernetes versions that are supported by Trident, see the https://docs.netapp.com/us-en/trident/index.html[Trident documentation^]. See the following tables for details on the environments that were used to validate the various components of this solution.

== Apache Airflow Validation Environment

|===
|Software Component |Version

|Apache Airflow
|2.0.1, deployed via link:https://artifacthub.io/packages/helm/airflow-helm/airflow[Apache Airflow Helm chart^] 8.0.8
|Kubernetes
|1.18
|NetApp Astra Trident
|21.01
|===

== JupyterHub Validation Environment

|===
|Software Component |Version

|JupyterHub
|4.1.5, deployed via link:https://hub.jupyter.org/helm-chart/[JupyterHub Helm chart^] 3.3.7
|Kubernetes
|1.29
|NetApp Astra Trident
|24.02
|===

== MLflow Validation Environment

|===
|Software Component |Version

|MLflow
|2.14.1, deployed via link:https://artifacthub.io/packages/helm/bitnami/mlflow[MLflow Helm chart^] 1.4.12
|Kubernetes
|1.29
|NetApp Astra Trident
|24.02
|===

== Kubeflow Validation Environment

|===
|Software Component |Version

|Kubeflow
|1.7, deployed via link:https://www.deploykf.org[deployKF^] 0.1.1
|Kubernetes
|1.26
|NetApp Astra Trident
|23.07
|===

== Support
NetApp does not offer enterprise support for Apache Airflow, JupyterHub, MLflow, Kubeflow, or Kubernetes. If you are interested in a fully supported MLOps platform, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us[contact NetApp^] about fully supported MLOps solutions that NetApp offers jointly with partners.
