---
sidebar: sidebar
permalink: ai/aicp_jupyterhub_deployment.html
keywords: AI, control plane, MLOps, JupyterHub
summary: Open Source MLOps with NetApp - JupyterHub Deployment
---

= JupyterHub Deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
This section describes the tasks that you must complete to deploy JupyterHub in your Kubernetes cluster.

[NOTE]
It is possible to deploy JupyterHub on platforms other than Kubernetes. Deploying JupyterHub on platforms other than Kubernetes is outside of the scope of this solution.

== Prerequisites

Before you perform the deployment exercise that is outlined in this section, we assume that you have already performed the following tasks:

. You already have a working Kubernetes cluster.
. You have already installed and configured NetApp Astra Trident in your Kubernetes cluster. For more details on Astra Trident, refer to the link:https://docs.netapp.com/us-en/trident/index.html[Astra Trident documentation].

== Install Helm

JupyterHub is deployed using Helm, a popular package manager for Kubernetes. Before you deploy JupyterHub, you must install Helm on your Kubernetes control node. To install Helm, follow the https://helm.sh/docs/intro/install/[installation instructions^] in the official Helm documentation.

== Set Default Kubernetes StorageClass

Before you deploy JupyterHub, you must designate a default StorageClass within your Kubernetes cluster. To designate a default StorageClass within your cluster, follow the instructions outlined in the link:aicp_kubeflow_deployment_overview.html[Kubeflow Deployment] section. If you have already designated a default StorageClass within your cluster, then you can skip this step.

== Deploy JupyterHub
# TODO - Sufian to complete
