---
sidebar: sidebar
permalink: ai/aicp_hardware_and_software_requirements.html
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu
summary: This verified architecture pairs a NetApp AFF A800 all-flash storage system with the NVIDIA DGX-1 Deep Learning System using Cisco Nexus networking.
---

= Hardware and Software Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:11.619251
//

[.lead]
The NetApp AI Control Plane solution that is outlined in this document is not dependent on this specific hardware. The solution is compatible with any NetApp physical storage appliance, software-defined instance, or cloud service, that is supported by Trident. Examples include a NetApp AFF storage system, Azure NetApp Files, NetApp Cloud Volumes Service, a NetApp ONTAP Select software-defined storage instance, or a NetApp Cloud Volumes ONTAP instance. Additionally, the solution can be implemented on any Kubernetes cluster as long as the Kubernetes version used is supported by Kubeflow and NetApp Trident. For a list of Kubernetes versions that are supported by Kubeflow, see the see the https://www.kubeflow.org/docs/started/getting-started/[official Kubeflow documentation^]. For a list of Kubernetes versions that are supported by Trident, see the https://netapp-trident.readthedocs.io/[Trident documentation^]. See the following tables for details on the environment that was used to validate the solution.

|===
|Infrastructure Component |Quantity |Details |Operating System

|Deployment jump host
|1
|VM
|Ubuntu 20.04.2 LTS
|Kubernetes master nodes
|1
|VM
|Ubuntu 20.04.2 LTS
|Kubernetes worker nodes
|2
|VM
|Ubuntu 20.04.2 LTS
|Kubernetes GPU worker nodes
|2
|NVIDIA DGX-1 (bare-metal)
|NVIDIA DGX OS 4.0.5
(based on Ubuntu 18.04.2 LTS)
|Storage
|1 HA Pair
|NetApp AFF A220
|NetApp ONTAP 9.7 P6
|===

|===
|Software Component |Version

|Apache Airflow
|2.0.1
|Apache Airflow Helm Chart
|8.0.8
|Docker
|19.03.12
|Kubeflow
|1.2
|Kubernetes
|1.18.9
|NetApp Trident
|21.01.2
|NVIDIA DeepOps
|Trident deployment functionality from master branch as of commit link:https://github.com/NVIDIA/deepops/tree/61898cdfdaa0c59c07e9fabf3022945a905b148e/docs/k8s-cluster[61898cdfda]; All other functionality from version 21.03
|===

=== Support
NetApp does not offer enterprise support for Apache Airflow, Docker, Kubeflow, Kubernetes, or NVIDIA DeepOps. If you are interested in a fully supported solution with capabilities similar to the NetApp AI Control Plane solution, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us[contact NetApp] about fully supported AI/ML solutions that NetApp offers jointly with partners.

link:aicp_kubernetes_deployment.html[Next: Kubernetes Deployment].
