---
sidebar: sidebar
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html
keywords: Trident, Kubernetes, Storageclass
summary: This page describes the tasks that you must complete to install and configure NetApp Trident in your Kubernetes cluster.
---

= NetApp Trident Deployment and Configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:11.732671
//

[.lead]
This section describes the tasks that you must complete to install and configure NetApp Trident in your Kubernetes cluster.

== Prerequisites

Before you perform the deployment exercise that is outlined in this section, we assume that you have already performed the following tasks:

. You already have a working Kubernetes cluster, and you are running a version of Kubernetes that is supported by Trident. For a list of supported versions, see the https://docs.netapp.com/us-en/trident/[Trident documentation^].
. You already have a working NetApp storage appliance, software-defined instance, or cloud storage service, that is supported by Trident.

== Install Trident

To install and configure NetApp Trident in your Kubernetes cluster, perform the following tasks from the deployment jump host:

. Deploy Trident using one of the following methods:
- If you used NVIDIA DeepOps to deploy your Kubernetes cluster, you can also use NVIDIA DeepOps to deploy Trident in your Kubernetes cluster. To deploy Trident with DeepOps, follow the https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#netapp-trident[Trident deployment instructions] on the NVIDIA DeepOps GitHub site.
- If you did not use NVIDIA DeepOps to deploy your Kubernetes cluster or if you simply prefer to deploy Trident manually, you can deploy Trident by following the https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html[deployment instructions^] in the Trident documentation. Be sure to create at least one Trident Backend and at least one Kubernetes StorageClass, for more information about how to configure https://docs.netapp.com/us-en/trident/trident-use/backends.html[Backends^] and https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html[StorageClasses^] see the linked subsections at NetApp Docs.
[NOTE]
If you are deploying the NetApp AI Control Plane solution on an ONTAP AI pod, see link:aicp_example_trident_backends_for_ontap_ai_deployments.html[Example Trident Backends for ONTAP AI Deployments] for some examples of different Trident Backends that you might want to create and link:aicp_example_kubernetes_storageclasses_for_ontap_ai_deployments.html[Example Kubernetes Storageclasses for ONTAP AI Deployments] for some examples of different Kubernetes StorageClasses that you might want to create.

link:aicp_example_trident_backends_for_ontap_ai_deployments.html[Next: Example Trident Backends for ONTAP AI Deployments.]
