---
sidebar: sidebar
permalink: ai/aicp_example_notebooks_and_pipelines.html
keywords: Jupyter Notebook, Kubeflow Pipeline, NetApp DataOps Toolkit
summary: Open Source MLOps with NetApp - Use the NetApp DataOps Toolkit with Kubeflow
---

= Use the NetApp DataOps Toolkit with Kubeflow
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:12.786137
//

[.lead]
The https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s[NetApp Data Science Toolkit for Kubernetes] can be used in conjunction with Kubeflow. Using the NetApp Data Science Toolkit with Kubeflow provides the following benefits:

* Data scientists can perform advanced NetApp data management operations, such as creating snapshots and clones, directly from within a Jupyter Notebook.
* Advanced NetApp data management operations, such as creating snapshots and clones, can be incorporated into automated workflows using the Kubeflow Pipelines framework.

Refer to the https://github.com/NetApp/netapp-dataops-toolkit/tree/main/netapp_dataops_k8s/Examples/Kubeflow[Kubeflow Examples] section within the NetApp Data Science Toolkit GitHub repository for details on using the toolkit with Kubeflow.
