---
sidebar: sidebar
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html
keywords: Trident, Kubernetes, Storageclass
summary: This page describes the tasks that you must complete to install and configure NetApp Trident in your Kubernetes cluster.
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-18 15:53:11.732671
//

[.lead]
This section describes the tasks that you must complete to install and configure NetApp Trident in your Kubernetes cluster.

== Prerequisites

Before you perform the deployment exercise that is outlined in this section, we assume that you have already performed the following tasks:

. You already have a working Kubernetes cluster, and you are running a version of Kubernetes that is supported by Trident. For a list of supported versions, see the https://netapp-trident.readthedocs.io/[Trident documentation^].
. You already have a working NetApp storage appliance, software-defined instance, or cloud storage service, that supports the NFS protocol.

== Install Trident

To install and configure NetApp Trident in your Kubernetes cluster, perform the following tasks from the deployment jump host:

. Deploy Trident for Kubernetes in your cluster by following the https://netapp-trident.readthedocs.io/[deployment instructions^] in the Trident documentation. Be sure to create at least one Trident Backend and at least one Kubernetes StorageClass. For more information about Backends and StorageClasses, see the https://netapp-trident.readthedocs.io/[Trident documentation^].

[NOTE]
If you are deploying the NetApp AI Control Plane solution on an ONTAP AI pod, see link:aicp_netapp_trident_deployment_and_configuration_overview.html[Trident Deployment and Configuration] for some examples of different Trident Backends that you might want to create and for some examples of different Kubernetes StorageClasses that you might want to create.

link:ai/aicp_example_trident_backends_for_ontap_ai_deployments.html[Next: Example Trident Backends for ONTAP AI Deployments]
