---
sidebar: sidebar
permalink: ai/aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html
keywords: toolkit, dataops, kubernetes, abstraction, python, jupyterlab
summary: The NetApp DataOps Toolkit for Kubernetes abstracts storage resources and Kubernetes workloads up to the data-science workspace level. These capabilities are packaged in a simple, easy-to-use interface that is designed for data scientists and data engineers.
---

= Dataset and model versioning using NetApp DataOps Toolkit
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-08-12 10:46:35.706837
//

link:aks-anf_monitor_dask_and_rapids_with_prometheus_and_grafana.html[Previous: Monitor Dask and RAPIDS with Prometheus and Grafana.]

[.lead]
The NetApp DataOps Toolkit for Kubernetes abstracts storage resources and Kubernetes workloads up to the data-science workspace level. These capabilities are packaged in a simple, easy-to-use interface that is designed for data scientists and data engineers. Using the familiar form of a Python program, the Toolkit enables data scientists and engineers to provision and destroy JupyterLab workspaces in just seconds. These workspaces can contain terabytes, or even petabytes, of storage capacity, enabling data scientists to store all their training datasets directly in their project workspaces. Gone are the days of separately managing workspaces and data volumes.

For more information, visit the Toolkit’s https://github.com/NetApp/netapp-data-science-toolkit[GitHub repository^].

link:aks-anf_conclusion.html[Next: Conclusion.]
