---
sidebar: sidebar
permalink: ai/aks-anf_click-through_rate_prediction_use_case_summary.html
keywords: use case, terabyte click log, random forest, training
summary: This page summarizes Azure NetApp Files advantages in distributed or large-scale training.
---

= Click-through rate prediction use case summary
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-08-12 10:46:35.608877
//

link:aks-anf_cloud_resource_requirements.html[Previous: Cloud resource requirements.]

This use case is based on the publicly available http://labs.criteo.com/2013/12/download-terabyte-click-logs/[Terabyte Click Logs^] dataset from https://ailab.criteo.com/[Criteo AI Lab^]. With the recent advances in ML platforms, a lot of attention is now on learning at scale. In this context, Terabyte Click Logs is now the dataset of reference in assessing the scalability of ML platforms and algorithms. By predicting the click-through rate, an advertiser can select the most plausible visitors who are most likely to respond to the ads, analyzing their browsing history, and showing the most relevant ads based on the interests of the user.

This solution provided in this technical report highlights the following benefits:

* Azure NetApp Files advantages in distributed or large-scale training
* RAPIDS CUDA-enabled data processing (cuDF, cuPy, and so on) and ML algorithms (cuML)
* Dask parallel computing framework for distributed training

The collaborative relationship between Dask and Azure NetApp Files demonstrates the drastic improvement in random forest model training time by two orders of magnitude. This improvement is comparable to the conventional Pandas approach when dealing with real-world click logs data with 45GB of text (on average) each day.

link:aks-anf_install_and_set_up_the_aks_cluster.html[Next: Install and set up the aks cluster.]
