---
sidebar: sidebar
permalink: ai/aks-anf_conclusion.html
keywords: Azure NetApp Files, RAPIDS AI, click-though rate (CTR) prediction, Machine Learning, Retail, E-commerce, Azure, Jupyter Notebook, Cloud computing, Digital marketing, Kubernetes
summary: Azure NetApp Files, RAPIDS, and Dask speed up and simplify the deployment of large-scale ML processing and training, integrated with orchestration tools such as Docker and Kubernetes. By unifying the end-to-end data pipeline, this solution reduces the latency and complexity inherent in many advanced computing workloads, effectively bridging the gap between development and operations.
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-08-12 10:46:35.710395
//

link:aks-anf_dataset_and_model_versioning_using_netapp_dataops_toolkit.html[Previous: Dataset and Model Versioning using NetApp DataOps Toolkit.]

Azure NetApp Files, RAPIDS, and Dask speed up and simplify the deployment of large-scale ML processing and training, integrated with orchestration tools such as Docker and Kubernetes. By unifying the end-to-end data pipeline, this solution reduces the latency and complexity inherent in many advanced computing workloads, effectively bridging the gap between development and operations. Data scientists can run queries on large datasets and securely share data and algorithmic models with other users during the training phase.

When building your own AI/ML pipelines, configuring the integration, management, security, and accessibility of the components in an architecture is a challenging task. Giving developers access and control of their environment presents another set of challenges.

The combination of NetApp and NVIDIA brings these technologies together as managed services to accelerate technology adoption and improve the time to market for new AI/ML applications. These advanced services are also delivered in a cloud native environment which can be easily ported for on-premises deployment.

link:aks-anf_where_to_find_additional_information.html[Next: Where to find additional information.]
