---
sidebar: sidebar
permalink: ai/cainvidia_executive_summary.html
keywords: WP-7328, wp7328, 7328, Executive Summary, NVIDIA, Jarvis,
summary:
---

= WP-7328: NetApp Conversational AI Using NVIDIA Jarvis
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-21 13:44:46.337348
//

Rick Huang, Sung-Han Lin, NetApp
Davide Onofrio, NVIDIA

[.lead]
The NVIDIA DGX family of systems is made up of the world's first integrated artificial intelligence (AI)-based systems that are purpose-built for enterprise AI. NetApp AFF storage systems deliver extreme performance and industry-leading hybrid cloud data-management capabilities. NetApp and NVIDIA have partnered to create the NetApp ONTAP AI reference architecture, a turnkey solution for AI and machine learning (ML) workloads that provides enterprise-class performance, reliability, and support.

This white paper gives directional guidance to customers building conversational AI systems in support of different use cases in various industry verticals. It includes information about the deployment of the system using NVIDIA Jarvis. The tests were performed using an NVIDIA DGX Station and a NetApp AFF A220 storage system.

The target audience for the solution includes the following groups:

* Enterprise architects who design solutions for the development of AI models and software for conversational AI use cases such as a virtual retail assistant
* Data scientists looking for efficient ways to achieve language modeling development goals
* Data engineers in charge of maintaining and processing text data such as customer questions and dialogue transcripts
* Executive and IT decision makers and business leaders interested in transforming the conversational AI experience and achieving the fastest time to market from AI initiatives

link:cainvidia_solution_overview.html[Next: Solution Overview]
