---
sidebar: sidebar
permalink: ai/dataops-toolkit.html
keywords: 
summary: 
---

= NetApp DataOps Toolkit
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
The NetApp DataOps Toolkit is a Python-based tool that simplifies the management of development/training workspaces and inference servers that are backed by high-performance, scale-out NetApp storage. Key capabilities include:

* Rapidly provision new high-capacity JupyterLab workspaces that are backed by high-performance, scale-out NetApp storage.
* Rapidly provision new NVIDIA Triton Inference Server instances that are backed by enterprise-class NetApp storage.
* Near-instantaneously clone high-capacity JupyterLab workspaces in order to enable experimentation or rapid iteration.
* Near-instantaneously save snapshots of high-capacity JupyterLab workspaces for backup and/or traceability/baselining.
* Near-instantaneously provision, clone, and snapshot high-capacity, high-performance data volumes.

link:https://github.com/NetApp/netapp-dataops-toolkit[NetApp DataOps Toolkit^] 