---
sidebar: sidebar
permalink: ai/ddlnexus_initial_setup.html
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, Hybrid, Hybrid Cloud, Hybrid Multicloud, Cloud, AWS, Amazon, Amazon Web Services, FSx for NetApp ONTAP, FSx, NetApp ONTAP, FlexCache, SnapMirror, BlueXP
summary: Hybrid Multicloud MLOps with Domino Data Lab and NetApp - Initial Setup
---

= Initial Setup
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

link:ddlnexus_architecture.html[Previous: Architecture.]

[.lead]
This section describes the initial setup tasks that need to be performed in order to utilize Domino Nexus with NetApp data services in a hybrid environment incorporating an on-premises data center and AWS.

== Prerequisites

Before you perform the steps that are outlined in this section, we assume that you have already performed the following tasks:

- You have already deployed and configured your on-premises NetApp ONTAP storage platform. For more information, refer to the link:https://www.netapp.com/support-and-training/documentation/[NetApp product documentation].
- You have already provisioned an Amazon FSx for NetApp ONTAP instance in AWS. For more information, refer to the link:https://aws.amazon.com/fsx/netapp-ontap/[Amazon FSx for NetApp ONTAP product page].
- You have already provisioned a Kubernetes cluster in your on-premises data center. For more information, refer to the link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/[Domino admin guide].
- You have already provisioned an Amazon EKS cluster in AWS. For more information, refer to the link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/[Domino admin guide].
- You have installed NetApp Astra Trident in your on-premises Kubernetes cluster. Additionally, you have configured this Trident instance to use your on-premises NetApp ONTAP storage platform when provisioning and managing storage resources. For more information, refer to the link:https://docs.netapp.com/us-en/trident/index.html[NetApp Astra Trident documentation].
- You have installed NetApp Astra Trident in your Amazon EKS cluster. Additionally, you have configured this Trident instance to use your Amazon FSx for NetApp ONTAP instance when provisioning and managing storage resources. For more information, refer to the link:https://docs.netapp.com/us-en/trident/index.html[NetApp Astra Trident documentation].
- You must have bi-directional network connectivity between your on-premises data center and your Virtual Private Cloud (VPC) in AWS. For more details on the various options for implementing this, refer to the link:https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html[Amazon Virtual Private Network (VPN) documentation]. 

== Install the Domino Enterprise AI Platform in AWS

To install the Domino Enterprise MLOps Platform in AWS, follow the instructions outlined in link:https://docs.dominodatalab.com/en/latest/admin_guide/c1eec3/deploy-domino/[Domino admin guide]. You must deploy Domino in the same Amazon EKS cluster that you previously provisioned. Additionally, NetApp Astra Trident must already be installed and configured in this EKS cluster, and you must specify a Trident-managed storage class as the shared storage class in your domino.yml install configuration file.

[NOTE]
Refer to the link:https://docs.dominodatalab.com/en/latest/admin_guide/7f4331/install-configuration-reference/#storage-classes[Domino install configuration reference guide] for details on how to specify a shared storage class in your domino.yml install configuration file.

[NOTE]
link:https://www.netapp.com/media/79922-tr-4952.pdf[Technical Report TR-4952] walks through the deployment of Domino in AWS with Amazon FSx for NetApp ONTAP and may be a useful reference for troubleshooting any issues that arise.

== Enable Domino Nexus

Next, you must enable Domino Nexus. Refer to the link:https://docs.dominodatalab.com/en/latest/admin_guide/c65074/nexus-hybrid-architecture/[Domino admin guide] for details.

== Deploy a Domino Data Plane in your On-premises Data Center

Next, you must deploy a Domino Data Plane in your on-premises data center. You must deploy this data plane in the on-premises Kubernetes cluster that you previously provisioned. Additionally, NetApp Astra Trident must already be installed and configured in this Kubernetes cluster. Refer to the link:https://docs.dominodatalab.com/en/latest/admin_guide/5781ea/data-planes/[Domino admin guide] for details.

link:ddlnexus_expose_netapp_vols.html[Next: Expose Existing NetApp Volumes to Domino.]