---
sidebar: sidebar
permalink: ai/hcaios_ontap_ai_deployment.html
keywords: ONTAP AI, Deployment, networking, compute, storage
summary:
---

= ONTAP AI Deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-20 13:35:29.821359
//

[.lead]
Deployment of ONTAP AI requires the installation and configuration of networking, compute, and storage hardware. Specific instructions for deployment of the ONTAP AI infrastructure are beyond the scope of this document. For detailed deployment information, see https://www.netapp.com/us/media/nva-1121-deploy.pdf[NVA-1121-DEPLOY: NetApp ONTAP AI, Powered by NVIDIA^].

For this solution validation, a single volume was created and mounted to the DGX-1 system. That mount point was then mounted to the containers to make data accessible for training. For large-scale deployments, NetApp Trident automates the creation and mounting of volumes to eliminate administrative overhead and enable end-user management of resources.

link:ai/hcaios_kubernetes_deployment.html[Next: Kubernetes Deployment]
