---
sidebar: sidebar
permalink: ai/hcaios_kubernetes_deployment.html
keywords: Kubernetes, Deployment, NVIDIA, DeepOps
summary:
---
= Kubernetes Deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-20 13:35:29.840557
//

[.lead]
To deploy and configure your Kubernetes cluster with NVIDIA DeepOps, perform the following tasks from a deployment jump host:

. Download NVIDIA DeepOps by following the instructions on the https://github.com/NVIDIA/deepops/blob/master/docs/getting-started.md[Getting Started page^] on the NVIDIA DeepOps GitHub site.
. Deploy Kubernetes in your cluster by following the instructions on the https://github.com/NVIDIA/deepops/blob/master/docs/kubernetes-cluster.md[Kubernetes Deployment Guide^] on the NVIDIA DeepOps GitHub site.

[NOTE]
For the DeepOps Kubernetes deployment to work, the same user must exist on all Kubernetes master and worker nodes.

If the deployment fails, change the value of `kubectl_localhost` to false in `deepops/config/group_vars/k8s-cluster.yml` and repeat step 2. The `Copy kubectl binary to ansible host` task, which executes only when the value of `kubectl_localhost` is true, relies on the fetch Ansible module, which has known memory usage issues. These memory usage issues can sometimes cause the task to fail. If the task fails because of a memory issue, then the remainder of the deployment operation does not complete successfully.

If the deployment completes successfully after you have changed the value of `kubectl_localhost` to `false`, then you must manually copy the `kubectl binary` from a Kubernetes master node to the deployment jump host. You can find the location of the `kubectl binary` on a specific master node by running the `which kubectl` command directly on that node.

