---
sidebar: sidebar
permalink: ai/hcaios_where_to_find_additional_information.html
keywords: NetApp Additional Information
summary:
---

= Where to Find Additional Information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-20 13:35:30.127404
//

[.lead]
To learn more about the information that is described in this document, see the following resources:

* Cnvrg.io ( https://cnvrg.io[https://cnvrg.io^]):
** Cnvrg CORE (free ML platform)
+
https://cnvrg.io/platform/core

** Cnvrg docs
+
https://app.cnvrg.io/docs[https://app.cnvrg.io/docs^]

* NVIDIA DGX-1 servers:
** NVIDIA DGX-1 servers
+
https://www.nvidia.com/en-us/data-center/dgx-1/
** NVIDIA Tesla V100 Tensor Core GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/
** NVIDIA GPU Cloud (NGC)
+
https://www.nvidia.com/en-us/gpu-cloud/
* NetApp AFF systems:
** AFF datasheet
+
https://www.netapp.com/us/media/d-3582.pdf
** NetApp FlashAdvantage for AFF
+
https://www.netapp.com/us/media/ds-3733.pdf

** ONTAP 9.x documentation
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286

** NetApp FlexGroup technical report
+
https://www.netapp.com/us/media/tr-4557.pdf
* NetApp persistent storage for containers:
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/

* NetApp Interoperability Matrix:
** NetApp Interoperability Matrix Tool
+
http://support.netapp.com/matrix
* ONTAP AI networking:
** Cisco Nexus 3232C Switches
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html
** Mellanox Spectrum 2000 series switches
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000
* ML framework and tools:
** DALI
+
https://github.com/NVIDIA/DALI
** TensorFlow: An Open-Source Machine Learning Framework for Everyone
+
https://www.tensorflow.org/

** Horovod: Uber’s Open-Source Distributed Deep Learning Framework for TensorFlow
+
https://eng.uber.com/horovod/

** Enabling GPUs in the Container Runtime Ecosystem
+
https://devblogs.nvidia.com/gpu-containers-runtime/

** Docker
+
https://docs.docker.com

** Kubernetes
+
https://kubernetes.io/docs/home/

** NVIDIA DeepOps
+
https://github.com/NVIDIA/deepops
** Kubeflow
+
http://www.kubeflow.org/
** Jupyter Notebook Server
+
http://www.jupyter.org/

* Dataset and benchmarks:
** NIH chest X-ray dataset
+
https://nihcc.app.box.com/v/ChestXray-NIHCC

** Xiaosong Wang, Yifan Peng, Le Lu, Zhiyong Lu, Mohammadhadi Bagheri, Ronald Summers, ChestX-ray8: Hospital-scale Chest X-ray Database and Benchmarks on Weakly-Supervised Classification and Localization of Common Thorax Diseases, IEEE CVPR, pp. 3462-3471, 2017TR-4841-0620
