---
sidebar: sidebar
permalink: ai/hciai_edge_virtual_infrastructure_with_automated_deployment.html
keywords:
summary:
---

= Deploy VMware Virtual Infrastructure on NetApp HCI with NDE (Automated Deployment)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-29 18:13:42.706400
//

[.lead]
== NDE Deployment Prerequisites

Consult the https://library.netapp.com/ecm/ecm_download_file/ECMLP2798490[NetApp HCI Prerequisites Checklist^] to see the requirements and recommendations for NetApp HCI before you begin deployment.

. Network and switch requirements and configuration
. Prepare required VLAN IDs
. Switch configuration
. IP Address Requirements for NetApp HCI and VMware
. DNS and time-keeping requirements
. Final preparations

== NDE Execution

Before you execute the NDE, you must complete the rack and stack of all components, configuration of the network switches, and verification of all prerequisites. You can execute NDE by connecting to the management address of a single storage node if you plan to allow NDE to automatically configure all addresses.

NDE performs the following tasks to bring an HCI system online:

. Installs the storage node (NetApp Element software) on a minimum of two storage nodes.
. Installs the VMware hypervisor on a minimum of two compute nodes.
. Installs VMware vCenter to manage the entire NetApp HCI stack.
. Installs and configures the NetApp storage management node (mNode) and NetApp Monitoring Agent.
+
[NOTE]
This validation uses NDE to automatically configure all addresses. You can also set up DHCP in your environment or manually assign IP addresses for each storage node and compute node. These steps are not covered in this guide.
+

As mentioned previously, this validation uses a two-cable configuration for compute nodes.
+

Detailed steps for the NDE are not covered in this document.
+
For step-by-step guidance on completing the deployment of the base NetApp HCI platform, see the http://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-180/home.html?cp=3_0[Deployment guide^].

. After NDE has finished, login to the vCenter and create a Distributed Port Group `NetApp HCI VDS 01-NFS_Network` for the NFS network to be used by ONTAP Select and the application.

link:hciai_edge_netapp_h615cmanual_deployment.html[Next: Configure NetApp H615c (Manual Deployment)]
