---
sidebar: sidebar
permalink: ai/mlops_fsxn_intro.html
keywords: FSxN, AWS S3, SageMaker, MLOps, NetApp ONTAP
summary: This is the introductory page to the FSxN MLOps section.
---

= AWS FSx for NetApp ONTAP (FSxN) for MLOps
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:highlighter: rouge
:imagesdir: ./../media/

[.lead]
*Author(s):* 
Jian Jian (Ken), Senior Data & Applied Scientist, NetApp

This section delves into the practical application of AI infrastructure development, providing an end-to-end walkthrough of constructing an MLOps pipeline using FSxN. Comprising three comprehensive examples, it guides you to meet your MLOps needs via this powerful data management platform.

These articles focus on:

1. Loading and managing large datasets in FSxN, an essential step in preparing for machine learning operations.
2. Training data models efficiently using the data stored in FSxN.
3. Building a Continuous Integration, Continuous Training, and Continuous Deployment (CI/CT/CD) pipeline to tackle complex issues often faced in computer vision projects.

By the end of this section, you will have gained a solid understanding of how to use FSxN to streamline MLOps processes.