---
sidebar: sidebar
permalink: ai/mlops_fsxn_intro.html
keywords: FSxN, AWS S3, SageMaker, MLOps, NetApp ONTAP
summary: This is the introductory page to the FSxN MLOps section.
---

= AWS FSx for NetApp ONTAP (FSxN) for MLOps
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:highlighter: rouge
:imagesdir: ./../media/

[.lead]
*Author(s):* 
Jian Jian (Ken), Senior Data & Applied Scientist, NetApp

This section delves into the practical application of AI infrastructure development, providing an end-to-end walkthrough of constructing an MLOps pipeline using FSxN. Comprising three comprehensive examples, it guides you to meet your MLOps needs via this powerful data management platform.

These articles focus on:

1. link:./mlops_fsxn_s3_integration.html[Part 1 - Integrating AWS FSx for NetApp ONTAP (FSxN) as a private S3 bucket into AWS SageMaker]
2. link:./mlops_fsxn_sagemaker_integration_training.html[Part 2 - Leveraging AWS FSx for NetApp ONTAP (FSxN) as a Data Source for Model Training in SageMaker]
3. link:./mlops_fsxn_cictcd.html[Part 3 - Building A Simplified MLOps Pipeline (CI/CT/CD)]

By the end of this section, you will have gained a solid understanding of how to use FSxN to streamline MLOps processes.