---
sidebar: sidebar
permalink: ai/mlrun_software_and_hardware_requirements.html
keywords: NetApp, Software, Hardware, Network, Requirements
summary:
---

= Software and Hardware Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-19 15:22:25.605000
//

[.lead]
== Network Configuration

The following is the network configuration requirement for setting up in the cloud:

* The Iguazio cluster and NetApp Cloud Volumes must be in the same virtual private cloud.
* The cloud manager must have access to port 6443 on the Iguazio app nodes.
* We used Amazon Web Services in this technical report. However, users have the option of deploying the solution in any Cloud provider.For on-premises testing in ONTAP AI with NVIDIA DGX-1, we used the Iguazio hosted DNS service for convenience.

Clients must be able to access dynamically created DNS domains. Customers can use their own DNS if desired.

== Hardware Requirements

You can install Iguazio on-premises in your own cluster. We have verified the solution in NetApp ONTAP AI with an NVIDIA DGX-1 system. The following table lists the hardware used to test this solution.

|===
|Hardware |Quantity

|DGX-1 systems
|1
|NetApp AFF A800 system
|1 high-availability (HA) pair, includes 2 controllers and 48 NVMe SSDs (3.8TB or above)
|Cisco Nexus 3232C network switches
|2
|===

The following table lists the software components required for on-premise testing:

|===
|Software |Version or Other Information

|NetApp ONTAP data management software
|9.7
|Cisco NX-OS switch firmware
|7.0(3)I6(1)
|NVIDIA DGX OS
|4.4 - Ubuntu 18.04 LTS
|Docker container platform
|19.03.5
|Container version
|20.01-tf1-py2
|Machine learning framework
|TensorFlow 1.15.0
|Iguazio
|Version 2.8+
|ESX Server
|6.5
|===

This solution was fully tested with Iguazio version 2.5 and NetApp Cloud Volumes ONTAP for AWS. The Iguazio cluster and NetApp software are both running on AWS.

|===
|Software |Version or Type

|Iguazio
|Version 2.8+
|App node
|M5.4xlarge
|Data node
|I3.4xlarge
|===

link:mlrun_network_device_failure_prediction_use_case_summary.html[Next: Network Device Failure Prediction Use Case Summary]
