---
sidebar: sidebar
permalink: ai/nva-1153-design-link.html
keywords: 
summary: 
---

= NVA-1153-DESIGN: NetApp ONTAP AI with NVIDIA DGX A100 systems and Mellanox Spectrum Ethernet switches
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

David Arnette and Sung-Han Lin, NetApp

[.lead]
NVA-1153-DESIGN describes a NetApp Verified Architecture for machine learning (ML) and artificial intelligence (AI) workloads using NetApp AFF A800 storage systems, NVIDIA DGX A100 systems, and NVIDIA Mellanox Spectrum SN3700V 200Gb Ethernet switches. This design features RDMA over Converged Ethernet (RoCE) for the compute cluster interconnect fabric to provide customers with a completely ethernet-based architecture for high-performance workloads. This document also includes benchmark test results for the architecture as implemented. 

link:https://www.netapp.com/pdf.html?item=/media/21793-nva-1153-design.pdf[NVA-1153-DESIGN: NetApp ONTAP AI with NVIDIA DGX A100 systems and Mellanox Spectrum Ethernet switches^]