---
sidebar: sidebar
permalink: ai/nvaie_initial_setup.html
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVAIE, VMware
summary: NVIDIA AI Enterprise with NetApp and VMware - Initial Setup
---

= Initial Setup
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

link:nvaie_architecture.html[Previous: Architecture.]

[.lead]
This section describes the initial setup tasks that need to be performed in order to utilize NVIDIA AI Enterprise with NetApp and VMware.

== Prerequisites

Before you perform the steps that are outlined in this section, we assume that you have already deployed VMware vSphere and NetApp ONTAP. Refer to the link:https://docs.nvidia.com/ai-enterprise/latest/product-support-matrix/index.html[NVIDIA AI Enterprise Product Support Matrix] for details on supported vSphere versions. Refer to the link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html[NetApp and VMware solution documentation] for details on deploying VMware vSphere with NetApp ONTAP.

== Install NVIDIA AI Enterprise Host Software

To install the NVIDIA AI Entrprise host software, follow the instructions outlined in sections 1-4 in the link:https://docs.nvidia.com/ai-enterprise/latest/quick-start-guide/index.html[NVIDIA AI Enterprise Quick Start Guide].

link:nvaie_ngc.html[Next: Utilize NVIDIA NGC Software.]