---
sidebar: sidebar
permalink: ai/osrunai_software_requirements.html
keywords:
summary:
---
= Software Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-11 12:14:20.349237
//

[.lead]
This solution was validated using a basic Kubernetes deployment with the Run:AI operator installed. Kubernetes was deployed using the https://github.com/NVIDIA/deepops[NVIDIA DeepOps^] deployment engine, which deploys all required components for a production-ready environment. DeepOps automatically deployed https://netapp.io/persistent-storage-provisioner-for-kubernetes/[NetApp Trident^] for persistent storage integration with the k8s environment, and default storage classes were created so containers leverage storage from the AFF A800 storage system. For more information on Trident with Kubernetes on ONTAP AI, see https://www.netapp.com/us/media/tr-4798.pdf[TR-4798^].

 The following table lists the software components that are required to implement the solution as tested.

|===
|Software |Version or Other Information

|NetApp ONTAP data management software
|9.6p4
|Cisco NX-OS switch firmware
|7.0(3)I6(1)
|NVIDIA DGX OS
|4.0.4 - Ubuntu 18.04 LTS
|Kubernetes version
|1.17
|Trident version
|20.04.0
|Run:AI CLI
|v2.1.13
|Run:AI Orchestration Kubernetes Operator version
|1.0.39
|Docker container platform
|18.06.1-ce [e68fc7a]
|===

Additional software requirements for Run:AI can be found at https://docs.run.ai/Administrator/Cluster-Setup/Run-AI-GPU-Cluster-Prerequisites/[Run:AI GPU cluster prerequisites^].
