---
sidebar: sidebar
permalink: ai/osrunai_testing_details_for_section_4.9.html
keywords:
summary:
---

= Testing Details for Section 4.9
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-11 12:14:20.934374
//

[.lead]
This section contains testing details for the section link:osrunai_basic_resource_allocation_fairness.html[Basic Resource Allocation Fairness].

Submit jobs in the following order:

|===
|Project |# GPUs |Total |Comment

|team-d
|2
|6/8
|Team-b/c workload pauses and moves to `pending`.
|team-d
|2
|8/8
|Other team (b/c) workloads pause and move to `pending`.
|===

See the following executed command sequence:

....
$ runai submit d-2-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-d$ runai submit d-3-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-d
....

At this point, you should have the following states:

|===
|Project |GPUs Allocated |Workloads Queued

|team-a
|4/4
|None
|team-b
|2/2
|None
|team-c
|2/2
|None
|team-d
|8/8
|None
|===

See the section link:osrunai_basic_resource_allocation_fairness.html[Basic Resource Allocation Fairness] for a discussion on the proceeding testing scenario.

link:osrunai_testing_details_for_section_4.10.html[Next: Testing Details for Section 4.10]
