---
sidebar: sidebar
permalink: ai/osrunai_testing_details_for_section_4.10.html
keywords:
summary:
---

= Testing Details for Section 4.10
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-11 12:14:20.957945
//

[.lead]
This section contains testing details for the section link:osrunai_over-quota_fairness.html[Over-Quota Fairness].

Submit jobs in the following order for `team-a`, `team-b`, and `team-c`:

|===
|Project |# GPUs |Total |Comment

|team-a
|2
|4/4
|1 workload queued
|team-a
|2
|4/4
|2 workloads queued
|team-b
|2
|2/2
|2 workloads queued
|team-c
|2
|2/2
|2 workloads queued
|===

See the following executed command sequence:

....
$ runai submit a-3-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit a-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit b-5-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-b$ runai submit c-6-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-c
....

At this point, you should have the following states:

|===
|Project |GPUs Allocated |Workloads Queued

|team-a
|4/4
|Two workloads asking for GPUs two each
|team-b
|2/2
|Two workloads asking for two GPUs each
|team-c
|2/2
|Two workloads asking for two GPUs each
|team-d
|8/8
|None
|===

Next, delete all the workloads for `team-d`:

....
$ runai delete -p team-d d-1-gggg d-2-gg d-3-gg
....

See the section link:osrunai_over-quota_fairness.html[Over-Quota Fairness], for discussions on the proceeding testing scenario.

link:osrunai_where_to_find_additional_information.html[Next: Where to Find Additional Information]
