---
sidebar: sidebar
permalink: ai/osrunai_where_to_find_additional_information.html
keywords:
summary:
---

= Where to Find Additional Information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-11 12:14:21.001092
//

[.lead]
To learn more about the information that is described in this document, see the following resources:

* NVIDIA DGX Systems
** NVIDIA DGX-1 System
https://www.nvidia.com/en-us/data-center/dgx-1/
** NVIDIA V100 Tensor Core GPU
https://www.nvidia.com/en-us/data-center/tesla-v100/
** NVIDIA NGC
https://www.nvidia.com/en-us/gpu-cloud/
* Run:AI container orchestration solution
** Run:AI product introduction
https://docs.run.ai/home/components/
** Run:AI installation documentation
https://docs.run.ai/Administrator/Cluster-Setup/Installing-Run-AI-on-an-on-premise-Kubernetes-Cluster/
https://docs.run.ai/Administrator/Researcher-Setup/Installing-the-Run-AI-Command-Line-Interface/
** Submitting jobs in Run:AI CLI
https://docs.run.ai/Researcher/Walkthroughs/Walkthrough-Launch-Unattended-Training-Workloads-/
https://docs.run.ai/Researcher/Walkthroughs/Walkthrough-Start-and-Use-Interactive-Build-Workloads-/
** Allocating GPU fractions in Run:AI CLI
https://docs.run.ai/Researcher/Walkthroughs/Walkthrough-Using-GPU-Fractions/
* NetApp AI Control Plane
** Technical report
https://www.netapp.com/us/media/tr-4798.pdf
** Short-form demo
https://youtu.be/gfr_sO27Rvo
** GitHub repository
https://github.com/NetApp/kubeflow_jupyter_pipeline
* NetApp AFF systems
** NetApp AFF A-Series Datasheet
https://www.netapp.com/us/media/ds-3582.pdf
** NetApp Flash Advantage for All Flash FAS
https://www.netapp.com/us/media/ds-3733.pdf
** ONTAP 9 Information Library
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286
** NetApp ONTAP FlexGroup Volumes technical report
https://www.netapp.com/us/media/tr-4557.pdf
* NetApp ONTAP AI
** ONTAP AI with DGX-1 and Cisco Networking Design Guide
https://www.netapp.com/us/media/nva-1121-design.pdf
** ONTAP AI with DGX-1 and Cisco Networking Deployment Guide
https://www.netapp.com/us/media/nva-1121-deploy.pdf
** ONTAP AI with DGX-1 and Mellanox Networking Design Guide
http://www.netapp.com/us/media/nva-1138-design.pdf
** ONTAP AI with DGX-2 Design Guide
https://www.netapp.com/us/media/nva-1135-design.pdf
