---
sidebar: sidebar
permalink: ai/rag_introduction.html
keywords: RAG, Retrieval Augmented Generation, NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NeMo, NIM, NIMS, Hybrid, Hybrid Cloud, Hybrid Multicloud, NetApp ONTAP, FlexCache, SnapMirror, BlueXP
summary: Enterprise RAG with NVIDIA NeMo and NetApp - Introduction
---
= Enterprise Retrieval Augmented Generation (RAG) with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Mike Oglesby, NetApp
Sathish Thyagarajan, NetApp

[.lead]
Generative AI is transforming enterprise search experience. It is enabling data users in a company to discover data assets residing anywhere, on-premises or public cloud. Whether generative AI is used by developers to generate code to design a modern web application, or to create animations using real-world physics and motion data, organizations are using generative AI and pre-trained large language models (LLMs) to build transformative AI applications, design new product features, improve engineering productivity and augment customer experience. 

However, generative AI and LLMs alone cannot guarantee business value. To create a tangible business impact, generative AI must leverage curated data for quality business outcomes. Large enterprises are therefore turning to an emerging and essential framework known as retrieval augmented generation (RAG). In this soluiton, we present an architecture for organizations taht wish to build a RAG pipeline. This solution can help you to unlock value from your private data by retrieving contextual information through a private RAG pipeline.
