---
sidebar: sidebar
permalink: ai/tr-4785-link.html
keywords: 
summary: 
---

= TR-4785: AI Deployment with NetApp E-Series and BeeGFS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

Nagalakshmi Raju, Daniel Landes, Nathan Swartz, Amine Bennani, NetApp

[.lead]
Artificial intelligence (AI), machine learning (ML), and deep learning (DL) applications involve large datasets and high computations. To run these workloads successfully, you need an agile infrastructure that allows you to scale out both storage and compute nodes seamlessly. This report includes the steps for running an AI training model in a distributed mode, which allows seamless scale-out of compute and storage nodes. The report also includes various performance metrics to show how a solution combining NetApp E-Series storage with the BeeGFS parallel file system provides a flexible, cost-effective, and simple solution for AI workloads.

link:https://www.netapp.com/pdf.html?item=/media/17040-tr4785pdf.pdf[TR-4785: AI Deployment with NetApp E-Series and BeeGFS^] 