---
sidebar: sidebar
permalink: ai/vector-database-technology-requirement.html
keywords: vector database
summary: Technology requirement - vector database solution for netapp
---

= Technology Requirement
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This section provides an overview of the requirements for the NetApp vector database solution.

== Technology Requirement

The hardware and software configurations outlined below were utilized for the majority of the validations performed in this document, with the exception of performance. These configurations serve as a guideline to help you set up your environment. However, please note that the specific components may vary depending on individual customer requirements.

== Hardware requirements

|===
|Hardware	| Details

|NetApp AFF Storage array HA Pair	
| * A800
* ONTAP 9.14.1
* 48 x 3.49TB SSD-NVM
* Two Flexible group volumes: metadata and data. 
* Metadata NFS volume has 12 x Persistent Volumes with 250GB.
* Data is a ONTAP NAS S3 volume
|6 x FUJITSU PRIMERGY RX2540 M4	| * 64 CPUs
* Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz
* 256 GM Physical Memory
* 1 x 100GbE network port
|Networking	
|100 GbE
|StorageGRID	
|* 1 x SG100, 3xSGF6024
* 3 x 24 x 7.68TB 
|===

== Software requirements
|===
|Software	|Details

|Milvus cluster
|* CHART - milvus-4.1.11. 
* APP Version – 2.3.4
* Dependent bundles such as bookkeeper, zookeeper, pulsar, etcd, proxy, querynode, worker
|Kubernetes
|* 5 node K8s cluster 
* 1 Master node and 4 Worker nodes
* Version – 1.7.2
|Python
|*3.10.12.
|===