---
sidebar: sidebar
permalink: ai/vector-database-introduction.html
keywords: vector database
summary: Introduction to vector database solution for netapp
---

= Introduction
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This section provide an introduction to vector database solution for NetApp.

== Introduction

Vector databases effectively address the challenges that are designed to handle the complexities of semantic search in Large Language Models (LLMs) and generative Artificial Intelligence (AI). Unlike traditional data management systems, vector databases are capable of processing and searching through various types of data, including images, videos, text, audio, and other forms of unstructured data, by using the content of the data itself rather than labels or tags.

The limitations of Relational Database Management Systems (RDBMS) are well-documented, particularly their struggles with high-dimensional data representations and unstructured data common in AI applications. RDBMS often necessitate a time-consuming and error-prone process of flattening data into more manageable structures, leading to delays and inefficiencies in searches. Vector databases, however, are designed to circumvent these issues, offering a more efficient and accurate solution for managing and searching through complex and high-dimensional data, thus facilitating the advancement of AI applications.

This document serves as a comprehensive guide for customers who are currently using or planning to use vector databases, detailing the best practices for utilizing vector databases on platforms such as NetApp ONTAP, NetApp StorageGRID, Amazon FSxN for NetApp ONTAP, and SnapCenter. The content provided herein covers a range of topics:

* Infrastructure guidelines for vector databases, like Milvus, provided by NetApp storage through NetApp ONTAP and StorageGRID object storage. 
* Validation of the Milvus database in AWS FSX for NetApp ONTAP through file and object store.
* Delves into NetApp’s file-object duality, demonstrating its utility for data in vector databases as well as other applications. 
* How NetApp’s Data Protection Management product, SnapCenter, offers backup and restore functionalities for vector database data.
* How NetApp’s Hybrid Cloud offers data replication and protection across on-premises and cloud environments. 
* Provides insights into the performance validation of vector databases like Milvus and pgvector on NetApp ONTAP.
* Two specific use cases: Retrieval Augmented Generation (RAG) with Large Language Models(LLM) and the NetApp IT team’s ChatAI, thereby offering practical examples of the concepts and practices outlined.
