---
sidebar: sidebar
permalink: ai/vector-database-solution-verification-overview.html
keywords: Solution Overview vector database
summary: solution verification overview - vector database solution for netapp
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
We have conducted a comprehensive solution validation focused on five key areas, the details of which are outlined below. Each section delves into the challenges faced by customers, the solutions provided by NetApp, and the subsequent benefits to the customer.

. link:./vector-database-milvus-cluster-setup.html[Milvus cluster setup with Kubernetes in on-premises]
Customer challenges to scale independently on storage and compute, effective infrastructure management and data management. In this section, we detail the process of installing a Milvus cluster on Kubernetes, utilizing a NetApp storage controller for both cluster data and customer data.

. link:./vector-database-milvus-with-Amazon-FSxN-for-NetApp-ONTAP.html[Milvus with Amazon FSxN for NetApp ONTAP – file and object duality]
In this section, Why we need to deploy vector database in cloud as well as steps to deploy vector database ( milvus standalone ) in Amazon FSxN for NetApp ONTAP within docker containers.

. link:./vector-database-protection-using-snapcenter.html[Vector database protection using NetApp SnapCenter.]
In this section, we delve into how SnapCenter safeguards the vector database data and Milvus data residing in ONTAP. For this example, we utilized a NAS bucket (milvusdbvol1) derived from an NFS ONTAP volume (vol1) for customer data, and a separate NFS volume (vectordbpv) for Milvus cluster configuration data.

. link:./vector-database-disaster-recovery-using-netapp-snapmirror.html[Disaster Recovery using NetApp SnapMirror]
In this section, we discuss about the importance of Disaster recovery(DR) for vector database and how netapp disaster recovery product snapmirror provides DR solution to vector database.

. link:./vector-database-performance-validation.html[Performance validation]
In this section, we aim to delve into the performance validation of vector databases, such as Milvus and pgvecto.rs, focusing on their storage performance characteristics such as I/O profile and netapp storage controller behavious in support of RAG and inference workloads within the LLM Lifecycle. We will evaluate and identify any performance differentiators when these databases are combined with the ONTAP storage solution. Our analysis will be based on key performance indicators, such as the number of queries processed per second(QPS).

