---
sidebar: sidebar
permalink: ai/vector-database-conclusion.html
keywords: vector database, conclusion
summary: conclusion - vector database solution for netapp
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
This section concludes the vector database solution for NetApp.

== Conclusion

In conclusion, this document provides a comprehensive overview of deploying and managing vector databases, such as Milvus and pgvector, on NetApp storage solutions. We discussed the infrastructure guidelines for leveraging NetApp ONTAP and StorageGRID object storage and validated the Milvus database in AWS FSX for NetApp ONTAP through file and object store. 

We explored NetApp's file-object duality, demonstrating its utility not only for data in vector databases but also for other applications. We also highlighted how SnapCenter, NetApp's enterprise management product, offers backup, restore, and clone functionalities for vector database data, ensuring data integrity and availability. 

The document also delves into how NetApp's Hybrid Cloud solution offers data replication and protection across on-premises and cloud environments, providing a seamless and secure data management experience. We provided insights into the performance validation of vector databases like Milvus and pgvecto on NetApp ONTAP, offering valuable information on their efficiency and scalability.

Finally, we discussed two generative AI use cases: RAG with LLM and the NetApp’s internal ChatAI. These practical examples underscore the real-world applications and benefits of the concepts and practices outlined in this document. Overall, this document serves as a comprehensive guide for anyone looking to leverage NetApp's powerful storage solutions for managing vector databases.

=== Acknowledgments
The author like to heartfelt thanks to the below contributors, others who provided their feedback and comments to make this paper valuable to NetApp customers and NetApp fields.   

. Sathish Thyagarajan, Technical Marketing Engineer, ONTAP AI & Analytics, NetApp
. Mike Oglesby, Technical Marketing Engineer, NetApp
. AJ Mahajan, Senior Director, NetApp
. Joe Scott, Manager, Workload Performance Engineering, NetApp
. Puneet Dhawan, Senior Director, Product Management Fsx, NetApp
. Yuval Kalderon, Senior Product Manager, FSx Product Team, NetApp

=== Where to find additional information
To learn more about the information that is described in this document, review the following documents and/or websites:

* Milvus documentation - https://milvus.io/docs/overview.md
* Milvus standalone documentation - https://milvus.io/docs/v2.0.x/install_standalone-docker.md
* NetApp Product Documentation
https://www.netapp.com/support-and-training/documentation/
* instaclustr - link:https://www.instaclustr.com/support/documentation/?_bt=&_bk=&_bm=&_bn=x&_bg=&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=1467100120&hsa_cam=20766399079&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAjw26KxBhBDEiwAu6KXtzOZhN0dl0H1smOMcj9nsC0qBQphdMqFR7IrVQqeG2Y4aHWydUMj2BoCdFwQAvD_BwE[instalclustr documentation]

=== Version history
|===
|Version	|Date	|Document version history
|Version 1.0	|April 2024	|Initial release
|===