---
sidebar: sidebar
permalink: ai/vector-database-solution-with-netapp.html
keywords: vector database, milvus, usecases
summary: This is abstract page for vector datbase solution with Netapp.
---

= Vector Database Solution with NetApp
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

Karthikeyan Nagalingam and Rodrigo Nascimento, NetApp

[.lead]
This document provides a thorough exploration of the deployment and management of vector databases, such as Milvus, and pgvecto an open-source PostgreSQL extension, using NetApp's storage solutions. It details the infrastructure guidelines for using NetApp ONTAP and StorageGRID object storage and validates the application of Milvus database in AWS FSX for NetApp ONTAP. The document elucidates NetApp's file-object duality and its utility for vector databases and applications that support vector embeddings. It emphasizes the capabilities of SnapCenter, NetApp's enterprise management product, in offering backup and restore functionalities for vector databases, ensuring data integrity and availability. The document further delves into NetApp's hybrid cloud solution, discussing its role in data replication and protection across on-premises and cloud environments. It includes insights into the performance validation of vector databases on NetApp ONTAP, and concludes with two practical use cases on generative AI : RAG with LLM and the NetApp’s internal ChatAI. This document serves as a comprehensive guide for leveraging NetApp's storage solutions for managing vector databases.

The Reference Architecture focus on the following:

. link:./vector-database-introduction.html[Introduction]
. link:./vector-database-solution-overview.html[Solution Overview]
. link:./vector-database-vector-database.html[Vector Database]
. link:./vector-database-technology-requirement.html[Technology Requirement]
. link:./vector-database-deployment-procedure.html[Deployment Procedure]
. link:./vector-database-solution-verification-overview.html[Solution Verification Overview]
* link:./vector-database-milvus-cluster-setup.html[Milvus cluster setup with Kubernetes in on-premises]
* link:./vector-database-milvus-with-Amazon-FSxN-for-NetApp-ONTAP.html[Milvus with Amazon FSxN for NetApp ONTAP – file and object duality]
* link:./vector-database-protection-using-snapcenter.html[Vector database protection using NetApp SnapCenter.]
* link:./vector-database-disaster-recovery-using-netapp-snapmirror.html[Disaster Recovery using NetApp SnapMirror]
* link:./vector-database-performance-validation.html[Performance validation]
. link:./vector-database-instaclustr-with-pgvector.html[Vector Database with Instaclustr using PostgreSQL: pgvector]
. link:./vector-database-use-cases.html[Vector Database Use Cases]
. link:./vector-database-conclusion.html[Conclusion]
. link:./vector-database-values-yaml.html[Appendix A: values.yaml]
. link:./vector-database-prepare-data-netapp-new-py.html[Appendix B: prepare_data_netapp_new.py]
. link:./vector-database-verify-data-netapp-py.html[Appendix C: verify_data_netapp.py]
. link:./vector-database-docker-compose-xml.html[Appendix D: docker-compose.yml]