---
sidebar: sidebar
permalink: ai/wp-dgxc.html
keywords: NetApp AI, AI, Artificial Intelligence, Data Management, Supercomputing
summary: NVIDIA DGX Cloud with NetApp Cloud Volumes ONTAP/ANF 
---

= NetApp Cloud Data Services for NVIDIA DGX Cloud 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

link:nvaie_technology_overview.html[Previous: Technology Overview.]

[.lead]
Advanced data management for world-class supercomputing

== Introduction 
This document describes how customers can use NetApp Cloud volumes/ANF to provide advanced data management capabilities in conjunction with NVIDIA DGX Cloud to optimize and streamline AI data pipeline operations.  

=== Partnership: NVIDIA, Microsoft, and NetApp 
DGX Cloud provides customers with immediate access to an AI supercomputer from a web browser.  With DGX Cloud, enterprises can access multi-node AI training at scale to speed complex model design. If businesses choose to expand to on-premises infrastructure, they can consolidate all of their resources to deliver a hybrid cloud leveraging NetApp BlueXP™ and NVIDIA Base Command Platform, which provides developers a consistent, single-pane view. 

=== NVIDIA DGX Cloud  
[let NVIDIA tell us what content should be added here] 

=== Microsoft Azure 

=== NetApp BlueXP™  

=== Azure NetApp Files® 

=== NetApp File-Object Duality 

== Architecture and Configuration 

=== Solution design/overview 

=== Architecture drawing 

=== CVO/ANF deployment 
Using BlueXP 

=== Configuration for file/object duality 
Automated via Ansible? 

=== Connection to DGXC

== Conclusion 