---
sidebar: sidebar
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware
permalink: cyber-vault-overview.html
summary: "NetApp's cyber vault solutions"
---
= Cyber vault overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The primary driving threat that necessitates the implementation of cyber vaulting is the growing prevalence and evolving sophistication of cyber-attacks, particularly ransomware and data breaches. link:https://www.verizon.com/business/resources/reports/dbir/[With a rise in phishing^] and ever more sophisticated methods of credential stealing, credentials used to begin a ransomware attack could then be used to access infrastructure systems.  In these cases, even hardened infrastructure systems are at risk of attack. The only defense to a compromised system is to have your data protected and isolated in a cyber vault.

NOTE: Beginning in July 2024, content from technical reports previously published as PDFs has been integrated with ONTAP product documentation. In addition, new technical reports (TRs) such as this document will no longer be getting TR numbers.

== What is cyber vaulting?
Cyber vaulting is a specific data protection technique that involves storing critical data in an isolated environment, separate from the primary IT infrastructure. 

"Air gapped", immutable and indelible data repository that is immune to threats affecting the main network, such as malware, ransomware, or even insider threats. Cyber vaulting can be achieved with immutable snapshots.

Air-gapping backups that use traditional methods involve creating space and physically separating the primary and secondary media. By moving the media offsite and/or severing connectivity, bad actors have no access to the data. This protects the data but can lead to slower recovery times.

== NetApp's approach to cyber vaulting
NetApp cyber vaulting, provides organizations with a comprehensive and flexible solution for protecting their most critical data assets. By leveraging logical air-gapping with robust hardening methodologies, NetApp enables you to create secure, isolated storage environments that are resilient against evolving cyber threats. With NetApp, you can ensure the confidentiality, integrity, and availability of your data while maintaining the agility and efficiency of your storage infrastructure.