---
sidebar: sidebar
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP
permalink: /cyber-vault/index.html
summary: "NetApp ONTAP cyber vault, powered by SnapLock Compliance for immutable and indelible data retention."
---

= ONTAP cyber vault
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp's ONTAP based cyber vault provides organizations with a comprehensive and flexible solution for protecting their most critical data assets. By leveraging logical air-gapping with robust hardening methodologies, ONTAP enables you to create secure, isolated storage environments that are resilient against evolving cyber threats. With ONTAP, you can ensure the confidentiality, integrity, and availability of your data while maintaining the agility and efficiency of your storage infrastructure.

NOTE: Beginning in July 2024, content from technical reports previously published as PDFs has been integrated with ONTAP product documentation. In addition, new technical reports (TRs) such as this document will no longer be getting TR numbers.