---
sidebar: sidebar
permalink: cyber-vault/ontap-cyber-vault-powershell-considerations.html
keywords: Cyber vault, powershell, script, configuration, validation, hardening
summary: This is the NetApp ONTAP solution for configuring, hardening and validating a ONTAP based cyber vault
---

= Additional considerations

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
There are additional considerations when designing and deploying an ONTAP based cyber vault.

include::../_include/cyber-vault-capacity-sizing-considerations.adoc[]

== Performance impact on primary / source

Because the data transfer is a pull operation, the impact on primary storage performance can vary depending on the workload, data volume and the frequency of backups. However, the overall performance impact on the primary system is generally moderate and manageable, as data transfer is designed to offload data protection and backup tasks to the cyber vault storage system. During the initial relationship setup and the first full backup, a significant amount of data is transferred from the primary system to the cyber vault system (the SnapLock Compliance volume). This can lead to increased network traffic and I/O load on the primary system. Once the initial full backup is complete, ONTAP only needs to track and transfer blocks that have changed since the last backup. This results in a much smaller I/O load compared to the initial replication. Incremental updates are efficient and have minimal impact on primary storage performance. The vault process runs in the background, which reduces the chances of interference with the primary system's production workloads.

* Ensuring the storage system has enough resources (CPU, memory and IOPs) to handle the additional load mitigates the performance impact.