---
sidebar: sidebar
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, FAQ
permalink: cyber-vault/ontap-cyber-vault-faq.html
summary: "This document contains the frequently asked questions on the NetApp ONTAP cyber vault solution."
---

= Cyber vault frequently asked questions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This FAQ is intended for NetApp customers. It answers frequently asked questions about the NetApp WORM protection with logical air-gapped cyber vaulting.

== What is a NetApp cyber vault?

Cyber vault is a specific data protection technique that involves storing data in an isolated environment, separate from the primary IT infrastructure.

Cyber vault is an "air-gapped", immutable, and indelible data repository that is immune to threats affecting the primary data, such as malware, ransomware, or insider threats. A cyber vault can be achieved with immutable NetApp ONTAP Snapshot copies and made indelible with NetApp SnapLock Compliance. While under SnapLock Compliance protection, data cannot be modified or deleted, not even by ONTAP administrators or NetApp Support.

Air-gapping backups that use traditional methods involve creating space and physically separating the primary and secondary media. Air-gapping with cyber vault includes using a single data replication network connection outside of standard data access networks to replicate Snapshot copies to an indelible destination. Air-gapping with cyber vault should also include disabling all data access and replication protocols at the destination site (when they are not needed) which prevents any data access or data exfiltration at the destination site. By moving the media offsite and/or severing connectivity, bad actors have no access to the data. This protects the data but can lead to slower recovery times. With SnapLock Compliance, physical separation is not required. SnapLock Compliance protects your vaulted Snapshot point-in-time, read-only copies, resulting in data that is quickly accessible, safe from deletion, and immutable.

== NetApp's approach to cyber vaulting

NetApp cyber vault, powered by SnapLock, provides organizations with a comprehensive and flexible solution for protecting their most critical data assets. By leveraging hardening technologies in ONTAP, NetApp enables you to create a secure, air-gapped, and isolated cyber vault that is immune against evolving cyber threats. With NetApp, you can ensure the confidentiality, integrity, and availability of your data while maintaining the agility and efficiency of your storage infrastructure.

Key features of the NetApp reference architecture for a cyber vault include:

* Secure, isolated storage infrastructure (e.g., air-gapped storage systems)
* Backup copies of your data are both immutable and indelible
* Strict and separate access controls, multi-administrator verification and multi-factor authentication
* Rapid data restoration capabilities

== Cyber vault frequently asked questions

.Is cyber vault a product from NetApp?
[%collapsible%open]
====
No, "cyber vault" is an industry wide term. NetApp has created a reference architecture to make it easy for customers to build their own cyber vaults and leverage the dozens of ONTAP security features to help protect their data from cyber threats. More information is available on the ONTAP documentation site link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html[here^].
====

.Is cyber vault with NetApp just another name for LockVault or SnapVault?
[%collapsible%open]
====
No, LockVault was a feature of Data ONTAP 7-mode that is not available in current versions of ONTAP. SnapVault is legacy terminology for what is now done with a vault SnapMirror policy. This policy allows the destination to retain a different quantity of Snapshot copies than the source volume. 
====

.Which NetApp hardware can I use for a cyber vault, FAS, capacity flash, or performance flash?
[%collapsible%open]
====
This reference architecture for cyber vaulting applies to the entire ONTAP hardware portfolio. Customers can use AFF A-Series, AFF C-Series or FAS platforms as the vault. Flash-based platforms will provide the fastest recovery times while disk-based platforms will provide the most cost-effective solution. Depending on how much data is being recovered and if multiple recoveries are happening in parallel, using disk-based systems (FAS) may take days to weeks to complete. Please consult with a NetApp or partner representative to properly size a cyber vault solution to meet the business requirements.
====

.Can I use the cloud with NetApp's cyber vaulting?
[%collapsible%open]
====
The current reference architecture is designed for on-prem based implementations. *DO WE REALLY WANT TO SAY THIS IN PUBLIC* --> Stay tuned for more announcements from NetApp for cloud-based implementations.
====

.Is cyber vaulting with NetApp, just using SnapMirror? Is there any other technology or configurations used for cyber vaulting?
[%collapsible%open]
====
No, a NetApp cyber vault architecture leverages many ONTAP features to create a secure, isolated, air-gapped and hardened cyber vault. The foundation of a NetApp cyber vault is SnapMirror and SnapLock Compliance but using additional ONTAP features such as tamperproof Snapshot copies, Multi Factor Authentication (MFA), Multi Admin Verify, role-based access control, and remote and local audit logging, improves the security and safety of one's data.
==== 

.What makes ONTAP Snapshot copies better than others for a cyber vault?
[%collapsible%open]
====
ONTAP Snapshot copies are immutable by default and can be made indelible with SnapLock Compliance. Not even NetApp support can delete the SnapLock Snapshot copies. The better question to ask is what makes NetApp cyber vault better than other cyber vaults in the industry. First, ONTAP is the most secure storage on the planet and has obtained CSfC validation which allows for the storage of secret and top-secret  data at rest at both the hardware and software layers. More information on link:https://www.netapp.com/esg/trust-center/compliance/CSfC-Program/[CSfC can be found here^]. In addition, ONTAP can be air-gapped at the storage layer, with the cyber vault system controlling the replication allowing for an air-gap to be created within the cyber vault network.
====

.Can the source volume of a cyber vault be an ONTAP Fabric Pool enabled volume (tiered volume to ONTAP S3 or StorageGRID)?
[%collapsible%open]
====
A Fabric Pool enabled volume regardless of the policy used, can be replicated to a cyber vault destination.
====

.Does NetApp cyber vault run on a different ONTAP personality or profile?
[%collapsible%open]
====
No, it's a reference architecture.
====

.Can I turn on data protocols such as NFS and SMB in a cyber vault?
[%collapsible%open]
====
By default, data protocols should be disabled on the cyber vault to make it secure. However, data protocols can be enabled on the cyber vault to access data for recovery or when needed. This should be done on a temporary basis and disabled after recovery has completed.
====

.Can you convert an existing SnapVault environment to a cyber vault, or do you need to reseed everything?
[%collapsible%open]
====
Yes. One could take a system that is a SnapMirror destination (with vault policy), disable the data protocols, harden the system per the link:https://docs.netapp.com/us-en/ontap/ontap-security-hardening/security-hardening-overview.html[ONTAP hardening guide^], isolate it a secure location, and follow the other procedures in the reference architecture to make it a cyber vault without having to reseed the destination.
====