---
sidebar: sidebar
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening
permalink: cyber-vault/ontap-cyber-vault-interoperability.html
summary: "Cyber vault interoperability"
---

= Cyber vault interoperability
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
ONTAP hardware and software can be used to create a cyber vault configuration.  

== ONTAP hardware recommendations
All ONTAP unified physical arrays can be used for a cyber vault implementation. 

* FAS hybrid storage offers the most cost-efficient solution.
* AFF C-Series offers the most efficient power consumption and density.
* AFF A-Series is the highest performing platform offering the best RTO. With the recent announcement of our latest AFF A-Series, this platform will offer the best storage efficiency without performance compromise.

== ONTAP software recommendations
Beginning with ONTAP 9.14.1, you can specify retention periods for specific SnapMirror labels in the SnapMirror policy of the SnapMirror relationship so that the replicated Snapshot copies from the source to the destination volume are retained for the retention-period specified in the rule. If no retention period is specified, the default-retention-period of the destination volume is used.

Beginning with ONTAP 9.13.1, you can instantaneously restore a locked Snapshot copy on the destination SnapLock volume of a SnapLock vault relationship by creating a FlexClone with the snaplock-type option set to "non-snaplock" and specifying the Snapshot copy as the "parent-snapshot" when executing the volume clone creation operation. Learn more about link:https://docs.netapp.com/us-en/ontap/volumes/create-flexclone-task.html?q=volume+clone[creating a FlexClone volume with a SnapLock type^]. 

== MetroCluster configuration 
For MetroCluster configurations, you should be aware of the following:

* You can create a SnapVault relationship only between sync-source SVMs, not between a sync-source SVM and a sync-destination SVM.
* You can create a SnapVault relationship from a volume on a sync-source SVM to a data-serving SVM.
* You can create a SnapVault relationship from a volume on a data-serving SVM to a DP volume on a sync-source SVM.