---
sidebar: sidebar
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening
permalink: ontap-cyber-vault-hardening.html
summary: "Additional steps recommended to harden a cyber vault for ONTAP"
---
= Cyber vault hardening
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
These are the additional recommendations to harden an ONTAP cyber vault.

== Cyber vault hardening recommendations

* Isolate your cyber vault data plane
* Do not enable data LIFs on the destination cluster because they provide an unnecessary attack vector
* On the destination cluster, limit intercluster LIF access to the source cluster with a service policy
* Restrict all data traffic from the source cluster to the cyber vault to allow only the ports required for SnapMirror traffic
* Isolate the cyber vault management plane
* Segment the management LIF on the destination cluster for limited access with a service policy and a bastion host
* Where possible, disable any unneeded management access methods to decrease the attack surface
* Make it harder for bad actors to access the cyber vault
* Require administrative multifactor authentication for System Manager and ssh
* Implement role-based access
* Guard against malicious tampering on your cyber vault
* Enable multi-admin verification and require verification from an admin outside your regular storage administrators (e.g. CISO staff)
* Enable audit logging and remote log storage

Please refer to the link:https://docs.netapp.com/us-en/ontap/ontap-security-hardening/security-hardening-overview.html[ONTAP hardening guide], link:https://docs.netapp.com/us-en/ontap/multi-admin-verify/index.html[Multi-admin verification overview^] and link:https://www.netapp.com/media/17055-tr4647.pdf[ONTAP multifactor authentication guide^] for how to accomplish these hardening steps.