---
sidebar: sidebar
permalink: cyber-vault/ontap-cyber-vault-powershell-conclusion.html
keywords: Cyber vault, powershell, script, configuration, validation, hardening
summary: This is the NetApp ONTAP solution for configuring, hardening and validating a ONTAP based cyber vault
---

= >>> Level One Title

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
>>> Placeholder for descriptive lead sentence or paragraph

= ONTAP cyber vault PowerShell solution conclusion

By leveraging air-gapping with robust hardening methodologies provided by ONTAP, NetApp enables you to create a secure, isolated storage environment that is resilient against evolving cyber threats. All of this is accomplished while maintaining the agility and efficiency of existing storage infrastructure. This secure access empowers companies to achieve their stringent safety and uptime goals with minimal change to their existing people, process, and technology framework.

ONTAP cyber vault uses native features in ONTAP is an easy approach for additional protection to create immutable and indelible copies of your data. Adding NetApp's ONTAP based cyber vault to the overall security posture will:

* Create an environment that is separate and disconnected to the production and backup networks and restrict user access to it.
