---
sidebar: sidebar
permalink: automation/automation_introduction.html
summary: NetApp solutions automation enables the customer to automate the deployment, configuration and execution of many common infrastrucure and application tasks.
keywords: netapp, solutions, automation, ansible, terraform
---

= NetApp Solution Automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/


=== Introduction
One of the objectives of validating and architecting solutions is to make it easily consumable. Therefore, it is paramount that the deployment and configuration of infrastructure and/or applications delivered through our solutions is simplified through automation. NetApp is committed to simplifying solution consumption through automation using RedHat Ansible.

Ansible is an open-source automation engine that helps IT teams automate application deployment, cloud provisioning, configuration management, and many other IT needs. Ansible is agentless and does not require a custom security infrastructure. You can manage automation of multiple systems from your control system remotely via SSH making it a robust solution for IT teams looking to automate their tedious and repetitive IT needs.

For more information about RedHat Ansible, refer the documentation https://www.ansible.com/[here^].
