---
sidebar: sidebar
permalink: automation/automation_dashboard.html
summary: NetApp solutions automation enables the customer to automate the deployment, configuration and execution of many common infrastrucure and application tasks.
keywords: netapp, solutions, automation, ansible, terraform
---

= NetApp Solution Automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

[.lead]
Automation simplifies the consumption of NetApp Solutions.

++++
<style>
.n-band.n-band--docs.n-band--belted {
  padding: 0px;
}
a, a:hover{color:#0065B3;}
.n-feature-block.n-feature-block__align--center.n-layout-flex__item.ie-feature-block {
  border: 1px solid rgba(217, 217, 214, 0.8);
  box-shadow: 0 3px 7px 0 rgba(0, 0, 0, 0.1);
  height: auto;
  padding: 15px;
  max-width: 260px;
  min-width: 30%;
  margin: 10px 15px 10px 0px;
  flex:1;
  /* min-width: 29.9%;
  margin: 10px; */
}

.ie-feature-block__header {
  align-items: center;
  border-bottom: 2px solid #efefed;
  display: block;
  font-weight: 600;
  font-size: 16px;
  height: 32px;
  line-height: 16px;
  text-align: left;
  padding-bottom: 6px;
}

.ie-feature-block__text {
  align-items: center;
  padding-bottom: 0px;
  display: flex;
  line-height: 16px;
}

.ie-feature-block__image {
  display: inline-block;
  align-self: center!important;
  margin-right: 4px;
}

.ie-feature-block__section {
  display: block;
  margin-top: 15px;
  text-align: left;
}

.ie-feature-block__link {
  font-size: 14px;
  font-weight: 500;
}

.ie-feature-block__summary {
  font-size: 14px;
  overflow-wrap: break-word;
}

.n-layout-flex {
  /* max-width: 1200px; */
  justify-content: normal;
}

@media screen and (max-width: 1300px){
.n-feature-block.n-feature-block__align--center.n-layout-flex__item.ie-feature-block {
  min-width: 47%;
  margin: 10px 15px 10px 0px;

}
}
@media screen and (max-width:1024px){
  .n-feature-block.n-feature-block__align--center.n-layout-flex__item.ie-feature-block {
    min-width: 45%;
  }
}
@media screen and (max-width:889px){
  .n-feature-block.n-feature-block__align--center.n-layout-flex__item.ie-feature-block {
    min-width: 95%;
    margin: 0 10px 20px;
  }
}
</style>

<div class="n-band__content">
  <div class="n-layout-flex" data-ntap-layout="4">

    <div class="n-feature-block n-feature-block__align--center n-layout-flex__item ie-feature-block">
      <div class="n-feature-block__content">
        <div class="ie-feature-block__header">
          <div class="ie-feature-block__text">
            Automated Solutions
            </div>
          </div>
<div class="ie-feature-block__section">
  <a class="ie-feature-block__link" href="/">What's New</a>
  <p class="ie-feature-block__summary"></p>
</div>

<div class="ie-feature-block__section">
  <a class="ie-feature-block__link" href="/">Videos and Demos</a>
  <p class="ie-feature-block__summary"></p>
</div>

<div class="ie-feature-block__section">
  <a class="ie-feature-block__link" href="/">Blogs</a>
  <p class="ie-feature-block__summary"></p>
</div>

</div>
</div>

<div class="n-feature-block n-feature-block__align--center n-layout-flex__item ie-feature-block">
  <div class="n-feature-block__content">
    <div class="ie-feature-block__header">
      <div class="ie-feature-block__text">
        Request Automation
      </div>
    </div>
    <div class="ie-feature-block__section">
      <a class="ie-feature-block__link" href="https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20<request_title>">Raise a request</a></a>
      <p class="ie-feature-block__summary">For requesting automation for any NetApp solutions published on this site, fill the details in the above link and raise a request.</p>
    </div>
  </div>
</div>

</div>
</div>
++++
