---
sidebar: sidebar
permalink: automation/cloud_volumes_terraform.html
keywords: AWS, Azure, GCP, FSX, CVO, ANF, Terraform, automation
summary: This page describes the Automated method for deploying Netapp volumes on Cloud providers (AWS, Azure, GCP) using terraform.
---

= Cloud Volumes Terraform Repository Implementation Procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
This solution has been designed to be run in a Terraform environment.

== Repository Details
Collection of Terraform configuration files to deploy NetApp Cloud Volumes (CVO, CVS, FSx, ANF) on Public Cloud Platforms (AWS, Microsoft Azure, GCP).


== Terraform Configuration Files for NetApp Cloud Volumes

This is an archive of Terraform configuration files to deploy NetApp Cloud Volumes on Public Clouds using Terraform.

These configuration files use NetApp cloud manager terraform provider and cloud terraform providers for AWS, Azure and GCP.

== Folder Contents
`AWS:` This folder contains various deployment and configuration scenarios for NetApp Cloud Volumes on AWS.
`azure:` This folder contains various deployment and configuration scenarios for NetApp Cloud Volumes on Microsoft Azure.


== Requirements
. Terraform >= 0.13
. Cloud Manager Account
. Cloud Provider Account – AWS, Azure
. Host machine (any OS supported by Terraform)

== Provider documentation
The documentation is available at: link:https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest/docs[https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest/docs]

=== Controlling the provider version
Note that you can also control the provider version. This is controlled by a required_providers block in your Terraform configuration.

The syntax is as follows:

----
terraform {
  required_providers {
    netapp-cloudmanager = {
      source = "NetApp/netapp-cloudmanager"
      version = "20.10.0"
    }
  }
}
----

Read more on provider version control.


== Running Specific Modules

.AWS
[%collapsible]
====
include::automation/cloud_volumes_aws.adoc[]
====

.Azure
[%collapsible]
====
include::automation/cloud_volumes_azure.adoc[]
====

== License
By accessing, downloading, installing or using the content in this repository, you agree the terms of the License laid out in License file.

Note that there are certain restrictions around producing and/or sharing any derivative works with the content in this repository. Please make sure you read the terms of the License before using the content. If you do not agree to all of the terms, do not access, download or use the content in this repository.

Copyright: 2021 NetApp Inc.


## Author Information
NetApp Solutions Engineering Team
