---
sidebar: sidebar
permalink: automation/cloud_volumes_terraform.html
keywords: AWS, Azure, GCP, FSX, CVO, ANF, CVS, Terraform, automation
summary: This page describes the Automated method for deploying Netapp volumes on Cloud providers (AWS, Azure, GCP) using terraform.
---

= Cloud Volumes Automation via Terraform
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This solution documents the automated deployments of Cloud Volumes on AWS (CVO Single Node, CVO HA and FSX ONTAP) and Azure (CVO Single Node, CVO HA and ANF) using Terraform modules. The code can be found at https://github.com/NetApp/na_cloud_volumes_automation


== Pre-requisites
. Terraform >= 0.13
. Cloud Manager Account
. Cloud Provider Account – AWS, Azure
. Host machine (any OS supported by Terraform)

== Provider documentation
The documentation of Terraform provider for Cloud Manager is available at: link:https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest/docs[https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest/docs]

=== Controlling the provider version
Note that you can also control the provider version. This is controlled by a required_providers block in your Terraform configuration.

The syntax is as follows:

[source, cli]
terraform {
  required_providers {
    netapp-cloudmanager = {
      source = "NetApp/netapp-cloudmanager"
      version = ">= 23.0.0"
    }
  }
}


Read more on provider version control.


== Running Specific Modules

.AWS
[%collapsible]
====
include::../_include/cloud_volumes_aws.adoc[]
====

.Azure
[%collapsible]
====
include::../_include/cloud_volumes_azure.adoc[]
====

.GCP
[%collapsible]
====
include::../_include/cloud_volumes_gcp.adoc[]
====
