---
sidebar: sidebar
permalink: ent-apps-db/getting_started_requirements.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Cloud Volumes Terraform Repository Implementation procedure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[.lead]
This solution has been designed to be run in an AWX/Tower environment or by CLI on an Ansible control host.

== Repository Details
Collection of Terraform configuration files to deploy NetApp Cloud Volumes (CVO, CVS, FSx, ANF) on Public Cloud Platforms (AWS, Microsoft Azure, GCP).


== Terraform Configuration Files for NetApp Cloud Volumes

This is an archive of Terraform configuration files to deploy NetApp Cloud Volumes on Public Clouds using Terraform.

These configuration files use NetApp cloud manager terraform provider and cloud terraform providers for AWS, Azure and GCP.

== Folder Contents
`AWS:` This folder contains various deployment and configuration scenarios for NetApp Cloud Volumes on AWS.
`azure:` This folder contains various deployment and configuration scenarios for NetApp Cloud Volumes on Microsoft Azure.


== Requirements
. Terraform >= 0.13
. Cloud Manager Account
. Cloud Provider Account – AWS, Azure
. Host machine (any OS supported by Terraform)

== Provider documentation
The documentation is available at: link:https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest/docs[https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest/docs]

=== Controlling the provider version
Note that you can also control the provider version. This is controlled by a required_providers block in your Terraform configuration.

The syntax is as follows:

----
terraform {
  required_providers {
    netapp-cloudmanager = {
      source = "NetApp/netapp-cloudmanager"
      version = "20.10.0"
    }
  }
}
----

Read more on provider version control.


== Running Specific Modules

[role="tabbed-block"]
=====
.AWS
--
include::automation/cloud_volumes_aws.adoc[]
--
.Azure
--
include::automation/cloud_volumes_azure.adoc[]
--
=====

=== AWS

***AWS CVO Single Node Deployment:*** [aws/cvo_single_node_deployment/README.md](aws/cvo_single_node_deployment/README.md)

***AWS CVO HA Deployment:*** [aws/cvo_ha_deployment/README.md](aws/cvo_ha_deployment/README.md)

***AWS FSx Deployment:*** [aws/fsx_deployment/README.md](aws/fsx_deployment/README.md)

### Azure

***ANF Deployment:*** [azure/anf/README.md](azure/anf/README.md)

***ANF Data Protection:*** [azure/anf_data_protection/README.md](azure/anf_data_protection/README.md)

***ANF Dual Protocol:*** [azure/anf_dual_protocol/README.md](azure/anf_dual_protocol/README.md)

***ANF Volume from Snapshot:*** [azure/anf_dual_protocol/README.md](azure/anf_dual_protocol/README.md)

***Azure CVO Single Node Deployment:*** [azure/cvo_single_node_deployment/README.md](azure/cvo_single_node_deployment/README.md)

***Azure CVO HA Deployment:*** [azure/cvo_ha_deployment/README.md](azure/cvo_ha_deployment/README.md)

## Author Information
NetApp Solutions Engineering Team

== License
By accessing, downloading, installing or using the content in this repository, you agree the terms of the License laid out in License file.

Note that there are certain restrictions around producing and/or sharing any derivative works with the content in this repository. Please make sure you read the terms of the License before using the content. If you do not agree to all of the terms, do not access, download or use the content in this repository.

Copyright: 2021 NetApp Inc.
