---
sidebar: sidebar
permalink: automation/getting-started.html
summary: NetApp solutions automation enables the customer to automate the deployment, configuration and execution of many common infrastructure and application tasks.
keywords: netapp, awx, tower, ansible tower, solutions, automation, ansible, getting, started
---

= Getting Started with NetApp solution automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./../media/

[.lead]
NetApp solution automation provides simplicity and repeatability for many of the common tasks utilized by the NetApp Solutions.

Prior to running any solution automation, the environment must be configured for how the automation will be executed.  There are options to run the automation from the command line or through a tool such as AWX or tower.

The following sections will outline the steps required to configure the environment for each of the specified environments.

==================================================
.Setup the Ansible Control Node for CLI deployments on RHEL / CentOS
[%collapsible]
====
include::automation/automation_rhel_centos_setup.adoc[tag=steps]
====
==================================================

==================================================
.Setup the Ansible Control Node for CLI deployments on Ubuntu / Debian
[%collapsible]
====
include::automation/automation_ubuntu_debian_setup.adoc[tag=steps]
====
==================================================

==================================================
.Getting Started: Setup Ansible Tower or AWX for Tower / AWX deployments
[%collapsible]
====
include::automation/setup_awx.adoc[tag=steps]
====
==================================================
