---
sidebar: sidebar
permalink: ent-db/automated_ontap_oracle19c.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-02-16 10:32:05.121542
//
=== VARS
++++
<style>
div {
position: relative;
}
div button {
position: absolute;
top: 0;
right: 0;
}
button {
  transition-duration: 0.4s;
  background-color: white;
  color: #1563a3;
  border: 2px solid #1563a3;
}
button:hover {
  background-color: #1563a3;
  color: white;
}
#more_storage_vlans {
  display: block;
}
#more_storage_vlans_button {
  display: none;
}
#more_nfs_volumes {
  display: block;
}
#more_nfs_volumes_button {
  display: none;
}
</style>
<div class="listingblock"><div class="content"><div><button id="copy-button" onclick="CopyClassText()">Copy</button></div><pre><code><div class="CopyMeClass" id="CopyMeID">
######################################################################
###### Oracle 19c deployment user configuration variables       ######
###### Consolidate all variables from ontap, linux and oracle   ######
######################################################################

###########################################
### Ontap env specific config variables ###
###########################################

#Inventory group name
#Default inventory group name - 'ontap'
#Change only if you are changing the group name either in inventory/hosts file or in inventory groups in case of AWX/Tower
hosts: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>ontap</i></span>

#CA_signed_certificates (ONLY CHANGE to 'true' IF YOU ARE USING CA SIGNED CERTIFICATES)
ca_signed_certs: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>false</i></span>

#Names of the Nodes in the ONTAP Cluster
nodes:
 - <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>AFF-01</i></span>
 - <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>AFF-02</i></span>


#Storage VLANs
#Add additional rows for vlans as necessary
storage_vlans:
   - {vlan_id: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>203</i></span>&quot;, name: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>infra_NFS</i></span>&quot;, protocol: &quot;<span <div contenteditable="true"/><i>NFS</i></span>&quot;}
<a id="more_storage_vlans" href="javascript:storagevlandropdown();">More Storage VLANs</a><div id="select_more_storage_vlans"></div><a id="more_storage_vlans_button" href="javascript:addstoragevlans();">Enter Storage VLANs details</a><div id="extra_storage_vlans"></div>

#Details of the Data Aggregates that need to be created
#If Aggregate creation takes longer, subsequent tasks of creating volumes may fail.
#There should be enough disks already zeroed in the cluster, otherwise aggregate create will zero the disks and will take long time
data_aggregates:
  - {aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr01_node01</i></span>}
  - {aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr01_node02</i></span>}

#SVM name
svm_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>ora_svm</i></span>

# Root volume for infrastructure svm
#Default name is <svm_name>_root
#Only if you wish to change, delete the '#' before the start of the line below and enter the desired root volume name
<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>#</i></span>svm_root_volume: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>svm_root</i></span>&quot;

# Create root mirror volumes for oracle SVM
#Default names are <svm_name>_m01 and <svm_name>_m02
#Only if you wish to change, delete the '#' before the start of 3 lines below and enter the desired root_mirror_volume names
<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>#</i></span>root_mirror_volumes:
<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>#</i></span>  - {root_mirror_volume: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>ora_svm_1_m01</i></span>&quot;} #for node-1
<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>#</i></span>  - {root_mirror_volume: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>ora_svm_1_m02</i></span>&quot;} #for node-2

#Job Schedule
job_schedule:
  - {job_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>15min</i></span>,job_minutes: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>15</i></span>}

  # SVM Management LIF Details
  svm_mgmt_details:
  - {address: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.91.100</i></span>, netmask: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>255.255.255.0</i></span>, home_port: <span <div contenteditable="true"/><i>e0M</i></span>}

# NFS storage parameters when sprotocol set to NFS
volumes_nfs:
  - {vol_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>rtpora03_u01</i></span>, aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr01_node01</i></span>, lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.200</i></span>, size: <span <div contenteditable="true"/><i>25</i></span>}
<a id="more_nfs_volumes" href="javascript:nfsvolumesdropdown();">More NFS volumes</a><div id="select_more_nfs_volumes"></div><a id="more_nfs_volumes_button" href="javascript:addnfsvolumes();">Enter NFS volumes' details</a><div id="extra_nfs_volumes"></div>

#NFS LIFs IP address and netmask
nfs_lifs_details:
  - address: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.200</i></span> #for node-1
    netmask: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>255.255.255.0</i></span>
  - address: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.201</i></span> #for node-2
    netmask: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>255.255.255.0</i></span>

#Data Protocol to be used for export policy rules
data_protocol: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>nfs</i></span></p>

#NFS export policy name
#Default name is svm_client
#Only if you wish to change, delete the '#' before the start of the line below and enter the desired NFS export policy name.
<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>#</i></span>nfs_exp_policy: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>svm_client</i></span>&quot;

#NFS client match
client_match: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.0/24</i></span>

###########################################
### Linux env specific config variables ###
###########################################

#NFS Mount points for Oracle DB volumes
mount_points:
  - <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>/u01</i></span>
  - <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>/u02</i></span>
  - <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>/u03</i></span>

# Up to 75% of node memory size divided by 2mb. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB.
# Leave it blank if hugepage is not configured on the host.
hugepages_nr: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i></i></span>

####################################################
### DB env specific install and config variables ###
####################################################

db_domain: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>your.domain.com</i></span>

# CDB listener port, use different listener port for additional CDB on same host
#listener_port: 1522

# CDB is created with SGA at 75% of memory_limit, MB. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB. The grand total SGA should not exceed 75% available RAM on node.
#memory_limit: 2732

# Set initial password for all required Oracle passwords. Change them after installation.
initial_pwd_all: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>netapp123</i></span>

# Set "em_configuration: DBEXPRESS" to install enterprise manager express and choose a unique port from 5500 to 5599 for each sid on the host.
# Leave them blank if enterprise manager express is not installed.
#em_configuration: DBEXPRESS
#em_express_port: 5501
</div></code></pre></div></div>
<script>
function CopyClassText(){
  	var textToCopy = document.getElementById("CopyMeID");
  	var currentRange;
  	if(document.getSelection().rangeCount > 0)
  	{
  		currentRange = document.getSelection().getRangeAt(0);
  		window.getSelection().removeRange(currentRange);
  	}
  	else
  	{
  		currentRange = false;
  	}
  	var CopyRange = document.createRange();
  	CopyRange.selectNode(textToCopy);
  	window.getSelection().addRange(CopyRange);
    document.getElementById("more_storage_vlans").style.display = "none";
    document.getElementById("more_nfs_volumes").style.display = "none";
    var command = document.execCommand("copy");
      if (command)
      {
          document.getElementById("copy-button").innerHTML = "Copied!";
          setTimeout(revert_copy, 3000);
      }
  	window.getSelection().removeRange(CopyRange);
  	if(currentRange)
  	{
  		window.getSelection().addRange(currentRange);
  	}
}
function revert_copy() {
      document.getElementById("copy-button").innerHTML = "Copy";
      document.getElementById("more_storage_vlans").style.display = "block";
      document.getElementById("more_nfs_volumes").style.display = "block";
}
function storagevlandropdown() {
    document.getElementById("more_storage_vlans").style.display = "none";
	document.getElementById("more_storage_vlans_button").style.display = "block";
    var x=1;
    var myHTML = '';
    var buildup = '';
    var wrapper = document.getElementById("select_more_storage_vlans");
    while (x < 10) {
      buildup += '<option value="' + x + '">' + x + '</option>';
  	  x++;
    }
    myHTML += '<a id="more_storage_vlans_info">How many extra VLANs do you wish to add?</a><select name="number_of_extra_storage_vlans" id="number_of_extra_storage_vlans">' + buildup + '</select>';
    wrapper.innerHTML = myHTML;
}
function addstoragevlans() {
    var y = document.getElementById("number_of_extra_storage_vlans").value;
    var j=0;
    var myHTML = '';
    var wrapper = document.getElementById("extra_storage_vlans");
    while (j < y) {
    	j++;
        myHTML += '   - {vlan_id: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>203</i></span>&quot;, name: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>infra_NFS</i></span>&quot;, protocol: &quot;<span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>NFS</i></span>&quot;}<br>';
    }
	wrapper.innerHTML = myHTML;
	document.getElementById("select_more_storage_vlans").style.display = "none";
	document.getElementById("more_storage_vlans_button").style.display = "none";
}
function nfsvolumesdropdown() {
    document.getElementById("more_nfs_volumes").style.display = "none";
	document.getElementById("more_nfs_volumes_button").style.display = "block";
    var x=1;
    var myHTML = '';
    var buildup = '';
    var wrapper = document.getElementById("select_more_nfs_volumes");
    while (x < 100) {
      buildup += '<option value="' + x + '">' + x + '</option>';
  	  x++;
    }
    myHTML += '<a id="more_nfs_volumes_info">How many extra NFS volumes do you wish to add?</a><select name="number_of_extra_nfs_volumes" id="number_of_extra_nfs_volumes">' + buildup + '</select>';
    wrapper.innerHTML = myHTML;
}
function addnfsvolumes() {
    var y = document.getElementById("number_of_extra_nfs_volumes").value;
    var j=0;
    var myHTML = '';
    var wrapper = document.getElementById("extra_nfs_volumes");
    while (j < y) {
    	j++;
        myHTML += '  - {vol_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>rtpora04_u01</i></span>, aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr01_node02</i></span>, lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.201</i></span>, size: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>25</i></span>}<br>';
    }
	wrapper.innerHTML = myHTML;
	document.getElementById("select_more_nfs_volumes").style.display = "none";
	document.getElementById("more_nfs_volumes_button").style.display = "none";
}

</script>
++++
=== Host VARS Config
++++
<style>
div {
position: relative;
}
div button {
position: absolute;
top: 0;
right: 0;
}
button {
  transition-duration: 0.4s;
  background-color: white;
  color: #1563a3;
  border: 2px solid #1563a3;
}
button:hover {
  background-color: #1563a3;
  color: white;
}
#more_datastores_nfs {
  display: block;
}
#more_datastores_nfs_button {
  display: none;
}
</style>
<div class="listingblock"><div class="content"><div><button id="copy-button1" onclick="CopyClassText1()">Copy</button></div><pre><code><div class="CopyMeClass1" id="CopyMeID1">
######################################################################
##############      Host Variables Configuration        ##############
######################################################################

# Oracle db log mode: true or false
log_archive_mode: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>true</i></span>

# Number of pluggable database per container instance identified by sid
oracle_sid: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>cdb2</i></span>
pdb_num: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>3</i></span>
pdb_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>"{{ oracle_sid }}_pdb"</i></span>

# CDB listener port, use different listener port for additional CDB on same host
listener_port: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>1523</i></span>

# CDB is created with SGA at 75% of memory_limit, MB. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB. The grand total SGA should not exceed 75% available RAM on node.
memory_limit: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>5464</i></span>

# Set "em_configuration: DBEXPRESS" to install enterprise manager express and choose a unique port from 5500 to 5599 for each sid on the host.
# Leave them blank if em express is not installed.
em_configuration: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>DBEXPRESS</i></span>
em_express_port: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline; text-decoration:underline;"/><i>5501</i></span>

host_datastores_nfs:
  - {vol_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>"{{groups.oracle[0]}}_u01"</i></span>, aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr01_node01</i></span>, lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.200</i></span>, size: <span <div contenteditable="true"/><i>25</i></span>}
<a id="more_datastores_nfs" href="javascript:datastoredropdown();">More NFS volumes</a><div id="select_more_datastores_nfs"></div><a id="more_datastores_nfs_button" href="javascript:adddatastorevolumes();">Enter NFS volumes' details</a><div id="extra_datastores_nfs"></div>
</div></code></pre></div></div>
<script>
function CopyClassText1(){
  	var textToCopy = document.getElementById("CopyMeID1");
  	var currentRange;
  	if(document.getSelection().rangeCount > 0)
  	{
  		currentRange = document.getSelection().getRangeAt(0);
  		window.getSelection().removeRange(currentRange);
  	}
  	else
  	{
  		currentRange = false;
  	}
  	var CopyRange = document.createRange();
  	CopyRange.selectNode(textToCopy);
  	window.getSelection().addRange(CopyRange);
    document.getElementById("more_datastores_nfs").style.display = "none";
    var command = document.execCommand("copy");
      if (command)
      {
          document.getElementById("copy-button1").innerHTML = "Copied!";
          setTimeout(revert_copy, 3000);
      }
  	window.getSelection().removeRange(CopyRange);
  	if(currentRange)
  	{
  		window.getSelection().addRange(currentRange);
  	}
}
function revert_copy() {
      document.getElementById("copy-button1").innerHTML = "Copy";
      document.getElementById("more_datastores_nfs").style.display = "block";
}

function datastoredropdown() {
    document.getElementById("more_datastores_nfs").style.display = "none";
	document.getElementById("more_datastores_nfs_button").style.display = "block";
    var x=1;
    var myHTML = '';
    var buildup = '';
    var wrapper = document.getElementById("select_more_datastores_nfs");
    while (x < 100) {
      buildup += '<option value="' + x + '">' + x + '</option>';
  	  x++;
    }
    myHTML += '<a id="more_datastores_nfs">How many extra NFS volumes do you wish to add?</a><select name="number_of_extra_datastores_nfs" id="number_of_extra_datastores_nfs">' + buildup + '</select>';
    wrapper.innerHTML = myHTML;
}
function adddatastorevolumes() {
    var y = document.getElementById("number_of_extra_datastores_nfs").value;
    var j=0;
    var myHTML = '';
    var wrapper = document.getElementById("extra_datastores_nfs");
    while (j < y) {
    	j++;
        myHTML += '  - {vol_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>"{{groups.oracle[0]}}_u01"</i></span>, aggr_name: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>aggr01_node02</i></span>, lif: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>172.21.94.201</i></span>, size: <span <div contenteditable="true" style="color:#004EFF; font-weight:bold; font-style:italic; text-decoration:underline;"/><i>25</i></span>}<br>';
    }
	wrapper.innerHTML = myHTML;
	document.getElementById("select_more_datastores_nfs").style.display = "none";
	document.getElementById("more_datastores_nfs_button").style.display = "none";
}

</script>
++++
