---
sidebar: sidebar
permalink: ent-db/automation_rhel_centos_setup.html
summary: NetApp solutions automation utilizes RedHat Ansible for configuration and management.
keywords: netapp, solutions, automation, ansible, terraform
---

= NetApp Solution Automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:table-stripes: odd
:imagesdir: ./media/

=== Procedure

. Requirements for the Ansible control node,:
.. A RHEL/CentOS machine with the following packages installed:
... Python3
... Pip3
... Ansible (version greater than 2.10.0)
... Git

If you have a fresh RHEL/CentOS machine without the above requirements installed, follow the below steps to setup that machine as the Ansible control node:

. Enable the Ansible repository for RHEL-8/RHEL-7
.. For RHEL-8 (run the below command as root)
[source, cli]
subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms

.. For RHEL-7 (run the below command as root)
[source, cli]
subscription-manager repos --enable rhel-7-server-ansible-2.9-rpms

. Create a .sh file
[source, cli]
vi setup.sh

. Paste the below content in the file
[source, cli]
#!/bin/bash
echo "Installing Python ------>"
sudo yum -y install python3 >/dev/null
echo "Installing Python Pip ------>"
sudo yum -y install python3-pip >/dev/null
echo "Installing Ansible ------>"
python3 -W ignore -m pip --disable-pip-version-check install ansible >/dev/null
echo "Installing git ------>"
sudo yum -y install git >/dev/null

. Make the file executable
[source, cli]
chmod +x setup.sh

. Run the script (as root)
[source, cli]
./setup.sh
