---
sidebar: sidebar
permalink: ent-db/awx_automation.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/



== AWX/Tower Deployment Oracle 19c Database

==== 1. Create the Inventory, Group, Hosts, and Credentials for your Environment:

=== Procedure

This section describes the steps to configure the parameters in AWX/Ansible Tower that will prepare the environment for consuming NetApp automated solutions.

. Configure Inventory
.. Go to 'Resources' → 'Inventories' → 'Add' and click on 'Add Inventory'.
.. Provide name and organization details and click on 'Save'.
.. In 'Inventories' page, click on the Inventory created.
.. If there are any inventory variables, paste them in the variables field.
.. Go to 'Groups' sub-menu and click on 'Add'
.. Provide name of the group, paste the group variables (if any) and click on 'Save'
.. Then click on the group created, go to 'Hosts' sub-menu and click on 'Add New Host'
.. Provide hostname/IP address of the host, paste the host variables (if any) and click on 'Save'
.. This process will need to be done for the ONTAP Cluster Management IP/Hostname, and Oracle servers management IP/Hostname

. Create Credential Types
.. For solutions involving ONTAP you will need to configure credential type to match username and password entries.
.. Go to 'Administration' → 'Credential Types' and click on 'Add'
.. Provide name and description
.. Paste the following content in 'Input Configuration':
[source, cli]
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true

.. Paste the following content in 'Injector Configuration':
[source, cli]
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'

. Configure Credentials
.. Go to 'Resources' → 'Credentials' and click on 'Add'
.. Enter the name and organization details
.. Select the custom 'Credential Type' you created for ONTAP
.. Under 'Type Details' Enter the Username, Password, and vsadmin_password

. Configure host_vars
.. Go to 'Resources' → 'Hosts' and select your Oracle server
.. Under 'Variables' click edit and add copy the variables from below that are specific to the server
NOTE: The Items in blue must be changed to match your Oracle server and ONTAP environment.
include::ent-db/host_vars.adoc[]
.. Click Save
.. Repeat process for additional Oracle servers

. Create Project
.. Go to 'Resources' → 'Projects' and click on 'Add'
.. Enter the name and organization details
.. Select 'Git' in 'Source Control Credential Type'
.. <GITHUB URL>
.. Click on 'Save'

. Configure Job Template
.. Go to 'Resources' → 'Templates' → 'Add' and click on 'Add Job Template'
.. Enter the name and description
.. Select the Job type - 'Run' configures the system based on playbook and 'Check' performs a dry run of playbook without actually configuring the system
.. Select the corresponding inventory, project and credentials for the playbook
.. Select the playbook that is desired to be run as part of the job template
.. Usually the variables will be pasted during runtime. So to get the prompt to populate the variables during runtime, make sure to tick the checkbox 'Prompt on Launch' corresponding to the 'Variable' field.
.. Provide any other details as required and click on Save

- Edit and copy the variables from VARS section
NOTE: The Items in blue must be changed to match your ONTAP environment.

include::ent-db/vars.adoc[]

. Launching the Job Template
.. Go to 'Resources' → 'Templates'
.. Click on the desired template and then click on 'Launch'
.. Fill in any variables if prompted on launch and then click on 'Launch' again
