---
sidebar: sidebar
permalink: ent-db/cli_automation.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---
= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-02-16 10:32:05.121542
//
== CLI Deployment Oracle 19c Database
=== Procedure
This section covers the steps required to prepare and deploy Oracle19c Database via CLI. Make sure that you have reviewed the    link:getting_started_requirements.html[Getting Started and Requirements Section] and prepared your environment accordingly.

=== 1. Download Oracle19c Repo:
- From your ansible controller, run the following command:

[source, CLI]

git clone https://github.com/NetApp-Automation/na_oracle19c_deploy.git

- After downloading the repository, change directories to na_oracle19c_deploy <cd na_oracle19c_deploy>

=== 2. Edit the hosts file:
The Following steps should be completed before deployment.

- Edit your "hosts" file na_oracle19c_deploy directory.
- Under "[ontap]", change the IP address to your cluster management IP.
- Under "[oracle]" group, add oracle hosts names. The host name needs to be resolved to its IP address either through DNS, hosts file or specified in host
- Once you have completed the steps above, save changes.

===== Following is an example of "host" file
++++
#ONTAP Host<div>
[ontap]
<div>
<span <div contenteditable="false" style="color:#7EAF97
; font-weight:bold; font-style:italic; text-decoration:;"/>10.61.184.183<i></i></span>
</div>
#Oracle hosts<div>
<div>
[oracle]<div>
<span <div contenteditable="false" style="color:#7EAF97
; font-weight:bold; font-style:italic; text-decoration:;"/>rtpora01<i></i></span>
<div>
<span <div contenteditable="false" style="color:#7EAF97
; font-weight:bold; font-style:italic; text-decoration:;"/>rtpora02<i></i></span>
</div>

++++
This will execute the playbook and deploy oracle 19c on two oracle DB servers concurrently. You can also test with just one DB server. In that case, you only need to configure one host variable file.

NOTE: The playbook will execute the same way regardless of how many Oracle Hosts and Databases are to be deployed.

=== 3. Edit the "host_name.yml" file under host_vars:
Each Oracle host has its host variable file identified by its host name that contains host specific variables. You can specify any name for your host. Edit and copy the host_vars from "Host VARS Config" section and paste it into your desired "host_name.yml" file.

NOTE: The Items in blue must be changed to match your environment.

include::ent-db/host_vars.adoc[]

=== 4. Edit the vars.yml file:
The "vars.yml" file consolidates all environment specific variables (ONTAP, Linux, Oracle) for Oracle deployment.

- Edit and copy the variables from VARS section and paste these variables into your "vars.yml" file.


include::ent-db/vars.adoc[]

=== 5. Run the playbook:
After completing the required environment prerequisites and copying the variables into "vars.yml" and "your_host.yml", we are now ready to deploy the playbooks.

NOTE: "username" Must be changed to match your environment.

++++
<strong>5.1</strong>
Run the ONTAP playbook by passing the correct tags and ONTAP cluster username. Fill the password for ONTAP cluster, and vsadmin when prompted.
++++

[source, CLI]

ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config -e @vars/vars.yml

++++
<strong>5.2</strong>
Run the Linux playbook to execute Linux portion of deployment. Input for admin ssh password as well as sudo password.
++++

[source, CLI]

ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config -e @vars/vars.yml

++++
<strong>5.3</strong>
Run the Oracle playbook to execute Oracle portion of deployment. Input for admin ssh password as well as sudo password.
++++

[source, CLI]

ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config -e @vars/vars.yml

=== 6. Deploy Additional Database on Same Oracle Host

==== Procedure

The Oracle portion of playbook will create single Oracle container database on an Oracle server per execution. To create additional container database on the same server, follow below procedure.

. Revise host_vars variables
.. Go back to step 3 - Edit the "host_name.yml" file under host_vars:
.. Change Oracle sid to a different naming string
.. Change listener port to different number
.. Change EM Express port to a different number if EM Express is to be installed
.. Copy and paste the revised host variables to Oracle host variable file under host_vars
. Execute the playbook with oracle_config tag only as show in above section 5.3

include::ent-db/validation.adoc[]
