---
sidebar: sidebar
permalink: ent-db/cli_automation.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---
= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-02-16 10:32:05.121542
//
== CLI Deployment Oracle 19c Database
=== Procedure
This section covers the steps required to prepare and deploy Oracle19c Database via CLI. Make sure that you have reviewed the    link:getting_started_requirements.html[Getting Started and Requirements Section] and prepared your environment accordingly.

==== 1. Download Oracle19c Repo:
- From your ansible controller, run the following command:

[source, CLI]

git clone "Place holder url for GitHub"

- After downloading the repository, change directories to na_oracle19c_deploy <cd na_oracle19c_deploy>

==== 2. Edit the hosts file:
The Following steps should be completed before deployment.

- Edit your "hosts" file na_oracle19c_deploy directory.
- Under "[ontap]", change the IP address to your cluster management IP.
- Under "[oracle]" group, add oracle hosts names. The host name needs to be resolved to its IP address either through DNS, hosts file or specified in host
- Once you have completed the steps above, save changes.

===== Following is an example of "host" file
++++
#ONTAP Host<div>
[ontap]
<div>
<span <div contenteditable="false" style="color:#7EAF97
; font-weight:bold; font-style:italic; text-decoration:;"/>10.61.184.183<i></i></span>
</div>
#Oracle hosts<div>
<div>
[oracle]<div>
<span <div contenteditable="false" style="color:#7EAF97
; font-weight:bold; font-style:italic; text-decoration:;"/>rtpora01<i></i></span>
<div>
<span <div contenteditable="false" style="color:#7EAF97
; font-weight:bold; font-style:italic; text-decoration:;"/>rtpora02<i></i></span>
</div>

++++
This will execute the playbook and deploy oracle 19c on two oracle DB servers concurrently. You can also test with just one DB server. In that case, you only need to configure one host variable file.

NOTE: The playbook will execute the same way regardless of how many Oracle Hosts and Databases are to be deployed.

==== 3. Edit the vars.yml file:
The "vars.yml" file consolidates all environment specific variables (ONTAP, Linux, Oracle) for Oracle deployment.

- Edit and copy the variables from VARS section and paste these variables into your "vars.yml" file.

NOTE: The Items in blue must be changed to match your ONTAP environment.

include::ent-db/vars.adoc[]


==== 4. Edit the "your_host.yml" file under host_vars:
Each Oracle host has its host variable file identified by its host name that contains host specific variables. You can specify any name for your host. Edit and copy the host_vars from VARS section and paste it into your desired "your_host.yml" file.

include::ent-db/host_vars.adoc[]


==== 5. Run the playbook:
After completing the required environment prerequisites and copying the variables into "vars.yml" and "your_host.yml", we are now ready to deploy the playbooks.

NOTE: "username" Must be changed to match your environment.

++++
<strong>5.1</strong>
Run the ONTAP playbook by passing the correct tags and ONTAP cluster username. Fill the password for ONTAP cluster, and vsadmin when prompted.
++++

[source, CLI]

ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config

++++
<strong>5.2</strong>
Run the Linux playbook to execute Linux portion of deployment. Input for admin ssh password as well as sudo password.
++++

[source, CLI]

ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config

++++
<strong>5.3</strong>
Run the Oracle playbook to execute Oracle portion of deployment. Input for admin ssh password as well as sudo password.
++++

[source, CLI]

ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config

++++
<strong>5.4</strong>
Run the All playbook to execute ONTAP, Linux, and Oracle deployment for an end to end deployment in a single run. Input for admin ssh password as well as sudo password.
++++

[source, CLI]

ansible-playbook -i hosts all_playbook.yml -u username -k -K



==== 6. Validate Oracle installation:
++++
<div>
<strong>1</strong>. Login to Oracle server as root and the following command:
++++
[source, cli]
ps -ef | grep ora

NOTE:  This will list oracle processes if installation completed as expected and oracle DB started

++++
<div>
<strong>2.</strong> Login database to check db setting and PDBs created with following command sets.
++++

[source, cli]
su - oracle

[source, cli]
sqlplus / as sysdba

[source, cli]
select name, log_mode from v$database;

++++
<div>
<pre>
<strong>
<div style = "padding: 0; margin-bottom: auto; border-width:1px; border-style:solid; height: 100px; width: 170px">
NAME LOG_MODE
--------- -----
CDB2 ARCHIVELOG
</strong>
</div><code></pre></div></div>

++++

[source, cli]
show pdbs;

++++
<div>
<pre>
<strong>
<div style = "padding: 0; margin-bottom: auto; border-width:1px; border-style:solid; height: 170px; width: 400px">
CON_ID CON_NAME OPEN MODE RESTRICTED
---------- ------------------------------
2 PDB$SEED READ ONLY NO
3 CDB2_PDB1 READ WRITE NO
4 CDB2_PDB2 READ WRITE NO
5 CDB2_PDB3 READ WRITE NO
</strong>
</div><code></pre></div></div>

++++

[source, cli]
check dnfs;

++++
<div>
<pre>
<strong>
<div style = "padding: 0; margin-bottom: auto; border-width:1px; border-style:solid; height: 100px; width: 200px">
col svrname form a30

col dirname form a30
</strong>
</div><code></pre></div></div>

++++


[source, cli]
Select svrname, dirname, nfsversion from v$dnfs_servers

++++
<div>
<pre>
<strong>
<div style = "padding: 0; margin-bottom: auto; border-width:1px; border-style:solid; height: 300; width: 400px">
SVRNAME DIRNAME NFSVERSION
------------------------------ ------
172.21.126.200 /rhelora02_u02 NFSv3.0
172.21.126.200 /rhelora02_u03 NFSv3.0
172.21.126.200 /rhelora02_u01 NFSv3.0
</strong>
</div><code></pre></div></div>

++++

++++
<p><div>
This confirms that dnfs is working properly.
</p>
++++
