---
sidebar: sidebar
permalink: ent-db/cli_automation.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-02-16 10:32:05.121542
//
== CLI Deployment Oracle 19c Database

==== 1. Download Oracle19c Repo:
From your ansible controller, run the command git clone "Place holder url for GitHub" (login with your SSO when prompted)
Then change directories to na_oracle19c_deploy <cd na_oracle19c_deploy>

==== 2. Edit the hosts file:
- vim hosts
- Under ontap, change the IP address to your cluster management IP.
- Under oracle group, add oracle hosts names. The host name needs to be resolved to its IP address either through DNS, hosts file or specified in host
- variable files in host_vars directory.
- Save changes

Following is an example of host file
++++
#ONTAP Host<div>
[ontap]
<div>
<span <div contenteditable="false" style="color:#008000; font-weight:bold; font-style:italic; text-decoration:;"/>10.61.184.183<i></i></span>
</div>
#Oracle hosts<div>
<div>
[oracle]<div>
<span <div contenteditable="false" style="color:#008000; font-weight:bold; font-style:italic; text-decoration:;"/>rtpora01<i></i></span>
<div>
<span <div contenteditable="false" style="color:#008000; font-weight:bold; font-style:italic; text-decoration:;"/>rtpora02<i></i></span>
</div>

++++
This will execute playbook and deploy oracle 19c on two oracle DB servers concurrent. You can also test with just one DB server. In that case, you only need to configure one host variable file.

NOTE: The playbook will execute the same regardless number of Oracle hosts and number of databases to be deployed.

==== 3. Edit the vars.yml file:
The vars.yml file consolidates all environment specific variables (ONTAP, Linux, Oracle) for Oracle deployment.
3.1 Edit and copy the variables from VARS section,

NOTE: The Items in blue must be changed to match your ONTAP environment.


==== 4. Edit the host_name.yml file under host_vars:
Each Oracle host has its host variable file identified by its host name that contains host specific variables. Edit and copy the host_vars from VARS section.

==== 5. Run the playbook:
++++
<div>
<p>
5.1. Run the ONTAP playbook by passing the correct tags and ONTAP cluster username. Fill the password for ONTAP cluster, and vsadmin when prompted.
<span <div contenteditable="false" style="color:#008000; font-weight:bold; font-style:italic; text-decoration:;"/>#playbook -i hosts ontap_playbook.yml -u username -k -t ontap_cofig<i></i></span>
<div>
<p>
<div>
5.2. Run the Linux playbook to execute Linux portion of deployment. Input for admin ssh password as well as sudo password.
<div><span <div contenteditable="false" style="color:#008000; font-weight:bold; font-style:italic; text-decoration:;"/>
#ansible-playbook -i hosts linux_playbook.yml -u username -k -K -t linux_config<i></i></span>
<p>
</div>
5.3. Run the Oracle playbook to execute Oracle portion of deployment. Input for admin ssh password as well as sudo password.
<div>
<p>
<span <div contenteditable="false" style="color:#008000; font-weight:bold; font-style:italic; text-decoration:;"/>#ansible-playbook -i hosts oracle_playbook.yml -u username -k -K -t oracle_config<i></i></span>
</div>
5.4. Run the All playbook to execute ONTAP, Linux, and Oracle deployment for an end to end deployment in a single run. Input for admin ssh password as well as sudo password.
 <div contenteditable="false" style="color:#008000; font-weight:bold; font-style:italic; text-decoration:;"/>#ansible-playbook -i hosts all_playbook.yml -u username -k -K<i></i></span>
</div>
<p>
++++
NOTE: To deploy second database instance on same host, Make changes in sid, memory_limit, listener_ports and/or em_express_port if em express is to be configured, then execute Oracle playbook again.
