---
sidebar: sidebar
permalink: ent-db/getting_started_requirements.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Getting Started
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

This solution has been designed to be ran in an AWX/Tower environment or by CLI on an Ansible control host.

=== AWX/Tower

. For AWX/Tower environments you will be guided through creating an inventory of your ONTAP cluster and Oracle servers, creating credentials, configuring a Project that pulls the Ansible code from NetApp Automation Github, and the Job Template that will launch the automation.
. Next you will the fill out the variables specific to your environment, and copy and paste those into the Extra Vars into your Job Template.
. Once you have your Extra vars added to your Job Template you will be able to launch the automation.
. The Job Template will be ran in three phases by specifying tags, for ontap_config, linux_config, and finally oracle_config.

=== CLI via Ansible Control host

. 


= Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[width=100%,cols="6, 5, 6",grid="all"]
|===
| *Ansible Environment* | *Oracle Server(s)* | *ONTAP*
| AWX/Tower or Linux host to be the Ansible control host | RHEL 7/8 | ONTAP version 9.3 - 9.8
| Ansible v.2.10 and higher | Oracle Linux 7/8 | Two data aggregates
| Python 3 | NFS vlan configured interface | NFS vlan and ifgrp created
| Python libraries
  - netapp-lib
  - xmltodict
  - jmespath | Oracle installation files on Oracle servers |
|===

= Automation Details
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

The automated deployment is designed with a single Ansible playbook, that consists of three separate roles. The roles are for ONTAP, Linux, and Oracle configurations.
The table below describes what tasks are being automated.

[width=100%,cols="6, 5, 6",grid="all"]
|===
| *ontap_config* | *linux_config* | *oracle_config*
| Pre-check of the ONTAP environment | Create mount points and mount NFS volumes | Oracle software installation
| Creation of NFS based SVM for Oracle | Verify NFS mounts | Create Oracle listener
| Creation of export policy | OS specific configuration | Create Oracle databases
| Creation of volumes for Oracle | Create Oracle directories | Oracle environment configuration
| Creation of NFS LIFs | Configure hugepages | Save PDB state
| | Disable SELinux and Firewall Daemon | Enable instance archive mode
| | Enable and start chronyd service | Enable dnfs client
| | Increase file descriptor hard limit | Enable database auto startup and shutdown between OS reboots
| | Create pam.d session file |
|===
