---
sidebar: sidebar
permalink: ent-db/getting_started_requirements.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Getting Started
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

This solution has been designed to be ran in an AWX/Tower environment or by CLI on an Ansible control host.

=== AWX/Tower

. For AWX/Tower environments you will be guided through creating an inventory of your ONTAP cluster management and Oracle server (IPs and hostnames), creating credentials, configuring a Project that pulls the Ansible code from NetApp Automation Github, and the Job Template that will launch the automation.
. Next fill out the variables specific to your environment, and copy and paste those into the Extra Vars into your Job Template.
. After the Extra vars have been added to your Job Template you will be able to launch the automation.
. The Job Template will be ran in three phases by specifying tags, for ontap_config, linux_config, and finally oracle_config.

=== CLI via Ansible Control host

. Linux host configured to be used for an Ansible control host, click the link for details on getting those configurations installed.
link:../automation/automation_rhel_centos_setup.html[RHEL 7/8 || CentOS 7/8^, window="_blank"]
link:../automation/automation_ubuntu_debian_setup.html[Ubuntu/Debian^, window="_blank"]
. After the Ansible control host configured you can git clone the Ansible Automation repository.
. Edit the hosts file with the IPs and/or hostnames of your ONTAP cluster management, and Oracle server's management IPs.
. Next fill out the variables specific to your environment, and copy and paste those into the vars.yml file.
. Each Oracle host will have a variable file identified by its hostname that contains host specific variables.
. After all variable files have been completed, you can run the playbook in three phases specifying tags, for ontap_config, linux_config, and finally oracle_config.

= Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

[width=100%, cols="3, 9",grid="all"]
|===
|Environment | Requirements

.4+| *Ansible Environment* |
AWX/Tower or Linux host to be the Ansible control host
| Ansible v.2.10 and higher
| Python 3
| Python libraries
- netapp-lib
- xmltodict
- jmespath
.3+| *ONTAP* |
ONTAP version 9.3 - 9.8
| Two data aggregates
| NFS vlan and ifgrp created
.5+| *Oracle Server(s)* |
RHEL 7/8 | Oracle Linux 7/8 | Network interfaces for NFS, public, and optional mgmt | Oracle installation files on Oracle servers
|===

= Automation Details
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

The automated deployment is designed with a single Ansible playbook, that consists of three separate roles. The roles are for ONTAP, Linux, and Oracle configurations.
The table below describes what tasks are being automated.

[width=100%, cols="4, 9",grid="all"]
|===
|Role | Tasks

.5+|*ontap_config* |
Pre-check of the ONTAP environment
| Creation of NFS based SVM for Oracle
| Creation of export policy
| Creation of volumes for Oracle
| Creation of NFS LIFs
.9+|*linux_config* |
Create mount points and mount NFS volumes
| Verify NFS mounts
| OS specific configuration
| Create Oracle directories
| Configure hugepages
| Disable SELinux and Firewall Daemon
| Enable and start chronyd service
| increase file descriptor hard limit
| Create pam.d session file
.8+|*oracle_config* |
Oracle software installation
| Create Oracle listener
| Create Oracle databases
| Oracle environment configuration
| Save PDB state
| Enable instance archive mode
| Enable dnfs client
| Enable database auto startup and shutdown between OS reboots
|===

== Default Parameters
To simplify automation, we have preset many required Oracle deployment parameters with default values. It is generally not necessary to change the default parameters for most deployment. For more advanced user, who wish to make changes for those default parameters can do so with caution. The default parameters are located in each role folder under defaults directory.

== Deployment Instructions
Before start, download following Oracle installation and patch files and place them in /tmp/archive directory with read, write, execute access for  all users on each DB servers to be deployed. The automation tasks will look for those named installation files in that particular directory for Oracle installation and configuration.

  LINUX.X64_193000_db_home.zip -- 19.3 base installer
  p31281355_190000_Linux-x86-64.zip -- 19.8 RU patch
  p6880880_190000_Linux-x86-64.zip -- opatch version 12.2.0.1.23

== License
Read license information as stated in Github repository. By accessing, downloading, installing or using the content in this repository, you agree the terms of the License laid out in the link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT[License, window="_blank"]

Note that there are certain restrictions around producing and/or sharing any derivative works with the content in this repository. Please make sure you read the terms of the link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT[License, window="_blank"] before using the content. If you do not agree to all of the terms, do not access, download or use the content in this repository.


Once you are ready, click the link below for detailed deployment instructions.
link:awx_automation.html[AWX/Tower Deployment^, window="_blank"]
link:cli_automation.html[CLI Deployment^, window="_blank"]
