---
sidebar: sidebar
permalink: ent-db/marketing_overview.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/



== Automated Deployment of Oracle19c for ONTAP on NFS

Organizations are automating their environments to gain efficiencies, accelerate deployments, and reduce manual effort.  Configuration management tools, like Ansible, are being used to streamline enterprise database operations. In this solution, we demonstrate how you can leverage Ansible to automate the provisioning and configuration of Oracle 19c with NetApp ONTAP. By enabling storage administrators, systems administrators and DBAs to consistently and rapidly deploy new storage, configure database servers, and install Oracle 19c software, you achieve the following benefits:

* Eliminates design complexities and human errors, and implements a repeatable consistent deployment and best practices
* Decreases time for provisioning of storage, configuration of DB hosts, and Oracle installation
* Increases database administrators, systems and storage administrators productivity
* Enables scaling of storage and databases with ease

NetApp provides customers with validated Ansible modules and roles to accelerate deployment, configuration and lifecycle management of your Oracle database environment. This solution provides instruction and Ansible playbook code, to help you:

* Create and configure ONTAP NFS storage for Oracle Database
* Install Oracle 19c on RedHat Enterprise Linux 7/8 or Oracle Linux 7/8
* Configure Oracle 19c on ONTAP NFS storage

For more details or to begin, please see the overview videos, link:./media/oracle_deployment_auto_v1.mp4[Part1 - AWX Setup, window="_blank"], link:./media/oracle_deployment_auto_v2.mp4[Part2 - Playbook Execution, window="_blank"] and Getting Started and Requirements in following section.
