---
sidebar: sidebar
permalink: ent-db/overview_requirements.html
keywords: Linux, RHEL Oracle19c, NFS, ONTAP
summary: This page describes the Automated method for deploying Oracle19c on NetApp ONTAP storage.
---

= Solution Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/



== Automated Deployment of Oracle19c for ONTAP NFS

This solution utilizes Ansible to enable storage administrators, systems administrators and DBAs to consistently and rapidly deploy new storage, configure database servers, and install Oracle19c:

* Eliminates design complexities, and provides a repeatable consistent deployment
* Decreases time for provisioning of storage, configuration of DB hosts, and Oracle installation
* Enables scaling of storage and number of databases
* Designed to run on RHEL 7/8 and Oracle Linux 7/8

= Requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

== Ansible Environment
* Ansible version 2.10 and above
* Python 3
* Python libraries:
** netapp-lib
** xmltodict
** jmespath

== ONTAP
* ONTAP version 9.3 - 9.8
* Two data aggregates
* NFS vlan and ifgrp created

== Linux
* RHEL 7/8
* Oracle Linux 7/8
* NFS vlan configured interface 
