---
sidebar: sidebar
permalink: ehc/gcp/gcp-gcve.html
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr
summary:
---

= NetApp Capabilities for Google Cloud Platform GCVE
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../../media/

[.lead]
Learn more about the capabilities that NetApp brings to the Google Cloud Platform (GCP) Google Cloud Virtualization Engine (GCVE) - from NetApp as a guest connected storage device or a native datastore to migrating workflows, extending/bursting to the cloud, backup/restore and disaster recovery.

Jump to the section for the desired content by selecting from the following options:

* link:#config[Configuring GCVE in GCP]
* link:#datastore[NetApp Storage Options for GCVE]
//* link:#solutions[NetApp / VMware Cloud Solutions]

[[config]]
== Configuring GCVE in GCP
As with on-premises, planning a cloud based virtualization environment is critical for a successful production-ready environment for creating VMs and migration.

include::ehc/ehc-config-vmware.adoc[tags=gcp-config;gcp;!ehc-gcp]

[[datastore]]
== NetApp Storage Options for GCVE
NetApp storage can be utilized in several ways  - either as guess connected or as a native datastore - within GCP GCVE.

Please visit link:ehc-support-configs.html[Supported NetApp Storage Options] for more information.

include::ehc/ehc-datastore.adoc[tags=gcp-datastore;gcp;!ehc-gcp]

[[solutions]]
//== Solution Use Cases
//With NetApp and VMware cloud solutions, many use cases are simple to deploy in Azure AVS.  The use cases include:
//
//* Extend / Burst
//* Data Center Maintenance
//* Migration
//* Backup / Restore
//* Disaster Recovery
//* Data Protection
//
//link:gcp-solutions.html[Browse the NetApp solutions for Google Cloud GCVE]
