---
sidebar: sidebar
permalink: hciai_edge_use_cases.html
keywords:
summary:
---

= Use Cases
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-29 18:13:42.309426
//

[.lead]
Although all applications today are not AI driven, they are evolving capabilities that allow them to access the immense benefits of AI. To support the adoption of AI, applications need an infrastructure that provides them with the resources needed to function at an optimum level and support their continuing evolution.

For AI-driven applications, edge locations act as a major source of data. Available data can be used for training when collected from multiple edge locations over a period of time to form a training dataset. The trained model can then be deployed back to the edge locations where the data was collected, enabling faster inferencing without the need to repeatedly transfer production data to a dedicated inferencing platform.

The NetApp HCI AI inferencing solution, powered by NetApp H615c compute nodes with NVIDIA T4 GPUs and NetApp cloud-connected storage systems, was developed and verified by NetApp and NVIDIA. NetApp HCI simplifies the deployment of AI inferencing solutions at edge data centers by addressing areas of ambiguity, eliminating complexities in the design and ending guesswork.
This solution gives IT organizations a prescriptive architecture that:

* Enables AI inferencing at edge data centers
* Optimizes consumption of GPU resources
* Provides a Kubernetes-based inferencing platform for flexibility and scalability
* Eliminates design complexities

Edge data centers manage and process data at locations that are very near to the generation point. This proximity increases the efficiency and reduces the latency involved in handling data. Many vertical markets have realized the benefits of an edge data center and are heavily adopting this distributed approach to data processing.

The following table lists the edge verticals and applications.


|===
|Vertical |Applications

|Medical
|Computer-aided diagnostics assist medical staff in early disease detection
|Oil and gas
|Autonomous inspection of remote production facilities, video, and image analytics
|Aviation
|Air traffic control assistance and real-time video feed analytics
|Media and entertainment
|Audio/video content filtering to deliver family-friendly content
|Business analytics
|Brand recognition to analyze brand appearance in live-streamed televised events
|E-Commerce
|Smart bundling of supplier offers to find ideal merchant and warehouse combinations
|Retail
|Automated checkout to recognize items a customer placed in cart and facilitate digital payment
|Smart city
|Improve traffic flow, optimize parking, and enhance pedestrian and cyclist safety
|Manufacturing
|Quality control, assembly-line monitoring, and defect identification
|Customer service
|Customer service automation to analyze and triage inquiries (phone, email, and social media)
|Agriculture
|Intelligent farm operation and activity planning, to optimize fertilizer and herbicide application
|===

== Target Audience

The target audience for the solution includes the following groups:

* Data scientists
* IT architects
* Field consultants
* Professional services
* IT managers
* Anyone else who needs an infrastructure that delivers IT innovation and robust data and application services at edge locations

link:hciaiedge_architecture.html[Next: Architecture]
