---
sidebar: sidebar
permalink: hciai_edge_setp_the_deployment_jump__and_the_kubernetes_master_node_vms_manual_deployment.html
keywords:
summary:
---

= Set Up the Deployment Jump VM and the Kubernetes Master Node VMs (Manual Deployment)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-09-29 18:13:42.890316
//

[.lead]
A Deployment Jump VM running a Linux distribution is used for the following purposes:

* Deploying ONTAP Select using an Ansible playbook
* Deploying the Kubernetes infrastructure with NVIDIA DeepOps and GPU Operator
* Installing and configuring NetApp Trident

Three more VMs running Linux are set up; these VMs are configured as Kubernetes Master Nodes in this solution.

Ubuntu 18.04.4 LTS was used in this solution deployment.

. Deploy the Ubuntu 18.04.4 LTS VM with VMware tools
+
You can refer to the high-level steps described in section link:hciaiedge_netapp_h615cmanual_deployment.html#install-ubuntu-18.04.4-lts[Install Ubuntu 18.04.4 LTS].

. Configure the in-band management network for the VM. See the following sample netplan template:
+

....
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    ens160:
      dhcp4: false
      addresses: [ipv4_address/subnet]
      routes:
      - to: 0.0.0.0/0
        via: 172.21.232.111
        metric: 100
        table: 3488
      routing-policy:
      - from: 0.0.0.0/0
        priority: 32768
        table: 3488
      nameservers:
        addresses: [nameserver_ip]
        search: [ search_domain ]
      mtu: 1500
....
+

This template is not the only way to setup the network. You can use any other approach that you prefer.

. Apply the netplan.
+

....
sudo netplan –-debug apply
....

. Stop and disable Network Manager if it is running.
+

....
systemctl stop NetworkManager
systemctl disable NetworkManager
....

. Open a VI editor to `/etc/iproute2/rt_tables` and add a table entry.
+

....
#
# reserved values
#
255     local
254     main
253     default
0       unspec
#
# local
#
#1      inr.ruhep
101     3488
....

. Add a host record for the VM in DNS.
. Verify outbound internet access.
. Update the system.
+

....
sudo apt-get update && sudo apt-get upgrade
....

. Reboot the system.
. Repeat steps 1 through 9 to set up the other three VMs.

link:hciai_edge_deploy_a_kubernetes_cluster_with_nvidia_deepops_automated_deployment.html[Next: Deploy a Kubernetes Cluster with NVIDIA DeepOps (Automated Deployment)]
