---
sidebar: sidebar
permalink: mlrun_where_to_find_additional_information.html
keywords: NetApp Find Additional Information
summary:
---

= Where to Find Additional Information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-08-19 15:22:26.388202
//

[.lead]
To learn more about the information that is described in this document, see the following resources:

* NetApp AI Control Plane:
** NetApp AI Control Plane Technical Report
+
https://www.netapp.com/us/media/tr-4798.pdf[https://www.netapp.com/us/media/tr-4798.pdf^]

* NetApp persistent storage for containers:
** NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[https://netapp.io/persistent-storage-provisioner-for-kubernetes/^]

* ML framework and tools:
** TensorFlow: An Open-Source Machine Learning Framework for Everyone https://www.tensorflow.org/[https://www.tensorflow.org/^]
** Docker
+
https://docs.docker.com[https://docs.docker.com^]

** Kubernetes
+
https://kubernetes.io/docs/home/[https://kubernetes.io/docs/home/^]

** Kubeflow
+
http://www.kubeflow.org/[http://www.kubeflow.org/^]

** Jupyter Notebook Server
+
http://www.jupyter.org/[http://www.jupyter.org/^]

* Iguazio Data Science Platform
** Iguazio Data Science Platform Documentation
+
https://www.iguazio.com/docs/[https://www.iguazio.com/docs/^]

** Nuclio serverless function
+
https://nuclio.io/[https://nuclio.io/^]

** MLRun opensource pipeline orchestration framework
+
https://www.iguazio.com/open-source/mlrun/[https://www.iguazio.com/open-source/mlrun/^]

* NVIDIA DGX-1 systems
** NVIDIA DGX-1 systems
+
https://www.nvidia.com/en-us/data-center/dgx-1/[https://www.nvidia.com/en-us/data-center/dgx-1/^]

** NVIDIA Tesla V100 Tensor core GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[https://www.nvidia.com/en-us/data-center/tesla-v100/^]

** NVIDIA GPU Cloud
+
https://www.nvidia.com/en-us/gpu-cloud/[https://www.nvidia.com/en-us/gpu-cloud/^]

* NetApp AFF systems
** AFF datasheet
+
https://www.netapp.com/us/media/ds-3582.pdf[https://www.netapp.com/us/media/ds-3582.pdf^]

** NetApp Flash Advantage for AFF
+
https://www.netapp.com/us/media/ds-3733.pdf[https://www.netapp.com/us/media/ds-3733.pdf^]

** ONTAP 9.x documentation
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286^]

** NetApp FlexGroup technical report
+
https://www.netapp.com/us/media/tr-4557.pdf[https://www.netapp.com/us/media/tr-4557.pdf^]

* NetApp ONTAP AI
** ONTAP AI with DGX-1 and Cisco Networking Design Guide
+
https://www.netapp.com/us/media/nva-1121-design.pdf[https://www.netapp.com/us/media/nva-1121-design.pdf^]

** ONTAP AI with DGX-1 and Cisco Networking Deployment Guide
+
https://www.netapp.com/us/media/nva-1121-deploy.pdf[https://www.netapp.com/us/media/nva-1121-deploy.pdf^]

** ONTAP AI with DGX-1 and Mellanox Networking Design Guide
+
https://www.netapp.com/us/media/nva-1138-design.pdf[https://www.netapp.com/us/media/nva-1138-design.pdf^]

* ONTAP AI networking
** Cisco Nexus 3232C Series Switches
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html^]

** Mellanox Scale-Out SN2000 Ethernet Switch Series
+
https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[https://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000^]
